T.WallThicknessAnalysis=function(ba){function ka(h,c){function b(h,b){var c=a.inputParent&&a.inputParent.scale?1/(a.inputParent.scale.x*a.inputParent.scale.y*a.inputParent.scale.z):0;l.depthTestUniform=0==h?0:1;r=N[h%2];G=O[h%2];q=N[(h+1)%2];C=O[(h+1)%2];backFacePixelBuffer=I[h%2];prevBackFacePixelBuffer=I[(h+1)%2];if(a.floatTextures){l.tDiffuseUniform=q;l.side=T.FrontSide;n=z();if(!n)return 0;a.renderer.render(p,a.camera,r,!0);0<h&&(a.renderer.clearTarget(k,!0,!1,!1),J.uniforms.tDiffuse2.value=r,
J.render(a.renderer,k,C),e.readPixels(0,0,a.width-1,a.height-1,e.RGBA,e.UNSIGNED_BYTE,P),0==b&&a.inputParent&&(a.renderer.clearTarget(k,!0,!1,!1),ga.uniforms.tDiffuse2.value=r,ga.render(a.renderer,k,C),e.readPixels(0,0,a.width-1,a.height-1,e.RGBA,e.UNSIGNED_BYTE,t),a.inputParent.supportVolume+=Q()*c));0==b&&0==h&&a.inputParent&&(a.renderer.clearTarget(k,!0,!1,!1),la.render(a.renderer,k,r),e.readPixels(0,0,a.width-1,a.height-1,e.RGBA,e.UNSIGNED_BYTE,t),a.inputParent.supportVolume=Q()*c);l.tDiffuseUniform=
C;l.side=T.BackSide;z();a.renderer.render(p,a.camera,G,!0);a.renderer.clearTarget(k,!0,!1,!1);ha.render(a.renderer,k,r);e.readPixels(0,0,a.width-1,a.height-1,e.RGBA,e.UNSIGNED_BYTE,x);a.renderer.clearTarget(k,!0,!1,!1);ha.render(a.renderer,k,G);e.readPixels(0,0,a.width-1,a.height-1,e.RGBA,e.UNSIGNED_BYTE,backFacePixelBuffer);a.renderer.clearTarget(k,!0,!1,!1);K.uniforms.tDiffuse2.value=G;K.render(a.renderer,k,r)}else{l.tDiffuseUniform=q;l.side=T.FrontSide;l.infoMode=0;n=z();if(!n)return 0;a.renderer.render(p,
a.camera,r,!0);l.infoMode=1;z();a.renderer.render(p,a.camera,ca,!0);l.infoMode=2;z();a.renderer.render(p,a.camera,da,!0);e.readPixels(0,0,a.width-1,a.height-1,e.RGBA,e.UNSIGNED_BYTE,x);0<h&&(a.renderer.clearTarget(y,!0,!1,!1),J.uniforms.tDiffuse2.value=r,J.render(a.renderer,y,C),e.readPixels(0,0,a.width-1,a.height-1,e.RGBA,e.UNSIGNED_BYTE,P),0==b&&a.inputParent&&(a.renderer.clearTarget(y,!0,!1,!1),R.uniforms.tDiffuse2.value=r,R.render(a.renderer,y,C),e.readPixels(0,0,a.width-1,a.height-1,e.RGBA,e.UNSIGNED_BYTE,
t),a.inputParent.supportVolume+=Q()*c));0==b&&0==h&&a.inputParent&&(a.renderer.clearTarget(y,!0,!1,!1),ma.render(a.renderer,y,r),e.readPixels(0,0,a.width-1,a.height-1,e.RGBA,e.UNSIGNED_BYTE,t),a.inputParent.supportVolume=Q()*c);l.tDiffuseUniform=C;l.side=T.BackSide;l.infoMode=0;z();a.renderer.render(p,a.camera,G,!0);l.infoMode=1;z();a.renderer.render(p,a.camera,ea,!0);l.infoMode=2;z();a.renderer.render(p,a.camera,da,!0);e.readPixels(0,0,a.width-1,a.height-1,e.RGBA,e.UNSIGNED_BYTE,backFacePixelBuffer);
a.renderer.clearTarget(y,!0,!1,!1);R.uniforms.tDiffuse2.value=G;R.render(a.renderer,y,r);a.renderer.clearTarget(S,!0,!1,!1);L.uniforms.tDiffuse2.value=ea;L.render(a.renderer,S,ca);a.renderer.clearTarget(k,!0,!1,!1);ia.uniforms.tDiffuse2.value=S;ia.render(a.renderer,k,y)}e.readPixels(0,0,a.width-1,a.height-1,e.RGBA,e.UNSIGNED_BYTE,t);var c=a.width,f=a.camera.far-a.camera.near,d,g,m,aa,u,w,B=new T.Vector2(0,1),U=m=0,Z=0,H,v,M,ja,V=[1/255,1/65025,1/16581375,1/4228250625],ba=1+a.thicknessAccuracy,W=I[h%
2],X=I[(h+1)%2];v=fa;for(ja=D;v<=ja&&!a.abort;v++){var Y=0;H=E[v];for(M=F[v];H<=M;H++)m=4*(H+v*c),d=t[m+3]*V[0]+t[m+2]*V[1]+t[m+1]*V[2]+t[m+0]*V[3],0!==P[m]&&(u=A[x[m+3]],w=A[X[m+3]],u&&w&&(g=x[m+0]<<16|x[m+1]<<8|x[m+2],aa=X[m+0]<<16|X[m+1]<<8|X[m+2],(g=u.material.attributes.vertexThickness.value[g])&&0==g.y%1&&(++u.intersections,g.y=.5),(u=w.material.attributes.vertexThickness.value[aa])&&0==u.y%1&&(++w.intersections,u.y=.5))),0<d&&(0==Y&&(E[v]=H),F[v]=H,++Y,d<ba&&(u=A[x[m+3]],w=A[W[m+3]],u&&w&&
(++Z,g=x[m+0]<<16|x[m+1]<<8|x[m+2],m=W[m+0]<<16|W[m+1]<<8|W[m+2],B.x=d*f,g=u.material.attributes.vertexThickness.value[g],u=w.material.attributes.vertexThickness.value[m],g&&g.add(B),u&&u.add(B))));0===Y?(E[v]=0,F[v]=0):(D=v,0==U&&(D=v),U+=Y)}return U}function f(c,f){function e(f,d){if(f>a.maxIterations-1||a.abort)d&&d();else{var l=b(f,c),w=Date.now()-g,n=0===c?a.timeLimits[0]:3>c?a.timeLimits[1]:a.timeLimits[2];h&&h(c+Math.min(w/n,1),a.maxCameras);0===l||w>n?d&&d(f):setTimeout(function(){e(f+1,d)},
2)}}na(c);fa=0;D=a.height-1;for(var d=0;d<a.height;++d)E[d]=0,F[d]=a.width-1;var g=Date.now();e(0,function(a){Z();console.log("Wall thickness - Camera",c,"Iterations",a,"Time",.001*(Date.now()-g));f&&f()})}function g(b,c){void 0!==a.debugCamera&&b!==a.debugCamera||b>a.maxCameras-1||a.abort?c&&c():f(b,function(){h&&h(b+1,a.maxCameras);setTimeout(function(){g(b+1,c)},5)})}if(a.enabled){var e=a.renderer.context,d=a.renderer.renderSelectedMode,w=T.SceneUtils.wireframeMaterial.visible,aa=a.renderer.getClearColor().clone(),
n=0,r,G,q,C;K&&(K.uniforms.minAngle.value=a.minAngle,K.uniforms.maxAngleDifference.value=a.maxAngleDifference);L&&(L.uniforms.minAngle.value=a.minAngle,L.uniforms.maxAngleDifference.value=a.maxAngleDifference);a.renderer.setClearColor(oa,0);a.renderer.renderSelectedMode=T.WebGLRenderer.RENDER_ALL;var B=Date.now();g(void 0!==a.debugCamera?a.debugCamera:0,function(){console.log("Total time for analysis",.001*(Date.now()-B));a.renderer.setClearColor(aa,1);T.SceneUtils.wireframeMaterial.visible=w;a.renderer.renderSelectedMode=
d;a.abort||pa();Z();M();c&&c()})}}function pa(){a.inputScene.traverse(function(a){a.wallThicknessStarted&&(a.wallThicknessFinished=!0,a.wallThicknessStarted=!1)})}function Z(){a.inputScene.traverse(function(a){a instanceof T.Mesh&&a.material&&(a.material.needsUpdate=!0,a.material.attributes&&a.material.attributes.vertexThickness&&(a.material.attributes.vertexThickness.needsUpdate=!0))})}function z(){if(a.enabled){var h=0;p.traverse(function(a){a instanceof T.Mesh&&(++h,B(a.material))});return h}}
function M(){A=[];a.inputParent=null;a.inputScene.traverse(function(a){a.wallThicknessStarted&&(a.wallThicknessStarted=void 0)});p.traverse(function(a){a instanceof T.Mesh&&a.material&&(a.material.dispose(),a.material=null)})}function Q(){var h=a.width,c=a.height,b=a.camera.far-a.camera.near,f,g=f=0,e,d,l,k,n=[1/255,1/65025,1/16581375,1/4228250625],r=1+a.thicknessAccuracy,q=0;d=fa;for(k=D;d<=k&&!a.abort;d++){var p=0;e=E[d];for(l=F[d];e<=l;e++)f=4*(e+d*h),f=t[f+3]*n[0]+t[f+2]*n[1]+t[f+1]*n[2]+t[f+
0]*n[3],0<f&&(0==p&&(E[d]=e),F[d]=e,++p,f<r&&(q+=f));0===p?(E[d]=0,F[d]=0):(D=d,0==g&&(D=d),g+=p)}return(a.camera.top-a.camera.bottom)/c*((a.camera.right-a.camera.left)/h)*b*q}function B(h){h.depthTest=l.depthTest;h.depthWrite=l.depthWrite;h.side=l.side;h.uniforms.mode&&(h.uniforms.mode.value=l.infoMode);h.uniforms.tDiffuse.value=l.tDiffuseUniform;h.uniforms.depthTest.value=l.depthTestUniform;h.uniforms.screenWidth.value=a.width;h.uniforms.screenHeight.value=a.height;h.needsUpdate=!0}function na(h){if(!q.empty()){var c=
new T.Vector2,b=new T.V3,f=new T.V3,g=q.center();q.size(f);c.set(f.x,f.y).length();var e=c.set(f.x,f.z).length(),c=c.set(f.y,f.z).length(),d=new T.Box3,l=Math.max(f.x,f.y,f.z);d.setFromCenterAndSize(g,new T.V3(l,l,l));d.size(b);var b=b.length(),k,n;switch(h){case 0:a.camera.position.set(g.x,g.y,q.min.z);k=f.x;n=f.y;a.camera.far=f.z;break;case 1:a.camera.position.set(g.x,q.min.y,g.z);k=f.z;n=f.x;a.camera.far=f.y;break;case 2:a.camera.position.set(q.min.x,g.y,g.z);k=f.z;n=f.y;a.camera.far=f.x;break;
case 3:a.camera.position.set(d.max.x,d.max.y,d.min.z);n=k=b;a.camera.far=b;break;case 4:a.camera.position.set(d.max.x,d.min.y,d.max.z);k=e;n=b;a.camera.far=b;break;case 5:a.camera.position.set(d.min.x,d.max.y,d.max.z);k=c;n=b;a.camera.far=b;break;case 6:a.camera.position.set(d.max.x,d.max.y,d.max.z),n=k=b,a.camera.far=b}a.camera.lookAt(g);a.camera.updateMatrixWorld();a.camera.matrixWorldInverse.getInverse(a.camera.matrixWorld);a.camera.near=-1*a.camera.far*a.thicknessAccuracy;a.camera.far*=1+a.thicknessAccuracy;
a.camera.left=k/-2;a.camera.right=k/2;a.camera.top=n/2;a.camera.bottom=n/-2;a.camera.updateProjectionMatrix()}}this.inputParent=this.inputScene=null;this.renderer=ba;this.camera=new T.OrthographicCamera(0,0,0,0,0,1E4);this.floatTextures=this.renderer.supportsFloatTextures();this.height=this.width=0;this.maxIterations=200;this.maxCameras=7;this.minAngle=Math.PI/5;this.maxAngleDifference=Math.PI/4;this.thicknessAccuracy=.001;this.timeLimits=[3E4,2E4,5E3];this.enabled=!1;var a=this,p=new T.Scene,A,q=
new T.Box3,l={depthTest:!0,depthWrite:!0,side:T.FrontSide,tDiffuseUniform:null,depthTestUniform:0,infoMode:0},E=[],F=[],fa=0,D=0,oa=new T.Color(0,0,0),N=[],O=[],k=null,x=null,I=[],t=null,P=null,ca=null,ea=null,da=null,y=null,S=null,ma=new T.ShaderPass(T.CopyShader);if(this.floatTextures)var ha=new T.ShaderPass(T.ExtractFloatFaceShader),K=new T.ShaderPass(T.ComputeThicknessFromDepthNormalShader,"tDiffuse1"),J=new T.ShaderPass(T.CheckNegativeThicknessFloatShader,"tDiffuse1"),la=new T.ShaderPass(T.ExtractFloatDepthShader),
ga=new T.ShaderPass(T.ComputeDepthDifferenceFromDepthNormalShader);else var R=new T.ShaderPass(T.ComputeThicknessFromDepthShader,"tDiffuse1"),L=new T.ShaderPass(T.ComputeThicknessCorrectionFromNormalShader,"tDiffuse1"),ia=new T.ShaderPass(T.ApplyThicknessCorrectionShader,"tDiffuse1"),J=new T.ShaderPass(T.CheckNegativeThicknessByteShader,"tDiffuse1");this.operate=function(a,c){if(this.inputScene){if(0==this.width||0==this.height)this.floatTextures?this.setSize(800,800):this.setSize(400,400);this.abort=
!1;ka(a,c)}else c&&c()};this.setSize=function(a,c){if(this.floatTextures){var b=new T.WebGLRenderTarget(a,c,{minFilter:T.LinearFilter,magFilter:T.LinearFilter,depthBuffer:!0,stencilBuffer:!1,format:T.RGBAFormat,type:T.FloatType});N=[b,b.clone()];O=[b.clone(),b.clone()];k=new T.WebGLRenderTarget(a,c,{minFilter:T.LinearFilter,magFilter:T.LinearFilter,depthBuffer:!1,stencilBuffer:!1,format:T.RGBAFormat})}else b=new T.WebGLRenderTarget(a,c,{minFilter:T.LinearFilter,magFilter:T.LinearFilter,depthBuffer:!0,
stencilBuffer:!1,format:T.RGBAFormat}),N=[b,b.clone()],O=[b.clone(),b.clone()],ca=b.clone(),ea=b.clone(),da=b.clone(),k=new T.WebGLRenderTarget(a,c,{minFilter:T.LinearFilter,magFilter:T.LinearFilter,depthBuffer:!1,stencilBuffer:!1,format:T.RGBAFormat}),y=k.clone(),S=k.clone();this.width=a;this.height=c;x=new Uint8Array(4*a*c);I=[new Uint8Array(4*a*c),new Uint8Array(4*a*c)];t=new Uint8Array(4*a*c);P=new Uint8Array(4*a*c)};this.setScene=function(a){this.inputScene=a};this.setMinMaxThickness=function(a,
c,b){(b=b?b:this.inputScene)&&b.traverse(function(b){b instanceof T.Mesh&&b.material&&(b.material.needsUpdate=!0,null!==a&&void 0!==a&&(b.material.minThickness=a),null!==c&&void 0!==c&&(b.material.maxThickness=c))})};this.setAnalysisMode=function(a,c){(c=c?c:this.inputScene)&&c.traverse(function(b){b instanceof T.Mesh&&b.material&&(b.material.needsUpdate=!0,b.material.analysisMode&&(b.material.prevAnalysisMode=b.material.analysisMode),b.material.analysisMode=a)})};this.restoreAnalysisMode=function(a){(a=
a?a:this.inputScene)&&a.traverse(function(a){a instanceof T.Mesh&&a.material&&(a.material.needsUpdate=!0,a.material.analysisMode||(a.material.analysisMode=void 0!==a.material.prevAnalysisMode?a.material.prevAnalysisMode:3))})};this.getMinMaxThickness=function(a){if(a=a?a:this.inputScene){var c=null,b=null;a.traverse(function(a){a instanceof T.Mesh&&a.material&&(void 0!==a.material.minThickness&&(null===c||c>a.material.minThickness)&&(c=a.material.minThickness),void 0!==a.material.maxThickness&&(null===
b||b<a.material.maxThickness)&&(b=a.material.maxThickness))});if(null!==c&&null!==b)return{min:c,max:b}}};this.getAnalysisMode=function(a){if(a=a?a:this.inputScene){var c=null;a.traverse(function(a){a instanceof T.Mesh&&a.material&&void 0!==a.material.analysisMode&&(null===c||c<a.material.analysisMode)&&(c=a.material.analysisMode)});return c}};this.resetObject=function(a){(a=a?a:this.inputScene)&&a.traverse(function(a){a.wallThicknessStarted=void 0;a.wallThicknessFinished=void 0})};this.updateObjects=
function(){if(a.enabled){M();var h=function(a){if(a.visible&&a.selected&&a instanceof T.Mesh)return a;for(var c=null,g=0,e=0;e<a.children.length;e++){var d=h(a.children[e]);d&&(++g,c=d)}return 0==g?null:1==g?c:a},c=function(b){if(b.wallThicknessFinished||b.dummy)return null;var f=null;if(b instanceof T.Scene)f=new T.Scene;else if(b.visible&&b.selected&&b instanceof T.Mesh){f=A.length;if(255<f)return null;b.intersections=0;A.push(b);var g;g=a.floatTextures?new T.ShaderMaterial({fragmentShader:T.DepthTestFloatInfoShader.fragmentShader,
vertexShader:T.DepthTestFloatInfoShader.vertexShader,uniforms:T.UniformsUtils.clone(T.DepthTestFloatInfoShader.uniforms),blending:T.NoBlending}):new T.ShaderMaterial({fragmentShader:T.DepthTestByteInfoShader.fragmentShader,vertexShader:T.DepthTestByteInfoShader.vertexShader,uniforms:T.UniformsUtils.clone(T.DepthTestByteInfoShader.uniforms),blending:T.NoBlending});g.uniforms.objectId.value=f;B(g);var e=b.geometry,f=new T.Mesh(e,g);g.attributes={faceIndex:{type:"f",boundTo:"faces",value:[]}};for(var d=
0;d<e.faces.length;d++)g.attributes.faceIndex.value[d]=d;g.needsUpdate=!0;g.attributes.faceIndex.needsUpdate=!0;d=b.material;d.attributes&&d.attributes.vertexThickness||(d.attributes={vertexThickness:{type:"v2",boundTo:"faces",value:[]}});for(var h=0;h<e.faces.length;h++)d.attributes.vertexThickness.value[h]=new T.Vector2(0,0);g.attributes.vertexThickness=d.attributes.vertexThickness;b.wallThicknessStarted=!0}else f=new T.Object3D;T.Object3D.prototype.clone.call(b,f,!1);for(g=0;g<b.children.length;g++)f.add(c(b.children[g]));
return f};a.inputParent=h(a.inputScene);(function(){q.makeEmpty();a.inputScene.traverse(function(a){a.visible&&a.selected&&a instanceof T.Mesh&&q.union(T.GeometryUtils.getGlobalBoundingBox(a))})})();p=c(a.inputScene);return A.length}}};
