jQuery.fn.farbtastic=function(e){$.farbtastic(this,e);return this};jQuery.farbtastic=function(e,m){e=$(e).get(0);return e.farbtastic||(e.farbtastic=new jQuery._farbtastic(e,m))};
jQuery._farbtastic=function(e,m){var a=this;$(e).html('<div class="farbtastic"><div class="color"></div><div class="wheel"></div><div class="overlay"></div><div class="h-marker marker"></div><div class="sl-marker marker"></div></div>');var l=$(".farbtastic",e);a.wheel=$(".wheel",e).get(0);a.radius=84;a.square=100;a.width=194;navigator.appVersion.match(/MSIE [0-6]\./)&&$("*",l).each(function(){if("none"!=this.currentStyle.backgroundImage){var b=this.currentStyle.backgroundImage,b=this.currentStyle.backgroundImage.substring(5,
b.length-2);$(this).css({backgroundImage:"none",filter:"progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled=true, sizingMethod=crop, src='"+b+"')"})}});a.linkTo=function(b){"object"==typeof a.callback&&$(a.callback).unbind("keyup",a.updateValue);a.color=null;if("function"==typeof b)a.callback=b;else if("object"==typeof b||"string"==typeof b)a.callback=$(b),a.callback.bind("keyup",a.updateValue),a.callback.get(0).value&&a.setColor(a.callback.get(0).value);return this};a.updateValue=function(b){this.value&&
this.value!=a.color&&a.setColor(this.value)};a.setColor=function(b){var f=a.unpack(b);a.color!=b&&f&&(a.color=b,a.rgb=f,a.hsl=a.RGBToHSL(a.rgb),a.updateDisplay());return this};a.setHSL=function(b){a.hsl=b;a.rgb=a.HSLToRGB(b);a.color=a.pack(a.rgb);a.updateDisplay();return this};a.widgetCoords=function(b){var f,c,e=b.target||b.srcElement,g=a.wheel;if("undefined"!=typeof b.offsetX){var d={x:b.offsetX,y:b.offsetY};for(b=e;b;)b.mouseX=d.x,b.mouseY=d.y,d.x+=b.offsetLeft,d.y+=b.offsetTop,b=b.offsetParent;
b=g;for(d=g=0;b;){if("undefined"!=typeof b.mouseX){f=b.mouseX-g;c=b.mouseY-d;break}g+=b.offsetLeft;d+=b.offsetTop;b=b.offsetParent}for(b=e;b;)b.mouseX=void 0,b.mouseY=void 0,b=b.offsetParent}else d=a.absolutePosition(g),f=(b.pageX||0*(b.clientX+$("html").get(0).scrollLeft))-d.x,c=(b.pageY||0*(b.clientY+$("html").get(0).scrollTop))-d.y;return{x:f-a.width/2,y:c-a.width/2}};a.mousedown=function(b){document.dragging||($(document).bind("mousemove",a.mousemove).bind("mouseup",a.mouseup),document.dragging=
!0);var f=a.widgetCoords(b);a.circleDrag=2*Math.max(Math.abs(f.x),Math.abs(f.y))>a.square;a.mousemove(b);return!1};a.mousemove=function(b){b=a.widgetCoords(b);a.circleDrag?(b=Math.atan2(b.x,-b.y)/6.28,0>b&&(b+=1),a.setHSL([b,a.hsl[1],a.hsl[2]])):a.setHSL([a.hsl[0],Math.max(0,Math.min(1,-(b.x/a.square)+.5)),Math.max(0,Math.min(1,-(b.y/a.square)+.5))]);return!1};a.mouseup=function(){$(document).unbind("mousemove",a.mousemove);$(document).unbind("mouseup",a.mouseup);document.dragging=!1};a.updateDisplay=
function(){var b=6.28*a.hsl[0];$(".h-marker",l).css({left:Math.round(Math.sin(b)*a.radius+a.width/2)+"px",top:Math.round(-Math.cos(b)*a.radius+a.width/2)+"px"});$(".sl-marker",l).css({left:Math.round(a.square*(.5-a.hsl[1])+a.width/2)+"px",top:Math.round(a.square*(.5-a.hsl[2])+a.width/2)+"px"});$(".color",l).css("backgroundColor",a.pack(a.HSLToRGB([a.hsl[0],1,.5])));"object"==typeof a.callback?($(a.callback).css({backgroundColor:a.color,color:.5<a.hsl[2]?"#000":"#fff"}),$(a.callback).each(function(){this.value&&
this.value!=a.color&&(this.value=a.color)})):"function"==typeof a.callback&&a.callback.call(a,a.color)};a.absolutePosition=function(b){var f={x:b.offsetLeft,y:b.offsetTop};b.offsetParent&&(b=a.absolutePosition(b.offsetParent),f.x+=b.x,f.y+=b.y);return f};a.pack=function(b){var a=Math.round(255*b[0]),c=Math.round(255*b[1]);b=Math.round(255*b[2]);return"#"+(16>a?"0":"")+a.toString(16)+(16>c?"0":"")+c.toString(16)+(16>b?"0":"")+b.toString(16)};a.unpack=function(b){if(7==b.length)return[parseInt("0x"+
b.substring(1,3))/255,parseInt("0x"+b.substring(3,5))/255,parseInt("0x"+b.substring(5,7))/255];if(4==b.length)return[parseInt("0x"+b.substring(1,2))/15,parseInt("0x"+b.substring(2,3))/15,parseInt("0x"+b.substring(3,4))/15]};a.HSLToRGB=function(b){var a,c=b[0];a=b[1];b=b[2];a=.5>=b?b*(a+1):b+a-b*a;b=2*b-a;return[this.hueToRGB(b,a,c+.33333),this.hueToRGB(b,a,c),this.hueToRGB(b,a,c-.33333)]};a.hueToRGB=function(b,a,c){c=0>c?c+1:1<c?c-1:c;return 1>6*c?b+(a-b)*c*6:1>2*c?a:2>3*c?b+(a-b)*(.66666-c)*6:b};
a.RGBToHSL=function(b){var a,c,e,g,d=b[0],h=b[1],k=b[2];a=Math.min(d,Math.min(h,k));b=Math.max(d,Math.max(h,k));c=b-a;g=(a+b)/2;e=0;0<g&&1>g&&(e=c/(.5>g?2*g:2-2*g));a=0;0<c&&(b==d&&b!=h&&(a+=(h-k)/c),b==h&&b!=k&&(a+=2+(k-d)/c),b==k&&b!=d&&(a+=4+(d-h)/c),a/=6);return[a,e,g]};$("*",l).mousedown(a.mousedown);a.setColor("#000000");m&&a.linkTo(m)};
