'use strict';var BookmarkManager=function(){function b(m){for(var b=0,a=d.length;b<a;b++)if(d[b].id==m)return b;return-1}function h(){for(var b=[],a=0,c=d.length;a<c;a++)b.push(d[a].id);return b}function c(b){if("object"==typeof a[b]){b=a[b];for(var d=0;d<b.length;d++)b[d].apply(BookmarkManager,[])}}var a={},d=[];return{getList:function(a){for(var f=[],c=h(),p=0;p<c.length;p++){var t=b(c[p]);if(-1!=t){var q=d[t];q.index=t;f.push(q)}}a(f)},getTotal:function(){return d.length},getNextName:function(){for(var b,
a=1;;){b="Bookmark "+(d.length+a);var c;a:{c=b;for(var p=0,h=d.length;p<h;p++)if(d[p].name==c){c=!0;break a}c=!1}if(!c)return b;a++}},getBookmarksInRange:function(b,d){for(var a=[],c,t=[],q=h(),u=[],z=0,F=q.length;z<F;z++)c=q[z],u=c.split(":"),u[0]>>=0,u[1]>>=0,t.push({start:u[0],stop:u[0]+u[1]-1,length:u[1],index:z,id:c});q=0;for(u=t.length;q<u;q++)c=t[q],c.stop<b||c.start>d||(c.start<b&&c.stop>d?a.push(c):c.start>=b&&c.start<=d?a.push(c):c.stop>=b&&c.stop<=d&&a.push(c));return a},setNameByIndex:function(b,
a){if(!d[b])return!1;d[b].name=a;c("update")},setRangeByIndex:function(b,a){if(!d[b])return!1;d[b].id=a.getId();c("update")},getBookmarkBySelection:function(a){a=b(a.getId());if(-1==a)return!1;var c=d[a];c.index=a;return c},add:function(b,a){var h=d.push({id:b.getId(),name:a})-1;c("update");return h},remove:function(a){a=b(a.getId());if(-1==a)return!1;d.splice(a,1);c("update")},on:function(b,d){a[b]=a[b]||[];a[b].push(d)},getById:function(a){a=b(a);if(-1==a)a=!1;else{var c=d[a];c.index=a;a=c}return a},
load:function(b){d="object"==typeof b?b:[]},getRawList:function(){return d}}}();
function searchFile(b,h,c,a){a=a||0;var d=0+a,m=!0,f=!1,y=b.slice(a,2097152),p=-1,t=new FileReader;t.onload=function(a){a=bufferHasByteSequence(a.target.result,h);if(-1!=a)return p=d+a,m=!1,c(d+a);if(f)return t.onload=function(){},c(-1),m=!1;d+=2097152;d<b.size?(y=b.slice(d,2097152+d),t.readAsArrayBuffer(y)):(m=!1,c(-1))};t.readAsArrayBuffer(y);return{abort:function(){f=!0},getMatchOffset:function(){return p},isActive:function(){return m}}}
function bufferHasByteSequence(b,h){for(var c=new Uint8Array(b),a=0;;){var d=Array.prototype.indexOf.call(c,h[0],a);if(-1==d)return-1;for(var a=d+1,m=!0,f=1;f<h.length;f++)if(c[f+d]!=h[f]){m=!1;break}if(m)break}return d}
function getSearchBytes(b,h){b=b.trim();"0x"==b.substr(0,2).toLowerCase()&&(b=parseInt(b,16));var c=[],a=b,d=getIntegerValue(b,!1,h);!1!==d&&(b=d.toString(16));if(isValidHexString(b)){for(var m=b.replace(/\s/gi,""),f=[],y=[],d=0;d<m.length;d+=2)f.push(m.substr(d,2));for(d=0;d<f.length;d++)2==f[d].length&&y.push(parseInt(f[d],16));0<y.length&&c.push(y)}m=[];a=encodeURIComponent(a);for(d=0;d<a.length;d++)f=a.charAt(d),"%"==f?(m.push(parseInt(a.substr(d+1,2),16)),d+=2):m.push(f.charCodeAt(0));0<m.length&&
c.push(m);return c}function getIntegerValue(b,h,c){b=(b+"").toLowerCase();for(var a,d=[2,8,16,10];0<d.length;)if(a=d.pop(),parseInt(b,a).toString(a)==b){a=parseInt(b,a);if(256>a)return a;if(65535>=a)return b=new ArrayBuffer(2),b=new DataView(b),b.setUint16(0,a),b.getUint16(0,c);if(4294967295>=a)return b=new ArrayBuffer(4),b=new DataView(b),b.setUint32(0,a),b.getUint32(0,c)}return!h?getIntegerValue(b.replace(/\s/g,""),!0,c):!1}
function isValidHexString(b){return 0==b.replace(/[a-f0-9]/gi,"").trim().length?!0:!1}function copyToClipboard(b,h){var c=b.createElement("textarea");c.style.width="0px";c.style.height="0px";c.style.top="0px";c.style.left="0px";c.style.zIndex="-100";b.body.appendChild(c);c.value=h;c.focus();c.select();b.execCommand("copy");c.parentNode.removeChild(c)}
chrome.app.runtime.onLaunched.addListener(function(){function b(){BookmarkManager.getList(function(a){var b=v.document.getElementById("blist");b.innerHTML="";for(var d=0;d<a.length;d++){var c=document.createElement("li"),k=document.createElement("a");c.appendChild(k);var f=document.createTextNode(a[d].name);k.appendChild(f);k.href="#";(function(b){k.onclick=function(){var a=b.split(":"),d=parseInt(a[0],10),a=d+parseInt(a[1],10)-1,j=r.getSelection();j.setStart(d);j.setStop(a);r.showFrom(d)}})(a[d].id);
b.appendChild(c)}0==a.length&&(b.innerHTML="<li>No Bookmarks</li>");v.document.styleSheets[0].rules[37].style.height=(150>b.offsetHeight?b.offsetHeight:150)+"px"})}function h(){for(var a=r.getOffset(),b=r.getSize(),d=BookmarkManager.getBookmarksInRange(a,a+b-1),c=0;c<b;c++){var k=r.getElementsByIndex(c);k&&(k["byte"].style.backgroundImage="none",k["byte"].style.backgroundRepeat="repeat-x",k["byte"].style.backgroundPosition="0% 100%",k["char"].style.backgroundImage="none",k["char"].style.backgroundRepeat=
"repeat-x",k["char"].style.backgroundPosition="0% 100%")}for(var b=0,f=d.length;b<f;b++)for(var k=d[b],c=k.start-a,c=0>c?0:c,e=k.stop-a;c<=e;c++)if(k=r.getElementsByIndex(c))k["byte"].style.backgroundImage="url('bookmark_line.gif')",k["char"].style.backgroundImage="url('bookmark_line.gif')"}function c(a){var c=v.document;c.title=a.name+" - "+u.appName;c.getElementById("appTitle").innerHTML=u.appName+" - "+a.name;A=a.name+":"+a.size+":"+a.type;chrome.storage.local.get("bookmarks",function(c){var d=
c.bookmarks||{};BookmarkManager.load(d[A]);b();BookmarkManager.on("update",function(){d[A]=BookmarkManager.getRawList();chrome.storage.local.set({bookmarks:d})});p(a,D,0)});var h=c.getElementById("grid"),w=c.getElementById("bttOpen");h.style.display="block";w.style.display="none";c.getElementById("startup").style.display="none";c.getElementById("info").style.display="block";c.getElementById("search").style.display="block";c.getElementById("jumper").style.display="block";c.getElementById("bookmarkSection").style.display=
"block";c.getElementById("toolbarOpen").style.display="block";v.onresize=t;J||(chrome.contextMenus.onClicked.addListener(function(a){switch(a.menuItemId){case "copyAsString":d(c);break;case "copyAsHex":m(c);break;case "addToBookmarks":c.getElementById("bookmarkImg").click();break;case "deleteFromBookmarks":c.getElementById("bookmarkImg").click();break;case "inLittleEndian":q=!q;break;case "jumpTo":f(r.getSelection(),function(a){c.getElementById("jumper").value="0x"+a.toString(16).toUpperCase();r.showFrom(a);
var b=r.getSelection();b.setStart(a);b.setStop(a)})}}),J=!0)}function a(){v.chrome.fileSystem.chooseEntry({type:"openFile"},function(a){a.file(function(a){c(a)})})}function d(a){var b=r.getSelection(),b=B.slice(b.getStart(),b.getStop()+1),c=new FileReader;c.onload=function(b){copyToClipboard(a,b.target.result)};c.readAsText(b)}function m(a){var b=r.getSelection(),b=B.slice(b.getStart(),b.getStop()+1),c=new FileReader;c.onload=function(b){b=new Uint8Array(b.target.result);for(var c=[],d=0;d<b.length;d++){var e=
b[d].toString(16).toUpperCase();c.push(1==(e+"").length?"0"+e:e)}copyToClipboard(a,c.join(" "))};c.readAsArrayBuffer(b)}function f(a,b){var c=B.slice(a.getStart(),a.getStart()+a.getLength()),d=new FileReader;d.onload=function(a){a=new Uint8Array(a.target.result);for(var c=[],d,f=0;f<a.byteLength;f++)d=a[f].toString(16),d=1==d.length?"0"+d:d,c.push(d);q&&c.reverse();a=parseInt(c.join(""),16);b(a)};d.readAsArrayBuffer(c)}function y(a,b){var c=v.document.getElementById("search"),d=setTimeout(function(){c.className=
"inprogress"},500);b=b||0;x&&x.abort();var f=getSearchBytes(a,q);return x=searchFile(B,f[0],function(a){d&&clearTimeout(d);if(!x.isActive()||-1==a)c.className="";if(-1==a)return!1;r.showFrom(a);var b=r.getSelection();b.setStart(a);b.setStop(a+(f[0].length-1))},b)}function p(b,c,u,w){function k(a,b){b=b||{};BookmarkManager.getBookmarkBySelection(a)?chrome.contextMenus.create({title:"Remove Bookmark",id:"deleteFromBookmarks",contexts:["all"]}):chrome.contextMenus.create({title:"Add to Bookmarks",id:"addToBookmarks",
contexts:["all"]});b.jumpTo&&(chrome.contextMenus.create({type:"separator",contexts:["all"],id:"subselect3"}),chrome.contextMenus.create({title:"Jump to 0x"+b.jumpTo.toString(16).toUpperCase(),id:"jumpTo",contexts:["all"]}));chrome.contextMenus.create({type:"separator",contexts:["all"],id:"subselect"});chrome.contextMenus.create({title:"Copy as String",id:"copyAsString",contexts:["all"]});chrome.contextMenus.create({title:"Copy as Hex",id:"copyAsHex",contexts:["all"]});chrome.contextMenus.create({type:"separator",
contexts:["all"],id:"subselect2"})}function t(){if(q)return chrome.contextMenus.create({type:"checkbox",title:"Little Endian Mode",id:"inLittleEndian",checked:!0,contexts:["all"]}),!0;chrome.contextMenus.create({type:"checkbox",title:"Little Endian Mode",id:"inLittleEndian",checked:!1,contexts:["all"]})}var e=v.document,n=e.getElementById("grid");n.innerHTML="";n.style.margin="0 auto";n.style.display="block";var g=HexGrid(c,b,n,w);r=g;c=g.getDimensions();F=c.row.height;B||K.resizeTo(c.width+240,c.height+
112);B=b;n.style.width=c.width+"px";n.style.height=c.height+"px";n.style.overflow="hidden";g.on("bytehover",function(a){if(!1===a)return e.getElementById("valOffset").value="",e.getElementById("valUint8").disabled=!0,e.getElementById("valUint8").value="",e.getElementById("valInt8").disabled=!0,e.getElementById("valInt8").value="",e.getElementById("valUint16").disabled=!0,e.getElementById("valUint16").value="",e.getElementById("valInt16").disabled=!0,e.getElementById("valInt16").value="",e.getElementById("valUint32").disabled=
!0,e.getElementById("valUint32").value="",e.getElementById("valInt32").disabled=!0,e.getElementById("valInt32").value="",!1;e.getElementById("valOffset").value="0x"+a.offset.address.toString(16);var b=g.getBuffer();if(!b)return!1;a=new DataView(b.slice(a.offset["byte"]));b=a.getUint8(0);e.getElementById("valUint8").disabled=!1;e.getElementById("valUint8").value=b;b=a.getInt8(0);e.getElementById("valInt8").disabled=!1;e.getElementById("valInt8").value=b;if(2>a.byteLength)return!1;b=a.getUint16(0,q);
e.getElementById("valUint16").disabled=!1;e.getElementById("valUint16").value=b;b=a.getInt16(0,q);e.getElementById("valInt16").disabled=!1;e.getElementById("valInt16").value=b;if(4>a.byteLength)return!1;b=a.getUint32(0,q);e.getElementById("valUint32").disabled=!1;e.getElementById("valUint32").value=b;a=a.getInt32(0,q);e.getElementById("valInt32").disabled=!1;e.getElementById("valInt32").value=a});g.on("bytecontext",function(a){var b=g.getBuffer(),b=new DataView(b.slice(a.index));b.getUint8(0);b.getUint16(0);
var c=g.getSelection();chrome.contextMenus.removeAll(function(){if(c.hasAddress(a.address)){var b=c.getLength();0<b&&5>b?f(c,function(a){a<B.size?k(c,{jumpTo:a}):k(c);t()}):(k(c),t())}else t()})});g.on("update",function(){h()});g.on("rangechange",function(a,b){var c,d,f,j;c=e.getElementById("rangeStart");d=e.getElementById("rangeStop");f=e.getElementById("rangeSize");if(a.exists()){e.getElementById("bookmarkImg").style.display="";if(b&&(b.exists()&&!a.inProgress)&&(j=a.getLength()-b.getLength(),-1==
j||1==j))j=BookmarkManager.getBookmarkBySelection(b),BookmarkManager.setRangeByIndex(j.index,a);j=BookmarkManager.getBookmarkBySelection(a);if(!1===j)j=e.getElementById("bookmarkName"),e.getElementById("bookmarkImg").src="bookmark_off.png",j.style.display="none",j.setAttribute("_bmIndex",-1);else{var g=e.getElementById("bookmarkName");e.getElementById("bookmarkImg").src="bookmark_on.png";g.style.display="";g.setAttribute("_bmIndex",j.index);g.value=j.name}c.value=a.getStart();d.value=a.getStop();
c.max=a.getStop();d.min=a.getStart();c=d.value-c.value+1;f.value=c+" (0x"+c.toString(16)+")"}else c.value="",d.value="",f.value="",e.getElementById("bookmarkImg").style.display="none";h()});e.getElementById("rangeStop").max=b.size-1;e.getElementById("rangeStart").onchange=function(){g.getSelection().setStart(this.value)};e.getElementById("rangeStop").onchange=function(){g.getSelection().setStop(this.value)};var l=!1,s=e.getElementById("search"),p=e.getElementById("jumper");s.onkeyup=function(a){if(13==
a.keyCode||27==a.keyCode||17==a.keyCode||16==a.keyCode||18==a.keyCode)return!1;0<this.value.length?y(this.value):(g.getSelection().reset(),x&&x.abort())};s.onkeydown=function(a){27==a.keyCode&&l&&(l.focus(),l=!1);13==a.keyCode&&x&&(a=x.getMatchOffset(),-1!=a&&y(this.value,a+1))};s.onfocus=function(){if(0<this.value.length){var a=getSearchBytes(this.value,q);if(x.isActive())return!1;x.abort();searchFile(b,a[0],function(b){s.className="";if(-1==b)return!1;g.showFrom(b);var c=g.getSelection();c.setStart(b);
c.setStop(b+(a[0].length-1))})}};p.onblur=function(){this.value=""};p.onkeypress=function(a){if(-1==[48,49,50,51,52,53,54,55,56,57,88,120,65,66,67,68,69,70,97,98,99,100,101,102].indexOf(a.keyCode))return!1;var b=this.selectionStart,c=this.value.substr(b-1,1);if(88==a.keyCode||120==a.keyCode)if(1!=b||"0"!=c)return!1};p.onkeydown=function(a){if(13!=a.keyCode)return!0;a=this.value.trim().toLowerCase();if(0==a.length)return!0;var b=0,b=!1;if("0x"==a.substr(0,2))b=a.substr(2);else for(var c=[97,98,99,
100,101,102],d=0;d<a.length;d++)if(-1!=c.indexOf(a.charCodeAt(d))){b=a;break}b=b?parseInt(b,16):parseInt(a,10);r.showFrom(b);a=r.getSelection();a.setStart(b);a.setStop(b)};p.onpaste=function(a){a.preventDefault();return!1};e.body.onkeydown=function(b){if(67==b.keyCode&&b.ctrlKey){switch(g.getLastHoverType()){case "char":d(e);break;case "byte":m(e)}return!1}70==b.keyCode&&b.ctrlKey&&(e.activeElement!==s&&(l=e.activeElement),s.focus(),s.select());71==b.keyCode&&b.ctrlKey&&(p.focus(),p.select());79==
b.keyCode&&b.ctrlKey&&a()};g.showFrom(u);g.render()}function t(){z=z||this.innerHeight;var a=Math.floor((this.innerHeight-z)/F);a!=E&&(E=a,p(B,D+a,r.getOffset(),r.getSelection()))}var q=!0,u={appName:chrome.runtime.getManifest().name,version:chrome.runtime.getManifest().version},z=0,F=0,D=16,E=0,v=!1,K,B=!1,r,x=!1,A="",J=!1;chrome.app.window.create("window.html",{width:400,height:280},function(d){K=d;v=d.contentWindow;var f=v.document;v.onload=function(){f.getElementById("appTitle").innerHTML=u.appName;
f.getElementById("sitelink").onmouseover=function(){this.style.right="20px"};f.getElementById("sitelink").onmouseout=function(){this.style.right="-64px"};f.body.addEventListener("dragleave",function(a){f.getElementById("dragboundary").className="";a.stopPropagation();a.preventDefault();return!1},!1);var d=f.getElementById("bookmarkName");d.onkeyup=function(){var a=this.getAttribute("_bmIndex");-1!=a&&BookmarkManager.setNameByIndex(a,this.value)};f.getElementById("bookmarkImg").addEventListener("click",
function(){switch(this.src.split("/").pop()){case "bookmark_off.png":this.src="bookmark_on.png";d.style.display="";d.value=BookmarkManager.getNextName();d.focus();d.select();var a=BookmarkManager.add(r.getSelection(),d.value);d.setAttribute("_bmIndex",a);break;case "bookmark_on.png":this.src="bookmark_off.png",d.style.display="none",BookmarkManager.remove(r.getSelection())}h()},!1);f.body.addEventListener("dragover",function(a){f.getElementById("dragboundary").className="draghover";a.stopPropagation();
a.preventDefault();return!1},!1);f.body.addEventListener("drop",function(a){c(a.dataTransfer.files[0]);a.stopPropagation();a.preventDefault();return!1},!1);f.title=u.appName;f.getElementById("startup").style.height=v.innerHeight+"px";v.onresize=function(){f.getElementById("startup").style.height=v.innerHeight+"px"};f.getElementById("bttOpen").onclick=function(){a()};f.getElementById("toolbarOpen").onclick=function(){a()};b();BookmarkManager.on("update",function(){b()})}})});
function GridSelection(b,h){function c(){m=new GridSelection(this.getStart(),this.getStop());"function"==typeof this.onbeforechange&&this.onbeforechange.apply(this,arguments)}function a(){"function"==typeof this.onchange&&this.onchange.apply(this,[this,m])}var d=h,m;b=void 0==b?-1:b;d=void 0==d?-1:d;this.inProgress=!1;this.setStart=function(d){c.apply(this,[]);b=parseInt(d,10);a.apply(this,[])};this.setStop=function(b){c.apply(this,[]);d=parseInt(b,10);a.apply(this,[])};this.getStart=function(){return b<
d?b:d};this.getStop=function(){return d>b?d:b};this.getLength=function(){return!this.exists()?!1:this.getStop()-this.getStart()+1};this.exists=function(){return!(-1==b||-1==d)};this.hasAddress=function(a){return!this.exists()?!1:a>=this.getStart()&&a<=this.getStop()?!0:!1};this.reset=function(){c.apply(this,[]);d=b=-1;a.apply(this,[])};this.getId=function(){return this.getStart()+":"+(this.getStop()-this.getStart()+1)};this.setInProgress=function(a){if(b>d){var c=d;d=b;b=c}this.inProgress=a}}
window.GridSelection=GridSelection;
function HexGrid(b,h,c,a){function d(a){for(var b="",c=0;c<a;c++)b+=".";return b}function m(){if(!j.exists())return!1;for(var a=j.getStart(),b=j.getStop(),c,d,e,f=w.length,g=0;g<f;g++)c=w[g].parentNode,d=k[g].parentNode,e=A+g,e>=a&&e<=b?(c.className="byte selected",d.className="text selected"):(c.className="byte",d.className="text")}function f(a,b){if("function"!=typeof N[a])return!1;N[a].apply(this,b)}function y(a){0<(a.wheelDelta||-1*a.detail)?E(-1):E(1);return!1}function p(a){var b="byte"==this.getAttribute("_type")?
this:this.parentNode.cells[this.cellIndex-16],c=x(b);if(!1===c)return!1;b=16*b.parentNode.rowIndex+(b.cellIndex-1);2==a.button&&f("bytecontext",[{address:c,index:b}]);0==a.button&&(j.setInProgress(!0),j.setStart(c),j.setStop(c))}function t(){if(!j.inProgress)return!1;j.reset()}function q(){if(!j.inProgress)return!1;j.setInProgress(!1)}function u(){var a=this.getAttribute("_type");O=a;var b="byte"==a?this:this.parentNode.cells[this.cellIndex-16],c="byte"==a?"text":"byte",d="byte"==a?16:-16,e=x(b);
if(!1===e)return!1;f("bytehover",[{offset:{address:e,"byte":16*b.parentNode.rowIndex+(b.cellIndex-1)}}]);this.className=a+" highlight";this.parentNode.cells[this.cellIndex+d].className=c+" highlight";if(!j.inProgress)return!1;j.setStop(e)}function z(){var a="byte"==this.getAttribute("_type")?this:this.parentNode.cells[this.cellIndex-16];j.hasAddress(x(a))?(a.className="byte selected",a.parentNode.cells[a.cellIndex+16].className="text selected"):(a.className="byte",a.parentNode.cells[a.cellIndex+16].className=
"text");f("bytehover",[!1])}function F(){var a=Math.ceil(T*this.scrollTop/16);D(16*a,!0)}function D(a,c){a=a||0;0>a&&(a=0);a=parseInt(a,10);var d=a.toString(16);"0"!=d.substr(d.length-1,1)&&(a=parseInt(d.substr(0,d.length-1)+"0",16));a+16*b>h.size&&(a=b>G?0:16*(G-b));var d=new FileReader,e=a+16*b,e=e+7,g=h.slice(a,e);d.onload=function(b){J=b=b.target.result;b=new Uint8Array(b);for(var d=0;d<w.length;d++)if(void 0==b[d])w[d].nodeValue="  ",k[d].nodeValue=" ";else{if(0==d%16){var g=P[d/16],h;for(h=
(d+a).toString(16);8>h.length;)h="0"+h;h=h.toUpperCase();g.nodeValue=h}g=w[d];h=b[d].toString(16);h=1==h.length?"0"+h:h;h=h.toLowerCase();g.nodeValue=h;k[d].nodeValue=-1==Q.indexOf(b[d])?String.fromCharCode(b[d]):"."}A=a;m();f("update",[{offset:a,length:e-7-a}]);c||(C.onscroll=function(){this.onscroll=F},C.scrollTop=Math.floor(A/16/S))};d.readAsArrayBuffer(g)}function E(a){a=parseInt(a,10);D(A+16*a)}function v(a){D(A+16*b*a)}function K(){D(0)}function B(){D(b>G?0:16*(G-b))}function r(){var a=document.createElement("div");
a.style.visibility="hidden";a.style.width="100px";document.body.appendChild(a);var b=a.offsetWidth;a.style.overflow="scroll";var c=document.createElement("div");c.style.width="100%";a.appendChild(c);c=c.offsetWidth;a.parentNode.removeChild(a);return b-c}function x(a){a=A+(16*a.parentNode.rowIndex+(a.cellIndex-1));return a>=h.size?!1:a}if(!h)return!1;var A=0,J=!1,O="",j=a||new GridSelection;j.onchange=function(){f("rangechange",arguments);if(j.exists())m();else for(var a,b,c=w.length,d=0;d<c;d++)a=
w[d].parentNode,b=k[d].parentNode,a.className="byte",b.className="text"};var P=[],w=[],k=[],Q;a=document.createElement("span");document.body.appendChild(a);for(var e=a.offsetWidth,n=[],g=0;256>g;g++)if(32!=g){var l=String.fromCharCode(g).replace(/\s+/g,"");a.innerHTML=l;a.offsetWidth==e&&n.push(g)}a.parentNode.removeChild(a);Q=n;var s=document.createElement("div");s.onkeydown=function(a){switch(a.keyCode){case 36:return K(),!1;case 35:return B(),!1;case 38:return E(-1),!1;case 40:return E(1),!1;case 33:return v(-1),
!1;case 34:return v(1),!1}};var N={};s.addEventListener("mousewheel",y,!1);s.addEventListener("DOMMouseScroll",y,!1);s.style.position="relative";a=document.createElement("table");a.className="hexgrid";a.setAttribute("cellpadding","0");a.setAttribute("cellspacing","0");a.style.fontFamily="monospace";a.style.fontSize="14px";a.style.paddingLeft="10px";a.style.paddingRight="10px";for(e=0;e<b;e++){n=a.insertRow(e);g=n.insertCell(-1);g.className="address";l=document.createTextNode(d(8));P.push(l);g.appendChild(l);
g.style.paddingRight="10px";g.style.paddingTop="2px";g.style.paddingBottom="2px";for(var I,g=0;16>g;g++)l=n.insertCell(-1),l.addEventListener("click",t,!1),l.addEventListener("mousedown",p,!1),l.addEventListener("mouseup",q,!1),l.addEventListener("mouseover",u,!1),l.addEventListener("mouseout",z,!1),l.className="byte",l.setAttribute("_type","byte"),I=document.createTextNode(d(2)),w.push(I),l.appendChild(I);for(g=0;16>g;g++)l=n.insertCell(-1),l.addEventListener("click",t,!1),l.addEventListener("mousedown",
p,!1),l.addEventListener("mouseup",q,!1),l.addEventListener("mouseover",u,!1),l.addEventListener("mouseout",z,!1),l.className="text",l.setAttribute("_type","char"),I=document.createTextNode(d(1)),k.push(I),l.appendChild(I)}var G=Math.ceil(h.size/16);a.style.visibility="hidden";a.style.position="absolute";a.style.top="0px";a.style.left="0px";c.appendChild(a);var H=a.offsetHeight,M=a.offsetWidth;c.removeChild(a);a.style.visibility="visible";var R=Math.floor(H/b),C=document.createElement("div");C.style.position=
"absolute";C.style.top="0px";C.style.left="0px";e=R*G;e>22*H&&(e=22*H+r());n=document.createElement("div");n.style.height=e+"px";n.innerHTML="&nbsp;";n.style.position="absolute";n.style.top="0px";n.style.left="0px";n.style.visibility="hidden";C.appendChild(n);var e=e-H,n=b>G?0:16*(G-b),S=n/16/e,T=n/e;C.onscroll=F;var L=r();C.style.height=H+L+"px";C.style.width=M+L+"px";C.style.overflow="scroll";s.style.overflow="hidden";s.style.height=H+"px";s.appendChild(C);s.style.width=M+L+"px";s.appendChild(a);
return{render:function(){c.appendChild(s);s.setAttribute("tabindex","1");s.style.outline="none";s.focus();return s},getDimensions:function(){return{height:H,width:M+L,row:{height:R,count:b}}},getElementsByIndex:function(a){return!w[a]||!k[a]?!1:{"byte":w[a].parentNode,"char":k[a].parentNode}},getLastHoverType:function(){return O},getOffset:function(){return A},getSize:function(){return 16*b},getBuffer:function(){return J},getSelection:function(){return j},showFrom:D,scrollBy:E,scrollByPage:v,scrollToTop:K,
scrollToBottom:B,on:function(a,b){N[a]=b}}}window.HexGrid=HexGrid;