window.onresize=doLayout;var isLoading=!1;window.addEventListener("message",messageHandler);
onload=function(){var a=document.querySelector("webview");window.top.postMessage({loaded:!0},"*");doLayout();document.querySelector("#back").onclick=function(){a.back()};document.querySelector("#forward").onclick=function(){a.forward()};document.querySelector("#home").onclick=function(){navigateTo("http://www.thingiverse.com/explore")};document.querySelector("#close").onclick=function(){window.close()};a.addEventListener("exit",handleExit);a.addEventListener("loadstart",handleLoadStart);a.addEventListener("loadstop",
handleLoadStop);a.addEventListener("loadabort",handleLoadAbort);a.addEventListener("loadredirect",handleLoadRedirect);a.addEventListener("loadcommit",handleLoadCommit);a.addEventListener("newwindow",handleNewWindow);a.addEventListener("permissionrequest",handlePermisssion)};
function updateButtons(){var a=document.querySelector("webview"),c=document.querySelector("#back"),b=document.querySelector("#forward");a.canGoForward()?b.className=b.className.replace(" inactive",""):0>b.className.search("inactive")&&(b.className+=" inactive");a.canGoBack()?c.className=b.className.replace(" inactive",""):0>b.className.search("inactive")&&(c.className+=" inactive")}
function navigateTo(a){a!=document.querySelector("webview").src&&(resetExitedState(),document.querySelector("webview").src=a)}function doLayout(){var a=document.querySelector("webview"),c=document.querySelector("#controls").offsetHeight,b=document.documentElement.clientWidth,c=document.documentElement.clientHeight-c;a.style.width=b+"px";a.style.height=c+"px";a=document.querySelector("#sad-webview");a.style.width=b+"px";a.style.height=2*c/3+"px";a.style.paddingTop=c/3+"px"}
function handleExit(a){console.log(a.type);document.body.classList.add("exited");"abnormal"==a.type?(document.body.classList.add("crashed"),window.top.postMessage({exit:"crashed"},"*")):"killed"==a.type?(document.body.classList.add("killed"),window.top.postMessage({exit:"killed"},"*")):window.top.postMessage({exit:"exited"},"*")}function resetExitedState(){document.body.classList.remove("exited");document.body.classList.remove("crashed");document.body.classList.remove("killed")}
function handleLoadCommit(a){document.querySelector("webview");window.top.postMessage({commit:a.url,webview:document.querySelector("webview").src},"*");resetExitedState();updateButtons();a.isTopLevel&&(document.querySelector("#location").value=a.url,document.querySelector("webview"))}function handleLoadStart(a){document.body.classList.add("loading");isLoading=!0;resetExitedState();a.isTopLevel&&(document.querySelector("#location").value=a.url)}function handleLoadStop(a){isLoading=!1}
function handleLoadAbort(a){window.top.postMessage({exit:a.reason},"*")}function handleLoadRedirect(a){resetExitedState();window.top.postMessage({redirect:a.newUrl},"*");a.isTopLevel&&(document.querySelector("#location").value=a.newUrl)}function handleNewWindow(a){resetExitedState();window.top.postMessage({newWindow:a.targetUrl},"*")}function handlePermisssion(a){resetExitedState();window.top.postMessage({permission:a.targetUrl},"*")}
function messageHandler(a){a&&a.data&&(a.data.navigateToUrl?navigateTo(a.data.navigateToUrl):a.data.reloadPage&&webview.reload())};
