var loaderAppId="khnneiggiaikbpmcicnaahnfofmcbbno",loaderAppId="dfmkjkgollnjopffnjfihgoibkicjpdo",loaderAppId="hjgibfcoeomknakfhedjmlkakgelnecf",viewAppId="hjmjdncmpkmdamcodbechlebmednfdhj",viewAppId="banggchkbjdemfnfjlkpbndnnbljkpfb",viewAppId="hhngciknjebkeffhafnaodkfidcdlcao",loaderAppURL="https://chrome.google.com/webstore/detail/click-to-open-3d/hjgibfcoeomknakfhedjmlkakgelnecf",supportedGoogleDrive=!1;chrome.identity&&(supportedGoogleDrive=!0);window.navigator.userAgent.match(/Chrome\/(.*?) /)[1];
var chromeVersion=parseInt(window.navigator.userAgent.match(/Chrome\/(\d+)\./)[1],10);
try{var initAnalyticsConfig=function(a){gAnalyticsConfig=a},gAnalyticsService=analytics.getService("3DView"),gAnalyticsTracker=gAnalyticsService.getTracker("UA-52966819-2"),gAnalyticsConfig=null;gAnalyticsService.getConfig().addCallback(initAnalyticsConfig);gAnalyticsTracker.sendAppView("MainView");var gAliveTiming=gAnalyticsTracker.startTiming("3DView","Alive");gAnalyticsTracker.sendEvent("Browsing","Browsed the app");chromeVersion&&gAnalyticsTracker.sendEvent("System","Version",chromeVersion.toString())}catch(a){}
function sendViewStatistic(a){gAnalyticsTracker&&gAnalyticsTracker.sendAppView(a)}function sendEventStatistic(a,c,b,d){gAnalyticsTracker&&gAnalyticsTracker.sendEvent(a,c,b,d)}function sendExceptionStatistic(a){gAnalyticsTracker&&gAnalyticsTracker.sendException(a.toString());console.log("Exception",a)}var port=chrome.runtime.connect(loaderAppId);port.postMessage({launched:!0});var tipDialog=new TipDialog;tipDialog.loadStatus(function(a){tipDialog.showAtStartup()&&tipDialog.open()});
zip.workerScriptsPath="js/Zip/";zip.useWebWorkers=!0;var extensionInstalled=!1,extensionEnabled=!1;function checkExtension(){try{chrome.storage.local.get("extension_installed_time",function(a){extensionInstalled=void 0!==a.extension_installed_time})}catch(a){console.log(a)}}checkExtension();window.URL=window.URL||window.webkitURL;window.BlobBuilder=window.BlobBuilder||window.WebKitBlobBuilder||window.MozBlobBuilder;var notifications=new Notifications,editor=new Editor(notifications),viewport=new Viewport(editor);
viewport.setTop("32px");viewport.setLeft("0px");viewport.setRight("308px");viewport.setBottom("0px");viewport.setOpacity("0");document.body.appendChild(viewport.dom);var menubar=new Menubar(editor);menubar.setWidth("100%");menubar.setHeight("32px");menubar.setOpacity("0");document.body.appendChild(menubar.dom);var sidebarDiv=(new UI.Panel).setId("sidebar-div");sidebarDiv.setDisplay("block");sidebarDiv.setTop("0px");sidebarDiv.setBottom("0px");sidebarDiv.setRight("0px");sidebarDiv.setOpacity("0");
document.body.appendChild(sidebarDiv.dom);var sidebarDivButton=(new UI.Panel).setId("sidebar-div-button");sidebarDivButton.setTextContent(String.fromCharCode(9658));sidebarDiv.add(sidebarDivButton);sidebarDiv.show=!0;var sidebar=new Sidebar(editor);sidebar.setRight("0px");sidebar.setTop("0px");sidebar.setBottom("0px");sidebarDiv.add(sidebar);
function getSidebarOptions(){try{chrome.storage.local.get("sidebar_shown",function(a){sidebarDiv.show=!1!==a.sidebar_shown;updateSidebar()})}catch(a){console.log(a)}}getSidebarOptions();
function updateSidebar(){sidebarDiv.show?(viewport.setRight("308px"),sidebarDivButton.setTextContent(String.fromCharCode(9658)),sidebarDivButton.setRight("300px"),sidebarDiv.setWidth("308px"),sidebar.setRight("0px")):(viewport.setRight("8px"),sidebarDivButton.setTextContent(String.fromCharCode(9668)),sidebarDivButton.setRight("6px"),sidebarDiv.setWidth("14px"),sidebar.setRight("-302px"));editor.signals.windowResize.dispatch()}
sidebarDivButton.onClick(function(a){sidebarDiv.show=sidebarDiv.show?!1:!0;updateSidebar();try{chrome.storage.local.set({sidebar_shown:sidebarDiv.show})}catch(c){console.log(c)}});var colorPicker=(new UI.Panel).setId("picker").setClass("color-picker").setDisplay("none");document.body.appendChild(colorPicker.dom);$("#picker").farbtastic(function(a){editor.signals.changeBackgroundColor.dispatch(a)});
document.addEventListener("dragover",function(a){a.preventDefault();a.dataTransfer.dropEffect="copy"},!1);document.addEventListener("drop",function(a){a.preventDefault();editor.loader.loadFile(a.dataTransfer.files[0])},!1);
document.addEventListener("keydown",function(a){switch(a.keyCode){case 46:editor.signals.deleteObject.dispatch();break;case 65:a.ctrlKey?(editor.signals.nest.dispatch(),sendEventStatistic("Printing","Nest","Shortcut")):a.altKey?(editor.signals.measureAngle.dispatch(),sendEventStatistic("Measure","Angle","Shortcut")):(editor.signals.toggleWallThickness.dispatch(),sendEventStatistic("View","Structural Analysis","Shortcut"));break;case 66:a.shiftKey?(editor.signals.createBridge.dispatch(),sendEventStatistic("Fixing",
"Create Bridge","Shortcut")):(editor.signals.transformModeChanged.dispatch("bottom"),sendEventStatistic("Edit","Set bottom","Shortcut"));break;case 67:a.ctrlKey&&(editor.signals.cloneObject.dispatch(),sendEventStatistic("Edit","Clone","Shortcut"));break;case 68:a.ctrlKey?(T.FileOperations.googleDrive(),sendEventStatistic("File","GoogleDrive","Shortcut")):a.altKey&&(editor.signals.measureDistance.dispatch(),sendEventStatistic("Measure","Distance","Shortcut"));break;case 71:a.ctrlKey&&a.shiftKey?(editor.signals.ungroup.dispatch(),
sendEventStatistic("Edit","Ungroup","Shortcut")):a.ctrlKey?(editor.signals.group.dispatch(),sendEventStatistic("Edit","Group","Shortcut")):(editor.signals.toggleTriangleVisualization.dispatch(),editor.signals.saveUI.dispatch(),sendEventStatistic("View","Triangles","Shortcut"));break;case 72:a.shiftKey?(editor.signals.fillHole.dispatch(),sendEventStatistic("Fixing","Fill Hole","Shortcut")):(editor.signals.toggleBadEdges.dispatch(),editor.signals.saveUI.dispatch(),sendEventStatistic("View","Bad edges",
"Shortcut"));break;case 73:a.ctrlKey&&a.shiftKey?(editor.signals.rescaleSelected.dispatch(1/25.4),editor.signals.unzoomCamera.dispatch(),sendEventStatistic("Units","MM to inch","Shortcut")):a.shiftKey?(editor.signals.invertNormals.dispatch(),sendEventStatistic("Fixing","Invert Normals","Shortcut")):(editor.signals.toggleInvertedTriangles.dispatch(),editor.signals.saveUI.dispatch(),sendEventStatistic("View","Inverted","Shortcut"));break;case 76:a.ctrlKey&&(T.FileOperations.importFile(editor),sendEventStatistic("File",
"Import","Shortcut"));break;case 77:a.ctrlKey&&a.shiftKey?(editor.signals.rescaleSelected.dispatch(25.4),editor.signals.unzoomCamera.dispatch(),sendEventStatistic("Units","Inch to mm","Shortcut")):a.ctrlKey&&(editor.signals.mirrorObject.dispatch(),sendEventStatistic("Edit","Mirror","Shortcut"));break;case 78:a.ctrlKey&&a.altKey?(editor.signals.resetView.dispatch(),sendEventStatistic("File","New","Shortcut")):a.shiftKey?(editor.signals.fixNormals.dispatch(),sendEventStatistic("Fixing","Fix Normals",
"Shortcut")):a.altKey&&(editor.signals.measureAnnotation.dispatch(),sendEventStatistic("Measure","Annotation","Shortcut"));break;case 82:a.shiftKey?(editor.signals.reduce.dispatch(),sendEventStatistic("Fixing","Reduce","Shortcut")):a.altKey?(editor.signals.measureRadius.dispatch(),sendEventStatistic("Measure","Radius","Shortcut")):(editor.signals.spaceChanged.dispatch("world"),editor.signals.transformModeChanged.dispatch("rotate"),sendEventStatistic("Edit","Rotate","Shortcut"));break;case 83:a.ctrlKey?
(T.FileOperations.exportScene(editor),sendEventStatistic("File","Export all","Shortcut")):a.shiftKey?(editor.signals.stitch.dispatch(),sendEventStatistic("Fixing","Stitch","Shortcut")):(editor.signals.transformModeChanged.dispatch("scale"),sendEventStatistic("Edit","Scale","Shortcut"));break;case 84:a.ctrlKey?(T.FileOperations.thingiverse(),sendEventStatistic("File","Thingiverse","Shortcut")):a.altKey?(editor.signals.measureThickness.dispatch(),sendEventStatistic("Measure","Thickness","Shortcut")):
(editor.signals.spaceChanged.dispatch("world"),editor.signals.transformModeChanged.dispatch("translate"),sendEventStatistic("Edit","Translate","Shortcut"));break;case 85:editor.signals.unzoomCamera.dispatch();sendEventStatistic("View","Unzoom","Menu");break;case 89:a.ctrlKey&&(editor.history.redo(),sendEventStatistic("Edit","Redo","Shortcut"));break;case 90:a.ctrlKey&&(editor.history.undo(),sendEventStatistic("Edit","Undo","Shortcut"));break;case 112:openHelp("index.html");break;case 107:editor.signals.zoomInCamera.dispatch();
break;case 109:editor.signals.zoomOutCamera.dispatch()}},!1);var onWindowClose=function(){T.FileOperations.closeGoogleDrive();T.FileOperations.closeThingiverse();T.FileOperations.closeAllShareWindows();helpWindow&&null!==helpWindow&&helpWindow.close();gAliveTiming&&gAliveTiming.send()};
window.onload=function(a){chrome.app.window.current().onClosed.addListener(onWindowClose);editor.scene&&editor.scene instanceof T.Platform&&editor.scene.loadFromDefaultProfile(function(){editor.signals.loadUI.dispatch(function(){editor.signals.renderHelpers.dispatch()});editor.signals.unzoomCamera.dispatch();editor.signals.sceneGraphChanged.dispatch();editor.signals.renderHelpers.dispatch();editor.scene.sendStatistic("start")});setTimeout(function(){viewport.setOpacity("1");menubar.setOpacity("1");
sidebarDiv.setOpacity("1")},10)};var onWindowResize=function(a){editor.signals.windowResize.dispatch()};window.addEventListener("resize",onWindowResize,!1);onWindowResize();var hash=window.location.hash.substr(1);if(""!==hash&&"A/"===hash.substr(0,2)){var string=RawDeflate.inflate(window.atob(hash.substr(2)));if(string){var json=JSON.parse(string),scene=(new T.ObjectLoader).parse(json);editor.setScene(scene)}}
chrome.runtime.onMessageExternal.addListener(function(a,c,b){if(c.id!=loaderAppId)return!0;if(!extensionInstalled){try{var d=(new Date).getTime();chrome.storage.local.set({extension_installed_time:d})}catch(e){console.log(e)}extensionInstalled=!0}extensionEnabled=!0;if(a.launched||a.alive)return b({ok:!0}),!0;if(a.url&&a.filename)return b({ok:!0}),tipDialog.cancel(),console.log("got url: "+a.url),sendEventStatistic("Load","External","Url"),setTimeout(function(){editor.loader.loadUrl(a.url,a.filename,
!1,function(){editor.signals.reloadComments.dispatch(a.url);editor.signals.unzoomCamera.dispatch();chrome.app.window.current().drawAttention()})},10),!0;if(a.content_supported)return b({ok:!0}),!0;if(a.content&&a.filename)return tipDialog.cancel(),console.log("got content: "+a.filename),sendEventStatistic("Load","External","Data"),setTimeout(function(){editor.loader.loadData(a.content,a.filename,function(){b({ok:!0});editor.signals.reloadComments.dispatch(a.contentUrl);editor.signals.unzoomCamera.dispatch();
chrome.app.window.current().show();chrome.app.window.current().focus();chrome.app.window.current().drawAttention()})},10),!0;b({ok:!1});return!0});function setupReminders(){notifications.remind('Consider "Click to open 3D"',"Want to open files in 3DView from the web? Click here to get Chrome extension.",1E4,9E5,6048E5,!0,function(){window.open(loaderAppURL,"_blank")},function(){return!extensionInstalled})}setupReminders();
