var Editor=function(a){var b=signals;this.signals={playAnimations:new b.Signal,loadUI:new b.Signal,saveUI:new b.Signal,toggleBadEdges:new b.Signal,toggleTriangleVisualization:new b.Signal,toggleInvertedTriangles:new b.Signal,toggleWallThickness:new b.Signal,togglePrinterVisibility:new b.Signal,toggleGridVisibility:new b.Signal,changeBackgroundColor:new b.Signal,updateWallThickness:new b.Signal,updateXRay:new b.Signal,nest:new b.Signal,cloneObject:new b.Signal,mirrorObject:new b.Signal,deleteObject:new b.Signal,
group:new b.Signal,ungroup:new b.Signal,splitShells:new b.Signal,mergeChildren:new b.Signal,reduce:new b.Signal,removeSharpTriangles:new b.Signal,fixNormals:new b.Signal,invertNormals:new b.Signal,stitch:new b.Signal,fillHole:new b.Signal,createBridge:new b.Signal,smooth:new b.Signal,resetTransform:new b.Signal,rescaleSelected:new b.Signal,resetView:new b.Signal,zoomInCamera:new b.Signal,zoomOutCamera:new b.Signal,unzoomCamera:new b.Signal,setDefaultView:new b.Signal,transformModeChanged:new b.Signal,
snapChanged:new b.Signal,spaceChanged:new b.Signal,rendererChanged:new b.Signal,restoreMeasurement:new b.Signal,measureDistance:new b.Signal,measureThickness:new b.Signal,measureAngle:new b.Signal,measureRadius:new b.Signal,measureAnnotation:new b.Signal,googleDriveCommentsChanged:new b.Signal,reloadComments:new b.Signal,sceneGraphChanged:new b.Signal,editorChanged:new b.Signal,historyUndo:new b.Signal,historyRedo:new b.Signal,historyAdded:new b.Signal,historyCleared:new b.Signal,objectSelected:new b.Signal,
objectMarked:new b.Signal,objectUnmarked:new b.Signal,objectAdded:new b.Signal,objectChanged:new b.Signal,objectChanging:new b.Signal,objectRemoved:new b.Signal,helperAdded:new b.Signal,helperRemoved:new b.Signal,renderHelpers:new b.Signal,materialChanged:new b.Signal,clearColorChanged:new b.Signal,fogTypeChanged:new b.Signal,fogColorChanged:new b.Signal,fogParametersChanged:new b.Signal,windowResize:new b.Signal};this.history=new History(this);this.notifications=a;this.loader=new Loader(this);this.scene=
new T.Platform;this.sceneHelpers=new T.Scene;this.sceneOrtho=new T.Scene;this.object={};this.geometries={};this.materials={};this.textures={};this.selected=null;this.marked=[];this.helpers={}};
Editor.prototype={setScene:function(a){this.scene.name=a.name;this.scene.userData=JSON.parse(JSON.stringify(a.userData));this.marked=[];for(this.history.clear();0<a.children.length;)this.addObject(a.children[0])},addObject:function(a,b){var d=this,k=0,l=0,e=0;b=b?b:this.scene;a.traverse(function(a){void 0!==a.geometry&&d.addGeometry(a.geometry);void 0!==a.material&&d.addMaterial(a.material);d.addHelper(a);void 0!==a.geometry&&(k+=a.geometry.vertices.length,l+=a.geometry.faces.length);++e});sendEventStatistic("Geometry",
"Add","Vertices",k);sendEventStatistic("Geometry","Add","Faces",l);sendEventStatistic("Geometry","Add","Children",e);b.add(a);this.signals.objectAdded.dispatch(a);this.signals.sceneGraphChanged.dispatch();T.GeometryUtils.resetGlobalBoundingBox(a)},removeObject:function(a){if(void 0!==a&&null!==a&&void 0!==a.parent){var b=this;T.GeometryUtils.resetGlobalBoundingBox(a);a.traverse(function(a){b.removeHelper(a)});a.parent.remove(a);this.unmark(a);this.signals.objectRemoved.dispatch(a);this.signals.sceneGraphChanged.dispatch()}},
addGeometry:function(a){this.geometries[a.uuid]=a},addMaterial:function(a){this.materials[a.uuid]=a},addTexture:function(a){this.textures[a.uuid]=a},addHelper:function(){new T.SphereGeometry(20,4,2);new T.MeshBasicMaterial({color:16711680});return function(a){}}(),removeHelper:function(a){if(void 0!==this.helpers[a.id]){var b=this.helpers[a.id];b.parent.remove(b);delete this.helpers[a.id];this.signals.helperRemoved.dispatch(b)}},parent:function(a,b){void 0===b&&(b=this.scene);b.add(a);this.signals.sceneGraphChanged.dispatch()},
select:function(a){a!=this.selected&&(this.selected&&!this.hasMarked()&&this.selected.traverse(function(a){a.selected=!1}),(this.selected=a)&&!this.hasMarked()&&this.selected.traverse(function(a){a.selected=!0}),this.signals.objectSelected.dispatch(a))},getObjectById:function(a){var b=null;this.scene.traverse(function(d){d.id===a&&(b=d)});return b},selectById:function(a){this.select(this.getObjectById(a))},deselect:function(){this.select(null)},mark:function(a){a=a?a instanceof Array?a:[a]:this.marked;
for(var b in a){var d=a[b];d&&-1==this.marked.indexOf(d)&&(this.marked.push(d),d.traverse(function(a){a.selected=!0}),this.signals.objectMarked.dispatch(d))}this.selected&&!this.isMarked(this.selected)&&this.selected.traverse(function(a){a.selected=!1});this.signals.materialChanged.dispatch()},setMark:function(a){var b=this.marked.slice(0),d=this;this.mark(a);this.unmark(b.filter(function(b){return!d.isMarked(b,a)}))},isMarked:function(a,b){b=b?b:this.marked;return 0<b.filter(function(b){return b.id==
a.id}).length},parentIsMarked:function(a){for(a=a.parent;a;a=a.parent)if(this.isMarked(a))return!0;return!1},parentIsSelected:function(a){for(a=a.parent;a;a=a.parent)if(a==this.selected)return!0;return!1},hasMarked:function(){return 0<this.marked.length},markByIds:function(a){var b=[],d;for(d in a)b.push(this.getObjectById(parseInt(a[d])));this.mark(b)},setMarkByIds:function(a){var b=[],d;for(d in a){var k=this.getObjectById(parseInt(a[d]));k&&b.push(k)}this.setMark(b)},unmark:function(a){var b=this;
a=a?a instanceof Array?a:[a]:this.marked;var d=[],k;for(k in a){var l=a[k],e=this.marked.indexOf(l);l&&-1!=e&&(this.marked.splice(e,1),d.push(l))}var q=this.hasMarked();for(k in d)l=a[k],this.parentIsMarked(l)||!q&&this.parentIsSelected(l)||l.traverse(function(a){b.isMarked(a)||!q&&a==b.selected||(a.selected=!1)}),this.signals.objectUnmarked.dispatch(l);this.selected&&!this.hasMarked()&&this.selected.traverse(function(a){a.selected=!0});this.signals.materialChanged.dispatch()},getTopLevelMarked:function(){var a=
this.marked.slice(0),b;for(b in a){var d=a[b];d.traverse(function(b){d!=b&&(b=a.indexOf(b),-1!=b&&a.splice(b,1))})}return a},defaultHistoryBehaviour:function(a,b,d,k,l){var e=this;return function(){editor.history.add(function(){if(k){for(var d=[],g=[],h=[],l=[],c=0;c<a.length;++c)a[c].newObject&&d.push(a[c].newObject),a[c].newParent&&g.push(a[c].newParent),a[c].oldObject&&h.push(a[c].oldObject),a[c].oldParent&&l.push(a[c].oldParent);k(h,l,d,g)}else for(c=0;c<a.length;++c)b?b(a[c].oldObject,a[c].oldParent,
a[c].newObject,a[c].newParent,a[c].parameters):(d=e.history.isRecording,e.history.isRecording=!1,a[c].newObject&&e.removeObject(a[c].newObject),a[c].oldObject&&e.addObject(a[c].oldObject,a[c].oldParent),a[c].oldObject instanceof T.Measurement&&e.signals.restoreMeasurement.dispatch(a[c].oldObject),e.selected&&(a[c].newObject&&a[c].newObject.id==e.selected.id?e.select(a[c].oldObject):e.select(null)),e.signals.materialChanged.dispatch(),e.history.isRecording=d)},function(){if(l){for(var b=[],g=[],h=
[],k=[],c=0;c<a.length;++c)a[c].newObject&&b.push(a[c].newObject),a[c].newParent&&g.push(a[c].newParent),a[c].oldObject&&h.push(a[c].oldObject),a[c].oldParent&&k.push(a[c].oldParent);l(h,k,b,g)}else for(c=0;c<a.length;++c)d?d(a[c].oldObject,a[c].oldParent,a[c].newObject,a[c].newParent,a[c].parameters):(b=e.history.isRecording,e.history.isRecording=!1,a[c].oldObject&&e.removeObject(a[c].oldObject),a[c].newObject&&e.addObject(a[c].newObject,a[c].newParent),a[c].newObject instanceof T.Measurement&&e.signals.restoreMeasurement.dispatch(a[c].newObject),
e.selected&&(a[c].newObject&&a[c].oldObject.id==e.selected.id?e.select(a[c].newObject):e.select(null)),e.signals.materialChanged.dispatch(),e.history.isRecording=b)},function(d){if(!k)for(var e=0;e<a.length;++e)if(!b&&a[e].oldObject!=a[e].newObject){var h="new"==d?a[e].newObject:a[e].oldObject;h&&T.GeometryUtils.disposeObject(h)}a=[]})}},applySequentialOperation:function(a,b,d,k,l,e,q){var g=[],h=this,n=this.getTopLevelMarked(),c=T.SceneUtils.wireframeMaterial.visible,r=[];b=b&&b[0]?b:this.hasMarked()?
n:!this.selected||this.selected instanceof T.PerspectiveCamera?this.scene.children:[this.selected];b=b.filter(function(a){return a&&a instanceof T.Object3D});for(var m=0;m<b.length;++m){var f=b[m],t={objectId:f.id,oldObject:f,oldParent:f?f.parent:null,parameters:q};k&&c&&T.SceneUtils.updateTriangleVisualization(f,!1);var v=function(a){h.history.isRecording=!1;t.newObject=a;t.newParent=a?a.parent:null;r.push(t);r.length==b.length&&h.defaultHistoryBehaviour(r,l,e).call(this);a&&(g.push(a),h.selected&&
f.id==h.selected.id&&h.select(a),f.id!==a.id&&h.isMarked(f,n)&&(h.unmark(f),h.mark(a)),f=a);k&&c&&T.SceneUtils.updateTriangleVisualization(f,!0);try{d&&d(a)}catch(w){sendExceptionStatistic(w)}h.history.isRecording=u},u=h.history.isRecording;h.history.isRecording=!1;var x=a(f,d?v:null);d||v(x)}return g},applyParallelOperation:function(a,b,d,k,l,e,q){var g=[],h=this,n=this.getTopLevelMarked(),c=[],r=T.SceneUtils.wireframeMaterial.visible,m=[];b=b&&b[0]?b:this.hasMarked()?n:!this.selected||this.selected instanceof
T.PerspectiveCamera?this.scene.children:[this.selected];for(g=0;g<b.length;++g){var f=b[g];f&&f instanceof T.Object3D&&(k&&r&&T.SceneUtils.updateTriangleVisualization(f,!1),c[f.id]=f.parent)}var f=function(a,b,d){return function(b,f){for(var g=0,n=Math.max(f?f.length:0,b?b.length:0);g<n;++g){var p=f&&g<f.length?f[g]:null,m=b&&g<b.length?b[g]:null;a.push({objectId:p?p.id:null,oldObject:p,oldParent:p?c[p.id]:null,newObject:m,newParent:m?m.parent:null,parameters:q})}h.defaultHistoryBehaviour(a,null,
null,l,e).call(this);b&&(h.unmark(f),h.mark(b),f=b);if(k&&r)for(g=0;g<f.length;++g)(p=f[g])&&p instanceof T.Object3D&&T.SceneUtils.updateTriangleVisualization(p,!0);try{d&&d(b?b:f,f)}catch(u){sendExceptionStatistic(u)}h.history.isRecording=t}},t=h.history.isRecording;h.history.isRecording=!1;g=a(b,d?f(m,n,d):null);d||f(m,n).call(this,g,b);return g},getObjectType:function(a){var b={Platform:T.Platform,Scene:T.Scene,PerspectiveCamera:T.PerspectiveCamera,AmbientLight:T.AmbientLight,DirectionalLight:T.DirectionalLight,
HemisphereLight:T.HemisphereLight,PointLight:T.PointLight,SpotLight:T.SpotLight,Mesh:T.Mesh,Object3D:T.Object3D},d;for(d in b)if(a instanceof b[d])return d},getGeometryType:function(a){var b={CircleGeometry:T.CircleGeometry,CubeGeometry:T.CubeGeometry,CylinderGeometry:T.CylinderGeometry,ExtrudeGeometry:T.ExtrudeGeometry,IcosahedronGeometry:T.IcosahedronGeometry,LatheGeometry:T.LatheGeometry,OctahedronGeometry:T.OctahedronGeometry,ParametricGeometry:T.ParametricGeometry,PlaneGeometry:T.PlaneGeometry,
PolyhedronGeometry:T.PolyhedronGeometry,ShapeGeometry:T.ShapeGeometry,SphereGeometry:T.SphereGeometry,TetrahedronGeometry:T.TetrahedronGeometry,TextGeometry:T.TextGeometry,TorusGeometry:T.TorusGeometry,TorusKnotGeometry:T.TorusKnotGeometry,TubeGeometry:T.TubeGeometry,Geometry:T.Geometry,BufferGeometry:T.BufferGeometry},d;for(d in b)if(a instanceof b[d])return d},getMaterialType:function(a){var b={LineBasicMaterial:T.LineBasicMaterial,LineDashedMaterial:T.LineDashedMaterial,MeshBasicMaterial:T.MeshBasicMaterial,
MeshDepthMaterial:T.MeshDepthMaterial,MeshFaceMaterial:T.MeshFaceMaterial,MeshLambertMaterial:T.MeshLambertMaterial,MeshNormalMaterial:T.MeshNormalMaterial,MeshPhongMaterial:T.MeshPhongMaterial,ParticleBasicMaterial:T.ParticleBasicMaterial,ParticleCanvasMaterial:T.ParticleCanvasMaterial,ShaderMaterial:T.ShaderMaterial,Material:T.Material},d;for(d in b)if(a instanceof b[d])return d}};
