var HUD=function(b,g){var c=new T.HUDControls(g);c.addEventListener("change",function(){b.signals.renderHelpers.dispatch()});c.boundingClientRect.left=0;c.boundingClientRect.right=850;c.boundingClientRect.top=0;c.boundingClientRect.bottom=450;var d=new T.SpriteGizmo(function(a){0==a?b.signals.setDefaultView.dispatch("top"):b.signals.setDefaultView.dispatch("bottom");d.nextSprite()});d.setPosition(40,25);d.setScale(1,1);c.add(d);d.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/top.png",.7,"Top view");
d.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/top_arrow.png",1,"Top view");d.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/top_arrow_select.png",1,"Top view");d.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/top.png",.7,"Bottom view");d.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/bottom_arrow.png",1,"Bottom view");d.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/bottom_arrow_select.png",1,"Bottom view");var e=new T.SpriteGizmo(function(a){0==a?b.signals.setDefaultView.dispatch("left"):
b.signals.setDefaultView.dispatch("right");e.nextSprite()});e.setPosition(24,47);e.setScale(1,1);c.add(e);e.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/left.png",.7,"Left view");e.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/left_arrow.png",1,"Left view");e.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/left_arrow_select.png",1,"Left view");e.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/left.png",.7,"Right view");e.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/right_arrow.png",
1,"Right view");e.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/right_arrow_select.png",1,"Right view");var f=new T.SpriteGizmo(function(a){0==a?b.signals.setDefaultView.dispatch("front"):b.signals.setDefaultView.dispatch("back");f.nextSprite()});f.setPosition(56,47);f.setScale(1,1);c.add(f);f.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/front.png",.7,"Front view");f.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/front_arrow.png",1,"Front view");f.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/front_arrow_select.png",
1,"Front view");f.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/front.png",.7,"Back view");f.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/back_arrow.png",1,"Back view");f.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/back_arrow_select.png",1,"Back view");var a=new T.SpriteGizmo(function(){b.history.undo();sendEventStatistic("Edit","Undo","HUD")},"undo");a.setPosition(26,84);a.setScale(.5,.8);c.add(a);a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/undo.png",.1,"Undo");a.addImage(T.SpriteGizmo.HIGHLIGHT,
"/assets/buttons/undo.png",.1,"Undo");a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/undo_click.png",.1,"Undo");a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/undo.png",.6,"Undo");a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/undo.png",1,"Undo");a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/undo_click.png",1,"Undo");a=new T.SpriteGizmo(function(){b.history.redo();sendEventStatistic("Edit","Redo","HUD")},"redo");a.setPosition(53,84);a.setScale(.5,.8);c.add(a);a.addImage(T.SpriteGizmo.INACTIVE,
"/assets/buttons/redo.png",.1,"Redo");a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/redo.png",.1,"Redo");a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/redo_click.png",.1,"Redo");a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/redo.png",.6,"Redo");a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/redo.png",1,"Redo");a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/redo_click.png",1,"Redo");a=new T.SpriteGizmo(function(){T.FileOperations.importFile(b);sendEventStatistic("File","Import",
"HUD")});a.setPosition(40,130);a.setScale(.5,1);c.add(a);a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/open.png",.6,"Import");a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/open.png",1,"Import");a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/open_click.png",1,"Import");a=new T.SpriteGizmo(function(){T.FileOperations.exportScene(b);sendEventStatistic("File","Export all","HUD")});a.setPosition(40,180);a.setScale(.5,1);c.add(a);a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/save.png",
.5,"Export all as single file");a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/save.png",1,"Export all as single file");a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/save_click.png",1,"Export all as single file");a=new T.SpriteGizmo(function(){T.FileOperations.thingiverse();sendEventStatistic("File","Thingiverse","HUD")});a.setPosition(40,260);a.setScale(.5,1);c.add(a);a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/open_thing.png",.6,"Open - Thingiverse");a.addImage(T.SpriteGizmo.HIGHLIGHT,
"/assets/buttons/open_thing_color.png",1,"Open - Thingiverse");a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/open_thing_color_click.png",1,"Open - Thingiverse");supportedGoogleDrive?(a=new T.SpriteGizmo(function(){T.FileOperations.googleDrive();sendEventStatistic("File","GoogleDrive","HUD")}),a.setPosition(40,310),a.setScale(.5,1),c.add(a),a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/open_drive.png",.5,"Open - Google Drive"),a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/open_drive_color.png",
1,"Open - Google Drive"),a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/open_drive_color_click.png",1,"Open - Google Drive")):(a=new T.SpriteGizmo(function(){}),a.setPosition(40,310),a.setScale(.5,1),c.add(a),a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/open_drive.png",.3,"Google Drive not supported - update to Chrome v.31"),a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/open_drive.png",.5,"Google Drive not supported - update to Chrome v.31"),a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/open_drive.png",
.5,"Google Drive not supported - update to Chrome v.31"));supportedGoogleDrive?(a=new T.SpriteGizmo(function(){T.FileOperations.shareScene(b);sendEventStatistic("File","Share","HUD")}),a.setPosition(40,360),a.setScale(.5,1),c.add(a),a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/share.png",.6,"Upload and Share on Google Drive"),a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/share.png",1,"Upload and Share on Google Drive"),a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/share_click.png",
1,"Upload and Share on Google Drive")):(a=new T.SpriteGizmo(function(){}),a.setPosition(40,360),a.setScale(.5,1),c.add(a),a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/share.png",.3,"Sharing not supported - update to Chrome v.31"),a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/share.png",.5,"Sharing not supported - update to Chrome v.31"),a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/share.png",.5,"Sharing not supported - update to Chrome v.31"));a=new T.SpriteGizmo(function(){b.signals.spaceChanged.dispatch("world");
b.signals.transformModeChanged.dispatch("translate");sendEventStatistic("Edit","Translate","HUD")});a.setPosition(130,30);a.setScale(.5,1);c.add(a);a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/translate.png",.5,"Translate");a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/translate.png",1,"Translate");a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/translate_click.png",1,"Translate");a=new T.SpriteGizmo(function(){b.signals.spaceChanged.dispatch("world");b.signals.transformModeChanged.dispatch("rotate");
sendEventStatistic("Edit","Rotate","HUD")});a.setPosition(180,30);a.setScale(.5,1);c.add(a);a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/rotate.png",.5,"Rotate");a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/rotate.png",1,"Rotate");a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/rotate_click.png",1,"Rotate");a=new T.SpriteGizmo(function(){b.signals.transformModeChanged.dispatch("scale");sendEventStatistic("Edit","Scale","HUD")});a.setPosition(230,30);a.setScale(.5,1);c.add(a);a.addImage(T.SpriteGizmo.INACTIVE,
"/assets/buttons/scale.png",.5,"Scale");a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/scale.png",1,"Scale");a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/scale_click.png",1,"Scale");a=new T.SpriteGizmo(function(){b.signals.nest.dispatch();sendEventStatistic("Printing","Nest","HUD")},"nest");a.setPosition(280,30);a.setScale(.5,1);c.add(a);a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/disassemble.png",.6,"Disassemble");a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/disassemble.png",
1,"Disassemble");a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/disassemble_click.png",1,"Disassemble");a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/assemble.png",.6,"Assemble");a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/assemble.png",1,"Assemble");a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/assemble_click.png",1,"Assemble");a=new T.SpriteGizmo(function(){b.signals.toggleInvertedTriangles.dispatch();b.signals.saveUI.dispatch();sendEventStatistic("View","Inverted","HUD")},"show_inverted");
a.setPosition(360,30);a.setScale(.5,1);c.add(a);a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/inverted_show.png",.6,"Inverted triangles: shown");a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/inverted_show.png",1,"Inverted triangles: shown");a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/inverted_show_click.png",1,"Inverted triangles: hide");a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/inverted_hide.png",.6,"Inverted triangles: hidden");a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/inverted_hide.png",
1,"Inverted triangles: hidden");a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/inverted_hide_click.png",1,"Inverted triangles: show");a=new T.SpriteGizmo(function(){b.signals.toggleTriangleVisualization.dispatch();b.signals.saveUI.dispatch();sendEventStatistic("View","Triangles","HUD")},"show_triangles");a.setPosition(410,30);a.setScale(.5,1);c.add(a);a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/triangles_hide.png",.6,"Triangles: hidden");a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/triangles_hide.png",
1,"Triangles: hidden");a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/triangles_hide_click.png",1,"Triangles: show");a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/triangles_show.png",.6,"Triangles: shown");a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/triangles_show.png",1,"Triangles: shown");a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/triangles_show_click.png",1,"Triangles: hide");a=new T.SpriteGizmo(function(){b.signals.toggleBadEdges.dispatch();b.signals.saveUI.dispatch();sendEventStatistic("View",
"Bad edges","HUD")},"show_edges");a.setPosition(460,30);a.setScale(.5,1);c.add(a);a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/edges_hide.png",.6,"Holes: hidden");a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/edges_hide.png",1,"Holes: hidden");a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/edges_hide_click.png",1,"Holes: show");a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/edges_show.png",.6,"Holes: shown");a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/edges_show.png",1,
"Holes: shown");a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/edges_show_click.png",1,"Holes: hide");a=new T.SpriteGizmo(function(){b.signals.toggleWallThickness.dispatch();sendEventStatistic("View","Structural Analysis","HUD")},"show_analysis");a.setPosition(510,30);a.setScale(.5,1);c.add(a);a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/analysis_hide.png",.65,"Structural Analysis: hidden");a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/analysis_hide.png",1,"Structural Analysis: hidden");
a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/analysis_hide_click.png",1,"Structural Analysis: show");a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/analysis_show.png",.6,"Structural Analysis: shown");a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/analysis_show.png",1,"Structural Analysis: shown");a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/analysis_show_click.png",1,"Structural Analysis: hide");a=new T.SpriteGizmo(function(){b.signals.measureDistance.dispatch();sendEventStatistic("Measure",
"Distance","HUD")});a.setPosition(590,30);a.setScale(.5,1);c.add(a);a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/distance.png",.6,"Measure distance");a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/distance.png",1,"Measure distance");a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/distance_click.png",1,"Measure distance");a=new T.SpriteGizmo(function(){b.signals.measureThickness.dispatch();sendEventStatistic("Measure","Thickness","HUD")});a.setPosition(640,30);a.setScale(.5,1);c.add(a);
a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/thickness.png",.6,"Measure thickness");a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/thickness.png",1,"Measure thickness");a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/thickness_click.png",1,"Measure thickness");a=new T.SpriteGizmo(function(){b.signals.measureAngle.dispatch();sendEventStatistic("Measure","Angle","HUD")});a.setPosition(690,30);a.setScale(.5,1);c.add(a);a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/angle.png",.6,"Measure angle");
a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/angle.png",1,"Measure angle");a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/angle_click.png",1,"Measure angle");a=new T.SpriteGizmo(function(){b.signals.measureRadius.dispatch();sendEventStatistic("Measure","Radius","HUD")});a.setPosition(740,30);a.setScale(.5,1);c.add(a);a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/radius.png",.6,"Measure radius");a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/radius.png",1,"Measure radius");a.addImage(T.SpriteGizmo.PRESSED,
"/assets/buttons/radius_click.png",1,"Measure radius");a=new T.SpriteGizmo(function(){b.signals.measureAnnotation.dispatch();sendEventStatistic("Measure","Annotation","HUD")});a.setPosition(790,30);a.setScale(.5,1);c.add(a);a.addImage(T.SpriteGizmo.INACTIVE,"/assets/buttons/annotation.png",.6,"Add annotation");a.addImage(T.SpriteGizmo.HIGHLIGHT,"/assets/buttons/annotation.png",1,"Add annotation");a.addImage(T.SpriteGizmo.PRESSED,"/assets/buttons/annotation_clicked.png",1,"Add annotation");b.sceneOrtho.add(c);
b.sceneOrtho.updateMatrixWorld();return c};
