var Loader=function(e){var z=this,k=e.notifications;this.loadLocalStorage=function(){};this.saveLocalStorage=function(b){};this.loadFile=function(b,h,c,f,d,v){try{var l=b.name,n=d?T.FileOperations.extractName(l):l,r=T.FileOperations.extractExtension(l);folderPath=h?h.replace(/\\/g,"/"):"";sendEventStatistic("Load","File",r);switch(r){case "babylon":var a=new FileReader;a.addEventListener("load",function(m){var b=JSON.parse(m.target.result);b&&(m.target.result="",m=(new T.BabylonLoader).parse(b),m.name||
(m.name=n),d||T.GeometryUtils.normalizeMeshCenter(m,!0,k),e.addObject(m,d),e.signals.unzoomCamera.dispatch());c&&c()},!1);a.readAsText(b);break;case "ctm":a=new FileReader;a.addEventListener("load",function(m){var q=m.target.result,a=new CTM.Stream(q);a.offset=0;(new T.CTMLoader).createModelClassic(new CTM.File(a),function(a){q="";m.target.result="";a.sourceType="ctm";a.sourceFile=b.name;a.mergeVertices();a=T.SceneUtils.createMesh(a);a.name=n;d||T.GeometryUtils.normalizeMeshCenter(a,!0,k);e.addObject(a,
d);e.signals.unzoomCamera.dispatch();c&&c()})},!1);a.readAsBinaryString(b);break;case "dae":a=new FileReader;a.addEventListener("load",function(b){var q=b.target.result,a=(new DOMParser).parseFromString(q,"text/xml"),q="";b.target.result="";(new T.ColladaLoader).parse(a,function(b){a=void 0;b.scene.name=n;d||T.GeometryUtils.normalizeMeshCenter(b.scene,!0,k);e.addObject(b.scene,d);e.signals.unzoomCamera.dispatch();c&&c()},folderPath)},!1);a.readAsText(b);break;case "js":case "json":case "3geo":case "3mat":case "3obj":case "3scn":a=
new FileReader;a.addEventListener("load",function(b){b=b.target.result;if(-1!==b.indexOf("postMessage")){var a=new Blob([b],{type:"text/javascript"}),a=URL.createObjectURL(a),a=new Worker(a);a.onmessage=function(b){b.data.metadata={version:2};A(b.data,l,d)};a.postMessage(Date.now())}else{try{a=JSON.parse(b)}catch(f){console.log(f);return}A(a,l,d);e.signals.unzoomCamera.dispatch();c&&c()}},!1);a.readAsText(b);break;case "obj":a=new FileReader;a.addEventListener("load",function(b){var a=b.target.result;
if(a=(new T.OBJLoader).parse(a))b.target.result="",a.name=n,d||T.GeometryUtils.normalizeMeshCenter(a,!0,k),e.addObject(a,d),e.signals.unzoomCamera.dispatch();c&&c()},!1);a.readAsText(b);break;case "ply":a=new FileReader;a.addEventListener("load",function(a){var q=a.target.result;if(q=(new T.PLYLoader).parse(q))a.target.result="",q.sourceType="ply",q.sourceFile=b.name,q.mergeVertices(),a=T.SceneUtils.createMesh(q),a.name=n,d||T.GeometryUtils.normalizeMeshCenter(a,!0,k),e.addObject(a,d),e.signals.unzoomCamera.dispatch();
c&&c()},!1);void 0!==a.readAsBinaryString?a.readAsBinaryString(b):a.readAsArrayBuffer(b);break;case "stl":a=new FileReader;a.addEventListener("load",function(b){var a=b.target.result;if(a=(new T.STLLoader).parse(a))b.target.result="",a.name=n,d||T.GeometryUtils.normalizeMeshCenter(a,!0,k),e.addObject(a,d),e.signals.unzoomCamera.dispatch();c&&c()},!1);void 0!==a.readAsBinaryString?a.readAsBinaryString(b):a.readAsArrayBuffer(b);break;case "amf":a=new FileReader;a.addEventListener("load",function(b){var a=
b.target.result;if(T.FileOperations.isZipData(a))z.loadData(a,l+".zip",c,f,d,v);else{if(a=(new T.AMFLoader).parse(a))b.target.result="",a.name=n,d||T.GeometryUtils.normalizeMeshCenter(a,!0,k),e.addObject(a,d),e.signals.unzoomCamera.dispatch();c&&c()}},!1);void 0!==a.readAsBinaryString?a.readAsBinaryString(b):a.readAsArrayBuffer(b);break;case "3ds":a=new FileReader;a.addEventListener("load",function(b){var a=b.target.result;if(a=(new T.Loader3DS).parse(a))b.target.result="",a.name=n,d||T.GeometryUtils.normalizeMeshCenter(a,
!0,k),e.addObject(a,d),e.signals.unzoomCamera.dispatch();c&&c()},!1);void 0!==a.readAsBinaryString?a.readAsBinaryString(b):a.readAsArrayBuffer(b);break;case "vtk":a=new FileReader;a.addEventListener("load",function(a){var f=a.target.result;if(f=(new T.VTKLoader).parse(f))a.target.result="",f.sourceType="vtk",f.sourceFile=b.name,f.mergeVertices(),a=T.SceneUtils.createMesh(f),a.name=n,d||T.GeometryUtils.normalizeMeshCenter(a,!0,k),e.addObject(a,d),e.signals.unzoomCamera.dispatch();c&&c},!1);a.readAsText(b);
break;case "wrl":a=new FileReader;a.addEventListener("load",function(b){var a=b.target.result;if(a=(new T.VRMLLoader).parse(a))b.target.result="",a.name||(a.name=n),d||T.GeometryUtils.normalizeMeshCenter(a,!0,k),e.addObject(a,d),e.signals.unzoomCamera.dispatch();c&&c()},!1);a.readAsText(b);break;case "thing":case "zip":var g=null;!1!==v&&(g=new T.Object3D,g.name=n,e.addObject(g,d));var w=T.SceneUtils.badEdgesMaterial.visible;T.SceneUtils.badEdgesMaterial.visible=!1;T.FileOperations.unzip(b,f?null:
k,function(a,b,c){g&&c&&1>=c&&(e.removeObject(g),g=null);z.loadFile(a,a.fileEntry?a.fileEntry.fullPath:a.name,b,null,g)},function(a){g&&g.parent&&g.parent instanceof T.Scene&&T.GeometryUtils.normalizeMeshCenter(g,!0,k);w&&T.SceneUtils.updateBadEdges(e.scene,!0,!0);T.SceneUtils.badEdgesMaterial.visible=w;T.FileOperations.clearTempFiles(a);c&&c()},function(a,b){if(f)return f(a,b)},function(a){T.SceneUtils.badEdgesMaterial.visible=w;console.log(a);c&&c()});break;default:console.log("Unsupported file format."),
c&&c()}}catch(m){console.log(m),c&&c()}};this.loadUrl=function(b,h,c,f,d,v,l,n){var r=T.FileOperations.extractExtension(h);try{var a=null;d||(a=k.createProgress("Downloading",h,function(){void 0!==g&&null!==g&&g.abort();f&&f()},"Cancel download"));var g=null,g=new XMLHttpRequest,w=this;onProgress=function(b){void 0!==b&&void 0!==b.loaded&&void 0!==b.total&&0<b.total&&!1!==b.lengthComputable&&(a&&(k.updateProgress(a,b.loaded/b.total*100),b.loaded>=b.total&&("zip"==r||"thing"==r)&&k.endProgress(a)),
d&&d(b.loaded/b.total*("zip"==r||"thing"==r?80:100),100)&&g&&(g.abort(),f&&f()))};onError=function(d){a&&k.endProgress(a);v&&v(d);c?sendEventStatistic("Error","Load","Google Drive"):sendEventStatistic("Error","Load",b.substring(0,b.indexOf("/",14)).toLowerCase())};onLoadProgress=function(b,a){if(("zip"==r||"thing"==r)&&b&&a&&d&&d)return d(80+b/a*20,100)};onLoad=function(g){c?sendEventStatistic("Load","Url","Google Drive"):sendEventStatistic("Load","Url",b.substring(0,b.indexOf("/",14)).toLowerCase());
w.loadData(g.target.response||g.target.responseText,h,function(){!1!==c&&e.signals.reloadComments.dispatch(c?c:b);a&&k.endProgress(a);f&&f()},d?onLoadProgress:null,l,n)};g.addEventListener("load",function(b){200===b.target.status||0===b.target.status?onLoad(b):onError(b)},!1);g.addEventListener("progress",onProgress,!1);g.addEventListener("error",onError,!1);g.overrideMimeType("text/plain; charset=x-user-defined");g.open("GET",b,!0);T.FileOperations.setXHRHeader&&T.FileOperations.setXHRHeader(g,b);
g.send(null)}catch(m){console.log(m)}};this.loadData=function(b,h,c,f,d,v){try{var l=d?T.FileOperations.extractName(h):h,n=T.FileOperations.extractExtension(h);sendEventStatistic("Load","Data",n);switch(n){case "babylon":var r=JSON.parse(b);b="";var a=new T.BabylonLoader,g=a.parse(r);g&&(r=void 0,g.name||(g.name=l),d||T.GeometryUtils.normalizeMeshCenter(g,!0,k),e.addObject(g,d));c&&c();break;case "ctm":var w=new CTM.Stream(b);w.offset=0;a=new T.CTMLoader;a.createModelClassic(new CTM.File(w),function(a){b=
"";a.sourceType="ctm";a.sourceFile=h;a.mergeVertices();a=T.SceneUtils.createMesh(a);a.name=l;d||T.GeometryUtils.normalizeMeshCenter(a,!0,k);e.addObject(a,d);c&&c()});break;case "dae":var m=(new DOMParser).parseFromString(b,"text/xml");b="";a=new T.ColladaLoader;a.parse(m,function(a){m=void 0;a.scene.name=l;d||T.GeometryUtils.normalizeMeshCenter(a.scene,!0,k);e.addObject(a.scene,d);c&&c()},"");break;case "js":case "json":case "3geo":case "3mat":case "3obj":case "3scn":if(-1!==b.indexOf("postMessage")){var q=
new Blob([b],{type:"text/javascript"}),E=URL.createObjectURL(q),D=new Worker(E);D.onmessage=function(a){a.data.metadata={version:2};A(a.data,h,d)};D.postMessage(Date.now());break}try{b=JSON.parse(b)}catch(B){console.log(B);break}A(b,h,d);c&&c();break;case "obj":var p=(new T.OBJLoader).parse(b);p&&(b="",p.name=l,d||T.GeometryUtils.normalizeMeshCenter(p,!0,k),e.addObject(p,d));c&&c();break;case "ply":var u=(new T.PLYLoader).parse(b);if(u){b="";u.sourceType="ply";u.sourceFile=h;u.mergeVertices();var x=
T.SceneUtils.createMesh(u);x.name=l;d||T.GeometryUtils.normalizeMeshCenter(x,!0,k);e.addObject(x,d)}c&&c();break;case "stl":if(p=(new T.STLLoader).parse(b))b="",p.name=l,d||T.GeometryUtils.normalizeMeshCenter(p,!0,k),e.addObject(p,d);c&&c();break;case "amf":if(T.FileOperations.isZipData(b))z.loadData(b,h+".zip",c,f,d,v);else{if(p=(new T.AMFLoader).parse(b))b="",p.name=l,d||T.GeometryUtils.normalizeMeshCenter(p,!0,k),e.addObject(p,d);c&&c()}break;case "3ds":if(p=(new T.Loader3DS).parse(b))b="",p.name=
l,d||T.GeometryUtils.normalizeMeshCenter(p,!0,k),e.addObject(p,d);c&&c();break;case "vtk":if(u=(new T.VTKLoader).parse(b))b="",u.sourceType="vtk",u.sourceFile=h,u.mergeVertices(),x=T.SceneUtils.createMesh(u),x.name=l,d||T.GeometryUtils.normalizeMeshCenter(x,!0,k),e.addObject(x,d);c&&c();break;case "wrl":var y=(new T.VRMLLoader).parse(b);y&&(b="",y.name||(y.name=l),d||T.GeometryUtils.normalizeMeshCenter(y,!0,k),e.addObject(y,d));c&&c();break;case "thing":case "zip":var t=null;!1!==v&&(t=new T.Object3D,
t.name=l,e.addObject(t,d));var C=T.SceneUtils.badEdgesMaterial.visible;T.SceneUtils.badEdgesMaterial.visible=!1;T.FileOperations.unzip({data:b,name:h},f?null:k,function(a,b,c){t&&c&&1>=c&&(e.removeObject(t),t=null);z.loadFile(a,a.fileEntry?a.fileEntry.fullPath:a.name,b,null,t)},function(a){t&&t.parent&&t.parent instanceof T.Scene&&T.GeometryUtils.normalizeMeshCenter(t,!0,k);C&&T.SceneUtils.updateBadEdges(e.scene,!0,!0);T.SceneUtils.badEdgesMaterial.visible=C;T.FileOperations.clearTempFiles(a);c&&
c()},function(a,b){if(f)return f(a,b)},function(a){T.SceneUtils.badEdgesMaterial.visible=C;console.log(a);c&&c()});break;default:console.log("Unsupported file format.")}}catch(B){console.log(B)}};var A=function(b,h,c){void 0===b.metadata&&(b.metadata={type:"Geometry"});void 0===b.metadata.type&&(b.metadata.type="Geometry");void 0===b.metadata.version&&(b.metadata.version=b.metadata.formatVersion);if("geometry"===b.metadata.type.toLowerCase()){var f=new T.JSONLoader,f=f.parse(b);b=f.geometry;f=void 0!==
f.materials?1<f.materials.length?T.SceneUtils.createDefaultMaterials()[0]:f.materials[0]:T.SceneUtils.createDefaultMaterials()[0];b.sourceType="ascii";b.sourceFile=h;h=T.SceneUtils.createMesh(b,f);h.name=name;c||T.GeometryUtils.normalizeMeshCenter(h,!0,k);e.addObject(h,c);e.select(h)}else if("object"===b.metadata.type.toLowerCase())f=new T.ObjectLoader,f=f.parse(b),f instanceof T.Scene?(f.name||(f.name=name),e.addObject(f,c)):(e.addObject(f,c),e.select(f));else if("scene"===b.metadata.type.toLowerCase())f=
new T.SceneLoader,f.parse(b,function(b){b.scene.name||(b.scene.name=name);e.addObject(b.scene,c)},"");else if("measurement"===b.metadata.type.toLowerCase())try{if(b.measurements&&b.measurements.length)for(h=0;h<b.measurements.length;++h)switch(b.measurements[h].type){case "Angle":e.signals.measureAngle.dispatch(b.measurements[h],c);break;case "Distance":e.signals.measureDistance.dispatch(b.measurements[h],c);break;case "Thickness":e.signals.measureThickness.dispatch(b.measurements[h],c);break;case "Radius":e.signals.measureRadius.dispatch(b.measurements[h],
c);break;case "Annotation":e.signals.measureAnnotation.dispatch(b.measurements[h],c)}}catch(d){console.log(d)}else if("platform"===b.metadata.type.toLowerCase())try{b.platform&&e.scene&&e.scene instanceof T.Platform&&(e.scene.updatePlatformFromDTO(b.platform),e.signals.sceneGraphChanged.dispatch(),e.scene.sendStatistic("load"))}catch(d){console.log(d)}}};
