T.MeasurementGizmoMaterial=function(e){T.MeshBasicMaterial.call(this);this.depthWrite=this.depthTest=!1;this.side=T.DoubleSide;this.transparent=!0;this.setValues(e)};T.MeasurementGizmoMaterial.prototype=Object.create(T.MeshBasicMaterial.prototype);T.MeasurementPickerMaterial=new T.MeasurementGizmoMaterial({visible:!1});
T.Measurement=function(){T.Object3D.call(this);this.measurementGizmo=null;this.color=new T.Color(13062224);this.comments="";this.visible=!1;this.createGizmo=function(e){return this.measurementGizmo};this.getValue=function(){return null};this.getInfo=function(){return[]};this.getType=function(){return"Measurment"};this.getDescription=function(){return"Generic Measurement"};this.getComments=function(){return this.comments};this.setComments=function(e){this.comments=e}};T.Measurement.prototype=Object.create(T.Object3D.prototype);
T.Measurement.prototype.exportMeasurement=function(){for(var e=[],f=0;f<this.measurementGizmo.controlPoints.length;++f){e[f]=(new T.V3).copy(this.measurementGizmo.controlPoints[f].point);var c=this.measurementGizmo.controlPoints[f].object;if(c){c.localToWorld(e[f]);for(var g=c;null!=c;c=c.parent)c instanceof T.Mesh&&(g=c);e[f].name=g.referenceName}}return{type:this.getType(),name:this.name,points:e,visible:this.visible,comments:this.comments}};
T.Measurement.prototype.translatePointsForObject=function(e,f){for(var c=0;c<this.measurementGizmo.controlPoints.length;++c){var g=this.measurementGizmo.controlPoints[c].point;g&&this.measurementGizmo.controlPoints[c].object==e&&g.add(f)}};
T.MeasurementGizmo=function(e,f){T.Object3D.call(this);this.handleGizmos={};this.dragNormal=new T.V3;this.dragOrigin=new T.V3;this.lastPosition=new T.V3;this.dragGizmo="";this.container=f;this.measurement=e;this.selected=!1;var c=this;this.controlPoints=[];var g=new T.Projector;this.transformGizmo=function(b,a,d){a&&b.geometry.applyMatrix((new T.Matrix4).makeTranslation(a.x,a.y,a.z));if(d){a=new T.Matrix4;var c=new T.Matrix4,e=new T.Matrix4,f=new T.Matrix4;c.makeRotationX(d.x);e.makeRotationY(d.y);
f.makeRotationZ(d.z);a.multiplyMatrices(c,e);a.multiply(f);b.geometry.applyMatrix(a)}};this.init=function(){this.handles=new T.Object3D;this.pickers=new T.Object3D;this.add(this.handles);this.add(this.pickers);this.container&&(this.initText?this.initText():(this.text=new UI.Text,this.text.setDisplay("none"),this.text.setPosition("absolute"),this.text.setColor("#000000"),this.text.setPadding("3px"),this.text.setPaddingRight("8px"),this.text.setPaddingLeft("8px"),this.text.setBackgroundColor("#FFFFFF"),
this.text.setBorder("1px solid #FF0000"),this.text.setOpacity("0.9"),this.text.setStyle("font",["normal normal normal 13px/normal 'Helvetica Neue', arial, sans-serif"]),this.text.setStyle("overflow",["hidden"]),this.container.add(this.text)),this.text.dom.addEventListener("mousedown",function(a){a.cancel=!0;c.dispatchEvent({type:"textMouseDown",measurementGizmo:c,originalEvent:a})}),this.text.onMouseOver(function(){!1!==c.selected?(c.text.setBackgroundColor("#FFFF88"),c.text.setBorder("2px solid #FF0000")):
(c.text.setBackgroundColor("#EEEEEE"),c.text.setBorder("1px solid #FF0000"));c.text.setOpacity("1")}),this.text.onMouseOut(function(){!1!==c.selected?(c.text.setBackgroundColor("#FFFF88"),c.text.setBorder("2px solid #FF0000"),c.text.setOpacity("1")):(c.text.setBackgroundColor("#FFFFFF"),c.text.setBorder("1px solid #FF0000"),c.text.setOpacity("0.92"))}));for(var b in this.handleGizmos){var a=this.handleGizmos[b][0];a.name=b;this.transformGizmo(a,this.handleGizmos[b][1],this.handleGizmos[b][2]);a.visible=
!1;this.handles.add(a)}for(b in this.pickerGizmos)a=this.pickerGizmos[b][0],a.name=b,this.transformGizmo(a,this.pickerGizmos[b][1],this.pickerGizmos[b][2]),a.visible=!0,a.measurementGizmo=this,this.pickers.add(a)};this.hide=function(){for(var b in this.handles.children)this.handles.children[b].visible=!1;for(b in this.pickers.children)this.pickers.children[b].visible=!1;this.text&&this.text.setDisplay("none");this.measurement.visible=!1};this.show=function(){for(var b in this.handles.children)this.handles.children[b].visible=
!1;for(b in this.pickers.children)this.pickers.children[b].visible=!0;this.text&&this.text.dom.textContent&&this.text.setDisplay("block");this.measurement.visible=!0};this.isVisible=function(){return this.measurement.visible};this.getMainPicker=function(){for(var b in this.pickerGizmos)return this.pickerGizmos[b][0]};this.getTextPicker=function(){return this.pickerGizmos.TEXT?this.pickerGizmos.TEXT[0]:null};this.highlight=function(b){var a,d;for(d in this.handleGizmos)a=this.handleGizmos[d][0],a.material.oldColor&&
(a.material.color.copy(a.material.oldColor),a.material.opacity=a.material.oldOpacity);b&&this.handleGizmos[b]&&(a=this.handleGizmos[b][0],a.material.oldColor=a.material.color.clone(),a.material.oldOpacity=a.material.opacity,a.material.color.setRGB(1,1,0),a.material.opacity=1)};this.dragStart=function(b,a,d){this.dragNormal.copy(a);this.dragGizmo=b;this.dragOrigin=d;this.lastPosition=(new T.V3).copy(d)};this.onGizmoMoved=function(b,a){this.pickerGizmos&&this.pickerGizmos[b]&&this.pickerGizmos[b][0].position.add(a);
this.handleGizmos&&this.handleGizmos[b]&&this.handleGizmos[b][0].position.add(a)};this.dragMove=function(b,a,d){b===this.dragGizmo&&(a=linePlaneIntersection(d,a,this.dragOrigin,this.dragNormal))&&(this.onGizmoMoved(b,this.lastPosition.sub(a).negate()),this.lastPosition=(new T.V3).copy(a))};this.mustDragGizmo=function(){return!1};this.mustSnapToPart=function(){return!0};this.acceptPoints=function(){return!1};this.getCenterPointWorld=function(){for(var b=new T.V3,a=this.getControlPointsWorld(),d=0;d<
a.length;++d)b.add(a[d]);0<a.length&&b.divideScalar(a.length);return b};this.getWidth=function(b,a){var d=(new T.V3).setFromMatrixPosition(a.matrixWorld);return b.distanceTo(d)/300};this.getScreenCoords=function(b,a){var d=this.container.dom.getBoundingClientRect(),c=d.width/2,d=d.height/2,e=(new T.V3).copy(b);e.project?e.project(a):g.projectVector(e,a);return new T.Vector2(e.x*c+c,-(e.y*d)+d)};this.getControlPointsWorld=function(){for(var b=[],a=0;a<this.controlPoints.length;++a)b[a]=(new T.V3).copy(this.controlPoints[a].point),
this.controlPoints[a].object&&this.controlPoints[a].object.localToWorld(b[a]);return b};this.offsetControlPoint=function(b,a){if(!(b>=this.controlPoints.length)&&this.controlPoints[b].point)if(this.controlPoints[b].object){(new T.V3).copy(a);var d=(new T.V3).copy(this.controlPoints[b].point);this.controlPoints[b].object.localToWorld(d);d.add(a);this.controlPoints[b].object.worldToLocal(d);this.controlPoints[b].point.copy(d)}else this.controlPoints[b].point.add(a)};this.setText=function(b,a,d){if(this.text){this.text.setDisplay("block");
a=this.getScreenCoords(a,d);d=this.text.dom.getBoundingClientRect();a.x-=d.width/2;a.y-=d.height/2;var c=this.container.dom.getBoundingClientRect();b&&this.text.setValue(b);this.text.setLeft(a.x.toString()+"px");this.text.setTop(a.y.toString()+"px");d=this.text.dom.getBoundingClientRect();0<d.width&&0<d.height&&(d.left>c.right||d.right<c.left||d.top>c.bottom||d.bottom<c.top)&&this.text.setDisplay("none")}};this.getValue=function(){return null};this.clean=function(){this.container&&this.text&&(this.text.setDisplay("none"),
this.container.remove(this.text))};this.restore=function(){this.container&&this.text&&(this.text.dom.textContent&&this.text.setDisplay("block"),this.container.add(this.text))};this.removeUIObject=function(){this.measurement&&this.measurement.parent&&this.measurement.parent.remove(this.measurement)}};T.MeasurementGizmo.prototype=Object.create(T.Object3D.prototype);T.MeasurementGizmo.prototype.update=function(e){};
T.MeasurementGizmo.prototype.addControlPoint=function(e,f,c,g,b){e=(new T.V3).copy(e);f&&f.worldToLocal(e);this.controlPoints.push({point:e,object:f})};
T.MeasurementGizmo.prototype.select=function(e){this.selected=e;this.text&&(!1!==e?(this.text.setBackgroundColor("#FFFF88"),this.text.setBorder("2px solid #FF0000"),this.text.setOpacity("1"),this.text.setStyle("z-index",["2"]),this.highlight("TOPLINE")):(this.text.setBackgroundColor("#FFFFFF"),this.text.setBorder("1px solid #FF0000"),this.text.setOpacity("0.92"),this.text.setStyle("z-index",["1"])))};
