T.MeasurementAngle=function(){T.Measurement.call(this);this.createGizmo=function(f){return this.measurementGizmo=new T.MeasurementGizmoAngle(this,f)};this.getValue=function(){return this.measurementGizmo.getValue()};this.getInfo=function(){for(var f=this.measurementGizmo.getControlPointsWorld(),p=[],d=0;d<Math.min(3,f.length);++d)p.push({name:"Point "+(d+1).toString(),values:[f[d].x,f[d].y,f[d].z]});return p};this.getType=function(){return"Angle"};this.getDescription=function(){return null==this.getValue()?
"angle":"angle = "+this.getValue().toFixed(2)+String.fromCharCode(176)}};T.MeasurementAngle.prototype=Object.create(T.Measurement.prototype);
T.MeasurementGizmoAngle=function(f,p){T.MeasurementGizmo.call(this,f,p);this.curveIn=!0;var d=this;this.handleGizmos={CURVE:[new T.Mesh(new T.DynamicTorusGeometry(10,.5,2,24,2*Math.PI,!1),new T.MeasurementGizmoMaterial({color:0,opacity:.1}))],START:[new T.Mesh(new T.SphereGeometry(2),new T.MeasurementGizmoMaterial({color:16711680,opacity:.4}))],MIDDLE:[new T.Mesh(new T.SphereGeometry(2),new T.MeasurementGizmoMaterial({color:16711680,opacity:.4}))],END:[new T.Mesh(new T.SphereGeometry(2),new T.MeasurementGizmoMaterial({color:16711680,
opacity:.4}))],STARTLINE:[new T.Mesh(new T.CylinderGeometry(1,1,1,4,1,!1),new T.MeasurementGizmoMaterial({color:16711680,opacity:.4})),new T.V3(0,.5,0),new T.V3(Math.PI/2,0,0)],ENDLINE:[new T.Mesh(new T.CylinderGeometry(1,1,1,4,1,!1),new T.MeasurementGizmoMaterial({color:16711680,opacity:.4})),new T.V3(0,.5,0),new T.V3(Math.PI/2,0,0)]};this.pickerGizmos={CURVE:[new T.Mesh(new T.DynamicTorusGeometry(10,.5,2,24,2*Math.PI,!1),T.MeasurementPickerMaterial)],TEXT:[new T.Mesh(new T.SphereGeometry(4),T.MeasurementPickerMaterial)]};
this.addControlPoint=function(m,e,a,g,c){e=3>d.controlPoints.length?e:d.controlPoints[1].object;T.MeasurementGizmo.prototype.addControlPoint.call(this,m,e,a,g,c);2==d.controlPoints.length&&e&&(e.add(this.measurement),c&&c(this.measurement));this.show()};this.acceptPoints=function(){return 3>this.controlPoints.length};this.mustDragGizmo=function(){return 3==this.controlPoints.length?this.pickerGizmos.TEXT[0]:!1};this.mustSnapToPart=function(){return 3>this.controlPoints.length};this.update=function(m){if(this.isVisible()){this.show();
var e=d.getWidth(d.getCenterPointWorld(),m),a,g,c=d.getControlPointsWorld();switch(d.controlPoints.length){case 4:var b=d.handleGizmos.CURVE[0];a=d.pickerGizmos.CURVE[0];b.visible=!1;var k=(new T.V3).subVectors(c[1],c[2]),l=(new T.V3).subVectors(c[0],c[1]);g=(new T.V3).copy(k).cross(l);if(1E-4<g.length()){var h=projectPointToPlane(c[3],c[1],g),f=(new T.V3).subVectors(h,c[1]),n=(new T.V3).copy(l).cross(f),f=(new T.V3).copy(k).cross(f);d.curveIn=0<=g.dot(n)&&0<=g.dot(f);f=d.curveIn?Math.PI-l.angleTo(k):
Math.PI+l.angleTo(k);n=Math.PI/2;b.geometry.updateArc(f,!1);a.geometry.updateArc(f,!1);h=h.distanceTo(c[1]);l.setLength(h);l=(new T.V3).copy(c[1]).sub(l);k.setLength(h);k=(new T.V3).copy(c[1]).sub(k);b.position.copy(c[1]);a.position.copy(c[1]);b.up.copy(g);a.up.copy(g);d.curveIn?(b.lookAt(l),a.lookAt(l)):(b.lookAt(k),a.lookAt(k),n+=Math.PI);b.rotateOnAxis(new T.V3(1,0,0),Math.PI/2*3);a.rotateOnAxis(new T.V3(1,0,0),Math.PI/2*3);b.rotateOnAxis(new T.V3(0,0,1),n);a.rotateOnAxis(new T.V3(0,0,1),n);b.scale.set(h/
10.5,h/10.5,e);a.scale.set(h/10.5,h/10.5,e);b.visible=!0}b=d.pickerGizmos.TEXT[0];b.position.copy(c[3]);b.scale.set(e,e,e);b=d.getValue();d.setText(b.toFixed(2)+String.fromCharCode(176),c[3],m);case 3:a=d.getWidth(c[2],m),b=d.handleGizmos.END[0],b.position.copy(c[2]),b.scale.set(a,a,a),b.visible=!0,a=c[1].distanceTo(c[2]),h&&(a=Math.max(a,h)),a>2*e?(b=d.handleGizmos.ENDLINE[0],g=(new T.V3).copy(c[2]).sub(c[1]).setLength(e),b.position.copy(c[1]).add(g),b.lookAt(c[2]),b.scale.set(e,e,a-2*e),b.visible=
!0):d.handleGizmos.ENDLINE[0].visible=!1;case 2:a=d.getWidth(c[1],m),b=d.handleGizmos.MIDDLE[0],b.position.copy(c[1]),b.scale.set(a,a,a),b.visible=!0,a=c[0].distanceTo(c[1]),h&&(a=Math.max(a,h)),a>2*e?(b=d.handleGizmos.STARTLINE[0],g=(new T.V3).copy(c[1]).sub(c[0]).setLength(e),b.position.copy(c[1]).sub(g),b.lookAt(c[0]),b.scale.set(e,e,a-2*e),b.visible=!0):d.handleGizmos.STARTLINE[0].visible=!1;case 1:a=d.getWidth(c[0],m),b=d.handleGizmos.START[0],b.position.copy(c[0]),b.scale.set(a,a,a),b.visible=
!0}}else this.hide()};this.onGizmoMoved=function(d,e){switch(d){case "CURVE":case "TEXT":if(4==this.controlPoints.length){var a=this.getControlPointsWorld(),g=(new T.V3).subVectors(a[2],a[1]),a=(new T.V3).subVectors(a[0],a[1]),g=(new T.V3).copy(g).cross(a);1E-4<g.length()&&this.offsetControlPoint(3,(new T.V3).copy(e).projectOnPlane(g))}}};this.getValue=function(){if(3>this.controlPoints.length)return null;var f=d.getControlPointsWorld(),e=(new T.V3).copy(f[1]).sub(f[0]),f=(new T.V3).copy(f[1]).sub(f[2]);
if(0==e.length()||0==f.length())return 0;e=180*e.angleTo(f)/Math.PI;this.curveIn||(e=360-e);return e};this.init()};T.MeasurementGizmoAngle.prototype=Object.create(T.MeasurementGizmo.prototype);
