var editNestingMenuItem=null;
Menubar.Edit=function(c){var e=new UI.Panel;e.setClass("menu");e.setId("editmenu");e.onMouseOver(function(){b.setDisplay("block")});e.onMouseOut(function(){b.setDisplay("none")});e.onClick(function(){b.setDisplay("block")});var a=new UI.Panel;a.setTextContent("Edit").setColor("#666");a.setMargin("0px");a.setPadding("8px");e.add(a);var b=new UI.Panel;b.setClass("options");b.setDisplay("none");b.setWidth("190px");e.add(b);a=new UI.Panel;a.setClass("option");a.setTextContent("Undo").add((new UI.Text("Ctrl+Z")).setClass("shortcut")).setOpacity(.5);a.onClick(function(){c.history.undo();
sendEventStatistic("Edit","Undo","Menu")});b.add(a);undoMenuItem=a;a=new UI.Panel;a.setClass("option");a.setTextContent("Redo").add((new UI.Text("Ctrl+Y")).setClass("shortcut")).setOpacity(.5);a.onClick(function(){c.history.redo();sendEventStatistic("Edit","Redo","Menu")});b.add(a);redoMenuItem=a;b.add(new UI.HorizontalRule);a=new UI.Panel;a.setClass("option");a.setTextContent("Translate").add((new UI.Text("T")).setClass("shortcut"));a.onClick(function(){c.signals.spaceChanged.dispatch("world");c.signals.transformModeChanged.dispatch("translate");
sendEventStatistic("Edit","Translate","Menu")},!0);b.add(a);a=new UI.Panel;a.setClass("option");a.setTextContent("Rotate").add((new UI.Text("R")).setClass("shortcut"));a.onClick(function(){c.signals.spaceChanged.dispatch("world");c.signals.transformModeChanged.dispatch("rotate");sendEventStatistic("Edit","Rotate","Menu")},!0);b.add(a);a=new UI.Panel;a.setClass("option");a.setTextContent("Scale").add((new UI.Text("S")).setClass("shortcut"));a.onClick(function(){c.signals.transformModeChanged.dispatch("scale");
sendEventStatistic("Edit","Scale","Menu")},!0);b.add(a);a=new UI.Panel;a.setClass("option");a.setTextContent("Set bottom plane").add((new UI.Text("B")).setClass("shortcut"));a.onClick(function(){c.signals.transformModeChanged.dispatch("bottom");sendEventStatistic("Edit","Set bottom","Menu")},!0);b.add(a);b.add(new UI.HorizontalRule);a=new UI.Panel;a.setClass("option");a.setTextContent("Split Shells");a.onClick(function(){c.signals.splitShells.dispatch();sendEventStatistic("Edit","Split Shells","Menu")},
!0);b.add(a);a=new UI.Panel;a.setClass("option");a.setTextContent("Merge Children");a.onClick(function(){c.signals.mergeChildren.dispatch();sendEventStatistic("Edit","Merge Children","Menu")},!0);b.add(a);a=new UI.Panel;a.setClass("option");a.setTextContent("Group").add((new UI.Text("Ctrl+G")).setClass("shortcut"));a.onClick(function(){c.signals.group.dispatch();sendEventStatistic("Edit","Group","Menu")},!0);b.add(a);a=new UI.Panel;a.setClass("option");a.setTextContent("Ungroup").add((new UI.Text("Ctrl+Shift+G")).setClass("shortcut"));
a.onClick(function(){c.signals.ungroup.dispatch();sendEventStatistic("Edit","Ungroup","Menu")},!0);b.add(a);b.add(new UI.HorizontalRule);a=new UI.Panel;a.setClass("option");a.setTextContent("Clone").add((new UI.Text("Ctrl+C")).setClass("shortcut"));a.onClick(function(){c.signals.cloneObject.dispatch();sendEventStatistic("Edit","Clone","Menu")},!0);b.add(a);a=new UI.Panel;a.setClass("option");a.setTextContent("Mirror").add((new UI.Text("Ctrl+M")).setClass("shortcut"));a.onClick(function(){c.signals.mirrorObject.dispatch();
sendEventStatistic("Edit","Mirror","Menu")},!0);b.add(a);a=new UI.Panel;a.setClass("option");a.setTextContent("Delete").add((new UI.Text("Del")).setClass("shortcut"));a.onClick(function(){c.signals.deleteObject.dispatch();sendEventStatistic("Edit","Delete","Menu")},!0);b.add(a);b.add(new UI.HorizontalRule);a=new UI.Panel;a.setClass("option");a.setTextContent("Units Conversion >");a.onMouseOver(function(){d.setDisplay("block")});a.onMouseOut(function(){d.setDisplay("none")});a.onClick(function(){d.setDisplay("block")});
b.add(a);var d=new UI.Panel;d.setClass("options");d.setDisplay("none");d.setMarginLeft("130px");d.setPadding("5px");d.setWidth("180px");a.add(d);a=new UI.Panel;a.setClass("option");a.setTextContent("MM to Inch").add((new UI.Text("Ctrl+Shift+I")).setClass("shortcut"));a.onClick(function(){c.signals.rescaleSelected.dispatch(1/25.4);c.signals.unzoomCamera.dispatch();b.setDisplay("none");sendEventStatistic("Units","MM to inch","Menu")},!0);d.add(a);a=new UI.Panel;a.setClass("option");a.setTextContent("Inch to MM").add((new UI.Text("Ctrl+Shift+M")).setClass("shortcut"));
a.onClick(function(){c.signals.rescaleSelected.dispatch(25.4);c.signals.unzoomCamera.dispatch();b.setDisplay("none");sendEventStatistic("Units","Inch to mm","Menu")},!0);d.add(a);return e};
