T.PlatformHelper=function(a){T.Object3D.call(this);this.box=a&new T.Box3;this.autoUpdate=this.dummy=!0;this.boxLines=new T.BoxHelper;this.boxLines.scale.set(.5001,.5001,.5);this.boxLines.position.set(.5,.5,.5);this.boxLines.material.color.setRGB(1,.5,0);this.boxLines.material.linewidth=1.5;this.boxMaterial=this.boxLines.material;this.boxLines.dummy=!0;this.planeMaterial1=new T.MeshBasicMaterial({color:8947848,wireframe:!1,side:T.FrontSide,transparent:!0,opacity:.5,depthWrite:!1});this.planeMesh1=
new T.Mesh(new T.PlaneGeometry(1,1),this.planeMaterial1);this.planeMesh1.position.set(.5,.5,0);this.planeMesh1.dummy=!0;this.planeMaterial2=new T.MeshBasicMaterial({color:8947848,wireframe:!1,side:T.FrontSide,transparent:!0,opacity:.1,depthWrite:!1});this.planeMesh2=new T.Mesh(new T.PlaneGeometry(1,1),this.planeMaterial2);T.GeometryUtils.invertGeometry(this.planeMesh2.geometry);this.planeMesh2.position.set(.5,.5,0);this.planeMesh2.dummy=!0;this.add(this.planeMesh1);this.add(this.planeMesh2);this.add(this.boxLines);
this.updateMatrixWorld()};T.PlatformHelper.prototype=Object.create(T.Object3D.prototype);T.PlatformHelper.prototype.update=function(a){this.box=a;this.position=(new T.V3).copy(a.min);this.scale.subVectors(a.max,a.min);this.updateMatrixWorld()};T.PlatformHelper.prototype.getBox=function(a){a=new T.Box3;a.min=this.position;a.max.addVectors(this.position,this.scale);return a};
T.PlatformHelper.prototype.setVisible=function(a){this.visible=a;this.planeMaterial1.visible=a;this.planeMaterial2.visible=a;this.boxMaterial.visible=a};T.PlatformHelper.prototype.isVisible=function(a){return this.visible};
T.Platform=function(){T.Scene.call(this);this.name="Default 3D printer";this.description="";this.minimumZ=0;this.featureResolution=this.layerThickness=.1;this.margin=5;this.units="Mm";this.platformHelper=new T.PlatformHelper;this.platformHelper.setVisible(!1);this.setPlatformBox(new T.Box3(new T.V3(0,0,0),new T.V3(200,200,200)));this.nestedObjectIds=[]};T.Platform.prototype=Object.create(T.Scene.prototype);
T.Platform.prototype.equals=function(a){return this.similarTo(a)&&this.name==a.name&&this.description==a.description&&this.platformHelper.visible==a.platformHelper.visible};
T.Platform.prototype.similarTo=function(a){if(!a)return!1;var b=a;a instanceof T.Platform||(b=new T.Platform,b.updatePlatformFromDTO(a));return a&&this.minimumZ==b.minimumZ&&this.layerThickness==b.layerThickness&&this.featureResolution==b.featureResolution&&this.margin==b.margin&&this.units==b.units&&this.platformHelper.position.equals(b.platformHelper.position)&&this.platformHelper.scale.equals(b.platformHelper.scale)};
T.Platform.prototype.updatePlatformFromDTO=function(a){a&&(void 0!==a.name&&(this.name=a.name),void 0!==a.description&&(this.description=a.description),void 0!==a.minimumZ&&(this.minimumZ=a.minimumZ),void 0!==a.layerThickness&&(this.layerThickness=a.layerThickness),void 0!==a.featureResolution&&(this.featureResolution=a.featureResolution),void 0!==a.margin&&(this.margin=a.margin),void 0!==a.units&&(this.units=a.units),void 0!==a.dimensions&&this.setPlatformBox(a.dimensions),void 0!==a.visible&&this.setPlatformVisible(a.visible))};
T.Platform.prototype.getPlatformDTO=function(){dataObject={};dataObject.name=this.name;dataObject.description=this.description;dataObject.minimumZ=this.minimumZ;dataObject.layerThickness=this.layerThickness;dataObject.featureResolution=this.featureResolution;dataObject.margin=this.margin;dataObject.units=this.units;dataObject.dimensions=this.getPlatformBox();dataObject.visible=this.isPlatformVisible();return dataObject};
T.Platform.prototype.loadFromDefaultProfile=function(a){try{var b=this;chrome.storage.local.get("default_platform",function(c){void 0!==c.default_platform&&(dataObject=JSON.parse(c.default_platform))&&b.updatePlatformFromDTO(dataObject);a&&a()})}catch(c){console.log(c)}};T.Platform.prototype.saveToDefaultProfile=function(){try{var a=JSON.stringify(this.getPlatformDTO(),null,"\t");chrome.storage.local.set({default_platform:a})}catch(b){console.log(b)}};
T.Platform.prototype.setPlatformBox=function(a){a&&this.platformHelper.update(a)};T.Platform.prototype.getPlatformBox=function(a){return this.platformHelper.getBox()};T.Platform.prototype.setPlatformVisible=function(a){this.platformHelper.setVisible(a)};T.Platform.prototype.isPlatformVisible=function(){return this.platformHelper.isVisible()};
T.Platform.prototype.clone=function(a){void 0===a&&(a=new T.Platform);T.Scene.prototype.clone.call(this,a);this.updatePlatformFromDTO(a);for(var b=0;b<this.children.length;++b)if(this.children[b]instanceof T.Platform){this.platformHelper=this.children[b];break}return a};
T.Platform.prototype.sendStatistic=function(a){if(this&&this instanceof T.Platform&&this.isPlatformVisible()&&this.name){var b=this.name.toLowerCase().replace("printer","").replace("platform","").replace("default","").trim(),c=T.Platform.findStandardProfileSimilarTo(this),e="Platform"+(c?"-standard":"-custom");a&&(e+="-"+a.toLowerCase());a=this.getPlatformBox();var f=a.size(),d="";c?(d=b,b=c.name.toLowerCase()):(d+=this.units,d+=" "+f.x+"x"+f.y+"x"+f.z,0!=a.min.x&&0!=a.min.y&&0!=a.min.z&&(d+=" p="+
a.min.x+"x"+a.min.y+"x"+a.min.z),d+=" l="+this.layerThickness,d+=" r="+this.featureResolution,d+=" z="+this.minimumZ,d+=" m="+this.margin);sendEventStatistic(e,b,d)}};T.Platform.profiles={};T.Platform.loadPlatformProfiles=function(a){try{chrome.storage.local.get("platform_profiles",function(b){void 0!==b.platform_profiles&&(T.Platform.profiles=JSON.parse(b.platform_profiles));a&&a(T.Platform.profiles)})}catch(b){console.log(b)}};
T.Platform.savePlatformProfiles=function(){try{var a=JSON.stringify(T.Platform.profiles,null,"\t");chrome.storage.local.set({platform_profiles:a})}catch(b){console.log(b)}};T.Platform.findStandardProfileSimilarTo=function(a){if(!printersInfo||!a)return null;for(var b=null,c=0;c<printersInfo.length;++c)if(a.similarTo(printersInfo[c])){if(printersInfo[c].name==a.name)return printersInfo[c];b=printersInfo[c]}return b};
T.Platform.findCustomProfileSimilarTo=function(a){if(!T.Platform.profiles||!a)return null;var b=null,c;for(c in T.Platform.profiles)if(a.similarTo(T.Platform.profiles[c])){if(printersInfo[i].name==a.name)return T.Platform.profiles[c];b=T.Platform.profiles[c]}return b};
