Sidebar.View=function(f){function g(){var a=f.selected;a instanceof T.Camera&&(a=f.scene);if(null!==a){var c=T.GeometryUtils.getGlobalBoundingBox(a);if(c&&c.min.distanceTo(c.max)!=T.NO_SECTIONS){var b=new T.V3(k.getValue(),l.getValue(),m.getValue()),d=D.getValue()?1:0,e=u.getValue();u.setRange(0,Math.abs(c.max.z-c.min.z));0==b.x?b.x=-.001:1==b.x&&(b.x=.999);0==b.y?b.y=-.001:1==b.y&&(b.y=.999);0==b.z?b.z=-.001:1==b.z&&(b.z=.999);var h=(new T.V3).subVectors(new T.V3(1,1,1),b),g=(new T.V3).addVectors(c.max.clone().multiply(b),
c.min.clone().multiply(h));cutModes=[0<v.getValue()?1==v.getValue()?1:-1:T.NO_SECTIONS,0<w.getValue()?1==w.getValue()?1:-1:T.NO_SECTIONS,0<x.getValue()?1==x.getValue()?1:-1:T.NO_SECTIONS];k.setDisabled(cutModes[0]==T.NO_SECTIONS);l.setDisabled(cutModes[1]==T.NO_SECTIONS);m.setDisabled(cutModes[2]==T.NO_SECTIONS);a.traverse(function(a){void 0!==a.material?(a.material.cutValue=g,a.material.cutMode=cutModes,a.material.sliceMode=d,a.material.sliceValue=e):a.userData&&(a.userData.cuttingPlanes={cutPoint:g,
cutModes:cutModes},a.userData.slice={sliceMode:d,sliceValue:e})});n.materialChanged.dispatch(a)}}}function y(){var a=f.selected;null!==a&&(a instanceof T.Mesh||a instanceof T.Object3D)&&(void 0!==a.color&&a.color.setHex(E.getHexValue()),void 0!==a.material&&void 0!==a.material.color&&a.material.color.setHex(F.getHexValue()),void 0!==a.groundColor&&a.groundColor.setHex(G.getHexValue()),a.traverse(function(a){a.visible=H.getValue()}),n.objectChanged.dispatch(a))}function I(){e.setDisplay("none");var a=
f.selected;if(null!==a&&(a instanceof T.Mesh||a instanceof T.Object3D)){e.setDisplay("block");var c=f.selected,b={color:z,groundColor:A},d;for(d in b)c instanceof T.Mesh?b[d].setDisplay(void 0!==c[d]?"":"none"):b[d].setDisplay("none");B.setDisplay(c instanceof T.Camera?"none":"");b=c instanceof T.Mesh?"":"none";C.setDisplay(b);b=c instanceof T.Measurement?"none":"";p.setDisplay(b);q.setDisplay(b);r.setDisplay(b);t.setDisplay(b);void 0!==a.color&&E.setValue("#"+a.color.getHexString());void 0!==a.material&&
void 0!==a.material.color&&F.setValue("#"+a.material.color.getHexString());void 0!==a.groundColor&&G.setValue("#"+a.groundColor.getHexString());H.setValue(a.visible)}}function J(){var a=f.selected;a instanceof T.Camera&&(a=f.scene);if(null!==a){var c=T.GeometryUtils.getGlobalBoundingBox(a);if(c&&Infinity!==Math.abs(c.min.distanceTo(c.max))||a instanceof T.Measurement){var b,d,g,h;void 0!==a.material&&a.material instanceof T.ObjectMaterial?(b=a.material.cutValue.clone(),d=a.material.cutMode,g=a.material.sliceMode,
h=a.material.sliceValue):a.userData&&a.userData.cuttingPlanes?(b=a.userData.cuttingPlanes.cutPoint,d=a.userData.cuttingPlanes.cutModes,g=a.userData.slice.sliceMode,h=a.userData.slice.sliceValue):(b=c.min,d=[T.NO_SECTIONS,T.NO_SECTIONS,T.NO_SECTIONS],g=0);a=(new T.V3).subVectors(b,c.min).divide((new T.V3).subVectors(c.max,c.min));b=isNaN(a.lengthSq());k.setDisabled(b||d[0]==T.NO_SECTIONS);l.setDisabled(b||d[1]==T.NO_SECTIONS);m.setDisabled(b||d[2]==T.NO_SECTIONS);b&&a.set(0,0,0);a.x=Math.min(Math.max(a.x,
0),1);a.y=Math.min(Math.max(a.y,0),1);a.z=Math.min(Math.max(a.z,0),1);k.setValue(a.x);l.setValue(a.y);m.setValue(a.z);v.setValue(d[0]!==T.NO_SECTIONS?1==d[0]?1:2:0);w.setValue(d[1]!==T.NO_SECTIONS?1==d[1]?1:2:0);x.setValue(d[2]!==T.NO_SECTIONS?1==d[2]?1:2:0);if(void 0===h||Infinity===h||NaN===h)c=Math.abs(c.max.z-c.min.z),h=f&&f.scene&&f.scene instanceof T.Platform&&f.scene.isPlatformVisible()?f.scene.layerThickness:1E3<c?c/100:10<c?.5:.1<c?.02:c/10;D.setValue(0!=g);u.setValue(h)}else e.setDisplay("none")}}
var n=f.signals,e=new UI.CollapsiblePanel;e.setBorderTop("1px solid #ccc");e.setPadding("10px");e.setDisplay("none");e.addStatic((new UI.Text).setValue("VIEW").setColor("#666"));e.add(new UI.Break);var p=(new UI.Panel).setWidth("270px"),v=(new UI.SectionCutCheckbox(0)).onChange(g),k=(new UI.Slider).setWidth("180px").setRange(0,1,.01).setHeight("15px").onChange(g);p.add((new UI.Text("Clip X")).setWidth("60px").setColor("#666"));p.add(v);p.add(k);e.add(p);var q=(new UI.Panel).setWidth("270px"),w=(new UI.SectionCutCheckbox).onChange(g),
l=(new UI.Slider).setWidth("180px").setRange(0,1,.01).setHeight("15px").onChange(g);q.add((new UI.Text("Clip Y")).setWidth("60px").setColor("#666"));q.add(w);q.add(l);e.add(q);var r=(new UI.Panel).setWidth("270px"),x=(new UI.SectionCutCheckbox).onChange(g),m=(new UI.Slider).setWidth("180px").setRange(0,1,.01).setHeight("15px").onChange(g);r.add((new UI.Text("Clip Z")).setWidth("60px").setColor("#666"));r.add(x);r.add(m);e.add(r);var t=new UI.Panel,D=(new UI.Checkbox).onChange(g),u=(new UI.Number).setWidth("60px").setRange(0,
Infinity).setPrecision(3).onChange(g);t.add((new UI.Text("Slice")).setWidth("60px").setColor("#666"));t.add(D);t.add(u);e.add(t);var z=new UI.Panel,E=(new UI.Color).onChange(y);z.add((new UI.Text("Color")).setWidth("60px").setColor("#666"));z.add(E);e.add(z);var C=(new UI.Panel).setMarginBottom("8px"),F=(new UI.Color).onChange(y);C.add((new UI.Text("Color")).setWidth("60px").setColor("#666"));C.add(F);e.add(C);var A=(new UI.Panel).setMarginBottom("8px"),G=(new UI.Color).onChange(y);A.add((new UI.Text("Ground color")).setWidth("60px").setColor("#666"));
A.add(G);e.add(A);var B=new UI.Panel,H=(new UI.Checkbox).onChange(y);B.add((new UI.Text("Visible")).setWidth("60px").setColor("#666"));B.add(H);e.add(B);n.objectSelected.add(function(a){I();J()});n.objectChanged.add(function(a){a!==f.selected||a instanceof T.Camera||(I(),J(),f.signals.sceneGraphChanged.dispatch())});n.objectChanging.add(function(a){a===f.selected&&I()});return e};
