Sidebar.Printer=function(f){function C(){var a={"":" "};if(T.Platform.profiles){for(var e in T.Platform.profiles)T.Platform.profiles[e]&&(a[e]=e);for(e=0;e<printersInfo.length;++e)!printersInfo[e].name||printersInfo[e].name in a||(a[printersInfo[e].name]=printersInfo[e].name);m.setOptions(a)}}function d(){var a=f.selected;if(null!==a&&a instanceof T.Platform){a.name=g.getValue();a.description=h.getValue();a.minimumZ=r.getValue();a.layerThickness=t.getValue();a.featureResolution=u.getValue();a.margin=
v.getValue();var e=new T.V3(w.getValue(),x.getValue(),y.getValue()),b=(new T.V3(z.getValue(),A.getValue(),B.getValue())).add(e);a.setPlatformBox(new T.Box3(e,b));k.objectChanged.dispatch(a);a.saveToDefaultProfile()}}function l(){c.setDisplay("none");var a=f.selected;if(null!==a&&a instanceof T.Platform){c.setDisplay("block");g.setValue(a.name);h.setValue(a.description);n.setValue(a.units);r.setValue(a.minimumZ);t.setValue(a.layerThickness);u.setValue(a.featureResolution);v.setValue(a.margin);var a=
a.getPlatformBox(),b=a.size();p.setDisplay(isNaN(a.min.x+a.min.y+a.min.z)?"none":"");w.setValue(a.min.x);x.setValue(a.min.y);y.setValue(a.min.z);q.setDisplay(isNaN(b.x+b.y+b.z)?"none":"");z.setValue(b.x);A.setValue(b.y);B.setValue(b.z)}}var k=f.signals,c=new UI.CollapsiblePanel;c.setBorderTop("1px solid #ccc");c.setPadding("10px");c.setDisplay("none");c.addStatic((new UI.Text).setValue("3D PRINTER").setColor("#666"));c.add(new UI.Break);var b=new UI.Panel,m=(new UI.Select).setWidth("170px").setColor("#444").setFontSize("12px");
T.Platform.loadPlatformProfiles(C);m.onChange(function(){var a=f.selected;if(null!==a&&a instanceof T.Platform){var b=m.getValue();if(""!=b){var c=T.Platform.profiles[b];if(!c)for(var d=0;d<printersInfo.length;++d)printersInfo[d].name==b&&(c=printersInfo[d]);a.updatePlatformFromDTO(c)}l();k.objectChanged.dispatch(a);a.saveToDefaultProfile()}});b.add((new UI.Text("Profile")).setWidth("90px").setColor("#666"));b.add(m);c.add(b);c.add(new UI.HorizontalRule);var b=new UI.Panel,g=(new UI.Input).setWidth("165px").setColor("#444").setFontSize("12px");
g.onChange(d);g.onKeyUp(function(){var a=f.selected;null!==a&&a instanceof T.Platform&&(a.name=g.getValue())});b.add((new UI.Text("Name")).setWidth("90px").setColor("#666"));b.add(g);c.add(b);var b=new UI.Panel,h=(new UI.TextArea).setWidth("165px").setColor("#444").setFontSize("12px");h.onChange(d);h.onKeyUp(function(){var a=f.selected;null!==a&&a instanceof T.Platform&&(a.description=h.getValue())});b.add((new UI.Text("Description")).setWidth("90px").setColor("#666"));b.add(h);c.add(b);var b=new UI.Panel,
n=(new UI.Select).setWidth("90px").setColor("#444").setFontSize("12px").setOptions({Mm:"Mm",Inch:"Inch"});n.onChange(function(){var a=f.selected;if(null!==a&&a instanceof T.Platform){a.units=n.getValue();var b=a.getPlatformBox();"Mm"==a.units?(b.min.multiplyScalar(25.4),b.max.multiplyScalar(25.4),a.minimumZ*=25.4,a.layerThickness*=25.4,a.featureResolution*=25.4,a.margin*=25.4):(b.min.divideScalar(25.4),b.max.divideScalar(25.4),a.minimumZ/=25.4,a.layerThickness/=25.4,a.featureResolution/=25.4,a.margin/=
25.4);a.setPlatformBox(b);l();k.objectChanged.dispatch(a);a.saveToDefaultProfile()}});b.add((new UI.Text("Units")).setWidth("90px").setColor("#666"));b.add(n);c.add(b);var q=new UI.Panel,z=(new UI.Number).setWidth("50px").onChange(d),A=(new UI.Number).setWidth("50px").onChange(d),B=(new UI.Number).setWidth("50px").onChange(d);q.add((new UI.Text("Size")).setWidth("90px").setColor("#666"));q.add(z,A,B);c.add(q);var p=new UI.Panel,w=(new UI.Number).setWidth("50px").onChange(d),x=(new UI.Number).setWidth("50px").onChange(d),
y=(new UI.Number).setWidth("50px").onChange(d);p.add((new UI.Text("Position")).setWidth("90px").setColor("#666"));p.add(w,x,y);c.add(p);var b=new UI.Panel,t=(new UI.Number).setWidth("50px").setRange(0,Infinity).onChange(d);b.add((new UI.Text("Layer")).setWidth("90px").setColor("#666"));b.add(t);c.add(b);var b=new UI.Panel,u=(new UI.Number).setWidth("50px").setRange(0,Infinity).onChange(d);b.add((new UI.Text("Resolution")).setWidth("90px").setColor("#666"));b.add(u);c.add(b);c.add(new UI.HorizontalRule);
c.add((new UI.Text).setValue("AUTO PLACEMENT").setColor("#666"));c.add(new UI.Break);var b=new UI.Panel,r=(new UI.Number).setWidth("50px").onChange(d);b.add((new UI.Text("Min Z")).setWidth("90px").setColor("#666"));b.add(r);c.add(b);var b=new UI.Panel,v=(new UI.Number).setWidth("50px").setRange(0,Infinity).onChange(d);b.add((new UI.Text("Margin")).setWidth("90px").setColor("#666"));b.add(v);c.add(b);var D=(new UI.Button("Save Profile")).setWidth("90px").setHeight("18px").setFontSize("12px").setPadding("0px").setMarginLeft("20px").onClick(function(){var a=
f.selected;if(null!==a&&a instanceof T.Platform){var b=a.name;b||(b="Default 3D printer");T.Platform.profiles[b]=a.getPlatformDTO();T.Platform.savePlatformProfiles();C();a.sendStatistic("profile")}});b.add(D);k.objectSelected.add(function(a){l()});k.objectChanged.add(function(a){a===f.selected&&l()});k.objectChanging.add(function(a){a===f.selected&&l()});return c};
