// Cookie Editor for Google Chrome™ - Copyright (c) 2024 hotcleaner.com - All Rights Reserved.
// Minified by Google Closure Compiler 20240317
'use strict';
(function(){let J,m,y,w;const x=()=>{},F=function(){let a=1;try{navigator.userAgentData.brands.forEach(b=>{b=parseInt(b.version,10);b>a&&(a=b)})}catch(b){console.info(b)}return a},T=function(a,b){let d=function(n){return 10>n-48?n-22:26>n-65?n-65:26>n-97?n-97:36},c=function(n,t,D){n=D?Math.floor(n/700):n>>1;n+=Math.floor(n/t);for(t=0;455<n;t+=36)n=Math.floor(n/35);return Math.floor(t+36*n/(n+38))},e=[],f=[],h=a.length,k;let g,l;var p;let z,A,E;k=128;g=0;l=72;var q=a.lastIndexOf("-");0>q&&(q=0);for(p=
0;p<q;++p){b&&(f[e.length]=26>a.charCodeAt(p)-65);if(128<=a.charCodeAt(p))throw new RangeError("Illegal input >= 0x80");e.push(a.charCodeAt(p))}for(q=0<q?q+1:0;q<h;){p=g;var r=1;for(z=36;;z+=36){if(q>=h)throw RangeError("punycode_bad_input(1)");A=d(a.charCodeAt(q++));if(36<=A)throw RangeError("bad input(2");if(A>Math.floor((2147483647-g)/r))throw RangeError("overflow");g+=A*r;E=z<=l?1:z>=l+26?26:z-l;if(A<E)break;if(r>Math.floor(2147483647/(36-E)))throw RangeError("overflow");r*=36-E}r=e.length+1;
l=c(g-p,r,0===p);if(Math.floor(g/r)>2147483647-k)throw RangeError("punycode_overflow(3)");k+=Math.floor(g/r);g%=r;b&&f.splice(g,0,26>a.charCodeAt(q-1)-65);e.splice(g,0,k);g++}if(b)for(g=0,a=e.length;g<a;g++)f[g]&&(e[g]=String.fromCharCode(e[g]).toUpperCase().charCodeAt(0));return function(n){let t=[],D=0,S=n.length,u;for(;D<S;){u=n[D++];if(55296===(u&63488))throw new RangeError("Illegal UTF-16 value");65535<u&&(u-=65536,t.push(String.fromCharCode(u>>>10&1023|55296)),u=56320|u&1023);t.push(String.fromCharCode(u))}return t.join("")}(e)},
U=function(a){a=a.split(".");let b=[];for(let d=0;d<a.length;++d){let c=a[d];b.push(c.match(/^xn--/)?T(c.slice(4),!0):c)}return b.join(".")},B=async function(a,b){let d;try{let c=JSON.stringify({id:a,v:b});d=await chrome.runtime.sendMessage(c)}catch(c){console.info(c),0<c.indexOf("context")&&window.location.reload()}return d},V=function(a,b,d,c){let e=document.createElement("div"),f=document.createElement("div"),h=function(k){k&&k.isTrusted&&(k=k.target)&&k.classList.contains("__prompt-ok")&&(f.removeEventListener("click",
h,!1),f.remove(),e.remove())};e.className="__shade";f.className="__prompt-box";e.appendChild(f);m.appendChild(e);v(f,[{n:"h3",textContent:a},{n:"p",textContent:b},{n:"button",className:"__prompt-ok",textContent:d}]);f.addEventListener("click",h,!1)},W=function(a,b){let d=document.createElement("div"),c=document.createElement("a"),e=function(f){f&&f.isTrusted&&(c.removeEventListener("click",e,!1),d.remove(),c.remove(),d=c=null)};d.className="__shade";c.className="__download-btn";c.textContent="Save";
c.href=a;c.download=b;d.appendChild(c);m.appendChild(d);c.addEventListener("click",e,!1)},K=function(a,b,d,c,e){let f=document.createElement("div"),h=document.createElement("div"),k=function(g){if(g&&g.isTrusted){let l;(g=g.target)&&g.classList.contains("__prompt-ok")?(g=g.previousElementSibling,g.validity.valid?(e(g.value),g.value=null,l=!0):g.reportValidity()):g&&g.classList.contains("__prompt-cancel")&&(e(),l=!0);l&&(h.removeEventListener("click",k,!1),h.remove(),f.remove(),f=null)}};f.className=
"__shade";h.className="__prompt-box";v(h,[{n:"h3",textContent:a},{n:"p",textContent:b},{n:"input",type:"password",className:"__prompt-pass",placeholder:"Enter password"},{n:"button",className:"__prompt-ok",textContent:d},{n:"button",className:"__prompt-cancel",textContent:c}]);f.appendChild(h);m.appendChild(f);h.addEventListener("click",k,!1);h.querySelector("input").focus()},X=function(a,b,d,c){let e,f;const h=function(l){l=Array.from(f).concat(Array.from(new Uint8Array(l)));c(btoa(String.fromCharCode.apply(null,
new Uint8Array(l))))},k=function(l){window.crypto.subtle.encrypt({name:"AES-GCM",iv:f,tagLength:128},l,(new TextEncoder("utf-8")).encode(a)).then(h,x)},g=function(l){f=l;window.crypto.subtle.importKey("raw",e,{name:"AES-GCM"},!1,["encrypt"]).then(k,x)};G(b,b+b,Math.pow(2,d),32,"SHA-256",function(l){e=l;l=btoa(String.fromCharCode.apply(null,window.crypto.getRandomValues(new Uint8Array(12))));G(b+l,a+(new Date).getTime().toString(),1,12,"SHA-256",g)})},Z=function(a,b,d,c){const e=Array.from(Y(a)),f=
function(k){c((new TextDecoder("utf-8")).decode(new Uint8Array(k)))},h=function(k){window.crypto.subtle.decrypt({name:"AES-GCM",iv:new Uint8Array(e.slice(0,12)),tagLength:128},k,new Uint8Array(e.slice(12))).then(f,x)};G(b,b+b,Math.pow(2,d),32,"SHA-256",function(k){window.crypto.subtle.importKey("raw",k,{name:"AES-GCM"},!1,["decrypt"]).then(h,x)})},G=function(a,b,d,c,e,f){a=(new TextEncoder("utf-8")).encode(a);a=new Uint8Array(a);b=(new TextEncoder("utf-8")).encode(b);const h=new Uint8Array(b),k=function(g){f(new Uint8Array(g))};
crypto.subtle.importKey("raw",a,{name:"PBKDF2"},!1,["deriveBits"]).then(function(g){crypto.subtle.deriveBits({name:"PBKDF2",salt:h,iterations:d,hash:e},g,8*c).then(k,x)},x)},Y=function(a){return new Uint8Array(atob(a).split("").map(b=>b.charCodeAt(0)))},C=function(){var a=w+" cookies from "+y+" domains";m.querySelector(".__status span").textContent=a},aa=function(){var a=m.querySelector(".__tree");if(a.__expanded){a.__expanded=!1;a=a.querySelectorAll("dt.__expanded");for(let b=0,d=a.length;b<d;b++)a[b].classList.remove("__expanded")}else{a.__expanded=
!0;a=a.querySelectorAll("dt:not(.__expanded)");for(let b=0,d=a.length;b<d;b++)a[b].classList.add("__expanded")}},ba=function(a){let b=m.querySelectorAll("dt:not([hidden]) input");for(let d=0,c=b.length;d<c;d++)b[d].checked=a;b=m.querySelectorAll("dt:not([hidden]) + dl input");for(let d=0,c=b.length;d<c;d++)b[d].checked=a},ca=async function(){let a=130>F(),b=m.querySelectorAll("dt:not([hidden]) + dl input:checked"),d=b&&b.length||0;if(0<d){let e;let f,h=new Set,k=[],g=[];for(let l=0;l<d;l++){e=b[l].parentElement;
var c=Object.assign(e.cprop);a&&e.cprop.partitionKey?k.push(c):(c.r=1,g.push(c));c=e.parentElement;e.remove();w--;h.add(c)}h.forEach(l=>{d=l.children.length;f=l.previousElementSibling;0<d?f.querySelector("span").textContent=d:(l.remove(),f.remove(),y--)});h=null;0<g.length&&await B(5,g);0<k.length&&await B(8,k);C()}},da=function(a){if(a&&a.isTrusted){a=a.target.value;let b=m.querySelectorAll("dt"),d;for(let c=0,e=b.length;c<e;c++)d=b[c],d.hidden=a?0>d.domain.indexOf(a)?!0:!1:!1}},ea=function(a){a=
new Date(1E3*a);let b=d=>10>d?"0"+d:d;return{date:a.getUTCFullYear()+"-"+b(a.getUTCMonth()+1)+"-"+b(a.getUTCDate()),time:b(a.getUTCHours())+":"+b(a.getUTCMinutes())}},L=function(a){a=a||{};let b=m.querySelector(".__prop");var d=ea(a.expirationDate||Date.now()/1E3+86400);let c=b.querySelector("#__cdate"),e=b.querySelector("#__ctime"),f=b.querySelector("#__cval");b.querySelector("#__cdomain").value=a.domain||".example.com";b.querySelector("#__cpath").value=a.path||"/";b.querySelector("#__cname").value=
a.name||"test";b.querySelector("#__cstore").value=a.storeId||0;f.value=a.value||"";b.querySelector("#__cpart").value=a?.partitionKey?.topLevelSite??"";c.value=d.date;e.value=d.time;c.disabled=e.disabled=a.session?!0:!1;d=a.sameSite||"";b.querySelector("#__csamesite").value="no_restriction"===d?"none":"unspecified"==d?"":d;b.querySelector("#__csession").checked=a.session?!0:!1;b.querySelector("#__chostonly").checked=a.hostOnly?!0:!1;b.querySelector("#__chttponly").checked=a.httpOnly?!0:!1;b.querySelector("#__csecure").checked=
a.secure?!0:!1},fa=function(){let a=m.querySelector(".__prop"),b={},d;var c,e=f=>{let h;d=a.querySelector(f);f=d.value;""===f?d.focus():d.validity.valid?h=f:"reportValidity"in d&&d.reportValidity();return h};if(c=e("#__cdomain"))if(b.domain=c,c=e("#__cpath"))if(b.path=c,c=e("#__cname"))if(b.name=c,c=e("#__cstore")){b.storeId=c;if(c=a.querySelector("#__cpart").value)b.partitionKey={topLevelSite:c};b.value=a.querySelector("#__cval").value||"";b.session=a.querySelector("#__csession").checked;b.session||
(c=a.querySelector("#__cdate").value,e=a.querySelector("#__ctime").value,c=Date.parse(c+" "+e+" GMT"),b.expirationDate=c/1E3);c=a.querySelector("#__csamesite").value;b.sameSite=c?"none"===c?"no_restriction":c:"unspecified";b.hostOnly=a.querySelector("#__chostonly").checked;b.httpOnly=a.querySelector("#__chttponly").checked;b.secure=a.querySelector("#__csecure").checked}return"secure"in b?b:null},O=function(a){var b=fa();if(b)if(a){var d=b.hostOnly?"":";Domain="+b.domain,c=b.session?"":";Expires="+
(new Date(1E3*b.expirationDate)).toUTCString();a=b.path?";Path="+b.path:"";var e=b?.partitionKey?.topLevelSite?";Partitioned":"",f=b.secure||b.partitioned?";Secure":"",h=b.sameSite||"",k=b.httpOnly?";HttpOnly":"";h&&(h=h.toLowerCase(),"unspecified"==h?h="":"no_restriction"==h?(h=";SameSite=None",f=";Secure"):h="lax"==h?";SameSite=Lax":";SameSite=Strict");try{navigator.clipboard.writeText(b.name+"="+b.value+d+a+c+k+h+f+e)}catch(g){console.info(g)}}else if(130>F()&&b.partitionKey)V("Please note","Due to the Chromium bug, the partitioned cookies cannot be set correctly before Chromium version 130",
"Ok");else{a=b.domain;e=m.querySelectorAll("dt");for(let g=0,l=e.length;g<l;g++)if(f=e[g],h=f.domain,h===a){d={exist:f};break}else if(h>a){d={insertBefore:f};break}d=d?d:{append:!0};if(d.exist){a=d.exist.nextElementSibling.querySelectorAll("dd");for(let g=0,l=a.length;g<l;g++)if(e=a[g],f=e.cprop,f.name===b.name&&f.hostOnly==b.hostOnly&&f?.partitionKey?.topLevelSite==b?.partitionKey?.topLevelSite){c={exist:e};break}else if(f.name>b.name){c={insertBefore:e};break}c=c?c:{append:!0};if(c.exist)c.exist.cprop=
b,d=c.exist.firstElementChild.nextElementSibling,d.className=M(b),d.title="Third-party "+b.sameSite+";"+(b.secure?"Secure":"Insecure");else{a=H(b);e=d.exist.nextElementSibling;c.append?e.appendChild(a):e.insertBefore(a,c.insertBefore);w++;if(d=d.exist.querySelector("span"))c=parseInt(d.textContent,10)+1,d.textContent=isNaN(c)?"":c;C()}}else{c=m.querySelector(".__tree");a=N(b.domain);e=document.createElement("span");f=document.createElement("dl");h=m.querySelector(".__filter");k=h.value;let g=H(b);
k&&0>b.domain.indexOf(k)&&(a.hidden=!0,h.focus());e.textContent="1";a.appendChild(e);f.appendChild(g);d.append?(c.appendChild(a),c.appendChild(f)):(c.insertBefore(a,d.insertBefore),c.insertBefore(f,d.insertBefore));y++;w++;C();g.scrollIntoView()}b=Object.assign(b);B(5,[b])}},ha=function(){let a=m.querySelectorAll("dt:not([hidden]) + dl input:checked"),b=a&&a.length||0,d=function(c){if(c){let e=[];for(let f=0;f<b;f++)e.push(a[f].parentElement.cprop);e=JSON.stringify(e);X(e,c,10,function(f){W('data:application/json;utf-8,{"url":"https://www.hotcleaner.com/cookie-editor/cookie-manager.html","version":2,"data":"'+
f+'"}',"cookies.json")})}};0<b&&K("Export Cookies","Please enter a password which will be used to encrypt or decrypt cookies. Only someone knowing this password can access and use cookies. Please note: we cannot recover your password if you lose it, so please ensure you keep it in a safe place.","Export","Cancel",d)},ia=function(a){let b=function(d){try{Z(a.data,d,10,function(c){try{c=JSON.parse(c)}catch(e){c=null}c&&0<c.length&&c[0].domain&&I(c,!0)})}catch(c){alert("Could not decrypt data.")}};try{a=
JSON.parse(a)}catch(d){a=null}a&&2==a.version&&a.data&&K("Import Cookies","Password required to decrypt cookies data:","Decrypt","Cancel",b)},ja=function(){let a=document.createElement("input"),b,d=function(e){b.removeEventListener("load",d,!1);ia(e.target.result||0);a=b=null},c=function(e){if(e&&e.isTrusted){let f=(e=e.target)&&e.files||[],h=f.length;e.removeEventListener("change",c,!1);1===h&&(b=new FileReader,b.addEventListener("load",d,!1),b.readAsText(f[0]))}};a.type="file";a.addEventListener("change",
c,!1);a.click()},ka=function(a){a&&a.isTrusted&&(a=a.target,"checkbox"===a.type?ba(a.checked):a.classList.contains("__btn-expand")?aa():a.classList.contains("__btn-refresh")?P(function(b){I(b,!1)}):a.classList.contains("__btn-remove")&&ca())},Q=function(a){if(a&&a.isTrusted)if(a=a.target,"checkbox"===a.type){var b=a.parentElement;if("dt"===b.localName){a=a.checked;b=b.nextElementSibling.querySelectorAll("input");for(let d=0,c=b.length;d<c;d++)b[d].checked=a}}else if(a.classList.contains("__btn-web"))window.open("https://"+
a.nextElementSibling.textContent,"_blank","noopener");else if("dd"===a.localName)L(a.cprop);else if("span"===a.localName&&"dd"===a.parentElement.localName)L(a.parentElement.cprop);else if("dt"===a.parentElement.localName)a.parentElement.classList.toggle("__expanded");else if(a.classList.contains("__btn-setsel")){a=130>F();let d=(b=m.querySelectorAll("dt:not([hidden]) + dl input:checked"))&&b.length||0;if(0<d){let c=[];for(let e=0;e<d;e++){let f=Object.assign(b[e].parentElement.cprop);a&&f.partitionKey||
c.push(f)}0<c.length&&B(5,c)}}},la=function(a){a&&a.isTrusted&&(a=a.target,a.classList.contains("__btn-export")&&ha(),a.classList.contains("__btn-import")&&ja())},ma=function(a){if(a&&a.isTrusted){var b=(a=a.target)&&a.id;if("__csession"===b){b=m.querySelector("#__cdate");let d=m.querySelector("#__ctime");b.disabled=d.disabled=a.checked}else"__btn-cset"===b?O(!1):"__btn-ccjs"===b&&O(!0)}},N=function(a){let b=document.createElement("dt");b.domain=a;v(b,[{n:"input",type:"checkbox",className:"__chk"},
{n:"button",className:"__btn-web",title:"Website"},{n:"b",textContent:a}]);return b},M=function(a){let b=a.sameSite||"unspecified";return"strict"===b?"__cook-green":"lax"===b?"__cook-salad":"unspecified"===b?"__cook-white":a.secure?"__cook-yellow":"__cook-red"},H=function(a){let b=document.createElement("dd"),d=a?.partitionKey?.topLevelSite;b.cprop=a;v(b,[{n:"input",type:"checkbox",className:"__chk"},{n:"i",className:M(a),title:"Third-Party "+a.sameSite+";"+(a.secure?"Secure":"Insecure")},{n:"span",
textContent:a.name+(d?" at "+d:"")}]);return b},I=function(a,b){var d=m.querySelector(".__lbox");var c=d.querySelector(".__tree");c&&(c.removeEventListener("click",Q,!1),c.remove());c=document.createElement("div");c.className="__tree";d.insertBefore(c,d.firstElementChild);c.addEventListener("click",Q,!1);y=w=0;C();d=c;c=document.createDocumentFragment();let e,f,h,k;if(b){var g=document.createElement("div");g.className="__imported";g.appendChild(document.createTextNode("Imported cookies. Select required cookies and click on the "));
b=document.createElement("button");b.className="__btn-setsel";b.textContent="Set";g.appendChild(b);c.appendChild(g);d.classList.add("__imported")}for(let l=0,p=a.length;l<p;l++)g=a[l],h!==g.domain&&(e&&(b=document.createElement("span"),b.textContent=k,e.appendChild(b)),h=g.domain,e=N(h),c.appendChild(e),f=document.createElement("dl"),c.appendChild(f),y++,k=0),b=H(g),f.appendChild(b),k++,w++;e&&(b=document.createElement("span"),b.textContent=k,e.appendChild(b));d.appendChild(c);C()},v=function(a,b){let d;
b.forEach(c=>{d=document.createElement(c.n);for(let e in c)"n"!==e&&(d[e]=c[e]);a.appendChild(d)})},na=function(){let a=document.createElement("div");a.className="__controls";v(a,[{n:"input",type:"checkbox",className:"__chk"},{n:"button",className:"__btn-expand",title:"Expand / Collapse All"},{n:"button",className:"__btn-refresh",title:"Refresh to see what \ncookies are set"},{n:"button",className:"__btn-remove",title:"Delete Selected"},{n:"input",type:"text",className:"__filter",placeholder:"Filter by domain",
spellcheck:!1}]);a.querySelector(".__filter").addEventListener("keyup",da,!1);return a},oa=function(){let a=document.createElement("div");a.className="__status";v(a,[{n:"span",textContent:"Initializing…"},{n:"button",className:"__btn-export",textContent:"Export",title:"Encypt selected cookies and save to file."},{n:"button",className:"__btn-import",textContent:"Import",title:"Import cookies from \nan encrypted file."}]);a.addEventListener("click",la,!1);return a},P=async function(a){let b=await B(3,
null);if(b&&0<b.length){for(let c=0,e=b.length;c<e;c++){var d=b[c].domain;"."===d[0]&&(b[c].domain=d.slice(1))}b.sort((c,e)=>{c=c.domain+c.name;e=e.domain+e.name;return c==e?0:c<e?-1:1});for(let c=0,e=b.length;c<e;c++)if(d=b[c].domain||"",-1<d.indexOf("xn--"))try{b[c].domain=U(d)}catch(f){console.info(f)}}else b=[];a(b)},pa=function(){m=document.body.attachShadow({mode:"open"});var a=document.createElement("link");a.rel="stylesheet";a.href="fcss129/eeditor129.css";m.appendChild(a);a=document.createElement("div");
a.className="__editor";m.appendChild(a);let b=document.createElement("div");b.className="__lbox";a.appendChild(b);a=na();a.addEventListener("click",ka,!1);b.appendChild(a);a=oa();b.appendChild(a);P(function(d){I(d,!1);d=document.createElement("div");d.className="__prop";v(d,[{n:"label",htmlFor:"__cdomain",textContent:"Domain"},{n:"br"},{n:"input",type:"text",id:"__cdomain",spellcheck:!1,placeholder:"The domain of the cookie"},{n:"br"},{n:"label",htmlFor:"__cpath",textContent:"Path"},{n:"br"},{n:"input",
type:"text",id:"__cpath",spellcheck:!1,placeholder:"The path of the cookie"},{n:"br"},{n:"label",htmlFor:"__cname",textContent:"Name",title:'Not allowed characters: \n( ) < > @ , ; :  " / [ ] ? = { }'},{n:"br"},{n:"input",type:"text",id:"__cname",spellcheck:!1,placeholder:"The name of the cookie"},{n:"br"},{n:"label",id:"__lstore",htmlFor:"__cstore",textContent:"Store ID",title:"Represents a cookie store in the browser. \nAn incognito mode window, for instance, \nuses a separate cookie store from \na non-incognito window"},
{n:"label",id:"__lpart",htmlFor:"__cpart",textContent:"Partition Key",title:"Partiitoned cookies can only be read \nwithin the context of the top-level site \nthey were set on."},{n:"br"},{n:"input",type:"number",id:"__cstore",value:0,min:0},{n:"input",type:"text",id:"__cpart",spellcheck:!1,placeholder:"The top-level site",title:"The top-level site the partitioned cookie is available in.\nFor example https://www.example.com\nLeave empty for unpartitioned cookies."},{n:"br"},{n:"label",htmlFor:"__cval",
textContent:"Value"},{n:"br"},{n:"textarea",id:"__cval",spellcheck:!1,rows:2,placeholder:"Empty"},{n:"label",htmlFor:"__cdate",textContent:"Expires",title:"The expiration date of the persistent cookie. \nNot required for session cookies.\nFrom Chrome 104 no more than 400 days."},{n:"br"},{n:"input",type:"date",id:"__cdate",title:"Date YYYY-MM-DD"},{n:"input",type:"time",id:"__ctime",title:"Time HH-MM"},{n:"br"},{n:"label",htmlFor:"__csamesite",textContent:"Same Site",title:"Set to none, lax, strict or leave empty. \nIf you set none, then select the Secure \ncheckbox also!"},
{n:"br"},{n:"input",type:"text",id:"__csamesite",placeholder:"Set to none, lax, strict or leave empty",pattern:"(strict|lax|none)"},{n:"br"},{n:"input",type:"checkbox",className:"__chk",id:"__csession"},{n:"label",htmlFor:"__csession",textContent:"Session",title:"The cookie will be deleted when the browser closes."},{n:"input",type:"checkbox",className:"__chk",id:"__chostonly"},{n:"label",htmlFor:"__chostonly",textContent:"Host-Only",title:"A request's host must exactly match the domain of the cookie.\nThe cookie becomes inaccessible to subdomains."},
{n:"br"},{n:"input",type:"checkbox",className:"__chk",id:"__chttponly"},{n:"label",htmlFor:"__chttponly",textContent:"Http-Only",title:"The cookie becomes inaccessible to client-side scripts."},{n:"input",type:"checkbox",className:"__chk",id:"__csecure"},{n:"label",htmlFor:"__csecure",textContent:"Secure",title:"A secure cookie can only be transmitted \nover an encrypted channel, for example HTTPS."},{n:"br"},{n:"button",id:"__btn-ccjs",textContent:"Copy",title:"Copy as string"},{n:"button",id:"__btn-cset",
textContent:"Update / Create new",title:"Save changes to the corresponding cookie \nor create a new one if a cookie does not exist yet."}]);d.addEventListener("click",ma,!1);m.querySelector(".__editor").appendChild(d)})},R=function(){J||(J=!0,pa())};window.top==window.self?window.location.href="https://www.hotcleaner.com/cookie-editor/cookie-manager.html":"complete"==document.readyState?R():window.addEventListener("DOMContentLoaded",R,!0)})();
