T.CTMLoader=function(a){T.Loader.call(this,a)};T.CTMLoader.prototype=Object.create(T.Loader.prototype);
T.CTMLoader.prototype.loadParts=function(a,r,c,u){var m=this,e=new XMLHttpRequest,l=0,h=c.basePath?c.basePath:this.extractUrlBase(a);e.onreadystatechange=function(){if(4===e.readyState){if(200===e.status||0===e.status){for(var a=JSON.parse(e.responseText),d=[],v=[],p=0,q=0;q<a.materials.length;q++)d[q]=T.Loader.prototype.createMaterial(a.materials[q],h);m.load(h+a.data,function(w){p+=1;v.push(w);p===a.offsets.length&&r(v,d)},{useWorker:c.useWorker,useBuffers:c.useBuffers,offsets:a.offsets})}}else 3==
request.readyState&&u&&(0==l&&(l=request.getResponseHeader("Content-Length")),u({total:l,loaded:request.responseText.length}))};e.open("GET",a,!0);T.FileOperations.setXHRHeader&&T.FileOperations.setXHRHeader(e,a);e.overrideMimeType&&e.overrideMimeType("text/plain; charset=x-user-defined");e.setRequestHeader("Content-Type","text/plain");e.send(null);return e};
T.CTMLoader.prototype.load=function(a,r,c,u,m){var e=this,l=void 0!==c.offsets?c.offsets:[0],h=void 0!==c.useBuffers?c.useBuffers:!0,k=0,d=new XMLHttpRequest;d.onreadystatechange=function(){if(4===d.readyState)if(200===d.status||0===d.status){var v=d.responseText;if(c.useWorker){var p=new Worker("js/loaders/ctm/CTMWorker.js");p.onmessage=function(a){a=a.data;for(var d=0;d<a.length;d++){var n=a[d];h?e.createModelBuffers(n,r):e.createModelClassic(n,r)}};p.postMessage({data:v,offsets:l})}else for(p=
0;p<l.length;p++){var q=new CTM.Stream(v);q.offset=l[p];q=new CTM.File(q);h?e.createModelBuffers(q,r):e.createModelClassic(q,r)}}else m&&m({type:"error",message:"Couldn't load URL ["+a+"]",responseStatus:event.target.status}),console.error("Couldn't load ["+a+"] ["+d.status+"]");else 3===d.readyState?u&&(0===k&&(k=d.getResponseHeader("Content-Length")),u({total:k,loaded:d.responseText.length})):2===d.readyState&&(k=d.getResponseHeader("Content-Length"))};d.overrideMimeType("text/plain; charset=x-user-defined");
d.open("GET",a,!0);T.FileOperations.setXHRHeader&&T.FileOperations.setXHRHeader(d,a);d.send(null);return d};
T.CTMLoader.prototype.createModelBuffers=function(a,r){var c=function(){this.materials=[];T.BufferGeometry.call(this);var c=a.body.indices,m=a.body.vertices,e=a.body.normals,l,h;void 0!==a.body.uvMaps&&0<a.body.uvMaps.length&&(l=a.body.uvMaps[0].uv);void 0!==a.body.attrMaps&&0<a.body.attrMaps.length&&"Color"===a.body.attrMaps[0].name&&(h=a.body.attrMaps[0].attr);var k=function(b){if(void 0===z[b]){z[b]=n;var a=3*b,d=3*b+1,f=3*b+2,g=3*n,c=3*n+1,k=3*n+2;v[g]=m[a];v[c]=m[d];v[k]=m[f];e&&(p[g]=e[a],p[c]=
e[d],p[k]=e[f]);l&&(q[2*n]=l[2*b],q[2*n+1]=l[2*b+1]);h&&(w[4*n]=h[4*b],w[4*n+1]=h[4*b+1],w[4*n+2]=h[4*b+2],w[4*n+3]=h[4*b+3]);n+=1}},d=new Uint32Array(c.length),v=new Float32Array(m.length),p,q,w;e&&(p=new Float32Array(e.length));l&&(q=new Float32Array(l.length));h&&(w=new Float32Array(h.length));for(var z={},n=0,g,b,x,f=0;f<c.length;f+=3)g=c[f],b=c[f+1],x=c[f+2],k(g),k(b),k(x),d[f]=z[g],d[f+1]=z[b],d[f+2]=z[x];c=d;m=v;e&&(e=p);l&&(l=q);h&&(h=w);this.offsets=[];k=c;d=0;b=m.length;x=0;g=b;for(f=0;f<
k.length;){for(var t=0;3>t;++t){var r=k[f++];r<b&&(b=r);r>x&&(x=r)}if(65535<x-b){f-=3;for(b=d;b<f;++b)k[b]-=g;this.offsets.push({start:d,count:f-d,index:g});d=f;b=m.length;x=0}g=b}for(b=d;b<f;++b)k[b]-=g;this.offsets.push({start:d,count:f-d,index:g});c=new Uint16Array(c);f=this.attributes;f.index={itemSize:1,array:c,numItems:c.length};f.position={itemSize:3,array:m,numItems:m.length};void 0!==e&&(f.normal={itemSize:3,array:e,numItems:e.length});void 0!==l&&(f.uv={itemSize:2,array:l,numItems:l.length});
void 0!==h&&(f.color={itemSize:4,array:h,numItems:h.length})};c.prototype=Object.create(T.BufferGeometry.prototype);c=new c;void 0===c.attributes.normal&&c.computeVertexNormals();r(c)};
T.CTMLoader.prototype.createModelClassic=function(a,r){var c=function(){function c(a){var d,n,g,b,e=a.length;for(b=0;b<e;b+=3)d=a[b],n=a[b+1],g=a[b+2],h.push(d,n,g)}function m(a){var c,n,g,b,e=a.length;for(b=0;b<e;b+=4){c=a[b];n=a[b+1];g=a[b+2];var f=new T.Color;f.setRGB(c,n,g);d.push(f)}}function e(a){var d,c,g,b=a.length;for(g=0;g<b;g+=2)d=a[g],c=a[g+1],k.push(d,c)}var l=this;l.materials=[];T.Geometry.call(this);var h=[],k=[],d=[];(function(a){var d,c,g,b,e=a.length;for(b=0;b<e;b+=3)d=a[b],c=a[b+
1],g=a[b+2],l.vertices.push(new T.V3(d,c,g))})(a.body.vertices);void 0!==a.body.normals&&c(a.body.normals);void 0!==a.body.uvMaps&&0<a.body.uvMaps.length&&e(a.body.uvMaps[0].uv);void 0!==a.body.attrMaps&&0<a.body.attrMaps.length&&"Color"===a.body.attrMaps[0].name&&m(a.body.attrMaps[0].attr);var r=0<h.length?!0:!1,p=0<k.length?!0:!1,q=0<d.length?!0:!1;this.useColor=q;(function(a){var c,e,g,b,m,f,t,u,y,C=a.length;for(y=0;y<C;y+=3){c=a[y];e=a[y+1];g=a[y+2];if(r){b=l;t=c;u=e;m=g;var A=h[3*e],D=h[3*e+
1],E=h[3*e+2],B=h[3*g],F=h[3*g+1],G=h[3*g+2];f=new T.V3(h[3*c],h[3*c+1],h[3*c+2]);A=new T.V3(A,D,E);B=new T.V3(B,F,G);t=new T.F3(t,u,m,[f,A,B],null,0)}else b=l,t=new T.F3(c,e,g,null,null,0);b.faces.push(t);b=t;q&&(b.vertexColors[0]=d[c],b.vertexColors[1]=d[e],b.vertexColors[2]=d[g]);p&&(b=k[2*c],c=k[2*c+1],m=k[2*e],f=k[2*e+1],t=k[2*g],u=k[2*g+1],g=l.faceVertexUvs[0],e=m,m=f,f=[],f.push(new T.Vector2(b,c)),f.push(new T.Vector2(e,m)),f.push(new T.Vector2(t,u)),g.push(f))}})(a.body.indices);this.computeCentroids();
this.computeFaceNormals()};c.prototype=Object.create(T.Geometry.prototype);r(new c)};
