function GDocs(a){this.lastResponse=null;this.__defineGetter__("SCOPE",function(){return"https://www.googleapis.com/drive/v2/"});this.__defineGetter__("DOCLIST_FEED",function(){return"https://www.googleapis.com/drive/v2/files"});this.__defineGetter__("CREATE_SESSION_URI",function(){return"https://www.googleapis.com/upload/drive/v2/files?uploadType=resumable"});this.__defineGetter__("DEFAULT_CHUNK_SIZE",function(){return 5242880})}
GDocs.prototype.auth=function(a,b){try{chrome.identity.getAuthToken({interactive:a},function(a){a&&(this.accessToken=a,b&&b())}.bind(this))}catch(c){console.log(c)}};GDocs.prototype.removeCachedAuthToken=function(a){if(this.accessToken){var b=this.accessToken;this.accessToken=null;try{chrome.identity.removeCachedAuthToken({token:b},function(){a&&a()})}catch(c){console.log(c)}}else a&&a()};
GDocs.prototype.revokeAuthToken=function(a){if(this.accessToken){var b=new XMLHttpRequest;b.open("GET","https://accounts.google.com/o/oauth2/revoke?token="+this.accessToken);b.send();this.xhr=b;this.removeCachedAuthToken(a)}};
GDocs.prototype.makeRequest=function(a,b,c,d,e,g){e=e||null;g=g||{};var f=new XMLHttpRequest;f.open(a,b,!0);f.setRequestHeader("Authorization","Bearer "+this.accessToken);for(var k in g)f.setRequestHeader(k,g[k]);f.onload=function(a){this.lastResponse=this.response=a.target.response;this.lastStatus=a.target.status;c(this.lastResponse,this,this.lastStatus)}.bind(this);f.onerror=function(a){this.response=a.target.response;d(this.response)};f.send(e);this.xhr=f};
GDocs.prototype.getCurrentXHR=function(){return this.uploader&&this.uploader.xhr?this.uploader.xhr:this.xhr};GDocs.prototype.getItemProperties=function(a,b,c){this.makeRequest("GET",this.DOCLIST_FEED+"/"+a,b,c,null)};GDocs.prototype.queryItems=function(a,b,c,d,e){a=this.DOCLIST_FEED+"?maxResults="+(e?e:100)+"&q="+encodeURIComponent(a);b&&(a=a+"&pageToken="+b);this.makeRequest("GET",a,c,d,null)};GDocs.prototype.removeFile=function(a,b,c){this.makeRequest("DELETE",this.DOCLIST_FEED+"/"+a,b,c,null)};
GDocs.prototype.getItemComments=function(a,b,c,d,e,g){a=this.DOCLIST_FEED+"/"+a+"/comments?maxResults="+(g?g:20)+"&fields=items%2CnextPageToken&includeDeleted=true";b&&(a=a+"&pageToken="+b);c&&(a=a+"&updatedMin="+encodeURIComponent(c));this.makeRequest("GET",a,d,e,null)};GDocs.prototype.addItemComment=function(a,b,c,d){this.makeRequest("POST",this.DOCLIST_FEED+"/"+b+"/comments",c,d,JSON.stringify({content:a}),{"content-type":"application/json"})};
GDocs.prototype.removeItemComment=function(a,b,c,d){this.makeRequest("DELETE",this.DOCLIST_FEED+"/"+b+"/comments/"+a,c,d,null)};GDocs.prototype.removeItemCommentReply=function(a,b,c,d,e){this.makeRequest("DELETE",this.DOCLIST_FEED+"/"+c+"/comments/"+b+"/replies/"+a,d,e,null)};GDocs.prototype.about=function(a,b){this.makeRequest("GET",this.SCOPE+"about?includeSubscribed=false",a,b,null)};
GDocs.prototype.setPermissions=function(a,b,c,d,e,g,f){b={value:"default",type:b,role:c,withLink:d};"reader"==c&&e&&(b.additionalRoles=["commenter"]);this.makeRequest("POST",this.DOCLIST_FEED+"/"+a+"/permissions",g,f,JSON.stringify(b),{fileId:a,"content-type":"application/json"})};
GDocs.prototype.setRevisionProperties=function(a,b,c,d,e,g,f,k){var h={};void 0!==c&&(h.pinned=c);void 0!==d&&(h.publishAuto=d);void 0!==e&&(h.published=e);void 0!==g&&(h.publishedOutsideDomain=g);this.makeRequest("PUT",this.DOCLIST_FEED+"/"+a+"/revisions/"+b,f,k,JSON.stringify(h),{"content-type":"application/json"})};GDocs.prototype.getItemRevisions=function(a,b,c){this.makeRequest("GET",this.DOCLIST_FEED+"/"+a+"/revisions",b,c,null)};
GDocs.prototype.getRevisionsProperties=function(a,b,c,d){this.makeRequest("GET",this.DOCLIST_FEED+"/"+a+"/revisions/"+b,c,d,null)};GDocs.prototype.removeRevision=function(a,b,c,d){this.makeRequest("DELETE",this.DOCLIST_FEED+"/"+a+"/revisions/"+b,c,d,null)};
GDocs.prototype.upload=function(a,b,c,d,e,g,f){function k(a,b,c,d,e){h.setPermissions(b,"anyone","writer",!0,!0,function(b){d&&d.call(h,a)},function(a){console.log("Error setting permissions.",a);e&&e.call(h,a)})}var h=this,m=function(a){a=JSON.parse(a);var c=a.id,e=a.headRevisionId,h=a.webContentLink;g&&c&&h&&this.accessToken?f?b.call(this,a):k(a,c,e,b,d):b.call(this,a)}.bind(this),n=function(c){e?this.removeCachedAuthToken(this.auth.bind(this,!0,this.upload.bind(this,a,b,!1))):(console.log("Error during upload.",
c),d(c))}.bind(this),l=function(b,d){h.folderId=b;var e={token:this.accessToken,file:a,metadata:{description:"STL file uploaded from 3DView app",title:a.name,mimeType:a.type,writersCanShare:!0},params:{pinned:!0},contentType:a.type,onComplete:m,onProgress:c,onError:n};d&&(e.fileId=d,e.params.newRevision=!0);b&&null!=b&&""!=b&&(e.metadata.parents=[{kind:"drive#fileLink",id:b}]);this.uploader=new MediaUploader(e);this.uploader.upload()}.bind(this),p=function(a,b,c){this.makeRequest("POST",this.DOCLIST_FEED,
b,c,JSON.stringify({title:a,mimeType:"application/vnd.google-apps.folder"}),{"content-type":"application/json"})}.bind(this),q=function(a,b,c){this.makeRequest("GET",this.DOCLIST_FEED+"?q=title+%3D+'"+a+"'+and+mimeType+%3D+'application%2Fvnd.google-apps.folder'+and+trashed%3Dfalse",b,c,null)}.bind(this);f?l(null,f):q("3DView",function(a){var b=JSON.parse(a);b.items&&0<b.items.length?l(b.items[0].id):p("3DView",function(a){a=JSON.parse(a);l(a.id)},function(){console.log("Unable make new folder.",a);
l()})},function(a){console.log("Unable to check for a folder existance.",a);l()})};
