var RetryHandler=function(){this.interval=1E3;this.maxInterval=6E4};RetryHandler.prototype.retry=function(a){setTimeout(a,this.interval);this.interval=this.nextInterval_()};RetryHandler.prototype.reset=function(){this.interval=1E3};RetryHandler.prototype.nextInterval_=function(){var a=2*this.interval+this.getRandomInt_(0,1E3);return Math.min(a,this.maxInterval)};RetryHandler.prototype.getRandomInt_=function(a,b){return Math.floor(Math.random()*(b-a+1)+a)};
var MediaUploader=function(a){var b=function(){};this.file=a.file;this.fileId=a.fileId;this.contentType=a.contentType||this.file.type||"application/octet-stream";this.metadata=a.metadata||{title:this.file.name,mimeType:this.contentType};this.token=a.token;this.onComplete=a.onComplete||b;this.onError=a.onError||b;this.onProgress=a.onProgress||b;this.offset=a.offset||0;this.chunkSize=a.chunkSize||0;this.retryHandler=new RetryHandler;this.url=a.url;this.url||(b=a.params||{},b.uploadType="resumable",
this.url=this.buildUrl_(a.fileId,b));this.httpMethod=this.fileId?"PUT":"POST"};
MediaUploader.prototype.upload=function(){var a=new XMLHttpRequest;a.open(this.httpMethod,this.url,!0);a.setRequestHeader("Authorization","Bearer "+this.token);a.setRequestHeader("Content-Type","application/json");a.setRequestHeader("X-Upload-Content-Length",this.file.size);a.setRequestHeader("X-Upload-Content-Type",this.contentType);a.onload=function(a){this.url=a.target.getResponseHeader("Location");this.sendFile_()}.bind(this);a.onerror=this.onUploadError_.bind(this);a.send(JSON.stringify(this.metadata));
this.xhr=a};
MediaUploader.prototype.sendFile_=function(){var a=this.file,b=this.file.size;if(this.offset||this.chunkSize)this.chunkSize&&(b=Math.min(this.offset+this.chunkSize,this.file.size)),a=a.slice(this.offset,b);var c=new XMLHttpRequest;c.open("PUT",this.url,!0);c.setRequestHeader("Content-Type",this.contentType);c.setRequestHeader("Content-Range","bytes "+this.offset+"-"+(b-1)+"/"+this.file.size);c.setRequestHeader("X-Upload-Content-Type",this.file.type);c.onload=this.onContentUploadSuccess_.bind(this);c.upload?
c.upload.onprogress=this.onContentUploadProgress_.bind(this):c.onprogress=this.onContentUploadProgress_.bind(this);c.onerror=this.onContentUploadError_.bind(this);c.send(a);this.xhr=c};
MediaUploader.prototype.resume_=function(){var a=new XMLHttpRequest;a.open("PUT",this.url,!0);a.setRequestHeader("Content-Range","bytes */"+this.file.size);a.setRequestHeader("X-Upload-Content-Type",this.file.type);a.onload=this.onContentUploadSuccess_.bind(this);a.upload?a.upload.onprogress=this.onContentUploadProgress_.bind(this):a.onprogress=this.onContentUploadProgress_.bind(this);a.onerror=this.onContentUploadError_.bind(this);a.send();this.xhr=a};
MediaUploader.prototype.extractRange_=function(a){if(a=a.getResponseHeader("Range"))this.offset=parseInt(a.match(/\d+/g).pop(),10)+1};MediaUploader.prototype.onContentUploadSuccess_=function(a){if(200==a.target.status||201==a.target.status)this.onComplete(a.target.response);else 308==a.target.status&&(this.extractRange_(a.target),this.retryHandler.reset(),this.sendFile_())};MediaUploader.prototype.onContentUploadProgress_=function(a){this.onProgress(a)&&this.xhr&&(this.xhr.abort(),this.onComplete("{}"))};
MediaUploader.prototype.onContentUploadError_=function(a){if(a.target.status&&500>a.target.status)this.onError(a.target.response);else this.retryHandler.retry(this.resume_.bind(this))};MediaUploader.prototype.onUploadError_=function(a){this.onError(a.target.response)};MediaUploader.prototype.buildQuery_=function(a){a=a||{};return Object.keys(a).map(function(b){return encodeURIComponent(b)+"="+encodeURIComponent(a[b])}).join("&")};
MediaUploader.prototype.buildUrl_=function(a,b){var c="https://www.googleapis.com/upload/drive/v2/files/";a&&(c+=a);var d=this.buildQuery_(b);d&&(c+="?"+d);return c};
