//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VariIconsReload.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VariIconsReload.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Airbrush ähnelt.
        /// </summary>
        internal static string AirBrushTool_Name {
            get {
                return ResourceManager.GetString("AirBrushTool_Name", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap antialias {
            get {
                object obj = ResourceManager.GetObject("antialias", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap batch {
            get {
                object obj = ResourceManager.GetObject("batch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brightness ähnelt.
        /// </summary>
        internal static string BrightnessEffect_Brightness {
            get {
                return ResourceManager.GetString("BrightnessEffect_Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contrast ähnelt.
        /// </summary>
        internal static string BrightnessEffect_Contrast {
            get {
                return ResourceManager.GetString("BrightnessEffect_Contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brightness and Contrast ähnelt.
        /// </summary>
        internal static string BrightnessEffect_Name {
            get {
                return ResourceManager.GetString("BrightnessEffect_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brush ähnelt.
        /// </summary>
        internal static string BrushTool_Name {
            get {
                return ResourceManager.GetString("BrushTool_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Strength: ähnelt.
        /// </summary>
        internal static string BrushTool_Strength {
            get {
                return ResourceManager.GetString("BrushTool_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brightness ähnelt.
        /// </summary>
        internal static string ColorEffect_Brightness {
            get {
                return ResourceManager.GetString("ColorEffect_Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hue ähnelt.
        /// </summary>
        internal static string ColorEffect_Hue {
            get {
                return ResourceManager.GetString("ColorEffect_Hue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Colorize ähnelt.
        /// </summary>
        internal static string ColorEffect_Name {
            get {
                return ResourceManager.GetString("ColorEffect_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saturation ähnelt.
        /// </summary>
        internal static string ColorEffect_Saturation {
            get {
                return ResourceManager.GetString("ColorEffect_Saturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Desaturate ähnelt.
        /// </summary>
        internal static string DesaturateEffect_Name {
            get {
                return ResourceManager.GetString("DesaturateEffect_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Draw Ellipse ähnelt.
        /// </summary>
        internal static string DrawEllipseTool_Name {
            get {
                return ResourceManager.GetString("DrawEllipseTool_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Line ähnelt.
        /// </summary>
        internal static string DrawLineTool_Name {
            get {
                return ResourceManager.GetString("DrawLineTool_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Draw Pie ähnelt.
        /// </summary>
        internal static string DrawPieTool_Name {
            get {
                return ResourceManager.GetString("DrawPieTool_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Draw Polygon ähnelt.
        /// </summary>
        internal static string DrawPolygonTool_Name {
            get {
                return ResourceManager.GetString("DrawPolygonTool_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Draw Rectangle ähnelt.
        /// </summary>
        internal static string DrawRectTool_Name {
            get {
                return ResourceManager.GetString("DrawRectTool_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Draw Rounded Rectangle ähnelt.
        /// </summary>
        internal static string DrawRoundedRectTool_Name {
            get {
                return ResourceManager.GetString("DrawRoundedRectTool_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spline ähnelt.
        /// </summary>
        internal static string DrawSplineTool_Name {
            get {
                return ResourceManager.GetString("DrawSplineTool_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Width: ähnelt.
        /// </summary>
        internal static string DrawTool_Width {
            get {
                return ResourceManager.GetString("DrawTool_Width", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ef_box {
            get {
                object obj = ResourceManager.GetObject("ef_box", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ef_bright {
            get {
                object obj = ResourceManager.GetObject("ef_bright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ef_canvas {
            get {
                object obj = ResourceManager.GetObject("ef_canvas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ef_contrast {
            get {
                object obj = ResourceManager.GetObject("ef_contrast", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ef_extra {
            get {
                object obj = ResourceManager.GetObject("ef_extra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ef_fliphor {
            get {
                object obj = ResourceManager.GetObject("ef_fliphor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ef_flipver {
            get {
                object obj = ResourceManager.GetObject("ef_flipver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ef_negative {
            get {
                object obj = ResourceManager.GetObject("ef_negative", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ef_replacecol {
            get {
                object obj = ResourceManager.GetObject("ef_replacecol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ef_rotatefree {
            get {
                object obj = ResourceManager.GetObject("ef_rotatefree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ef_rotleft {
            get {
                object obj = ResourceManager.GetObject("ef_rotleft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ef_rotright {
            get {
                object obj = ResourceManager.GetObject("ef_rotright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ef_shadow {
            get {
                object obj = ResourceManager.GetObject("ef_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Effects ähnelt.
        /// </summary>
        internal static string EffectManager_EffectBar_Text {
            get {
                return ResourceManager.GetString("EffectManager_EffectBar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eraser ähnelt.
        /// </summary>
        internal static string EraserTool_Name {
            get {
                return ResourceManager.GetString("EraserTool_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fill Ellipse ähnelt.
        /// </summary>
        internal static string FillEllipseTool_Name {
            get {
                return ResourceManager.GetString("FillEllipseTool_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fill Pie ähnelt.
        /// </summary>
        internal static string FillPieTool_Name {
            get {
                return ResourceManager.GetString("FillPieTool_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fill Polygon ähnelt.
        /// </summary>
        internal static string FillPolygonTool_Name {
            get {
                return ResourceManager.GetString("FillPolygonTool_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fill Rectangle ähnelt.
        /// </summary>
        internal static string FillRectTool_Name {
            get {
                return ResourceManager.GetString("FillRectTool_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fill Rounded Rectangle ähnelt.
        /// </summary>
        internal static string FillRoundedRectTool_Name {
            get {
                return ResourceManager.GetString("FillRoundedRectTool_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Region Flood ähnelt.
        /// </summary>
        internal static string FloodTool_Name {
            get {
                return ResourceManager.GetString("FloodTool_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icon ähnelt.
        /// </summary>
        internal static string IconEditorFactory_DocumentName {
            get {
                return ResourceManager.GetString("IconEditorFactory_DocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Icon with Standart Image Set... ähnelt.
        /// </summary>
        internal static string IconEditorFactory_NewText {
            get {
                return ResourceManager.GetString("IconEditorFactory_NewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Icon from File... ähnelt.
        /// </summary>
        internal static string IconEditorFactory_OpenText {
            get {
                return ResourceManager.GetString("IconEditorFactory_OpenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create from Images... ähnelt.
        /// </summary>
        internal static string IconEditorPlugin_CreateFromImages {
            get {
                return ResourceManager.GetString("IconEditorPlugin_CreateFromImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icon Library ähnelt.
        /// </summary>
        internal static string IconLibraryEditorFactory_DocumentName {
            get {
                return ResourceManager.GetString("IconLibraryEditorFactory_DocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Icon Library from Executable File... ähnelt.
        /// </summary>
        internal static string IconLibraryFactory_OpenText {
            get {
                return ResourceManager.GetString("IconLibraryFactory_OpenText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap library {
            get {
                object obj = ResourceManager.GetObject("library", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lock_alpha {
            get {
                object obj = ResourceManager.GetObject("lock_alpha", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lock_blue {
            get {
                object obj = ResourceManager.GetObject("lock_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lock_green {
            get {
                object obj = ResourceManager.GetObject("lock_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lock_red {
            get {
                object obj = ResourceManager.GetObject("lock_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lst_minus {
            get {
                object obj = ResourceManager.GetObject("lst_minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lst_plus {
            get {
                object obj = ResourceManager.GetObject("lst_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap movdo {
            get {
                object obj = ResourceManager.GetObject("movdo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap movle {
            get {
                object obj = ResourceManager.GetObject("movle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap movri {
            get {
                object obj = ResourceManager.GetObject("movri", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap movup {
            get {
                object obj = ResourceManager.GetObject("movup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click and Drag for Moving or Press Alt  and Scroll for Zoom ähnelt.
        /// </summary>
        internal static string NavigatorTool_Description {
            get {
                return ResourceManager.GetString("NavigatorTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Navigator ähnelt.
        /// </summary>
        internal static string NavigatorTool_Name {
            get {
                return ResourceManager.GetString("NavigatorTool_Name", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap newicon {
            get {
                object obj = ResourceManager.GetObject("newicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Tool Options ähnelt.
        /// </summary>
        internal static string NoConfig {
            get {
                return ResourceManager.GetString("NoConfig", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap openicon {
            get {
                object obj = ResourceManager.GetObject("openicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pencil ähnelt.
        /// </summary>
        internal static string PencilTool_Name {
            get {
                return ResourceManager.GetString("PencilTool_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click and drag for drawing. Right click and drag for drawing with background brush ähnelt.
        /// </summary>
        internal static string PenTool_Description {
            get {
                return ResourceManager.GetString("PenTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shape: ähnelt.
        /// </summary>
        internal static string PenTool_TipShape {
            get {
                return ResourceManager.GetString("PenTool_TipShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color Picker ähnelt.
        /// </summary>
        internal static string PickTool_Name {
            get {
                return ResourceManager.GetString("PickTool_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click to add a point, double click or hit return for finishing the shape. Right mouse button for background brush. ähnelt.
        /// </summary>
        internal static string PointListTool_Description {
            get {
                return ResourceManager.GetString("PointListTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear ähnelt.
        /// </summary>
        internal static string PointSelectTool_ClearAction {
            get {
                return ResourceManager.GetString("PointSelectTool_ClearAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remember Points ähnelt.
        /// </summary>
        internal static string PointSelectTool_Name {
            get {
                return ResourceManager.GetString("PointSelectTool_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Angle ähnelt.
        /// </summary>
        internal static string RotateFreeEffect_Angle {
            get {
                return ResourceManager.GetString("RotateFreeEffect_Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rotate Free ähnelt.
        /// </summary>
        internal static string RotateFreeEffect_Name {
            get {
                return ResourceManager.GetString("RotateFreeEffect_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selection ähnelt.
        /// </summary>
        internal static string SelectionTool_Name {
            get {
                return ResourceManager.GetString("SelectionTool_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blur ähnelt.
        /// </summary>
        internal static string ShadowEffect_Blur {
            get {
                return ResourceManager.GetString("ShadowEffect_Blur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shadow Color ähnelt.
        /// </summary>
        internal static string ShadowEffect_Color {
            get {
                return ResourceManager.GetString("ShadowEffect_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drop Shadow ähnelt.
        /// </summary>
        internal static string ShadowEffect_Name {
            get {
                return ResourceManager.GetString("ShadowEffect_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offset ähnelt.
        /// </summary>
        internal static string ShadowEffect_Offset {
            get {
                return ResourceManager.GetString("ShadowEffect_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click and drag to create the shape. Hold down Shift to make it square. Use the right mouse button for background brush. ähnelt.
        /// </summary>
        internal static string ShapeTool_Description {
            get {
                return ResourceManager.GetString("ShapeTool_Description", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap snap_grid {
            get {
                object obj = ResourceManager.GetObject("snap_grid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Angle: ähnelt.
        /// </summary>
        internal static string StartAngleOption_Name {
            get {
                return ResourceManager.GetString("StartAngleOption_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Swep Angle: ähnelt.
        /// </summary>
        internal static string SwepAngleOption_Name {
            get {
                return ResourceManager.GetString("SwepAngleOption_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tension: ähnelt.
        /// </summary>
        internal static string TensionOption_Name {
            get {
                return ResourceManager.GetString("TensionOption_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Font: ähnelt.
        /// </summary>
        internal static string TextFormatOption_Name {
            get {
                return ResourceManager.GetString("TextFormatOption_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text: ähnelt.
        /// </summary>
        internal static string TextFormatOption_Text {
            get {
                return ResourceManager.GetString("TextFormatOption_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text ähnelt.
        /// </summary>
        internal static string TextTool_Name {
            get {
                return ResourceManager.GetString("TextTool_Name", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tip_circle {
            get {
                object obj = ResourceManager.GetObject("tip_circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tip_square {
            get {
                object obj = ResourceManager.GetObject("tip_square", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tl_airbrush {
            get {
                object obj = ResourceManager.GetObject("tl_airbrush", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tl_brush {
            get {
                object obj = ResourceManager.GetObject("tl_brush", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tl_curve {
            get {
                object obj = ResourceManager.GetObject("tl_curve", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tl_ellipse {
            get {
                object obj = ResourceManager.GetObject("tl_ellipse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tl_eraser {
            get {
                object obj = ResourceManager.GetObject("tl_eraser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tl_filledellipse {
            get {
                object obj = ResourceManager.GetObject("tl_filledellipse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tl_filledpie {
            get {
                object obj = ResourceManager.GetObject("tl_filledpie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tl_filledpolygon {
            get {
                object obj = ResourceManager.GetObject("tl_filledpolygon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tl_filledrectangle {
            get {
                object obj = ResourceManager.GetObject("tl_filledrectangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tl_flood {
            get {
                object obj = ResourceManager.GetObject("tl_flood", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tl_froundrect {
            get {
                object obj = ResourceManager.GetObject("tl_froundrect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tl_line {
            get {
                object obj = ResourceManager.GetObject("tl_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tl_pen {
            get {
                object obj = ResourceManager.GetObject("tl_pen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tl_picker {
            get {
                object obj = ResourceManager.GetObject("tl_picker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tl_pie {
            get {
                object obj = ResourceManager.GetObject("tl_pie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tl_pointer {
            get {
                object obj = ResourceManager.GetObject("tl_pointer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tl_polygon {
            get {
                object obj = ResourceManager.GetObject("tl_polygon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tl_rectangle {
            get {
                object obj = ResourceManager.GetObject("tl_rectangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tl_remember {
            get {
                object obj = ResourceManager.GetObject("tl_remember", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tl_roundrect {
            get {
                object obj = ResourceManager.GetObject("tl_roundrect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tl_select {
            get {
                object obj = ResourceManager.GetObject("tl_select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tl_text {
            get {
                object obj = ResourceManager.GetObject("tl_text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tl_wipe {
            get {
                object obj = ResourceManager.GetObject("tl_wipe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tolerance: ähnelt.
        /// </summary>
        internal static string ToleranceOption_Name {
            get {
                return ResourceManager.GetString("ToleranceOption_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tool Options ähnelt.
        /// </summary>
        internal static string ToolManager_Configbar_Text {
            get {
                return ResourceManager.GetString("ToolManager_Configbar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toolbox ähnelt.
        /// </summary>
        internal static string ToolManager_ToolBox_Text {
            get {
                return ResourceManager.GetString("ToolManager_ToolBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diameter: ähnelt.
        /// </summary>
        internal static string ToolOption_Diameter {
            get {
                return ResourceManager.GetString("ToolOption_Diameter", resourceCulture);
            }
        }
    }
}
