//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VariIconsReload.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DrawTool_Width {
            get {
                return ((int)(this["DrawTool_Width"]));
            }
            set {
                this["DrawTool_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int BrushTool_Strength {
            get {
                return ((int)(this["BrushTool_Strength"]));
            }
            set {
                this["BrushTool_Strength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PenTool_TipShape {
            get {
                return ((int)(this["PenTool_TipShape"]));
            }
            set {
                this["PenTool_TipShape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConfigOption_AntiAlias {
            get {
                return ((bool)(this["ConfigOption_AntiAlias"]));
            }
            set {
                this["ConfigOption_AntiAlias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowGrid {
            get {
                return ((bool)(this["ShowGrid"]));
            }
            set {
                this["ShowGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoZoom {
            get {
                return ((bool)(this["AutoZoom"]));
            }
            set {
                this["AutoZoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ToolOption_Diameter {
            get {
                return ((int)(this["ToolOption_Diameter"]));
            }
            set {
                this["ToolOption_Diameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StartAngleOption_Value {
            get {
                return ((int)(this["StartAngleOption_Value"]));
            }
            set {
                this["StartAngleOption_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int SwepAngleOption_Value {
            get {
                return ((int)(this["SwepAngleOption_Value"]));
            }
            set {
                this["SwepAngleOption_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int TensionOption_Value {
            get {
                return ((int)(this["TensionOption_Value"]));
            }
            set {
                this["TensionOption_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ToleranceOption_Value {
            get {
                return ((int)(this["ToleranceOption_Value"]));
            }
            set {
                this["ToleranceOption_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int CustomFormat_ImageWidth {
            get {
                return ((int)(this["CustomFormat_ImageWidth"]));
            }
            set {
                this["CustomFormat_ImageWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int CustomFormat_ImageHeight {
            get {
                return ((int)(this["CustomFormat_ImageHeight"]));
            }
            set {
                this["CustomFormat_ImageHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public short CustomFormat_Bpp {
            get {
                return ((short)(this["CustomFormat_Bpp"]));
            }
            set {
                this["CustomFormat_Bpp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CustomFormat_Lock {
            get {
                return ((bool)(this["CustomFormat_Lock"]));
            }
            set {
                this["CustomFormat_Lock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial")]
        public string TextFormatOption_PreferredFont {
            get {
                return ((string)(this["TextFormatOption_PreferredFont"]));
            }
            set {
                this["TextFormatOption_PreferredFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public string TextFormatOptin_Size {
            get {
                return ((string)(this["TextFormatOptin_Size"]));
            }
            set {
                this["TextFormatOptin_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Text")]
        public string TextFormatOption_Text {
            get {
                return ((string)(this["TextFormatOption_Text"]));
            }
            set {
                this["TextFormatOption_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MiddleCenter")]
        public global::System.Drawing.ContentAlignment TextFormatOption_Alignment {
            get {
                return ((global::System.Drawing.ContentAlignment)(this["TextFormatOption_Alignment"]));
            }
            set {
                this["TextFormatOption_Alignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SnapGridOption_Value {
            get {
                return ((bool)(this["SnapGridOption_Value"]));
            }
            set {
                this["SnapGridOption_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RotateFreeEffect_Angle {
            get {
                return ((int)(this["RotateFreeEffect_Angle"]));
            }
            set {
                this["RotateFreeEffect_Angle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BrightnessEffect_Brightness {
            get {
                return ((int)(this["BrightnessEffect_Brightness"]));
            }
            set {
                this["BrightnessEffect_Brightness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BrightnessEffect_Contrast {
            get {
                return ((int)(this["BrightnessEffect_Contrast"]));
            }
            set {
                this["BrightnessEffect_Contrast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ColorEffect_Hue {
            get {
                return ((int)(this["ColorEffect_Hue"]));
            }
            set {
                this["ColorEffect_Hue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ColorEffect_Saturation {
            get {
                return ((int)(this["ColorEffect_Saturation"]));
            }
            set {
                this["ColorEffect_Saturation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ColorEffect_Brightness {
            get {
                return ((int)(this["ColorEffect_Brightness"]));
            }
            set {
                this["ColorEffect_Brightness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ShadowEffect_Blur {
            get {
                return ((int)(this["ShadowEffect_Blur"]));
            }
            set {
                this["ShadowEffect_Blur"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1, 1")]
        public global::System.Drawing.Point ShadowEffect_Offset {
            get {
                return ((global::System.Drawing.Point)(this["ShadowEffect_Offset"]));
            }
            set {
                this["ShadowEffect_Offset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 0, 0, 0")]
        public global::System.Drawing.Color ShadowEffect_Color {
            get {
                return ((global::System.Drawing.Color)(this["ShadowEffect_Color"]));
            }
            set {
                this["ShadowEffect_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("256, 256")]
        public global::System.Drawing.Size DocumentResize_Size {
            get {
                return ((global::System.Drawing.Size)(this["DocumentResize_Size"]));
            }
            set {
                this["DocumentResize_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DocumentResize_Lock {
            get {
                return ((bool)(this["DocumentResize_Lock"]));
            }
            set {
                this["DocumentResize_Lock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.AnchorStyles DocumentResize_Anchor {
            get {
                return ((global::System.Windows.Forms.AnchorStyles)(this["DocumentResize_Anchor"]));
            }
            set {
                this["DocumentResize_Anchor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DocumentResize_Scale {
            get {
                return ((bool)(this["DocumentResize_Scale"]));
            }
            set {
                this["DocumentResize_Scale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DocumentResize_Interpolation {
            get {
                return ((int)(this["DocumentResize_Interpolation"]));
            }
            set {
                this["DocumentResize_Interpolation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GradientList {
            get {
                return ((string)(this["GradientList"]));
            }
            set {
                this["GradientList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ColorList {
            get {
                return ((string)(this["ColorList"]));
            }
            set {
                this["ColorList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BrushParamsA {
            get {
                return ((string)(this["BrushParamsA"]));
            }
            set {
                this["BrushParamsA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BrushParamsB {
            get {
                return ((string)(this["BrushParamsB"]));
            }
            set {
                this["BrushParamsB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BrushAType {
            get {
                return ((bool)(this["BrushAType"]));
            }
            set {
                this["BrushAType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BrushBType {
            get {
                return ((bool)(this["BrushBType"]));
            }
            set {
                this["BrushBType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BrushEditingA {
            get {
                return ((bool)(this["BrushEditingA"]));
            }
            set {
                this["BrushEditingA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColorListLock {
            get {
                return ((bool)(this["ColorListLock"]));
            }
            set {
                this["ColorListLock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public int ImageEncoder_JPGQuality {
            get {
                return ((int)(this["ImageEncoder_JPGQuality"]));
            }
            set {
                this["ImageEncoder_JPGQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("224, 224, 224")]
        public global::System.Drawing.Color IconEditor_CheckerA {
            get {
                return ((global::System.Drawing.Color)(this["IconEditor_CheckerA"]));
            }
            set {
                this["IconEditor_CheckerA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color IconEditor_CheckerB {
            get {
                return ((global::System.Drawing.Color)(this["IconEditor_CheckerB"]));
            }
            set {
                this["IconEditor_CheckerB"] = value;
            }
        }
    }
}
