T.BlogControls=function(q,N){function E(a){return 0!==a.toLowerCase().indexOf("https:")?"https:"+a:a}function O(a){if(!a||!a.content)return a;var b=a.replyId?a.replyId:a.commentId?a.commentId:a.id;if(!b)return a;var c,g,f,k,d,w=null,l=['Sharing 3D model "','" (',")"+String.fromCharCode(10)+"Link: ",String.fromCharCode(10)+"ID: "];c=a.content.indexOf(l[0]);if(0!==c)return a;g=a.content.substr(l[0].length);c=g.indexOf(l[1]);if(0>c)return a;f=g.substr(0,c);g=g.substr(c+l[1].length);c=g.indexOf(l[2]);
if(0>c)return a;k=g.substr(0,c);g=g.substr(c+l[2].length);c=g.indexOf(l[3]);0>c?d=g:(d=g.substr(0,c),w=g.substr(c+l[3].length));a={kind:"drive#revision",id:b,title:f,fileSize:k,downloadUrl:d,type:a.type,createdDate:a.createdDate,modifiedDate:a.modifiedDate,lastModifyingUser:a.author,converted:!0};w&&(a.externalFileId=w);return a}function I(a,e){var c=h.comments;if(c&&c.id){if(""==r||""==z)return null;for(var g=a.split(String.fromCharCode(10)),f="",k=0;k<g.length;++k)0<k&&(f+="<br>"),f+=g[k];g="dummy_"+
getUID();f={type:e,commentId:g,htmlContent:f,content:a,createdDate:(new Date).toJSON(),lastModifyingUser:{displayName:r,picture:{url:z}},author:{displayName:r,picture:{url:z}}};"upload"==e||"download"==e?(f.progress=0,f.kind="drive#revision"):f.kind="drive#comment";c.push(f);b.update();b.scrollBottom();return g}}function J(a){return{kind:"drive#revision",id:a.headRevisionId,fileSize:a.fileSize,modifiedDate:a.modifiedDate,lastModifyingUser:a.lastModifyingUser,isFinished:!0}}function G(a,e){var c=h.comments;
if(c&&c.id){var g;g=a&&"string"==typeof a?a:b.responseInput.getValue();var f=I(g);b.responseInput.setValue("");e&&(b.activeCommentId=f);T.FileOperations.addComment(g,c.id,function(a){if(a){r=a.author&&a.author.displayName?a.author.displayName:"";z=a.author&&a.author.picture&&a.author.picture.url?E(a.author.picture.url):"";var d=T.FileOperations.getCommentIndexByID(c,f);null!==d?c[d]=a:c.push(a);e&&(b.activeCommentId=a.commentId);b.update();b.scrollBottom();sendEventStatistic("Message","Send","Text")}},
function(a){console.log("unable to send:",a);sendEventStatistic("Error","Message","Text")})}}function A(a){var b={},c;if(a&&a.className&&a.id&&(c=a.className.indexOf("-"),!(0>c||(b.className=a.className.substring(0,c),b.type=a.className.substring(c+1),c=a.id.indexOf("-"+b.type),0>c||(b.id=a.id.substring(0,c),"dummy_comment"==b.id)))))return b.author=a.getAttribute("authorName"),b.parentId=a.getAttribute("parentId"),b.link=a.getAttribute("link"),b.fileName=a.getAttribute("fileName"),b.externalFileId=
a.getAttribute("externalFileId"),b}function K(a){F=a;(a=A(a.target))&&a.author&&a.author==r&&(a=document.getElementById(a.id+"-remove-button"))&&(a.style.display="inline")}function P(a){F=!1;if(a=A(a.target))if(a=document.getElementById(a.id+"-remove-button"))a.style.display="none"}function Q(a){a=A(a.target);var e=h.comments;if(a&&e&&e.id)if(T.FileOperations.removeCommentFromList(e,a.id)&&b.update(),"commentReply"==a.className&&void 0!==a.parentId)T.FileOperations.removeCommentReply(a.id,a.parentId,
e.id,function(){b.reload(!1,function(){b.blink(!1)})},function(a){console.log("unable to remove:",a)});else if("comment"==a.className||a.externalFileId||a.link){var c=T.FileOperations.getCommentIndexByID(e,a.id);null!==c&&(e.splice(c,1),b.update());a.externalFileId&&T.FileOperations.removeGoogleDriveFile(a.externalFileId);T.FileOperations.removeComment(a.id,e.id,function(){b.reload(!1,function(){b.blink(!1)})},function(a){console.log("unable to remove:",a)})}else"revision"==a.className&&(c=T.FileOperations.getCommentIndexByID(e.revisions,
a.id),null!==c&&(e.revisions.splice(c,1),b.update()),T.FileOperations.removeRevision(e.id,a.id,function(){b.reload(!1,function(){b.blink(!1)})},function(a){console.log("unable to remove:",a)}))}function L(){b.isVisible()&&b.scrolledBottom()||b.blink(!0)}function C(a){var b=h.comments;if(b){var c=null,g=T.FileOperations.getCommentIndexByID(b,a);null!==g?c=b[g]:(a=T.FileOperations.getCommentIndexByID(b.revisions,a),null!==a&&(c=b.revisions[a]));return c}}function R(a){function e(){w||(w=!0,q.scene=
h,q.signals.editorChanged.dispatch())}function c(a){q.deselect();var b;for(b=a.children.length-1;0<=b;b--)object=a.children[b],void 0!==object.parent&&object!=cameraLight&&(object.traverse(function(a){q.removeHelper(a)}),object.parent.remove(object),q.signals.objectRemoved.dispatch(object))}var g=A(a.target);a=h.comments;if(g&&g.id&&a&&a.id){var f=g.fileName?g.fileName:a.fileInfo?a.fileInfo.title:null,k=C(g.id),d=g.link;!d&&k&&(d=k.downloadUrl);k.type="download";b.update();var w=!1;q.scene=new T.Scene;
q.scene.comments=a;q.signals.editorChanged.dispatch();f&&d&&q.loader.loadUrl(d,f,a.id,function(){var a=C(g.id);a&&(a.type="",a.cancelled?(e(),a.cancelled=!1):(c(h),b.activeCommentId=g.id),b.update());h=q.scene;setTimeout(function(){q.signals.sceneGraphChanged.dispatch();q.signals.materialChanged.dispatch()},1)},function(a,b){var c=C(g.id);if(c){if(a&&b){c.progress=a/b*100;var d=document.getElementById(g.id+"-file-progress");d&&(d.style.width=c.progress+"%")}if(c.cancelled)return!0}},function(){e()},
null,!1)}}function S(a){(a=A(a.target))&&a.id&&(a=C(a.id))&&(a.cancelled=!0)}function M(a){try{var b=function(b){b&&b.kind&&"drive#about"==b.kind&&(r=b.user&&b.user.displayName?b.user.displayName:"",z=b.user&&b.user.picture&&b.user.picture.url?E(b.user.picture.url):"",a&&a(b))};r&&z?a&&a():T.FileOperations.googleDriveInfo?b(T.FileOperations.googleDriveInfo):T.FileOperations.aboutGoogleDrive(b)}catch(c){}}function U(a){try{var e=function(e){c.fileInfo=e;var f=c.fileInfo;if(f){if(f.userPermission){x=
"reader"!==f.userPermission.role;if(f.userPermission.additionalRoles)for(var k=0;!x&&k<f.userPermission.additionalRoles.length;++k)x="commenter"==f.userPermission.additionalRoles[k];x?b.responseContainer.setDisplay("block"):b.responseContainer.setDisplay("none")}b.blogShowButton.setLabel(D());V()}a&&a(e)},c=h.comments;c&&c.id&&(c.fileInfo?e(c.fileInfo):T.FileOperations.requestGoogleDriveFileProperties(c.id,e))}catch(g){}}function V(){if(!b.isVisible()){var a=h.comments;if(a){var e=a.fileInfo;if(e&&
e.userPermission){var c="";e.ownerNames&&0<e.ownerNames.length&&(c=e.ownerNames[0]);var g="owner"==e.userPermission.role,f="writer"==e.userPermission.role,k=!1;e.shared&&g?k="You shared this 3D model.\nClick here to upload new revisions and communicate with your recepients":e.shared&&!g&&c&&(0<a.length?(e=c,(a=T.FileOperations.getLastModifiedComment(a))&&a.author&&a.author.displayName&&(e=a.author.displayName),e!==r&&(k="You got a message from "+e+".\n",k=x&&f?k+"Click here to respond back with your comment or 3D model":
x?k+"Click here to respond back":k+"Click here to check it out")):(k=c+" shared this file with you.\n",k=x&&f?k+"Click here to send him a message or a 3D model":x?k+"Click here to send him a message":!1));k&&notifications.remind("Discover Messages",k,100,100,6048E5,!0,function(){b.show()})}}}}function D(){var a="",e=h.comments,a=b.isVisible()?a+String.fromCharCode(9660):a+String.fromCharCode(9650),c=T.FileOperations.getAmountOfVisibleComments(e);e&&e.revisions&&(c+=e.revisions.length);return a=0<
c||!x?a+("Messages ("+c+")"):a+"Add Message"}UI.Element.call(this);var b=this,r="",z="",x=!0,H=!1,F=!1,h=q.scene;this.activeCommentId=null;this.update=function(){function a(a){a.sort(function(a,b){return new Date(a.createdDate?a.createdDate:a.modifiedDate)-new Date(b.createdDate?b.createdDate:b.modifiedDate)})}function e(c,d,f,l){if(c&&d&&d.kind&&1!=d.deleted){var p=d.replyId?d.replyId:d.commentId?d.commentId:d.id;if(p){d=O(d);var m="",t=d.kind.indexOf("drive#");0<=t&&(m=d.kind.substring(t+6));t=
(new UI.Panel).setClass(m+"-container").setId(p+"-container");t.onMouseOver(K);t.onMouseOut(P);c.add(t);f&&t.setStyle("padding-bottom",["0px"]);c=(new UI.Panel).setClass(m+"-author").setId(p+"-author");t.add(c);var q="",q="revision"==m?d.lastModifyingUser&&d.lastModifyingUser.picture&&d.lastModifyingUser.picture.url?E(d.lastModifyingUser.picture.url):"":d.author&&d.author.picture&&d.author.picture.url?E(d.author.picture.url):"";""==q&&(q="/assets/icons/silhouette96.png");f=(new UI.Image).setClass(m+
"-author-image").setId(p+"-author-image");(function(a){loadImage(q,function(b,c){a.setSource(b)})})(f);f.setStyle("vertical-align",[""]);c.add(f);c=b.activeCommentId&&p==b.activeCommentId||!b.activeCommentId&&h.comments.fileInfo&&p==h.comments.fileInfo.headRevisionId||!(b.activeCommentId||h.comments.fileInfo&&h.comments.fileInfo.headRevisionId)&&"revision"==m&&1==g?" active-comment":"";c=(new UI.Panel).setClass(m+"-body"+c).setId(p+"-body");t.add(c);f=(new UI.Panel).setClass(m+"-controls").setId(p+
"-controls");c.add(f);var u="",u="revision"==m?d.lastModifyingUser&&d.lastModifyingUser.displayName?d.lastModifyingUser.displayName:"":d.author&&d.author.displayName?d.author.displayName:"",x=(new UI.Text(u)).setClass(m+"-author-name").setId(p+"-author-name");f.add(x);var r=(new UI.Button("Remove")).setClass(m+"-remove-button").setId(p+"-remove-button");r.setDisplay("none");r.onClick(Q);l&&r.dom.setAttribute("parentId",l);d.converted&&d.externalFileId&&r.dom.setAttribute("externalFileId",d.externalFileId);
d.converted&&d.downloadUrl&&r.dom.setAttribute("link",d.downloadUrl);("revision"!==m||d.converted||h.comments.revisions&&1<h.comments.revisions.length&&void 0==d.progress&&h.comments.fileInfo&&h.comments.fileInfo.headRevisionId!==d.id)&&f.add(r);l="";d.createdDate&&(l=$.timeago(new Date(d.createdDate)));if(d.modifiedDate){var v=$.timeago(new Date(d.modifiedDate));""==l?l=v:v!=l&&(l=l+" (edited "+v+")")}l=(new UI.Text(l)).setClass(m+"-time").setId(p+"-time");f.add(l);v=(new UI.Panel).setClass(m+"-content").setId(p+
"-content");if("revision"!==m)v.dom.innerHTML=d.htmlContent?d.htmlContent:"";else{var z=(new UI.Image("/assets/buttons/open.png")).setClass(m+"-download-image").setId(p+"-download-image");v.add(z);var B=(new UI.Panel).setClass(m+"-file-container").setId(p+"-file-container");v.add(B);var n;if("upload"==d.type)B.dom.innerText="Uploading 3D scene";else{n="";n="download"==d.type?15:38;d.converted?n="3D model "+T.FileOperations.limitNameLength(d.title,n):(n="3D model revision "+g,++g);n=(new UI.Text(n)).setClass(m+
"-file-description").setId(p+"-file-description");n.setDisplay("block");B.add(n);var y=d.fileSize?d.converted?d.fileSize:bytesToSize(d.fileSize):"",y=(new UI.Text(y)).setClass(m+"-file-size").setId(p+"-file-size");y.setDisplay("block");B.add(y);n.dom.setAttribute("authorName",u);y.dom.setAttribute("authorName",u);n.setStyle("-webkit-user-select",["text"]);y.setStyle("-webkit-user-select",["text"])}if("upload"==d.type||"download"==d.type){var y=(new UI.Panel).setClass(m+"-progress-container").setId(p+
"-progress-container"),A=(new UI.Panel).setClass(m+"-file-progress").setId(p+"-file-progress");A.dom.style.width=d.progress?d.progress+"%":"0%";y.add(A);v.add(y);n=(new UI.Button("Cancel")).setClass(m+"-cancel-button").setId(p+"-cancel-button");n.dom.title="Cancel";v.add(n);n.onClick(S);y.dom.setAttribute("authorName",u);A.dom.setAttribute("authorName",u);y.setStyle("-webkit-user-select",["text"]);A.setStyle("-webkit-user-select",["text"])}else n=(new UI.Button("Open")).setClass(m+"-download-button").setId(p+
"-download-button"),n.dom.title="Open this revision",n.onClick(R),v.add(n),d.downloadUrl&&n.dom.setAttribute("link",d.downloadUrl),d.title&&n.dom.setAttribute("fileName",d.title);z.dom.setAttribute("authorName",u);B.dom.setAttribute("authorName",u);n.dom.setAttribute("authorName",u);z.setStyle("-webkit-user-select",["text"]);B.setStyle("-webkit-user-select",["text"]);n.setStyle("-webkit-user-select",["text"])}c.add(v);v.setDisplay("");f.dom.setAttribute("authorName",u);x.dom.setAttribute("authorName",
u);l.dom.setAttribute("authorName",u);v.dom.setAttribute("authorName",u);r.dom.setAttribute("authorName",u);c.setStyle("-webkit-user-select",["text"]);f.setStyle("-webkit-user-select",["text"]);x.setStyle("-webkit-user-select",["text"]);l.setStyle("-webkit-user-select",["text"]);v.setStyle("-webkit-user-select",["text"]);r.setStyle("-webkit-user-select",["text"]);if(d.replies&&0<d.replies.length)for(m=(new UI.Panel).setClass(m+"-replies-container").setId(p+"-replies-container"),t.add(m),a(d.replies),
t=0;t<d.replies.length;++t)e(m,d.replies[t],t==d.replies.length-1,p)}}}if(h.comments){var c=h.comments.revisions?h.comments.concat(h.comments.revisions):h.comments.slice(0),g=1;b.blogContainer.setDisplay("block");b.blogShowButton.setLabel(D());M();for(U();0<this.articleContainer.dom.children.length;)this.articleContainer.dom.removeChild(this.articleContainer.dom.firstChild);a(c);0==c.length?b.articleContainer.setStyle("margin-bottom",["0px"]):b.articleContainer.setStyle("margin-bottom",["10px"]);
for(var f=0;f<c.length;++f)e(this.articleContainer,c[f],f==c.length-1);F&&K(F)}else b.blogContainer.setDisplay("none")};this.show=function(){var a=0==b.articleContainer.dom.scrollHeight;b.blogBody.setDisplay("block");b.blogShowButton.setLabel(D());b.responseInput.dom.focus();a&&b.scrollBottom();b.reload();b.setRefreshInterval(5E3,!0);sendEventStatistic("Message","View","Show")};this.hide=function(){b.blogBody.setDisplay("none");b.blogShowButton.setLabel(D());b.setRefreshInterval(12E4,!0);sendEventStatistic("Message",
"View","Hide")};this.setHeight=function(a){b.articleContainer.setStyle("max-height",[a+"px"])};this.setWidth=function(a){b.blogContainer.setStyle("width",[a+"px"])};this.setMaxWidth=function(a){b.blogContainer.setStyle("max-width",[a+"px"])};this.setPosition=function(a){b.blogContainer.setStyle("left",[a+"px"])};this.scrollBottom=function(){b.articleContainer.dom.scrollTop=b.articleContainer.dom.scrollHeight;b.responseInput.dom.focus()};this.blink=function(a){this.blogShowButton.dom.className=a?this.blogShowButton.dom.className+
" blink":this.blogShowButton.dom.className.replace(" blink","")};this.isVisible=function(){return this.blogBody&&"none"!==this.blogBody.getDisplay()};this.scrolledBottom=function(){return this.articleContainer.dom.scrollTop>=this.articleContainer.dom.scrollHeight-this.articleContainer.dom.offsetHeight-16};this.reload=function(a,e){function c(a){var c=b.scrolledBottom();h.comments?k=T.FileOperations.mergeComments(h.comments,a):h.comments=a;k&&(b.update(),c&&b.scrollBottom(),L(),e&&e())}function g(a,
c){if(h.comments&&c){var d=b.scrolledBottom();c=h.comments.revisions?h.comments.revisions.length!=a.length:a.length;for(var f=0;!c&&f<a.length;++f)c=h.comments.revisions[f].md5Checksum!=a[f].md5Checksum;h.comments.revisions=a;for(var g=f=0;f<h.comments.length;){var k=h.comments[f];"drive#revision"==k.kind&&k.isFinished?(h.comments.splice(f,1),++g):++f}if(c||0<g)b.update(),0==g&&1<h.comments.revisions.length&&(L(),d&&b.scrollBottom()),e&&e()}}var f=h.comments,k=!0;if(f&&f.id){var d=null,w=T.FileOperations.getLastModifiedComment(f);
w&&w.modifiedDate&&(d=w.modifiedDate);T.FileOperations.loadComments(f.id,d,c,function(a){},a);a||T.FileOperations.requestGoogleDriveFileRevisions(f.id,g,function(a){})}};this.load=function(a){function e(){c&&g&&f&&(k.id||(k.id=l),h.comments=k,h.comments.revisions=d,h.comments.fileInfo=w,b.activeCommentId&&0>b.activeCommentId.indexOf("dummy")&&!C(b.activeCommentId)&&(b.activeCommentId=null),b.update(),b.scrollBottom())}var c=!1,g=!1,f=!1,k=[],d=[],w=null,l=T.FileOperations.extractIdFromGoogleDriveUIUrl(a);
""==l&&26<=a.length&&36>=a.length&&(l=a);T.FileOperations.loadComments(a,null,function(a){k=a;g=!0;e()},function(){g=!0;e()});T.FileOperations.requestGoogleDriveFileRevisions(l,function(a,b){d=a;c=!0;e()},function(){c=!0;e()});T.FileOperations.requestGoogleDriveFileProperties(l,function(a){w=a;f=!0;e()},function(){f=!0;e()})};this.setRefreshInterval=function(a,e){function c(){e&&0<g%5?b.reload(!0):b.reload();++g}H&&clearInterval(H);var g=0;a&&(H=setInterval(c,a))};b.blogContainer=(new UI.Panel).setClass("blog-container");
b.blogContainer.setDisplay("none");N.appendChild(b.blogContainer.dom);b.blogControlsContainer=(new UI.Panel).setClass("blog-controls-container");b.blogContainer.add(b.blogControlsContainer);b.blogShowButton=(new UI.Button(D())).setClass("blog-show-button");b.blogControlsContainer.add(b.blogShowButton);b.blogShowButton.onClick(function(){b.isVisible()?b.hide():(b.blink(!1),b.show())});b.blogBody=(new UI.Panel).setClass("blog-body");b.blogContainer.add(b.blogBody);b.blogBody.setDisplay("none");b.articleContainer=
(new UI.Panel).setClass("article-container");b.blogBody.add(b.articleContainer);b.articleContainer.dom.onscroll=function(a){b.scrolledBottom()&&b.blink(!1)};b.responseContainer=(new UI.Panel).setClass("reply-container");b.blogBody.add(b.responseContainer);b.responseBox=(new UI.Panel).setClass("reply-box");b.responseContainer.add(b.responseBox);b.responseInput=(new UI.TextArea).setClass("reply-input");b.responseBox.add(b.responseInput);b.responseInput.onKeyDown(function(a){13==a.which&&a.ctrlKey&&
(a.preventDefault(),G())});b.sendButton=(new UI.Button("Send")).setClass("send-button");b.sendButton.dom.title="Send Message";b.responseBox.add(b.sendButton);b.sendButton.onClick(G);b.attachModelButton=(new UI.Button("")).setClass("attach-model-button");b.attachModelButton.dom.title="Send 3D scene / Add new file revison";b.responseBox.add(b.attachModelButton);b.attachModelButton.onClick(function(){var a=h.comments;if(a&&a.id){var e=a.fileInfo&&"stl"==a.fileInfo.fileExtension?"stl":"zip",c=a.fileInfo?
a.fileInfo.title:T.FileOperations.getFileName(h)+"."+e;T.FileOperations.extractExtension(c)!==e&&(c=T.FileOperations.convertToFileName(c)+"."+e);var g=a.fileInfo&&a.fileInfo.userPermission&&"reader"!==a.fileInfo.userPermission.role,f=a.fileInfo.fileExtension&&("zip"==a.fileInfo.fileExtension||"stl"==a.fileInfo.fileExtension),k=g&&f?a.id:null,d=I("","upload");T.FileOperations.uploadScene(q,c,e,k,function(c){var e=T.FileOperations.getCommentIndexByID(a,d),h=null!==e?a[e].cancelled:null;c&&c.webContentLink&&
c.title&&c.fileSize&&!h?(g&&f?(a.fileInfo=c,null!==e?a[e]=J(c):a.push(J(c)),b.activeCommentId=c.headRevisionId,b.reload(!1),b.update(),b.scrollBottom()):(null!==e&&a.splice(e,1),G('Sharing 3D model "'+c.title+'" ('+bytesToSize(c.fileSize)+")"+String.fromCharCode(10)+"Link: "+c.webContentLink+String.fromCharCode(10)+"ID: "+c.id,!0)),sendEventStatistic("Message","Send","Scene")):(null!==e&&a.splice(e,1),b.update())},function(b,c,e,f){if(b&&c&&(e=T.FileOperations.getCommentIndexByID(a,d),null!==e)){e=
a[e];e.progress=b/c*100;if(b=document.getElementById(e.commentId+"-file-progress"))b.style.width=e.progress+"%";if(e.cancelled)return!0}},function(){var c=T.FileOperations.getCommentIndexByID(a,d);null!==c&&a.splice(c,1);b.update();sendEventStatistic("Error","Message","Scene")})}});M();b.setRefreshInterval(3E5,!0)};
