T.EditorControls=function(e,c,t,u){function v(a,n,d){g===l.ROTATE?(b.rotate(new T.V3(.005*-a,.005*-n,0),b.rotateType),c.style.cursor=b.rotateType==r.STANDARD?"move":"pointer"):g===l.ZOOM?(b.zoom(new T.V3(0,0,2*n)),c.style.cursor="n-resize"):g===l.PAN&&(b.pan(new T.V3(-a,n,0)),c.style.cursor="move")}function q(a){if(!(a&&a.cancel||!1===b.enabled)){a.preventDefault();A.set(a.clientX,a.clientY);if(h){var n=A.x-h.x,c=A.y-h.y;v(n,c,a);m=0==Math.abs(n)&&0==Math.abs(c)}else h=new T.Vector2;h.set(a.clientX,
a.clientY)}}function w(a){a&&a.cancel||a&&"mouseout"==a.type&&(a.relatedTarget&&a.relatedTarget.parentElement==c||a.currentTarget!==c&&a.currentTarget==b.controlsDom)||(c.style.cursor="default",b.controlsDom.removeEventListener("mousemove",q,!1),b.controlsDom.removeEventListener("mouseup",w,!1),b.controlsDom.removeEventListener("mouseout",w,!1),g=l.NONE)}function D(a){if(!(a&&a.cancel||!1===b.enabled||b.preserveScrolling&&m)){a.preventDefault();var n=0;a.wheelDelta?n=-a.wheelDelta:a.detail&&(n=10*
a.detail);b.zoom(new T.V3(0,0,n))}}function E(a){if(!(a&&a.cancel||!1===b.enabled))switch(c.style.cursor=F,a.keyCode){case void 0:case 18:case 91:case 93:case 17:case 16:g=l.NONE,b.controlsDom.removeEventListener("mousemove",q,!1),b.controlKeyDown=!1}}c=void 0!==c?c:document;this.enabled=!0;this.preserveScrolling=this.controlKeyDown=!1;var b=this,G=new T.V3,l={NONE:-1,ROTATE:0,ZOOM:1,PAN:2},g=l.NONE,r={STANDARD:0,LOOKUP:1};b.TYPE=r;b.rotateType=r.STANDARD;b.upVector=new T.V3(0,0,1);b.enableRotation=
!0;b.rotateSpeed=1;b.enableDamping=!0;b.dampingFactor=1;b.enableZoom=!0;b.zoomFactor=1;b.controlsDom=c;var p=new T.V3,x=new T.Matrix3,A=new T.Vector2,h=new T.Vector2,B=t&&u?new T.Raycaster:null,I=new T.Projector,y=new T.V3,H=t&&u?new T.Picking:null,F="default",m=!0,z={type:"change"};this.focus=function(a){void 0!==a.matrixWorld?p.setFromMatrixPosition(a.matrixWorld):p.copy(a);y.copy(p);e.lookAt(p);b.dispatchEvent(z)};this.pan=function(a){b.enableDamping&&(x.getNormalMatrix(e.matrix),a.applyMatrix3(x),
a.multiplyScalar(.001*G.copy(p).sub(e.position).length()*b.dampingFactor),e.position.add(a),p.add(a),y.add(a),b.dispatchEvent(z))};this.zoom=function(a){if(b.enableZoom){x.getNormalMatrix(e.matrix);a.applyMatrix3(x);a.multiplyScalar(.001*G.copy(p).sub(e.position).length()*b.zoomFactor);var n=e.position.clone().add(a);(8E3>e.position.length()||n.length()<e.position.length())&&e.position.add(a);b.dispatchEvent(z)}};this.rotate=function(a,n){if(b.enableRotation){new T.V3;var c=new T.V3,d=new T.Quaternion,
f=new T.V3,l=new T.V3,g=new T.V3,h=new T.V3,m=new T.V3,k=new T.Quaternion,q=new T.Quaternion;m.set(-a.x*b.rotateSpeed,a.y*b.rotateSpeed,0);if(m=m.length())p.lerp(y,m),c.copy(e.position).sub(p),f.copy(c).normalize(),l.copy(e.up).normalize(),g.crossVectors(l,f).normalize(),q.setFromAxisAngle(g,a.y*b.rotateSpeed),n==r.LOOKUP?k.setFromAxisAngle(l,a.x*b.rotateSpeed):(k.setFromAxisAngle(b.upVector,a.x*b.rotateSpeed),h.crossVectors(b.upVector,f),1E-5<h.lengthSq()&&(f=g.angleTo(h),.04<f&&f<Math.PI-.04?(d.setFromUnitVectors(g,
h.normalize()),d=(new T.Quaternion).slerp(d,m/f)):.02<f&&f<Math.PI-.02&&d.setFromUnitVectors(g,h.normalize()))),d.multiplyQuaternions(d,k),d.multiplyQuaternions(d,q),c.applyQuaternion(d),e.up.applyQuaternion(d),e.position.addVectors(p,c),e.lookAt(p);b.dispatchEvent(z)}};this.update=function(){};this.setControlsDom=function(a){b.controlsDom=a};c.addEventListener("contextmenu",function(a){a.preventDefault()},!1);c.addEventListener("mousedown",function(a){if(!1!==b.enabled){a.preventDefault();if(0===
a.button){a:{var d=a.clientX,p=a.clientY;if(t&&u&&H&&B){var k=t;if(u){var f=H.pickObject(t,u,e,d-c.offsetLeft,p-c.offsetTop,!1,!1);if(f)if(f.object)k=[f.object];else{b.rotateType=r.STANDARD;break a}}f=c.getBoundingClientRect();d=new T.V3((d-f.left)/f.width*2-1,2*-((p-f.top)/f.height)+1,.5);I.unprojectVector(d,e);B.set(e.position,d.sub(e.position).normalize());k=B.intersectObjects(k,!0);k[0]?(y.copy(k[0].point),b.rotateType=r.LOOKUP):b.rotateType=r.STANDARD}}g=l.ROTATE}else 1===a.button?g=l.ZOOM:2===
a.button&&(g=l.PAN);h||(h=new T.Vector2);h.set(a.clientX,a.clientY);b.controlsDom.addEventListener("mousemove",q,!1);b.controlsDom.addEventListener("mouseup",w,!1);b.controlsDom.addEventListener("mouseout",w,!1);m=!m}},!1);c.addEventListener("mousewheel",D,!1);window.addEventListener("keydown",function(a){if(!(a&&a.cancel||!1===b.enabled))switch(F=c.style.cursor,a.keyCode){case 18:case 91:case 93:g=l.ROTATE;b.rotateType=r.STANDARD;h=null;b.controlsDom.addEventListener("mousemove",q,!1);c.style.cursor=
"move";b.controlKeyDown=!0;break;case 17:g=l.ZOOM;h=null;b.controlsDom.addEventListener("mousemove",q,!1);c.style.cursor="n-resize";b.controlKeyDown=!0;break;case 16:g=l.PAN;h=null;b.controlsDom.addEventListener("mousemove",q,!1);c.style.cursor="move";b.controlKeyDown=!0;break;case 37:v(-30,0);break;case 39:v(30,0);break;case 38:v(0,-30);break;case 40:v(0,30);break;case 27:m=!0}},!1);window.addEventListener("keyup",E,!1);c.addEventListener("DOMMouseScroll",D,!1);window.addEventListener("blur",E,!1);
window.addEventListener("mousewheel",function(a){var b=c.getBoundingClientRect();!a||a.cancel||a.clientX>=b.left&&a.clientY>=b.top&&a.clientX<=b.right&&a.clientY<=b.bottom||(m=!0)},!1);new T.V3;var d=[new T.V3,new T.V3,new T.V3],k=[new T.V3,new T.V3,new T.V3],C=null;c.addEventListener("touchstart",function(a){if(!(a&&a.cancel||!1===b.enabled)){switch(a.touches.length){case 1:d[0].set(a.touches[0].pageX,a.touches[0].pageY,0);d[1].set(a.touches[0].pageX,a.touches[0].pageY,0);break;case 2:d[0].set(a.touches[0].pageX,
a.touches[0].pageY,0),d[1].set(a.touches[1].pageX,a.touches[1].pageY,0),C=d[0].distanceTo(d[1])}k[0].copy(d[0]);k[1].copy(d[1]);m=!0}},!1);c.addEventListener("touchmove",function(a){if(!(a&&a.cancel||!1===b.enabled)){var c=function(a,b){var c=b[0],d;for(d in b)c.distanceTo(a)>b[d].distanceTo(a)&&(c=b[d]);return c};switch(a.touches.length){case 1:d[0].set(a.touches[0].pageX,a.touches[0].pageY,0);d[1].set(a.touches[0].pageX,a.touches[0].pageY,0);var e=d[0].sub(c(d[0],k));Math.abs(e.x)>Math.abs(e.y)&&
(m=!1);if(b.preserveScrolling&&m)return;b.rotate(e.multiplyScalar(-.005));break;case 2:d[0].set(a.touches[0].pageX,a.touches[0].pageY,0),d[1].set(a.touches[1].pageX,a.touches[1].pageY,0),distance=d[0].distanceTo(d[1]),b.zoom(new T.V3(0,0,C-distance)),C=distance,e=d[0].clone().sub(c(d[0],k)),c=d[1].clone().sub(c(d[1],k)),e.x=-e.x,c.x=-c.x,b.pan(e.add(c).multiplyScalar(.5))}!1!==a.cancelable&&a.preventDefault();a.stopPropagation();k[0].copy(d[0]);k[1].copy(d[1])}},!1)};T.EditorControls.prototype=Object.create(T.EventDispatcher.prototype);
