var spriteGizmos=0;
T.SpriteGizmo=function(f,m){var g=this;this.sprites=[[],[],[]];this.textures=[[],[],[]];this.gizmoPosition=new T.Vector2(0,0);this.minScale=this.maxScale=this.gizmoScale=1;this.onClick=f;this.spriteId=0;this.imageType=T.SpriteGizmo.INACTIVE;this.gizmoId=++spriteGizmos;this.addImage=function(a,b,c,f){if(void 0!==a&&void 0!==b){var h=this.textures[a].length;this.textures[a].push(T.ImageUtils.loadTexture(b,void 0,function(b){var m=c?c:1,d=b.image.width,p=b.image.height;b=new T.SpriteMaterial({map:b,alignment:new T.Vector2(0,
0),opacity:m});b=new T.Sprite(b);b.position.set(g.gizmoPosition.x,g.gizmoPosition.y,0);b.scale.set(d*g.gizmoScale,-p*g.gizmoScale,1);b.id=h;b.type=a;b.name=f;g.sprites[a].push(b);g.handles.add(b);0==h&&a==T.SpriteGizmo.INACTIVE?(b.visible=!0,g.render&&g.render()):b.visible=!1}))}};this.update=function(){for(var a,b=0;b<this.sprites.length;++b)for(var c=0;c<this.sprites[b].length;++c){a=this.sprites[b][c];var f=this.textures[b][c],g=f.image.width,f=f.image.height;a.position.set(this.gizmoPosition.x,
this.gizmoPosition.y,0);a.scale.set(g*this.gizmoScale,-f*this.gizmoScale,1)}this.show()};this.getImageSize=function(a,b){void 0===a&&(a=this.imageType);void 0===b&&(b=this.spriteId);var c=this.sprites[a];if(!(b>=c.length))return new T.Vector2(c[b].material.map.image.width,c[b].material.map.image.height)};this.setPosition=function(a,b){this.gizmoPosition.x=a;this.gizmoPosition.y=b;this.update()};this.setScale=function(a,b){this.minScale=this.gizmoScale=a;this.maxScale=b?b:a;this.update()};this.hide=
function(){for(var a in this.handles.children)this.handles.children[a].visible=!1};this.show=function(a){var b;void 0===a?a=this.imageType:a<this.sprites.length&&(this.imageType=a);for(var c in this.handles.children)b=this.handles.children[c],this.handles.children[c].visible=b.id==g.spriteId&&b.type==a};this.getSpriteCount=function(){var a=1E7,b;for(b in this.sprites)this.sprites[b].length<a&&(a=this.sprites[b].length);return a};this.intersects=function(a,b,c){void 0===c&&(c=this.imageType);if(c>=
this.sprites.length)return!1;c=this.sprites[c];if(this.spriteId>=c.length)return!1;c=c[this.spriteId];return a>=c.position.x-Math.abs(c.scale.x)/2&&a<=c.position.x+Math.abs(c.scale.x)/2&&b>=c.position.y-Math.abs(c.scale.y)/2&&b<=c.position.y+Math.abs(c.scale.y)/2};this.getName=function(a){void 0===a&&(a=this.imageType);if(!(a>=this.sprites.length||(a=this.sprites[a],this.spriteId>=a.length)))return a[this.spriteId].name};this.nextSprite=function(){var a=this.getSpriteCount();this.spriteId=this.spriteId+
1<a?this.spriteId+1:0};this.init=function(){T.Object3D.call(this);this.name=m?m:"";this.handles=new T.Object3D;this.add(this.handles)};this.init()};T.SpriteGizmo.INACTIVE=0;T.SpriteGizmo.HIGHLIGHT=1;T.SpriteGizmo.PRESSED=2;T.SpriteGizmo.prototype=Object.create(T.Object3D.prototype);
T.HUDControls=function(f){function m(e,b){return d.boundingClientRect.left<=e&&d.boundingClientRect.right>=e&&d.boundingClientRect.top<=b&&d.boundingClientRect.bottom>=b}function g(){var e=document.getElementById("Tip");e&&(e.style.visibility="hidden");d.tipTimeout&&clearTimeout(d.tipTimeout)}function a(){var e=document.getElementById("Tip");e&&(e.style.visibility="visible")}function b(e,b,c,f){var l=document.getElementById("Tip");e=e.getName();l&&(e?(l.title=e,l.textContent=e,l.style.left=b+9+"px",
l.style.top=c+53+"px",f?(d.tipTimeout&&clearTimeout(d.tipTimeout),d.tipTimeout=setTimeout(a,f)):a()):l.style.visibility="hidden")}function c(e,b){var a,c,f,g;for(g in d.gizmo)c=d.gizmo[g],a=c.getImageSize(),void 0!==e&&void 0!=b?a&&(f=c.getImageSize().x/2,a=(new T.Vector2(e,b)).sub(c.gizmoPosition).length(),f&&0<f&&(a=(1-Math.min(Math.max((a-f)/f,0),1))*(c.maxScale-c.minScale)+c.minScale,c.gizmoScale=a,c.update())):(c.gizmoScale=c.minScale,c.update())}function q(e){e.preventDefault();e.stopPropagation();
var a=!1,k=e.touches?e.touches[0]:e;if(m(k.clientX,k.clientY)){var a=f.getBoundingClientRect(),t=k.clientX-a.left,l=k.clientY-a.top;c(t,l);var a=!0,h=r(k)}void 0!==h?(void 0!==d.highlightedSprite&&d.highlightedSprite!==h&&d.gizmo[d.highlightedSprite].show(T.SpriteGizmo.INACTIVE),d.highlightedSprite=h,k=d.gizmo[h],k.show(e.touches||void 0!==d.pointerDownSprite?T.SpriteGizmo.PRESSED:T.SpriteGizmo.HIGHLIGHT),b(k,t,l,400)):(void 0!==d.highlightedSprite&&d.gizmo[d.highlightedSprite].show(T.SpriteGizmo.INACTIVE),
d.highlightedSprite=void 0,g());!a||void 0!==d.pointerDown||e.touches||e.cancel||e.rendered||(e.rendered=!0,d.update())}function h(e){e.preventDefault();e.stopPropagation();d.pointerDown=!0;e=e.touches?e.touches[0]:e;if(0===e.button||void 0==e.button){if(m(e.clientX,e.clientY)){var a=f.getBoundingClientRect(),k=e.clientX-a.left,a=e.clientY-a.top;c(k,a);var h=r(e)}void 0!==h?(void 0!==d.highlightedSprite&&d.highlightedSprite!==h&&d.gizmo[d.highlightedSprite].show(T.SpriteGizmo.INACTIVE),d.highlightedSprite=
h,e=d.gizmo[h],d.pointerDownSprite=e,e.show(T.SpriteGizmo.PRESSED),b(e,k,a),d.update()):(void 0!==d.highlightedSprite&&(d.gizmo[d.highlightedSprite].show(T.SpriteGizmo.INACTIVE),d.update()),d.pointerDownSprite=null,d.highlightedSprite=void 0,g())}}function n(a){a.preventDefault();d.pointerDown=void 0;var b=a.touches?T.SpriteGizmo.INACTIVE:T.SpriteGizmo.HIGHLIGHT;if(a.touches||0===a.button||void 0===a.button){c();if(void 0!==d.highlightedSprite){var f=d.gizmo[d.highlightedSprite];f.onClick&&f==d.pointerDownSprite&&
(a.stopPropagation(),f.onClick(f.spriteId));f.show(b)}d.pointerDownSprite=void 0;a.rendered||(a.rendered=!0,d.update())}g()}function r(a,b){for(var c=f.getBoundingClientRect(),g=a.clientX-c.left,c=a.clientY-c.top,h=0;h<d.gizmo.length;++h)if(d.gizmo[h].intersects(g,c,b))return h}T.Object3D.call(this);var d=this;f=void 0!==f?f:document;this.boundingClientRect={left:f.getBoundingClientRect().left,right:f.getBoundingClientRect().right,top:f.getBoundingClientRect().top,bottom:f.getBoundingClientRect().bottom};
this.gizmo=[];var p={type:"change"};f.addEventListener("mousedown",h,!1);f.addEventListener("touchstart",h,!1);f.addEventListener("mousemove",q,!1);f.addEventListener("touchmove",q,!1);f.addEventListener("mouseup",n,!1);f.addEventListener("mouseout",n,!1);f.addEventListener("touchend",n,!1);f.addEventListener("touchcancel",n,!1);f.addEventListener("touchleave",n,!1);this.update=function(){d.dispatchEvent(p)};this.add=function(a){a.render||(a.render=this.update);this.gizmo.push(a);T.HUDControls.prototype.add.call(this,
a)};d.update()};T.HUDControls.prototype=Object.create(T.Object3D.prototype);
