T.MeasurementControls=function(G,f,w){function q(a){a?b.dispatchEvent({type:"select",measurement:a.measurement}):b.dispatchEvent({type:"select"})}function x(a){a.measurementGizmo&&(q(a.measurementGizmo),b.select(a.measurementGizmo.measurement))}function y(a){if(a.measurementGizmo&&a.originalEvent){b.selectedPicker=a.measurementGizmo.getTextPicker();if(b.selectedPicker){f.updateMatrixWorld();var c=r(a.originalEvent.touches?a.originalEvent.touches[0]:a.originalEvent),d=new T.V3(0,0,1);d.unproject?d.unproject(f):
z.unprojectVector(d,f);d=linePlaneIntersection(f.position,c,b.selectedPicker.position,d);a.measurementGizmo.dragStart(b.selectedPicker.name,c,d);b.dragging=!0;b.update()}q(a.measurementGizmo)}}function A(a){T.Object3D.prototype.add.call(b,a);b.measurementGizmos.push(a);a.addEventListener("select",x);a.addEventListener("textMouseDown",y);a.acceptPoints()&&(g.style.cursor="crosshair");for(var c=0;c<a.pickers.children.length;++c)b.pickers.push(a.pickers.children[c]);b.update();b.dispatchEvent(t)}function B(a){if(!(a&&
a.cancel||!b.enabled||b.dragging)){a.preventDefault();var c=u(a.touches?a.touches[0]:a,b.pickers,!1);c?b.selectedPicker!==c.object&&(b.selectedPicker=c.object,b.update(),a.rendered||(a.rendered=!0,b.dispatchEvent({type:"change",scope:"hover",object:b.selectedPicker?b.selectedPicker.measurementGizmo.measurement:null}))):!1!==b.selectedPicker&&(b.selectedPicker=!1,b.update(),a.rendered||(a.rendered=!0,b.dispatchEvent({type:"change",scope:"hover"})))}}function C(a){if((!a||!a.cancel)&&b.enabled){a.preventDefault();
a.stopPropagation();var c=a.touches?a.touches[0]:a;if(0===c.button||void 0==c.button){var d=0<b.measurementGizmos.length?b.measurementGizmos[b.measurementGizmos.length-1]:null;if(d&&d.acceptPoints()){var e=u(c,G.objects,!0);if(e){if(b.snap&&d.mustSnapToPart()){var h=e,v=d;if(h&&h.face&&h.object&&h.object.geometry){var H=[h.object.geometry.vertices[h.face.a],h.object.geometry.vertices[h.face.b],h.object.geometry.vertices[h.face.c]];f.updateMatrixWorld();for(var v=4*v.getWidth(h.point,f),m,n,p,l=null,
k=0;3>k;++k)m=(new T.V3).copy(H[k]),h.object.localToWorld(m),n=h.point.distanceTo(m),n<=v&&(!l||n<p)&&(p=n,l=m);l&&(h.point=l)}}d.addControlPoint(e.point,e.object,null,e.face,b.onAddedObject);d.mustDragGizmo()?(b.selectedPicker=d.mustDragGizmo(),c=r(c),d.addControlPoint(e.point,e.object,null,null,b.onAddedObject),d.dragStart(b.selectedPicker.name,c,e.point),g.style.cursor="default",b.dragging=!0):g.style.cursor=d.acceptPoints()?"crosshair":"default";a.cancel=!0;b.update();q(d);b.dispatchEvent(t)}}else if(e=
u(c,b.pickers,!1))if(b.selectedPicker=e.object,d=e.object.measurementGizmo)f.updateMatrixWorld(),c=r(c),d.dragStart(e.object.name,c,e.point),a.cancel=!0,b.dragging=!0,b.update(),q(d)}}}function D(a){if((!a||!a.cancel)&&b.enabled){var c=0<b.measurementGizmos.length?b.measurementGizmos[b.measurementGizmos.length-1]:null;c&&c.acceptPoints()&&(g.style.cursor="crosshair");if(b.dragging){a.preventDefault();a.stopPropagation();var d=a.touches?a.touches[0]:a;if(b.selectedPicker&&b.selectedPicker.measurementGizmo){c=
b.selectedPicker.measurementGizmo;f.updateMatrixWorld();var d=r(d),e=(new T.V3).setFromMatrixPosition(f.matrixWorld);c.dragMove(b.selectedPicker.name,d,e);a.cancel=!0;b.dispatchEvent({type:"change",scope:"dragging",object:b.selectedPicker.measurementGizmo.measurement});b.update()}}}}function k(a){if(!a||!a.cancel)if(!a||"mouseout"!=a.type||!a.relatedTarget||a.relatedTarget.parentElement!=g){var c=b.selectedPicker?b.selectedPicker.measurementGizmo.measurement:null;b.dragging=!1;b.selectedPicker=!1;
a.rendered||(a.rendered=!0);b.dispatchEvent({type:"change",scope:"finishDragging",object:c});b.update()}}function E(){var a=0<b.measurementGizmos.length?b.measurementGizmos[b.measurementGizmos.length-1]:null;a&&a.acceptPoints()&&(b.remove(a.measurement),a.removeUIObject(),q(),b.dispatchEvent(t))}function r(a){var b=g.getBoundingClientRect();a=new T.V3((a.clientX-b.left)/b.width*2-1,2*-((a.clientY-b.top)/b.height)+1,.5);a.unproject?a.unproject(f):z.unprojectVector(a,f);return a.sub(f.position).normalize()}
function u(a,b,d){F.set(f.position,r(a));b||console.log("err");a=F.intersectObjects(b,d);if(0<a.length)for(;0<a.length&&(a[0].object.measurementGizmo&&!1===a[0].object.measurementGizmo.isVisible()||!a[0].object.measurementGizmo&&!1===a[0].object.visible);)a.shift();return a[0]?a[0]:!1}T.Object3D.call(this);var g=w.dom;this.measurementGizmos=[];this.pickers=[];this.selectedPicker=this.enabled=!1;this.snap=!0;this.dragging=!1;var b=this,t={type:"sceneChanged"},F=new T.Raycaster,z=new T.Projector;g.addEventListener("mousedown",
C,!1);g.addEventListener("touchstart",C,!1);g.addEventListener("mousemove",B,!1);g.addEventListener("touchmove",B,!1);g.addEventListener("mousemove",D,!1);g.addEventListener("touchmove",D,!1);g.addEventListener("mouseup",k,!1);g.addEventListener("mouseout",k,!1);g.addEventListener("touchend",k,!1);g.addEventListener("touchcancel",k,!1);g.addEventListener("touchleave",k,!1);window.addEventListener("keydown",function(a){if(!1!==b.enabled)switch(a.keyCode){case 27:E()}},!1);this.add=function(a){a=a.createGizmo(w);
A(a)};this.remove=function(a){if(a&&a.measurementGizmo){for(var c=a.measurementGizmo,d=0;d<c.pickers.children.length;++d){var e=b.pickers.indexOf(c.pickers.children[d]);0<=e&&b.pickers.splice(e,1)}c.removeEventListener("select",x);c.removeEventListener("textMouseDown",y);e=b.measurementGizmos.indexOf(c);0<=e&&b.measurementGizmos.splice(e,1);c.clean();T.Object3D.prototype.remove.call(b,c);b.update()}b.dispatchEvent({type:"objectRemoved",object:a})};this.attachGizmo=function(a){A(a);a.restore()};this.onAddedObject=
function(a){b.dispatchEvent({type:"objectAdded",object:a})};this.update=function(){f.updateMatrixWorld();for(var a=0;a<this.measurementGizmos.length;++a)this.measurementGizmos[a].highlight(!1),this.measurementGizmos[a].update(f);b.selectedPicker&&b.selectedPicker.measurementGizmo.highlight(b.selectedPicker.name)};this.select=function(a){for(var c=0;c<this.measurementGizmos.length;++c)this.measurementGizmos[c].select(!1);a&&a.measurementGizmo&&(a.measurementGizmo.select(),this.update(),b.dispatchEvent({type:"change",
scope:"select",object:a}))};this.load=function(a,c,d){if(a&&c&&c.measurementGizmo&&d&&d.points){for(var e=c.measurementGizmo,h,f,k=null,m=0;m<d.points.length;++m){h=(new T.V3).copy(d.points[m]);f=d.points[m].name;for(var k=null,n=0;n<a.children.length;++n){var p=a.children[n].name,l=T.FileOperations.extractExtension(p),l="stl"==l||"zip"==l?T.FileOperations.extractName(p):null;if(f==p||l&&f==l){k=a.children[n];break}}e.addControlPoint(h,k?k:a,!0,null,b.onAddedObject)}g.style.cursor="default";void 0!==
d.visible&&(c.visible=d.visible);void 0!==d.name&&(c.name=d.name);void 0!==d.comments&&c.setComments(d.comments);e.acceptPoints()?E():(b.update(),b.dispatchEvent(t))}};this.acceptPoints=function(){var a=0<b.measurementGizmos.length?b.measurementGizmos[b.measurementGizmos.length-1]:null;return a&&a.acceptPoints()}};T.MeasurementControls.prototype=Object.create(T.Object3D.prototype);
