T.TransformGizmoMaterial=function(b){T.MeshBasicMaterial.call(this);this.depthWrite=this.depthTest=!1;this.side=T.DoubleSide;this.transparent=!0;this.setValues(b)};T.TransformGizmoMaterial.prototype=Object.create(T.MeshBasicMaterial.prototype);
T.TransformGizmo=function(){this.handleGizmos={X:[new T.Mesh(new T.CylinderGeometry(.005,.005,1,4,1,!1),new T.TransformGizmoMaterial({color:65280})),new T.V3(.5,0,0),new T.V3(0,0,-Math.PI/2)],Y:[new T.Mesh(new T.CylinderGeometry(.005,.005,1,4,1,!1),new T.TransformGizmoMaterial({color:65280})),new T.V3(0,.5,0)],Z:[new T.Mesh(new T.CylinderGeometry(.005,.005,1,4,1,!1),new T.TransformGizmoMaterial({color:16711680})),new T.V3(0,0,.5),new T.V3(Math.PI/2,0,0)]};this.init=function(){T.Object3D.call(this);
this.handles=new T.Object3D;this.pickers=new T.Object3D;this.planes=new T.Object3D;this.add(this.handles);this.add(this.pickers);this.add(this.planes);var b=new T.PlaneGeometry(50,50,2,2),a=new T.MeshBasicMaterial({wireframe:!0});a.side=T.DoubleSide;b={XY:new T.Mesh(b,a),YZ:new T.Mesh(b,a),XZ:new T.Mesh(b,a),XYZE:new T.Mesh(b,a)};b.YZ.rotation.set(0,Math.PI/2,0);b.XZ.rotation.set(-Math.PI/2,0,0);for(var f in b)b[f].name=f,this.planes.add(b[f]),this.planes[f]=b[f],b[f].visible=!1;for(f in this.handleGizmos)b=
this.handleGizmos[f][0],b.name=f,this.handleGizmos[f][1]&&b.position.set(this.handleGizmos[f][1].x,this.handleGizmos[f][1].y,this.handleGizmos[f][1].z),this.handleGizmos[f][2]&&b.rotation.set(this.handleGizmos[f][2].x,this.handleGizmos[f][2].y,this.handleGizmos[f][2].z),this.handles.add(b),this.pickerGizmos&&this.pickerGizmos[f]?(b=this.pickerGizmos[f][0],this.pickerGizmos[f][1]&&b.position.set(this.pickerGizmos[f][1].x,this.pickerGizmos[f][1].y,this.pickerGizmos[f][1].z),this.pickerGizmos[f][2]&&
b.rotation.set(this.pickerGizmos[f][2].x,this.pickerGizmos[f][2].y,this.pickerGizmos[f][2].z)):b=b.clone(),b.name=f,this.pickers.add(b);this.traverse(function(a){if(a instanceof T.Mesh){var b=new T.Geometry;T.GeometryUtils.merge(b,a);a.geometry=b;a.position.set(0,0,0);a.rotation.set(0,0,0);a.scale.set(1,1,1)}})};this.hide=function(){for(var b in this.handles.children)this.handles.children[b].visible=!1;for(b in this.pickers.children)this.pickers.children[b].visible=!1;for(b in this.planes.children)this.planes.children[b].visible=
!1};this.show=function(){for(var b in this.handles.children)this.handles.children[b].visible=!0;for(b in this.pickers.children)this.pickers.children[b].visible=!1;this.activePlane&&(this.activePlane.visible=!1)};this.highlight=function(b){var a,f;for(f in this.handleGizmos)a=this.handleGizmos[f][0],a.material.oldColor&&(a.material.color.copy(a.material.oldColor),a.material.opacity=a.material.oldOpacity);this.handleGizmos[b]&&(a=this.handleGizmos[b][0],a.material.oldColor=a.material.color.clone(),
a.material.oldOpacity=a.material.opacity,a.material.color.setRGB(1,1,0),a.material.opacity=1)};this.init()};T.TransformGizmo.prototype=Object.create(T.Object3D.prototype);T.TransformGizmo.prototype.update=function(b,a){var f=new T.V3(0,0,0),h=new T.V3(0,1,0),p=new T.Matrix4,m;for(m in this.children)for(var w in this.children[m].children){var c=this.children[m].children[w];-1!=c.name.search("E")?c.quaternion.setFromRotationMatrix(p.lookAt(a,f,h)):c.quaternion.setFromEuler(b)}};
T.TransformGizmoTranslate=function(){T.TransformGizmo.call(this);var b=new T.CylinderGeometry(.015,.015,1,4,1,!1),a=new T.Mesh(new T.CylinderGeometry(0,.06,.2,12,1,!1));a.position.y=.5;T.GeometryUtils.merge(b,a);for(var a=[],f=["X","Y","Z"],h=0;3>h;h++){var p=new T.Mesh(new T.TextGeometry(f[h],{size:.1,height:.01,weight:"bold"}));p.position.y=.65;p.position.x=-.04;a[h]=b.clone();T.GeometryUtils.merge(a[h],p)}this.handleGizmos={X:[new T.Mesh(a[0],new T.TransformGizmoMaterial({color:255,opacity:1})),
new T.V3(.5,0,0),new T.V3(0,0,-Math.PI/2)],Y:[new T.Mesh(a[1],new T.TransformGizmoMaterial({color:65280,opacity:1})),new T.V3(0,.5,0)],Z:[new T.Mesh(a[2],new T.TransformGizmoMaterial({color:16711680,opacity:1})),new T.V3(0,0,.5),new T.V3(Math.PI/2,0,0)],XYZ:[new T.Mesh(new T.OctahedronGeometry(.1,0),new T.TransformGizmoMaterial({color:16777215,opacity:.5}))],XY:[new T.Mesh(new T.PlaneGeometry(.47,.47),new T.TransformGizmoMaterial({color:65535,opacity:.25})),new T.V3(.25,.25,0)],YZ:[new T.Mesh(new T.PlaneGeometry(.47,
.47),new T.TransformGizmoMaterial({color:16776960,opacity:.25})),new T.V3(0,.25,.25),new T.V3(0,Math.PI/2,0)],XZ:[new T.Mesh(new T.PlaneGeometry(.47,.47),new T.TransformGizmoMaterial({color:16711935,opacity:.25})),new T.V3(.25,0,.25),new T.V3(-Math.PI/2,0,0)]};this.pickerGizmos={X:[new T.Mesh(new T.CylinderGeometry(.1,0,1.4,4,1,!1),new T.TransformGizmoMaterial({color:255,opacity:.25})),new T.V3(.6,0,0),new T.V3(0,0,-Math.PI/2)],Y:[new T.Mesh(new T.CylinderGeometry(.1,0,1.4,4,1,!1),new T.TransformGizmoMaterial({color:65280,
opacity:.25})),new T.V3(0,.6,0)],Z:[new T.Mesh(new T.CylinderGeometry(.1,0,1.4,4,1,!1),new T.TransformGizmoMaterial({color:16711680,opacity:.25})),new T.V3(0,0,.6),new T.V3(Math.PI/2,0,0)]};this.setActivePlane=function(a,b){var c=new T.Matrix4;b.applyProjection(c.getInverse(c.extractRotation(this.planes.XY.matrixWorld)));"X"==a&&(this.activePlane=this.planes.XY,Math.abs(b.y)>Math.abs(b.z)&&(this.activePlane=this.planes.XZ));"Y"==a&&(this.activePlane=this.planes.XY,Math.abs(b.x)>Math.abs(b.z)&&(this.activePlane=
this.planes.YZ));"Z"==a&&(this.activePlane=this.planes.XZ,Math.abs(b.x)>Math.abs(b.y)&&(this.activePlane=this.planes.YZ));"XYZ"==a&&(this.activePlane=this.planes.XYZE);"XY"==a&&(this.activePlane=this.planes.XY);"YZ"==a&&(this.activePlane=this.planes.YZ);"XZ"==a&&(this.activePlane=this.planes.XZ);this.hide();this.show()};this.init()};T.TransformGizmoTranslate.prototype=Object.create(T.TransformGizmo.prototype);
T.TransformGizmoRotate=function(){T.TransformGizmo.call(this);this.handleGizmos={XYZE:[new T.Mesh(new T.SphereGeometry(.995,64,64),new T.TransformGizmoMaterial({color:7895160,opacity:.15}))],X:[new T.Mesh(new T.TorusGeometry(1,.015,4,32,Math.PI),new T.TransformGizmoMaterial({color:255})),new T.V3(0,0,0),new T.V3(0,-Math.PI/2,-Math.PI/2)],Y:[new T.Mesh(new T.TorusGeometry(1,.015,4,32,Math.PI),new T.TransformGizmoMaterial({color:65280})),new T.V3(0,0,0),new T.V3(Math.PI/2,0,0)],Z:[new T.Mesh(new T.TorusGeometry(1,
.015,4,32,Math.PI),new T.TransformGizmoMaterial({color:16711680})),new T.V3(0,0,0),new T.V3(0,0,-Math.PI/2)],E:[new T.Mesh(new T.TorusGeometry(1.25,.045,4,64),new T.TransformGizmoMaterial({color:7895160,opacity:.25}))]};this.pickerGizmos={X:[new T.Mesh(new T.TorusGeometry(1,.07,4,12,Math.PI),new T.TransformGizmoMaterial({color:255,opacity:.95})),new T.V3(0,0,0),new T.V3(0,-Math.PI/2,-Math.PI/2)],Y:[new T.Mesh(new T.TorusGeometry(1,.07,4,12,Math.PI),new T.TransformGizmoMaterial({color:65280,opacity:.95})),
new T.V3(0,0,0),new T.V3(Math.PI/2,0,0)],Z:[new T.Mesh(new T.TorusGeometry(1,.07,4,12,Math.PI),new T.TransformGizmoMaterial({color:16711680,opacity:.95})),new T.V3(0,0,0),new T.V3(0,0,-Math.PI/2)],E:[new T.Mesh(new T.TorusGeometry(1.25,.1,2,24),new T.TransformGizmoMaterial({color:65535,opacity:.25}))],XYZE:[new T.Mesh(new T.Geometry)]};this.setActivePlane=function(b){"E"==b&&(this.activePlane=this.planes.XYZE);"X"==b&&(this.activePlane=this.planes.YZ);"Y"==b&&(this.activePlane=this.planes.XZ);"Z"==
b&&(this.activePlane=this.planes.XY);this.hide();this.show()};this.update=function(b,a){T.TransformGizmo.prototype.update.apply(this,arguments);var f={handles:this.handles,pickers:this.pickers},h=new T.Matrix4,p=new T.Euler(0,0,1),m=new T.Quaternion,w=new T.V3(1,0,0),c=new T.V3(0,1,0),z=new T.V3(0,0,1),l=new T.Quaternion,G=new T.Quaternion,C=new T.Quaternion,x=a.clone();p.copy(this.planes.XY.rotation);m.setFromEuler(p);h.makeRotationFromQuaternion(m).getInverse(h);x.applyProjection(h);for(var y in f)for(var H in f[y].children)h=
f[y].children[H],m.setFromEuler(p),"X"==h.name&&(l.setFromAxisAngle(w,Math.atan2(-x.y,x.z)),m.multiplyQuaternions(m,l),h.quaternion.copy(m)),"Y"==h.name&&(G.setFromAxisAngle(c,Math.atan2(x.x,x.z)),m.multiplyQuaternions(m,G),h.quaternion.copy(m)),"Z"==h.name&&(C.setFromAxisAngle(z,Math.atan2(x.y,x.x)),m.multiplyQuaternions(m,C),h.quaternion.copy(m))};this.init()};T.TransformGizmoRotate.prototype=Object.create(T.TransformGizmo.prototype);
T.TransformGizmoScale=function(){T.TransformGizmo.call(this);var b=new T.CylinderGeometry(.015,.015,1,4,1,!1),a=new T.Mesh(new T.CubeGeometry(.125,.125,.125));a.position.y=.5;T.GeometryUtils.merge(b,a);for(var a=[],f=["X","Y","Z"],h=0;3>h;h++){var p=new T.Mesh(new T.TextGeometry(f[h],{size:.1,height:.01,weight:"bold"}));p.position.y=.65;p.position.x=-.04;a[h]=b.clone();T.GeometryUtils.merge(a[h],p)}this.handleGizmos={XYZ:[new T.Mesh(new T.CubeGeometry(.125,.125,.125),new T.TransformGizmoMaterial({color:16777215,
opacity:.5}))],X:[new T.Mesh(a[0],new T.TransformGizmoMaterial({color:255})),new T.V3(.5,0,0),new T.V3(0,0,-Math.PI/2)],Y:[new T.Mesh(a[1],new T.TransformGizmoMaterial({color:65280})),new T.V3(0,.5,0)],Z:[new T.Mesh(a[2],new T.TransformGizmoMaterial({color:16711680})),new T.V3(0,0,.5),new T.V3(Math.PI/2,0,0)]};this.pickerGizmos={X:[new T.Mesh(new T.CylinderGeometry(.125,0,1.4,4,1,!1),new T.TransformGizmoMaterial({color:255,opacity:.25})),new T.V3(.6,0,0),new T.V3(Math.PI/4,0,-Math.PI/2)],Y:[new T.Mesh(new T.CylinderGeometry(.125,
0,1.4,4,1,!1),new T.TransformGizmoMaterial({color:65280,opacity:.25})),new T.V3(0,.6,0),new T.V3(0,Math.PI/4,0)],Z:[new T.Mesh(new T.CylinderGeometry(.125,0,1.4,4,1,!1),new T.TransformGizmoMaterial({color:16711680,opacity:.25})),new T.V3(0,0,.6),new T.V3(Math.PI/2,Math.PI/4,0)]};this.setActivePlane=function(a,b){var c=new T.Matrix4;b.applyProjection(c.getInverse(c.extractRotation(this.planes.XY.matrixWorld)));"X"==a&&(this.activePlane=this.planes.XY,Math.abs(b.y)>Math.abs(b.z)&&(this.activePlane=
this.planes.XZ));"Y"==a&&(this.activePlane=this.planes.XY,Math.abs(b.x)>Math.abs(b.z)&&(this.activePlane=this.planes.YZ));"Z"==a&&(this.activePlane=this.planes.XZ,Math.abs(b.x)>Math.abs(b.y)&&(this.activePlane=this.planes.YZ));"XYZ"==a&&(this.activePlane=this.planes.XYZE);this.hide();this.show()};this.init()};T.TransformGizmoScale.prototype=Object.create(T.TransformGizmo.prototype);
T.TransformControls=function(b,a){function f(t){if(!(t&&t.cancel||!c.hasAttachments()||z)){t.preventDefault();t.stopPropagation();var a=w(t.touches?t.touches[0]:t,c.gizmo[l].pickers.children);a?c.axis!=a.object.name&&(c.axis=a.object.name,c.update(),t.rendered||(t.rendered=!0,c.dispatchEvent(y))):c.axis&&(c.axis=!1,c.update(),t.rendered||(t.rendered=!0,c.dispatchEvent(y)))}}function h(a){if(!(a&&a.cancel||!c.hasAttachments()||z)&&(a.preventDefault(),a.stopPropagation(),a=a.touches?a.touches[0]:a,
0===a.button||void 0==a.button)){var b=w(a,c.gizmo[l].pickers.children);if(b){c.axis=b.object.name;c.update();D.copy(E).sub(B).normalize();c.gizmo[l].setActivePlane(c.axis,D);if(a=w(a,[c.gizmo[l].activePlane]))for(b=0;b<c.objects.length;++b){var g=c.objects[b];g&&g.parent&&(g.oldPosition||(g.oldPosition=new T.V3),g.oldScale||(g.oldScale=new T.V3),g.oldRotationMatrix||(g.oldRotationMatrix=new T.Matrix4),g.worldRotationMatrix||(g.worldRotationMatrix=new T.Matrix4),g.oldMatrix||(g.oldMatrix=new T.Matrix4),
g.parentRotationMatrix||(g.parentRotationMatrix=new T.Matrix4),g.parentScale||(g.parentScale=new T.V3),g.oldPosition.copy(g.position),g.oldScale.copy(g.scale),g.oldRotationMatrix.extractRotation(g.matrix),g.worldRotationMatrix.extractRotation(g.matrixWorld),g.oldMatrix.copy(g.matrix),g.parentRotationMatrix.extractRotation(g.parent.matrixWorld),g.parentScale.setFromMatrixScale(r.getInverse(g.parent.matrixWorld)),I.copy(a.point))}z=!0}}}function p(a){if((!a||!a.cancel)&&c.hasAttachments()&&c.axis&&
z){a.preventDefault();a.stopPropagation();var b=a.touches?a.touches[0]:a;if(c.gizmo[l].activePlane){if(b=w(b,[c.gizmo[l].activePlane]))for(var g=0;g<c.objects.length;++g){var e=c.objects[g];if(e&&e.oldPosition&&e.oldScale&&e.oldRotationMatrix&&e.worldRotationMatrix&&e.parentRotationMatrix&&e.parentScale)if(d.copy(b.point),"translate"==l){if(d.sub(I),d.multiply(e.parentScale),"local"==c.space&&(d.applyMatrix4(r.getInverse(e.worldRotationMatrix)),-1==c.axis.search("X")&&(d.x=0),-1==c.axis.search("Y")&&
(d.y=0),-1==c.axis.search("Z")&&(d.z=0),d.applyMatrix4(e.oldRotationMatrix),e.position.copy(e.oldPosition),e.position.add(d)),"world"==c.space||-1!=c.axis.search("XYZ"))-1==c.axis.search("X")&&(d.x=0),-1==c.axis.search("Y")&&(d.y=0),-1==c.axis.search("Z")&&(d.z=0),d.applyMatrix4(r.getInverse(e.parentRotationMatrix)),e.position.copy(e.oldPosition),e.position.add(d),c.snap&&(-1!=c.axis.search("X")&&(e.position.x=Math.round(e.position.x/c.snap)*c.snap),-1!=c.axis.search("Y")&&(e.position.y=Math.round(e.position.y/
c.snap)*c.snap),-1!=c.axis.search("Z")&&(e.position.z=Math.round(e.position.z/c.snap)*c.snap))}else"scale"==l?(d.sub(I),d.multiply(e.parentScale),"local"==c.space&&("XYZ"==c.axis?(A=1+d.y/50,e.scale.x=e.oldScale.x*A,e.scale.y=e.oldScale.y*A,e.scale.z=e.oldScale.z*A):(d.applyMatrix4(r.getInverse(e.worldRotationMatrix)),"X"==c.axis&&(e.scale.x=e.oldScale.x*(1+d.x/50)),"Y"==c.axis&&(e.scale.y=e.oldScale.y*(1+d.y/50)),"Z"==c.axis&&(e.scale.z=e.oldScale.z*(1+d.z/50))))):"rotate"==l&&(d.sub(B),d.multiply(e.parentScale),
k.copy(I).sub(B),k.multiply(e.parentScale),"E"==c.axis?(d.applyMatrix4(r.getInverse(N)),k.applyMatrix4(r.getInverse(N)),u.set(Math.atan2(d.z,d.y),Math.atan2(d.x,d.z),Math.atan2(d.y,d.x)),v.set(Math.atan2(k.z,k.y),Math.atan2(k.x,k.z),Math.atan2(k.y,k.x)),n.setFromRotationMatrix(r.getInverse(e.parentRotationMatrix)),J.setFromAxisAngle(D,u.z-v.z),q.setFromRotationMatrix(e.worldRotationMatrix),n.multiplyQuaternions(n,J),n.multiplyQuaternions(n,q),e.quaternion.copy(n)):"XYZE"==c.axis?(J.setFromEuler(d.clone().cross(k).normalize()),
n.setFromRotationMatrix(r.getInverse(e.parentRotationMatrix)),F.setFromAxisAngle(J,-d.clone().angleTo(k)),q.setFromRotationMatrix(e.worldRotationMatrix),n.multiplyQuaternions(n,F),n.multiplyQuaternions(n,q),e.quaternion.copy(n)):"local"==c.space?(d.applyMatrix4(r.getInverse(e.worldRotationMatrix)),k.applyMatrix4(r.getInverse(e.worldRotationMatrix)),u.set(Math.atan2(d.z,d.y),Math.atan2(d.x,d.z),Math.atan2(d.y,d.x)),v.set(Math.atan2(k.z,k.y),Math.atan2(k.x,k.z),Math.atan2(k.y,k.x)),q.setFromRotationMatrix(e.oldRotationMatrix),
F.setFromAxisAngle(O,u.x-v.x),K.setFromAxisAngle(P,u.y-v.y),L.setFromAxisAngle(Q,u.z-v.z),"X"==c.axis&&q.multiplyQuaternions(q,F),"Y"==c.axis&&q.multiplyQuaternions(q,K),"Z"==c.axis&&q.multiplyQuaternions(q,L),e.quaternion.copy(q)):"world"==c.space&&(u.set(Math.atan2(d.z,d.y),Math.atan2(d.x,d.z),Math.atan2(d.y,d.x)),v.set(Math.atan2(k.z,k.y),Math.atan2(k.x,k.z),Math.atan2(k.y,k.x)),n.setFromRotationMatrix(r.getInverse(e.parentRotationMatrix)),F.setFromAxisAngle(O,u.x-v.x),K.setFromAxisAngle(P,u.y-
v.y),L.setFromAxisAngle(Q,u.z-v.z),q.setFromRotationMatrix(e.worldRotationMatrix),"X"==c.axis&&n.multiplyQuaternions(n,F),"Y"==c.axis&&n.multiplyQuaternions(n,K),"Z"==c.axis&&n.multiplyQuaternions(n,L),n.multiplyQuaternions(n,q),e.quaternion.copy(n)))}a.rendered||(a.rendered=!0,c.dispatchEvent(x));c.update()}}}function m(b){if(!b||!b.cancel)if(!b||"mouseout"!=b.type||!b.relatedTarget||b.relatedTarget.parentElement!=a){if((0===b.button||void 0==b.button)&&"bottom"==l&&c.scene&&c.scene.children){var d=
w(b.touches?b.touches[0]:b,c.scene.children);if(d&&d.face&&d.object&&d.object.geometry){c.setMode(G);for(var d=T.GeometryUtils.computeFaceNormal.call(d.object.geometry,d.face).clone(),g=c.objects,e=0;e<g.length;++e){var f=g[e];if(f){f.oldMatrix||(f.oldMatrix=new T.Matrix4);f.oldMatrix.copy(f.matrix);var h=new T.Matrix4;h.getInverse(f.parent.matrixWorld);h=(new T.Matrix3).getNormalMatrix(h);h=(new T.V3(0,0,-1)).applyMatrix3(h).normalize();f.quaternion.setFromUnitVectors(d,h);f.updateMatrixWorld()}}a.style.cursor=
"default";C.objects=g;c.dispatchEvent(C)}}if(d=!b.rendered)a:{for(d=0;d<c.objects.length;++d)if((g=c.objects[d])&&g.oldMatrix&&!g.matrix.equals(g.oldMatrix)){d=!0;break a}d=!1}if(d)for(b.rendered=!0,z?c.dispatchEvent(C):c.dispatchEvent(y),b=0;b<c.objects.length;++b)if(d=c.objects[b])d.oldPosition=null,d.oldScale=null,d.oldRotationMatrix=null,d.oldMatrix=null,d.worldRotationMatrix=null,d.parentRotationMatrix=null,d.parentScale=null;z=c.axis=!1;c.update()}}function w(c,d){var g=a.getBoundingClientRect();
M.set((c.clientX-g.left)/g.width*2-1,2*-((c.clientY-g.top)/g.height)+1,.5);S.unprojectVector(M,b);H.set(E,M.sub(E).normalize());g=H.intersectObjects(d,!0);return g[0]?g[0]:!1}T.Object3D.call(this);a=void 0!==a?a:document;this.gizmo={};this.gizmo.translate=new T.TransformGizmoTranslate;this.gizmo.rotate=new T.TransformGizmoRotate;this.gizmo.scale=new T.TransformGizmoScale;this.gizmo.bottom=new T.TransformGizmo;this.add(this.gizmo.translate);this.add(this.gizmo.rotate);this.add(this.gizmo.scale);this.gizmo.translate.hide();
this.gizmo.rotate.hide();this.gizmo.scale.hide();this.objects=[];this.scene=null;this.snap=!1;this.space="world";this.size=1;this.axis=!1;var c=this,z=!1,l="translate",G="translate",C={type:"change"},x={type:"update"},y={type:"render"},H=new T.Raycaster,S=new T.Projector,M=new T.V3,d=new T.V3,I=new T.V3,u=new T.V3,v=new T.V3,A=1,N=new T.Matrix4,D=new T.V3,r=new T.Matrix4,k=new T.V3,n=new T.Quaternion,O=new T.V3(1,0,0),P=new T.V3(0,1,0),Q=new T.V3(0,0,1),q=new T.Quaternion,F=new T.Quaternion,K=new T.Quaternion,
L=new T.Quaternion,J=new T.Quaternion,B=new T.V3,R=new T.Euler,E=new T.V3,U=new T.Euler;a.addEventListener("mousedown",h,!1);a.addEventListener("touchstart",h,!1);a.addEventListener("mousemove",f,!1);a.addEventListener("touchmove",f,!1);a.addEventListener("mousemove",p,!1);a.addEventListener("touchmove",p,!1);a.addEventListener("mouseup",m,!1);a.addEventListener("mouseout",m,!1);a.addEventListener("touchend",m,!1);a.addEventListener("touchcancel",m,!1);a.addEventListener("touchleave",m,!1);this.isAttached=
function(a){for(var b=!1,d=0;d<c.objects.length&&!b;++d)a.id==c.objects[d].id?b=!0:c.objects[d].traverse(function(c){a.id==c.id&&(b=!0)});return b};this.hasAttachments=function(){return 0<c.objects.length};this.updateGizmos=function(){this.gizmo.translate.hide();this.gizmo.rotate.hide();this.gizmo.scale.hide();this.hasAttachments()&&this.gizmo[l].show()};this.setScene=function(a){this.scene=a};this.attach=function(a){this.isAttached(a)||(a.traverse(function(a){for(var b;-1!==(b=c.objects.indexOf(a));)c.objects.splice(b,
1)}),a&&this.objects.push(a),this.updateGizmos(),c.update())};this.detach=function(a){a?this.objects=this.objects.filter(function(b){return b.id!=a.id}):(this.objects=[],this.scene=null);this.axis=!1;this.updateGizmos()};this.setMode=function(b){l!=b&&(G=l,l=b?b:l,a.style.cursor="bottom"==l?"crosshair":"default","scale"==l&&(c.space="local"),this.updateGizmos(),c.dispatchEvent(y),this.update())};this.setSnap=function(a){c.snap=a};this.setSize=function(a){c.size=a;c.dispatchEvent(y);this.update()};
this.setSpace=function(a){c.space=a;c.dispatchEvent(y);this.update()};this.update=function(){if(this.hasAttachments()){var a=c.objects[c.objects.length-1];a.updateMatrixWorld();B.setFromMatrixPosition(a.matrixWorld);R.setFromRotationMatrix(r.extractRotation(a.matrixWorld));b.updateMatrixWorld();E.setFromMatrixPosition(b.matrixWorld);U.setFromRotationMatrix(r.extractRotation(b.matrixWorld));A=B.distanceTo(E)/6*c.size;this.position.copy(B);this.scale.set(A,A,A);D.copy(E).sub(B).normalize();"local"==
c.space?this.gizmo[l].update(R,D):"world"==c.space&&this.gizmo[l].update(new T.Euler,D);this.gizmo[l].highlight(c.axis)}}};T.TransformControls.prototype=Object.create(T.Object3D.prototype);
