T.WindowRectHelper=function(e,a,g,f){var b=[new T.V3(e,a,0),new T.V3(g,a,0),new T.V3(g,f,0),new T.V3(e,f,0)];this.vertices=b;var l=new T.Geometry;l.vertices.push(b[0],b[1],b[1],b[2],b[2],b[3],b[3],b[0]);T.Line.call(this,l,new T.LineBasicMaterial({color:16777215}),T.LinePieces);this.plane=new T.PlaneGeometry(g-e,f-a,1,1);this.add(new T.Mesh(this.plane,new T.MeshBasicMaterial({color:16777215,depthTest:!1,transparent:!0,opacity:.2,side:T.DoubleSide})))};T.WindowRectHelper.prototype=Object.create(T.Line.prototype);
T.WindowRectHelper.prototype.update1=function(e,a){for(var g=this.vertices,f=this.plane.vertices,b=0;4>b;b++)g[b].x=e,g[b].y=a,f[b].x=e,f[b].y=a;this.geometry.verticesNeedUpdate=!0;this.plane.verticesNeedUpdate=!0};T.WindowRectHelper.prototype.update2=function(e,a){var g=this.vertices,f=this.plane.vertices;g[3].y=a;g[2].x=e;g[2].y=a;g[1].x=e;f[2].y=a;f[3].x=e;f[3].y=a;f[1].x=e;this.geometry.verticesNeedUpdate=!0;this.plane.verticesNeedUpdate=!0};
T.WindowRectHelper.prototype.show=function(){this.visible=!0;this.children[0].visible=!0};T.WindowRectHelper.prototype.hide=function(){this.visible=!1;this.children[0].visible=!1};T.WindowRectHelper.prototype.isVisible=function(){return this.visible};T.WindowRectHelper.prototype.getX1=function(){return this.vertices[0].x};T.WindowRectHelper.prototype.getY1=function(){return this.vertices[0].y};
T.UniversalControls=function(e,a,g,f,b){function l(c){c.preventDefault();if(0===c.button)switch(d.mode){case "mark":var b=picker.pickFace(g,f,e,c.clientX-a.offsetLeft,c.clientY-a.offsetTop,!0,!1,!1);void 0!=b.object&&b.object instanceof T.Mesh&&(face=b.face,16777215==face.color.getHex()?(n=1,face.color=q):(n=2,face.color=r),b.object.geometry.colorsNeedUpdate=!0,c.stopPropagation());f.render(g,e);d.dispatchEvent(m);break;case "window":c.stopPropagation(),h.update1(c.clientX-a.offsetLeft,c.clientY-
a.offsetTop),h.show(),d.dispatchEvent(m)}}function t(c){c.preventDefault();if(0===c.button)switch(d.mode){case "mark":if(0!=n){var b=picker.pickFace(g,f,e,c.clientX-a.offsetLeft,c.clientY-a.offsetTop,!0,!1,!1);void 0!=b.object&&b.object instanceof T.Mesh&&(face=b.face,face.color=1==n?q:r,b.object.geometry.colorsNeedUpdate=!0,c.stopPropagation());f.render(g,e);d.dispatchEvent(m)}break;case "window":h.isVisible()&&(c.stopPropagation(),h.update2(c.clientX-a.offsetLeft,c.clientY-a.offsetTop),d.dispatchEvent(m),
k.bottom=a.offsetHeight-1,k.right=a.offsetWidth-1,k.updateProjectionMatrix(),f.render(u,k))}}function v(a){}function p(c){c.preventDefault();if(0===c.button)switch(d.mode){case "mark":n=0;break;case "window":if(h.isVisible()){h.hide();var b=c.clientX-a.offsetLeft;c=c.clientY-a.offsetTop;var k=h.getX1(),l=h.getY1();picker.markFacesWithRectangle(g,f,e,b,c,k,l,q,r,!0,!1,!1);f.render(g,e);d.dispatchEvent(m)}}}T.TransformControls.call(this,e,a);a=void 0!==a?a:document;var d=this,m={type:"change"};d.mode=
"transform";var q=new T.Color(65280),r=new T.Color(16777215),n=0,u=new T.Scene,k=new T.OrthographicCamera(0,0,0,0,50,15E3);k.position.set(0,0,100);k.lookAt(new T.V3(0,0,0));var h=new T.WindowRectHelper(100,100,1,1);u.add(h);h.hide();a.addEventListener("mousedown",l,!0);a.addEventListener("touchstart",l,!0);a.addEventListener("mousemove",v,!0);a.addEventListener("touchmove",v,!0);a.addEventListener("mousemove",t,!0);a.addEventListener("touchmove",t,!0);a.addEventListener("mouseup",p,!0);a.addEventListener("mouseout",
p,!0);a.addEventListener("touchend",p,!0);a.addEventListener("touchcancel",p,!0);a.addEventListener("touchleave",p,!0);picker=new T.Picking;var w=this.attach;this.attach=function(a){"mark"==d.mode||"window"==d.mode?(this.object=a,this.gizmo.translate.hide(),this.gizmo.rotate.hide(),this.gizmo.scale.hide(),d.dispatchEvent(m),d.update()):w.call(this,a)};var x=this.detach;this.detach=function(a){"mark"==d.mode||"window"==d.mode?(this.axis=this.object=!1,this.gizmo.translate.hide(),this.gizmo.rotate.hide(),
this.gizmo.scale.hide()):x.call(this,a)};var y=this.update;this.update=function(){"mark"!=d.mode&&"window"!=d.mode&&y.call(this)};var z=this.hide;this.hide=function(){"mark"!=d.mode&&"window"!=d.mode&&z.call(this)};var A=this.setMode;this.setMode=function(a){n=0;"mark"==a||"window"==a?(d.object=!1,d.axis=!1,d.mode=a,b.select(e),this.gizmo.translate.hide(),this.gizmo.rotate.hide(),this.gizmo.scale.hide(),d.dispatchEvent(m),this.update()):(d.mode="transform",A.call(this,a),this.object||b.select(e))}};
T.UniversalControls.prototype=Object.create(T.TransformControls.prototype);
