(function(){var f=function(e,a){return function(){return e.apply(a,arguments)}},g={}.hasOwnProperty,h=function(e,a){function b(){this.constructor=e}for(var c in a)g.call(a,c)&&(e[c]=a[c]);b.prototype=a.prototype;e.prototype=new b;e.__super__=a.prototype;return e},k=[].indexOf||function(e){for(var a=0,b=this.length;a<b;a++)if(a in this&&this[a]===e)return a;return-1};if("undefined"===typeof Backbone||null===Backbone)throw Error("Backbone is not defined. Please include the latest version from http://documentcloud.github.com/backbone/backbone.js");
Backbone.Modal=function(e){function a(){this.triggerCancel=f(this.triggerCancel,this);this.triggerSubmit=f(this.triggerSubmit,this);this.triggerView=f(this.triggerView,this);this.clickOutside=f(this.clickOutside,this);this.checkKey=f(this.checkKey,this);this.args=Array.prototype.slice.apply(arguments);Backbone.View.prototype.constructor.apply(this,this.args);this.setUIElements();this.delegateModalEvents()}h(a,e);a.prototype.prefix="bbm";a.prototype.render=function(b){var c,a=this;null==b&&(b={});
b=this.serializeData();this.$el.addClass(""+this.prefix+"-wrapper");this.modalEl=Backbone.$("<div />").addClass(""+this.prefix+"-modal");this.template&&this.modalEl.html(this.template(b));this.$el.html(this.modalEl);Backbone.$("body").on("keyup",this.checkKey);Backbone.$("body").on("click",this.clickOutside);this.viewContainer?(this.viewContainerEl=this.modalEl.find(this.viewContainer),this.viewContainerEl.addClass(""+this.prefix+"-modal__views")):this.viewContainerEl=this.modalEl;this.$el.show();
0<(null!=(c=this.views)?c.length:void 0)&&this.openAt(0);if("function"===typeof this.onRender)this.onRender();this.modalEl.css({opacity:0});this.$el.fadeIn({duration:100,complete:function(){return a.modalEl.css({opacity:1}).addClass(""+a.prefix+"-modal--open")}});return this};a.prototype.setUIElements=function(){var b;this.template=this.getOption("template");this.views=this.getOption("views");null!=(b=this.views)&&(b.length=_.size(this.views));this.viewContainer=this.getOption("viewContainer");this.$el.hide();
if(_.isUndefined(this.template)&&_.isUndefined(this.views))throw Error("No template or views defined for Backbone.Modal");if(this.template&&this.views&&_.isUndefined(this.viewContainer))throw Error("No viewContainer defined for Backbone.Modal");};a.prototype.getOption=function(b){if(b)return this.options&&0<=k.call(this.options,b)&&null!=this.options[b]?this.options[b]:this[b]};a.prototype.serializeData=function(){var b;b={};this.model&&(b=_.extend(b,this.model.toJSON()));this.collection&&(b=_.extend(b,
{items:this.collection.toJSON()}));return b};a.prototype.delegateModalEvents=function(){var b,c,a,d;this.active=!0;b=this.getOption("cancelEl");if(d=this.getOption("submitEl"))this.$el.on("click",d,this.triggerSubmit);if(b)this.$el.on("click",b,this.triggerCancel);d=[];for(c in this.views)"length"!==c?(a=c.match(/^(\S+)\s*(.*)$/),b=a[1],a=a[2],d.push(this.$el.on(b,a,this.views[c],this.triggerView))):d.push(void 0);return d};a.prototype.undelegateModalEvents=function(){var b,c,a,d;this.active=!1;b=
this.getOption("cancelEl");(d=this.getOption("submitEl"))&&this.$el.off("click",d,this.triggerSubmit);b&&this.$el.off("click",b,this.triggerCancel);d=[];for(c in this.views)"length"!==c?(a=c.match(/^(\S+)\s*(.*)$/),b=a[1],a=a[2],d.push(this.$el.off(b,a,this.views[c],this.triggerView))):d.push(void 0);return d};a.prototype.checkKey=function(b){if(this.active)switch(b.keyCode){case 27:return this.triggerCancel();case 13:return this.triggerSubmit()}};a.prototype.clickOutside=function(b){if(Backbone.$(b.target).hasClass(""+
this.prefix+"-wrapper")&&this.active)return this.triggerCancel(null,!0)};a.prototype.buildView=function(b){var c;if(b)return _.isFunction(b)?(c=new b(this.args[0]),c instanceof Backbone.View?{el:c.render().$el,view:c}:{el:b(this.args[0])}):{view:b,el:b.$el}};a.prototype.triggerView=function(b){var c,a,d;null!=b&&"function"===typeof b.preventDefault&&b.preventDefault();d=b.data;c=this.buildView(d.view);this.currentView&&(this.previousView=this.currentView);this.currentView=c.view||c.el;b=0;for(a in this.views)d.view===
this.views[a].view&&(this.currentIndex=b),b++;if(d.onActive)if(_.isFunction(d.onActive))d.onActive(this);else _.isString(d.onActive)&&this[d.onActive].call(this,d);if(this.shouldAnimate)return this.animateToView(c.el);this.shouldAnimate=!0;return this.$(this.viewContainerEl).html(c.el)};a.prototype.animateToView=function(b){var a,e,d,f=this;e={position:"relative",top:-9999,left:-9999};a=Backbone.$("<tester/>").css(e);a.html(this.$el.clone().css(e));0!==Backbone.$("tester").length?Backbone.$("tester").replaceWith(a):
Backbone.$("body").append(a);a=this.viewContainer?a.find(this.viewContainer):a.find("."+this.prefix+"-modal");a.removeAttr("style");e=a.outerHeight();a.html(b);a=a.outerHeight();if(e===a)return this.$(this.viewContainerEl).html(b),null!=(d=this.previousView)?"function"===typeof d.close?d.close():void 0:void 0;this.$(this.viewContainerEl).css({opacity:0});return this.$(this.viewContainerEl).animate({height:a},100,function(){var a;f.$(f.viewContainerEl).css({opacity:1}).removeAttr("style");f.$(f.viewContainerEl).html(b);
return null!=(a=f.previousView)?"function"===typeof a.close?a.close():void 0:void 0})};a.prototype.triggerSubmit=function(b){if(b&&(null!=b&&b.preventDefault(),!this.beforeSubmit||!1!==this.beforeSubmit()))return"function"===typeof this.submit&&this.submit(),this.regionEnabled?this.trigger("modal:close"):this.close()};a.prototype.triggerCancel=function(b){null!=b&&b.preventDefault();if(!this.beforeCancel||!1!==this.beforeCancel())return"function"===typeof this.cancel&&this.cancel(),this.regionEnabled?
this.trigger("modal:close"):this.close()};a.prototype.close=function(){var b=this;Backbone.$("body").off("keyup",this.checkKey);Backbone.$("body").off("click",this.clickOutside);if("function"===typeof this.onClose)this.onClose();this.shouldAnimate=!1;this.modalEl.addClass(""+this.prefix+"-modal--close");this.$el.fadeOut({duration:200});return _.delay(function(){var a;null!=(a=b.currentView)&&"function"===typeof a.remove&&a.remove();return b.remove()},200)};a.prototype.openAt=function(a){var c,e,d;
c=0;for(e in this.views)"length"!==e&&(c===a&&(d=this.views[e]),c++);d&&(this.currentIndex=a,this.triggerView({data:d}));return this};a.prototype.next=function(){if(this.currentIndex+1<this.views.length)return this.openAt(this.currentIndex+1)};a.prototype.previous=function(){if(this.currentIndex-1<this.views.length-1)return this.openAt(this.currentIndex-1)};return a}(Backbone.View)}).call(this);
