var idArray="z s x d c v g b h n j m comma l dot semicolon slash q two w three e four r t six y seven u i nine o zero p minus leftBrk oct1 oct2 oct3 oct4 click sustain save reset velDown velUp rndVel chord audioLoader helpBtn".split(" "),keyArray="90 83 88 68 67 86 71 66 72 78 74 77 188 76 190 186 191 81 50 87 51 69 52 82 84 54 89 55 85 73 57 79 48 80 189 219".split(" "),midiArray="0x18 0x19 0x1A 0x1B 0x1C 0x1D 0x1E 0x1F 0x20 0x21 0x22 0x23 0x24 0x25 0x26 0x27 0x28 0x29 0x2A 0x2B 0x2C 0x2D 0x2E 0x2F 0x30 0x31 0x32 0x33 0x34 0x35 0x36 0x37 0x38 0x39 0x3A 0x3B 0x3C 0x3D 0x3E 0x3F 0x40 0x41 0x42 0x43 0x44 0x45 0x46 0x47 0x48 0x49 0x4A 0x4B 0x4C 0x4D 0x4E 0x4F 0x50 0x51 0x52 0x53 0x54 0x55 0x56 0x57 0x58 0x59 0x5A 0x5B 0x5C 0x5D 0x5E 0x5F".split(" "),
noteArray="C1 Db1 D1 Eb1 E1 F1 Gb1 G1 Ab1 A1 Bb1 B1 C2 Db2 D2 Eb2 E2 F2 Gb2 G2 Ab2 A2 Bb2 B2 C3 Db3 D3 Eb3 E3 F3 Gb3 G3 Ab3 A3 Bb3 B3 C4 Db4 D4 Eb4 E4 F4 Gb4 G4 Ab4 A4 Bb4 B4 C5 Db5 D5 Eb5 E5 F5 Gb5 G5 Ab5 A5 Bb5 B5 C6 Db6 D6 Eb6 E6 F6 Gb6 G6 Ab6 A6 Bb6 B6".split(" "),sessionArray=[],monoArray=[],audioArray=[],volumeArray=[],notePressed=!1,ctx,previousTime,currentOctave,rndState=!1,sustainState,clickState=!1,t=[],middleC=$("#comma"),mouseState=0;
function hasClass(a,b){return-1<a.className.indexOf(b)}function removeClass(a,b){for(var c="",d=0,f=a.className.split(" ");d<f.length;d++)f[d]!==b&&(c+=f[d]+" ");a.className=c}
function helpTutorial(){var a=$("#generalHelp"),b=$("#octHelp"),c=$("#audioLoadHelp"),d=$("#midiDivHelp"),f=$("#velocityHelp"),m=$("#recordHelp"),q=$("#midiSaveHelp"),l=$("#susHelp"),h=$("#clickHelp"),g=$("#chorderHelp"),r=$("#chorderModuleHelp"),u=$("#chorderNoteHelp"),p=$("#chorderBypassHelp"),n=$("#chordsHelp");(function(){function k(e,v){$("#"+e).css("z-index",v)}function w(){b.modal();var e=$("#octaveDiv").position();b.css("top",e.top+30);k("octaveDiv",50);b.on($.modal.AFTER_CLOSE,function(){k("octaveDiv",
0);x()})}function x(){c.modal();var e=$("#audioLoaderDiv").position();c.css("top",e.top+30);k("audioLoaderDiv",50);c.on($.modal.AFTER_CLOSE,function(){k("audioLoaderDiv",0);y()})}function y(){d.modal();var e=$("#midiDiv").position();d.css("top",e.top+30);k("midiDiv",50);d.on($.modal.AFTER_CLOSE,function(){k("midiDiv",0);z()})}function z(){f.modal();var e=$("#vel").position();f.css("top",e.top+100);k("velTop",50);f.on($.modal.AFTER_CLOSE,function(){k("velTop",0);A()})}function A(){m.modal();var e=
$("#rec").position();m.css("top",e.top+100);m.css("left",e.left);k("recStreamBtn",50);k("rec",50);m.on($.modal.AFTER_CLOSE,function(){k("recStreamBtn",0);k("rec",0);B()})}function B(){q.modal();var e=$("#rec").position();q.css("top",e.top+100);q.css("left",e.left);k("save",50);q.on($.modal.AFTER_CLOSE,function(){k("save",0);C()})}function C(){l.modal();var e=$("#sustain").position();l.css("top",e.top+100);l.css("left",e.left-350);k("sustain",50);l.on($.modal.AFTER_CLOSE,function(){k("sustain",0);
D()})}function D(){h.modal();var e=$("#click").position();h.css("top",e.top+100);h.css("left",e.left-350);k("click",50);h.on($.modal.AFTER_CLOSE,function(){k("click",0);E()})}function E(){g.modal();var e=$("#chord").position();g.css("top",e.top+100);g.css("left",e.left-350);k("chord",50);g.on($.modal.AFTER_CLOSE,function(){k("chord",0);F()})}function F(){$("#topPanel").css("pointer-events","auto");chordHandler.toggleChordSelector();r.modal();var e=$("#chordSelector").position();r.css("top",e.top-
100);r.css("left",e.left);r.on($.modal.AFTER_CLOSE,function(){G()})}function G(){u.modal();var e=$("#chordButton").position();u.css("top",e.top-100);u.css("left",e.left);k("chordButton",50);u.on($.modal.AFTER_CLOSE,function(){k("chordButton",0);H()})}function H(){p.modal();var e=$("#chordButton").position();p.css("top",e.top-100);p.css("left",e.left);k("chordBypass",50);p.on($.modal.AFTER_CLOSE,function(){k("chordBypass",0);I()})}function I(){n.modal();var e=$("#chordButton").position();n.css("top",
e.top-100);n.css("left",e.left);k("chromatic",50);n.on($.modal.AFTER_CLOSE,function(){chordHandler.toggleChordSelector();k("chromatic",0);location.reload()})}$(".modal").on("click",function(){$.modal.close()});(function(){$("#topPanel").css("pointer-events","none");$("#bottomPanel").css("pointer-events","none");$(".modal").css("pointer-events","default");a.modal();a.on($.modal.AFTER_CLOSE,function(){w()})})()})()}
var eventHandler={sendEvent:function(a){var b=idArray.indexOf(a.id);if(-1<b&&36>b)notesHandler.runNote(b,a),chordHandler.checkForChord(b,a);else if("mouseenter"===a.type||"mousedown"===a.type||"keydown"===a.type||"touchstart"===a.type)35<b&&40>b?pitchHandler.changeOct(b-36):40===b?clickHandler.toggle():41===b?sustainHandler.toggle():42===b?midiHandler.exportMidi():43===b?location.reload():44===b?velocityHandler.velocityChangeHandler({type:a.type,val:-10}):45===b?velocityHandler.velocityChangeHandler({type:a.type,
val:10}):46===b?velocityHandler.toggleRnd():47===b?chordHandler.toggleChordSelector():48===b?audioLoader.createLoad():49===b&&helpTutorial()},catchEvent:function(a){var b={};b.type=a.type;if("mousedown"===b.type||"mouseover"===b.type||"mouseup"===b.type||"touchstart"===b.type||"touchend"===b.type)b.id=a.srcElement.id;else if("keyup"===b.type||"keydown"===b.type)b.id=idArray[keyArray.indexOf(String(a.keyCode))];"mouseover"===b.type?mouseState&&(b.type="mousedown",b.id=a.srcElement.id,36>idArray.indexOf(b.id)&&
eventHandler.sendEvent(b)):"mouseout"===b.type?mouseState&&(b.type="mouseup",b.id=a.srcElement.id,36>idArray.indexOf(b.id)&&eventHandler.sendEvent(b)):eventHandler.sendEvent(b)},setListeners:function(){for(var a="mouseup mousedown keyup keydown touchstart touchend mouseout mouseover".split(" "),b=document.querySelector("body"),c=0;c<a.length;c++)b.addEventListener(a[c],function(d){eventHandler.catchEvent(d)});Mousetrap.bind(["right"],function(){3!==currentOctave&&pitchHandler.changeOct(currentOctave+
1)});Mousetrap.bind(["left"],function(){0!==currentOctave&&pitchHandler.changeOct(currentOctave-1)});Mousetrap.bind(["up"],function(){velocityHandler.velocityChangeHandler({type:"mousedown",val:10})});Mousetrap.bind(["down"],function(){velocityHandler.velocityChangeHandler({type:"mousedown",val:-10})});Mousetrap.bind(["shift"],function(){sustainHandler.toggle()})}},notesHandler={sendNote:function(a){a.velocity=velocityHandler.setRandomVel(a.velocity,a.delta);0===a.velocity&&0===a.delta&&(a.delta=
8);sessionArray.push(a)},animateNote:function(a){a=document.querySelector("#"+a);hasClass(a,"active")?removeClass(a,"active"):a.className+=" active"},playAudio:function(a,b,c){c=noteArray[midiArray.indexOf(a)];velocityHandler.setVol(c);0!==Number(b)?(monoArray[midiArray.indexOf(a)]=new Howl({src:["audio/"+c+".mp3"],volume:volumeArray[c]}),monoArray[midiArray.indexOf(a)].play()):!0!==sustainState&&monoArray[midiArray.indexOf(a)].fade(volumeArray[c],0,200)},noteConstructor:function(a){0===sessionArray.length&&
(this.delta=this.channel=0,this.type=9,ctx=new AudioContext,document.querySelector("#save").style.opacity="1",document.querySelector("#reset").disabled=!1,$("#saveFa").css("color",""));this.pitch=pitchHandler.getPitch(a.id);this.velocity=velocityHandler.getVel(a.type);a=Math.floor((ctx.currentTime-(previousTime||0))/.00390625);previousTime=ctx.currentTime;this.delta=a;return this},runNote:function(a,b){var c=new notesHandler.noteConstructor(b);0!==c.velocity?!0!==audioArray[a]&&(notePressed=audioArray[a]=
!0,notesHandler.playAudio(c.pitch,c.velocity,a),notesHandler.animateNote(b.id),notesHandler.sendNote(c)):(notePressed=audioArray[a]=!1,notesHandler.playAudio(c.pitch,0,a),notesHandler.animateNote(b.id),notesHandler.sendNote(c),$("#"+b.id).removeClass("active"))}},pitchHandler={getPitch:function(a){a=Number(idArray.indexOf(a));0===currentOctave&&(a+=0);1===currentOctave&&(a+=12);2===currentOctave&&(a+=24);3===currentOctave&&(a+=36);return midiArray[a]},changeOct:function(a){var b=document.querySelector("#octaveDiv");
null!=middleC&&middleC.removeClass("middleC");0==a&&(middleC=null);1==a&&(middleC=$("#t"));2==a&&(middleC=$("#comma"));3==a&&(middleC=$("#z"));null!=middleC&&middleC.addClass("middleC");if(!1===notePressed)for(var c=0;c<b.children.length;c++){var d=document.querySelector("#octaveDiv").children[c];c===a?(currentOctave=c,d.setAttribute("class","selected oct")):d.setAttribute("class","oct")}}},velocityHandler={setVol:function(a){var b=document.querySelector("#velocityValue").innerHTML;1<=b&&20>=b?volumeArray[a]=
.2:21<=b&&40>=b?volumeArray[a]=.4:41<=b&&60>=b?volumeArray[a]=.6:61<=b&&80>=b?volumeArray[a]=.7:81<=b&&100>=b?volumeArray[a]=.8:101<=b&&120>=b?volumeArray[a]=.9:121<=b&&127>=b&&(volumeArray[a]=1)},setRandomVel:function(a){!0===rndState&&0!==a&&(a+=velocityHandler.getRandomModifier(),127<a&&(a=127));return a},velocityChangeHandler:function(a){var b=velocityHandler.getVel(a.type);-10===a.val?10!==b&&(127===b?velocityHandler.changeVel(-7):velocityHandler.changeVel(-10)):120!==b?127!==b&&velocityHandler.changeVel(10):
velocityHandler.changeVel(7)},changeVel:function(a){var b=document.querySelector("#velocityValue").innerHTML;a=Number(b)+a;document.querySelector("#velocityValue").innerHTML=a;localStorage.velocity=a},toggleRnd:function(){var a=document.querySelector("#rndVel");!1===rndState?(a.className="on",rndState=!0):(a.className="",rndState=!1)},getVel:function(a){var b=document.querySelector("#velocityValue").innerHTML;return"onmouseenter"===a||"mousedown"===a||"keydown"===a||"touchstart"===a?Number(b):0},
getRandomModifier:function(){return Math.floor(10*Math.random()*(.5>Math.random()?-1:1))}},chordHandler={init:function(){chordHandler.chordsInit();chordHandler.onbeforeunload();chordHandler.setListeners()},onbeforeunload:function(){window.onbeforeunload=function(){localStorage.width=window.outerWidth;localStorage.height=window.outerHeight;chordHandler.saveBypass()}},chordsInit:function(){chrome.storage.local.get("chords",function(a){jQuery.isEmptyObject(a)&&chordHandler.initChords();chordHandler.bypassInit();
chordHandler.notesInit()})},notesInit:function(){"allNotes"===localStorage.selectedNote||"undefined"===typeof localStorage.selectedNote?chordHandler.toggleAllNotes():chordHandler.toggleNote(localStorage.selectedNote)},bypassInit:function(){chrome.storage.local.get("bypass",function(a){jQuery.isEmptyObject(a)?chordHandler.toggleAllBypass():chordHandler.loadBypass(a)})},playChordNote:function(a,b,c){a=Number(a)+Number(c);b.id=idArray[Number(a)];47<a?3!==currentOctave&&(a-=48,b.id=idArray[a],c=new notesHandler.noteConstructor(b),
c.pitch=midiArray[Number(midiArray.indexOf(c.pitch)+48)],0!==c.velocity?(velocityHandler.setVol(a),notesHandler.playAudio(c.pitch,c.velocity,a),!0!==audioArray[a]&&(notePressed=audioArray[a]=!0,notesHandler.sendNote(c,b.id,a))):(audioArray[a]=!1,notePressed=audioArray[a]=!1,notesHandler.playAudio(c.pitch,c.velocity,a),notesHandler.sendNote(c,b.id,a))):notesHandler.runNote(a,b)},turnBtnOn:function(a){$("#"+a).addClass("selectedChordBtn")},turnBtnOff:function(a){$("#"+a).removeClass("selectedChordBtn")},
toggleAllNotes:function(){for(var a=$(".chordNote"),b=$(".chords"),c=0;c<a.length;c++)chordHandler.turnBtnOn(a[c].id);localStorage.selectedNote="allNotes";for(a=0;a<b.length;a++)chordHandler.turnBtnOff(b[a].id)},toggleAllBypass:function(){var a=$(".bypass"),b=$("#allBypass");!0===b.hasClass("selectedChordBtn")?(b.removeClass("selectedChordBtn"),b=!1):(b.addClass("selectedChordBtn"),b=!0);for(var c=1;c<a.length;c++)b?chordHandler.turnBtnOn(a[c].id):chordHandler.turnBtnOff(a[c].id)},noChords:function(){for(var a=
$(".chords"),b=1;b<a.length;b++){var c=a[b].id;chordHandler.turnBtnOff(c);chordHandler.saveToChordStorage(c,"chord chords")}},saveToChordStorage:function(a,b){var c=$("#"+localStorage.selectedNote).index(),d=$("#"+a).index(),f=$(".chordNote");if(0!==c)t[c][d]=b;else for(c=1;c<f.length;c++)t[c][d]=b;chrome.storage.local.set({chords:t})},toggleChord:function(a){var b="chord chords";$("#"+a).hasClass("selectedChordBtn")?chordHandler.turnBtnOff(a):(chordHandler.turnBtnOn(a),b="chord chords selectedChordBtn");
chordHandler.saveToChordStorage(a,b)},initChords:function(){for(var a=$(".chords"),b=$(".chordNote"),c=1;c<b.length;c++){t[c]=[];for(var d=1;d<a.length;d++)t[c][d]="chord chords"}},toggleBypass:function(a){$("#"+a).hasClass("selectedChordBtn")?chordHandler.turnBtnOff(a):chordHandler.turnBtnOn(a)},toggleNote:function(a){var b=$(".chordNote"),c=$("#allNotes");!0===c.hasClass("selectedChordBtn")&&c.removeClass("selectedChordBtn");for(c=1;c<b.length;c++)a!==b[c].id?chordHandler.turnBtnOff(b[c].id):chordHandler.turnBtnOn(a);
localStorage.selectedNote=a;b=$("#"+localStorage.selectedNote).index();a=$(".chords");b=t[b];for(c=1;c<b.length;c++)a[c].className=b[c]},clicked:function(a,b){"allNotes"===a?chordHandler.toggleAllNotes():"noChord"===a?chordHandler.noChords():"allBypass"===a?chordHandler.toggleAllBypass():!0===-1<b.indexOf("chords")?chordHandler.toggleChord(a):!0===-1<b.indexOf("chordNote")?chordHandler.toggleNote(a):!0===-1<b.indexOf("bypass")&&chordHandler.toggleBypass(a)},setListeners:function(){for(var a=$(".chord"),
b=0;b<a.length;b++)$(a[b]).on("click",function(c){chordHandler.clicked(c.target.id,c.target.className)})},loadBypass:function(a){for(var b=$(".bypass"),c=0;c<b.length;c++)b[c].className=a.bypass[c]},saveBypass:function(){for(var a=$(".bypass"),b=[],c=0;c<a.length;c++)b[c]=a[c].className;chrome.storage.local.set({bypass:b})},checkForChord:function(a,b){var c=a%12,d=$(".bypass")[c+1];c=t[c+1];var f=1;if(0<c.length)for(;f<c.length;f++)"chord chords selectedChordBtn"===c[f]&&"chord bypass selectedChordBtn"===
d.className&&(b.id=idArray[a+f],chordHandler.playChordNote(a,b,f))},toggleChordSelector:function(){var a=document.querySelector("#chordSelector"),b=document.querySelector("#kbd"),c=document.querySelector("#chord");"none"===a.style.display?(a.style.display="flex",b.style.display="none",c.className+=" on"):(a.style.display="none",b.style.display="flex",removeClass(c,"on"))}},clickHandler={init:function(){Fifer.loaded(function(a){}).registerAudio("click","/audio/click.mp3",!1)},play:function(){Fifer.play("click",
!0)},stop:function(){Fifer.stop("click")},toggle:function(){var a=document.querySelector("#click");!1===clickState?(a.className+=" on",clickHandler.play(),clickState=!0):(removeClass(a,"on"),clickHandler.stop(),clickState=!1)}},sustainHandler={toggle:function(){var a=document.querySelector("#sustain");!0!==sustainState?(sustainState=!0,a.className+=" on",localStorage.sustain=!0):(sustainState=!1,removeClass(a,"on"),localStorage.sustain=!1)}},audioLoader={init:function(){$("#KBD_Piano_audioFile").on("change",
function(a){var b=$("#KBD_Piano_audioControls");b.css("display","flex");a=a.currentTarget;var c=a.files[0],d=new FileReader;a.files&&c&&(d=new FileReader,d.onload=function(f){b.attr("src",f.target.result);b.play},d.readAsDataURL(c))})},createLoad:function(){$("#KBD_Piano_audioFile").click()}},midiHandler={init:function(){function a(c){function d(){var l=[],h=c.inputs.values(),g=h.next(),r=0;for(m.empty();g&&!g.done;g=h.next())l.push(g.value),m.append("<option id='"+g.value.id+"' + class='midiDevice'>"+
g.value.name+"</option>");h=m[0].length;if(0===h)q.css("display","none");else for(q.css("display","flex");r<h;r++)m[0][r].id===localStorage.midiPort&&(localStorage.midiPortName=m[0][r].value,$("#"+localStorage.midiPort).prop("selected",!0),l[r].onmidimessage=f)}function f(l){var h=l.data[0],g=l.data[1];var r=(128===h||144===h)&&l.target.name===localStorage.midiPortName&&23<g&&96>g?!0:void 0;r&&(g="0x"+g.toString(16),isNaN(g[3])&&(g=g[0]+g[1]+g[2]+g[3].toUpperCase()),function(u){var p={pitch:u},n=
midiArray.indexOf(u);u=noteArray[n];0===sessionArray.length?(p.channel=0,p.delta=0,p.type=9,ctx=new AudioContext,document.querySelector("#save").style.opacity="1",document.querySelector("#reset").disabled=!1,$("#saveFa").css("color","")):p.delta=Math.floor((ctx.currentTime-(previousTime||0))/.00390625);previousTime=ctx.currentTime;144===h?p.velocity=l.data[2]:128===h&&(p.velocity=0);0!==p.velocity?(audioArray[n]=new Howl({src:["audio/"+u+".mp3"],volume:p.velocity/100}),audioArray[n].play()):!0!==
sustainState&&audioArray[n].fade(audioArray[n]._volume,0,200);notesHandler.animateNote(function(){if(36>n)return pitchHandler.changeOct(0),idArray[n];if(48>n)return pitchHandler.changeOct(1),idArray[n-12];if(60>n)return pitchHandler.changeOct(2),idArray[n-24];if(72>n)return pitchHandler.changeOct(3),idArray[n-36]}());sessionArray.push(p);chordHandler.checkForChord(n,{id:idArray[n],type:0!==p.velocity?"keydown":"keyup"})}(g))}isNaN(Number(localStorage.midiPort))&&(localStorage.midiPort=0);var m=$("#midiDevices"),
q=$("#midiDiv");c.onstatechange=function(l){d()};m.change(function(){var l=$("select option:selected");localStorage.midiPort=l[0].id;d()});d()}function b(c){console.log(c)}navigator.requestMIDIAccess&&navigator.requestMIDIAccess().then(a,b)},exportMidi:function(){if(1<sessionArray.length){var a=[];sessionArray.forEach(function(c){Array.prototype.push.apply(a,MidiEvent.createNote(c))});var b=new MidiTrack({events:a});MidiWriter({tracks:[b]}).save()}}},recordHandler={recordStreamHandler:function(){function a(){var f=
window.Howler.ctx.createMediaStreamDestination();Howler.masterGain.connect(f);f=c.createMediaStreamSource(f.stream);b=new WebAudioRecorder(f,{workerDir:"../js/"});b.onComplete=function(m,q){var l=window.URL.createObjectURL(q),h=document.createElement("a");h.href=l;h.download="KBD2MIDI_PIANO_"+(new Date).toGMTString()+".wav";h.click()};b.setEncoding("wav");b.startRecording();d.className+=" on"}var b,c=new AudioContext,d=document.querySelector("#recStreamBtn");d.addEventListener("click",function(){hasClass(d,
"on")?(removeClass(d,"on"),b.finishRecording()):(d.className+=" on",a())})},recordMicHandler:function(){function a(){var f=navigator.mediaDevices.getUserMedia({audio:!0});f.then(function(m){m=b.createMediaStreamSource(m);c=new WebAudioRecorder(m,{workerDir:"../js/"});c.onComplete=function(q,l){var h=window.URL.createObjectURL(l),g=document.createElement("a");g.href=h;g.download="KBD2MIDI_PIANO_"+(new Date).toGMTString()+".wav";g.click()};c.setEncoding("wav");c.startRecording();d.className+=" on"});
f["catch"](function(m){console.log("audioStream error:",m.name)})}var b=new AudioContext,c,d=document.querySelector("#rec");d.addEventListener("click",function(){hasClass(d,"on")?(removeClass(d,"on"),c.finishRecording()):(d.className+=" on",a())})},init:function(){recordHandler.recordMicHandler();recordHandler.recordStreamHandler()}};
(function(){var a=document.querySelector("#loadingBar"),b=document.querySelector("#pianoWrapper"),c=document.querySelector("#loadingCont"),d=document.querySelector("#loading"),f=1;(function(){document.body.onmousedown=function(){mouseState=1};document.body.onmouseup=function(){mouseState=0};$("html").mouseleave(function(){mouseState=0})})();(function(){for(var l=document.querySelectorAll(".white"),h=0;h<l.length;++h)l[h].style.zIndex=l.length-h})();(function(){window.onbeforeunload=function(){localStorage.width=
window.outerWidth;localStorage.height=window.outerHeight;localStorage.selectedOct=currentOctave}})();var m=0,q=noteArray.length;$("#version").html(chrome.runtime.getManifest().version);pitchHandler.changeOct(Number(localStorage.selectedOct||2));midiHandler.init();chordHandler.init();audioLoader.init();clickHandler.init();recordHandler.init();eventHandler.setListeners();"true"===localStorage.sustain&&sustainHandler.toggle();"undefined"!==typeof localStorage.velocity&&(document.querySelector("#velocityValue").innerHTML=
localStorage.velocity);for(;m<q;m++)new Howl({src:["audio/"+noteArray[m]+".mp3"],html5:!1,volume:0,onload:function(){this.play();f+=1;d.innerHTML="Loading "+f+"/72";a.style.backgroundSize=Math.ceil(100*f/72)+"% 100%";f===q&&(c.style.display="none",b.style.display="flex")}})})();