var Parser=function(){function c(d,c,g,e,q,r){this.message=d;this.expected=c;this.found=g;this.offset=e;this.line=q;this.column=r;this.name="SyntaxError"}(function(d,c){function g(){this.constructor=d}g.prototype=c.prototype;d.prototype=new g})(c,Error);return{SyntaxError:c,parse:function(d){function n(a){if(O!==a){O>a&&(O=0,fa={line:1,column:1,seenCR:!1});var b=fa,g,k;for(g=O;g<a;g++)k=d.charAt(g),"\n"===k?(b.seenCR||b.line++,b.column=1,b.seenCR=!1):"\r"===k||"\u2028"===k||"\u2029"===k?(b.line++,
b.column=1,b.seenCR=!0):(b.column++,b.seenCR=!1);O=a}return fa}function g(b){a<V||(a>V&&(V=a,ga=[]),ga.push(b))}function e(){var d,g,h;d=a;g=r();g!==b?(h=x(),h!==b?d=g=[g,h]:(a=d,d=k)):(a=d,d=k);return d}function q(){var v,C,h,c,l,f,e,p;v=a;C=x();if(C!==b){h=a;c=[];l=z();if(l!==b)for(;l!==b;)c.push(l),l=z();else c=k;if(c!==b){l=a;f=t();if(f!==b){e=[];p=z();if(p!==b)for(;p!==b;)e.push(p),p=z();else e=k;e!==b?l=f=[f,e]:(a=l,l=k)}else a=l,l=k;l===b&&(l=I);l!==b?h=c=[c,l]:(a=h,h=k)}else a=h,h=k;if(h===
b)if(h=a,c=t(),c!==b){l=[];f=z();if(f!==b)for(;f!==b;)l.push(f),f=z();else l=k;l!==b?h=c=[c,l]:(a=h,h=k)}else a=h,h=k;h!==b&&(h="number");if(h===b){h=a;34===d.charCodeAt(a)?(c=ha,a++):(c=b,0===m&&g(ia));if(c!==b){c=[];ja.test(d.charAt(a))?(l=d.charAt(a),a++):(l=b,0===m&&g(ka));for(;l!==b;)c.push(l),ja.test(d.charAt(a))?(l=d.charAt(a),a++):(l=b,0===m&&g(ka));c!==b?(34===d.charCodeAt(a)?(l=ha,a++):(l=b,0===m&&g(ia)),l!==b?h="str":(a=h,h=k)):(a=h,h=k)}else a=h,h=k;if(h===b){h=a;39===d.charCodeAt(a)?
(c=la,a++):(c=b,0===m&&g(ma));if(c!==b){c=[];na.test(d.charAt(a))?(l=d.charAt(a),a++):(l=b,0===m&&g(oa));for(;l!==b;)c.push(l),na.test(d.charAt(a))?(l=d.charAt(a),a++):(l=b,0===m&&g(oa));c!==b?(39===d.charCodeAt(a)?(l=la,a++):(l=b,0===m&&g(ma)),l!==b?h="str":(a=h,h=k)):(a=h,h=k)}else a=h,h=k;h===b&&(h=pa())}}if(h===b){h=[];qa.test(d.charAt(a))?(c=d.charAt(a),a++):(c=b,0===m&&g(ra));if(c!==b)for(;c!==b;)h.push(c),qa.test(d.charAt(a))?(c=d.charAt(a),a++):(c=b,0===m&&g(ra));else h=k;h!==b&&(h="name");
h===b&&(c=h=a,l=x(),l!==b?(45===d.charCodeAt(a)?(f=sa,a++):(f=b,0===m&&g(ta)),f===b&&(43===d.charCodeAt(a)?(f=ua,a++):(f=b,0===m&&g(va)),f===b&&(126===d.charCodeAt(a)?(f=Pa,a++):(f=b,0===m&&g(Qa)),f===b&&(f=wa()))),f!==b?c=l=[l,f]:(a=c,c=k)):(a=c,c=k),c!==b?(l=r(),l!==b?h=c=[c,l]:(a=h,h=k)):(a=h,h=k),h===b&&(h=a,c=x(),c!==b?(l=E(),l!==b?(f=r(),f!==b?(e=x(),e!==b?(p=P(),p!==b?h=c=[c,l,f,e,p]:(a=h,h=k)):(a=h,h=k)):(a=h,h=k)):(a=h,h=k)):(a=h,h=k)))}h!==b?v=C=[C,h]:(a=v,v=k)}else a=v,v=k;return v}function r(){var v,
C,h,c,l,f,e,p,n,B,w,F,t;v=a;C=x();if(C!==b){h=a;c=q();c!==b?(l=a,f=x(),f!==b?(d.substr(a,2)===xa?(f=xa,a+=2):(f=b,0===m&&g(Ra)),f===b&&(42===d.charCodeAt(a)?(f=Sa,a++):(f=b,0===m&&g(Ta)),f===b&&(47===d.charCodeAt(a)?(f=Ua,a++):(f=b,0===m&&g(Va)),f===b&&(37===d.charCodeAt(a)?(f=Wa,a++):(f=b,0===m&&g(Xa)),f===b&&(43===d.charCodeAt(a)?(f=ua,a++):(f=b,0===m&&g(va)),f===b&&(45===d.charCodeAt(a)?(f=sa,a++):(f=b,0===m&&g(ta)),f===b&&(d.substr(a,2)===ya?(f=ya,a+=2):(f=b,0===m&&g(Ya)),f===b&&(d.substr(a,2)===
za?(f=za,a+=2):(f=b,0===m&&g(Za)),f===b&&(38===d.charCodeAt(a)?(f=$a,a++):(f=b,0===m&&g(ab)),f===b&&(124===d.charCodeAt(a)?(f=bb,a++):(f=b,0===m&&g(cb)),f===b&&(d.substr(a,2)===Aa?(f=Aa,a+=2):(f=b,0===m&&g(eb)),f===b&&(d.substr(a,2)===Ba?(f=Ba,a+=2):(f=b,0===m&&g(fb)),f===b&&(60===d.charCodeAt(a)?(f=gb,a++):(f=b,0===m&&g(hb)),f===b&&(62===d.charCodeAt(a)?(f=ib,a++):(f=b,0===m&&g(jb)),f===b&&(61===d.charCodeAt(a)?(f=kb,a++):(f=b,0===m&&g(lb)),f===b&&(d.substr(a,2)===Ca?(f=Ca,a+=2):(f=b,0===m&&g(mb)),
f===b&&(d.substr(a,2)===Da?(f=Da,a+=2):(f=b,0===m&&g(nb)),f===b&&(d.substr(a,2)===Ea?(f=Ea,a+=2):(f=b,0===m&&g(ob)),f===b&&(f=a,e=A(),e!==b?(p=J(),p===b&&(p=I),p!==b?f=e=[e,p]:(a=f,f=k)):(a=f,f=k),f===b&&(f=W(),f===b&&(f=D(),f===b&&(f=K(),f===b&&(f=y(),f===b&&(f=L(),f===b&&(f=a,X.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(Y)),e!==b?(Fa.test(d.charAt(a))?(p=d.charAt(a),a++):(p=b,0===m&&g(Ga)),p!==b?f=e=[e,p]:(a=f,f=k)):(a=f,f=k))))))))))))))))))))))))),f!==b?l="op":(a=l,l=k)):(a=l,l=k),l!==
b?(f=r(),f!==b?h=c=[c,l,f]:(a=h,h=k)):(a=h,h=k)):(a=h,h=k);if(h===b&&(h=a,c=q(),c!==b?(l=J(),l===b&&(l=I),l!==b?(f=u(),f!==b?(e=D(),e===b&&(e=y(),e===b&&(e=K())),e!==b?(p=r(),p!==b?h=c=[c,l,f,e,p]:(a=h,h=k)):(a=h,h=k)):(a=h,h=k)):(a=h,h=k)):(a=h,h=k),h===b&&(h=a,c=q(),c!==b?(l=a,f=u(),f!==b?(Z.test(d.charAt(a))?(f=d.charAt(a),a++):(f=b,0===m&&g(aa)),f!==b?(Ha.test(d.charAt(a))?(f=d.charAt(a),a++):(f=b,0===m&&g(Ia)),f!==b?(G.test(d.charAt(a))?(f=d.charAt(a),a++):(f=b,0===m&&g(H)),f!==b?(X.test(d.charAt(a))?
(f=d.charAt(a),a++):(f=b,0===m&&g(Y)),f!==b?(Q.test(d.charAt(a))?(f=d.charAt(a),a++):(f=b,0===m&&g(R)),f!==b?l=0:(a=l,l=k)):(a=l,l=k)):(a=l,l=k)):(a=l,l=k)):(a=l,l=k)):(a=l,l=k),l===b&&(l=a,f=u(),f!==b?(G.test(d.charAt(a))?(f=d.charAt(a),a++):(f=b,0===m&&g(H)),f!==b?(X.test(d.charAt(a))?(f=d.charAt(a),a++):(f=b,0===m&&g(Y)),f!==b?(Q.test(d.charAt(a))?(f=d.charAt(a),a++):(f=b,0===m&&g(R)),f!==b?(G.test(d.charAt(a))?(f=d.charAt(a),a++):(f=b,0===m&&g(H)),f!==b?(Ja.test(d.charAt(a))?(f=d.charAt(a),a++):
(f=b,0===m&&g(Ka)),f!==b?(S.test(d.charAt(a))?(f=d.charAt(a),a++):(f=b,0===m&&g(T)),f!==b?(S.test(d.charAt(a))?(f=d.charAt(a),a++):(f=b,0===m&&g(T)),f!==b?l=1:(a=l,l=k)):(a=l,l=k)):(a=l,l=k)):(a=l,l=k)):(a=l,l=k)):(a=l,l=k)):(a=l,l=k)):(a=l,l=k),l===b&&(l=a,f=J(),f!==b?(e=pa(),e!==b?l=f=[f,e]:(a=l,l=k)):(a=l,l=k))),l!==b?h=c=[c,l]:(a=h,h=k)):(a=h,h=k),h===b&&(h=a,c=q(),c!==b?(l=u(),l!==b?(f=A(),f!==b?(e=J(),e===b&&(e=I),e!==b?(p=r(),p!==b?h=c=[c,l,f,e,p]:(a=h,h=k)):(a=h,h=k)):(a=h,h=k)):(a=h,h=k)):
(a=h,h=k),h===b&&(h=a,c=q(),c!==b?(l=J(),l===b&&(l=I),l!==b?(f=a,e=u(),e!==b?(pb.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(qb)),e!==b?(M.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(N)),e!==b?(Q.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(R)),e!==b?(rb.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(sb)),e!==b?(M.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(N)),e!==b?(M.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(N)),e!==b?(G.test(d.charAt(a))?(e=d.charAt(a),
a++):(e=b,0===m&&g(H)),e!==b?f=0:(a=f,f=k)):(a=f,f=k)):(a=f,f=k)):(a=f,f=k)):(a=f,f=k)):(a=f,f=k)):(a=f,f=k)):(a=f,f=k),f!==b?(e=r(),e!==b?(p=u(),p!==b?(n=L(),n!==b?(B=r(),B!==b?h=c=[c,l,f,e,p,n,B]:(a=h,h=k)):(a=h,h=k)):(a=h,h=k)):(a=h,h=k)):(a=h,h=k)):(a=h,h=k)):(a=h,h=k),h===b))))){h=a;c=q();if(c!==b)if(l=J(),l===b&&(l=I),l!==b)if(f=u(),f!==b)if(e=W(),e!==b){p=a;n=E();if(n!==b){B=[];w=a;F=r();F!==b?(t=U(),t!==b?w=F=[F,t]:(a=w,w=k)):(a=w,w=k);if(w!==b)for(;w!==b;)B.push(w),w=a,F=r(),F!==b?(t=U(),
t!==b?w=F=[F,t]:(a=w,w=k)):(a=w,w=k);else B=k;B===b&&(B=I);B!==b?(w=P(),w!==b?p=n=[n,B,w]:(a=p,p=k)):(a=p,p=k)}else a=p,p=k;p!==b?h=c=[c,l,f,e,p]:(a=h,h=k)}else a=h,h=k;else a=h,h=k;else a=h,h=k;else a=h,h=k;h===b&&(h=q())}h!==b?v=C=[C,h]:(a=v,v=k)}else a=v,v=k;return v}function x(){var v,c;v=[];ba.test(d.charAt(a))?(c=d.charAt(a),a++):(c=b,0===m&&g(ca));for(;c!==b;)v.push(c),ba.test(d.charAt(a))?(c=d.charAt(a),a++):(c=b,0===m&&g(ca));return v}function u(){var c,e;c=[];ba.test(d.charAt(a))?(e=d.charAt(a),
a++):(e=b,0===m&&g(ca));if(e!==b)for(;e!==b;)c.push(e),ba.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(ca));else c=k;return c}function z(){var c;tb.test(d.charAt(a))?(c=d.charAt(a),a++):(c=b,0===m&&g(ub));return c}function t(){var c;46===d.charCodeAt(a)?(c=vb,a++):(c=b,0===m&&g(wb));return c}function U(){var c;44===d.charCodeAt(a)?(c=xb,a++):(c=b,0===m&&g(yb));return c}function E(){var c;40===d.charCodeAt(a)?(c=zb,a++):(c=b,0===m&&g(Ab));return c}function P(){var c;41===d.charCodeAt(a)?(c=
Bb,a++):(c=b,0===m&&g(Cb));return c}function L(){var c,e;c=a;La.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(Ma));e!==b?(G.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(H)),e!==b?(Db.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(Eb)),e!==b?c=0:(a=c,c=k)):(a=c,c=k)):(a=c,c=k);return c}function A(){var c,e;c=a;Z.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(aa));e!==b?(Ha.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(Ia)),e!==b?c=3:(a=c,c=k)):(a=c,c=k);return c}function y(){var c,
e;c=a;Fa.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(Ga));e!==b?(M.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(N)),e!==b?(Fb.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(Gb)),e!==b?(M.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(N)),e!==b?(Hb.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(Ib)),e!==b?(Jb.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(Kb)),e!==b?c=0:(a=c,c=k)):(a=c,c=k)):(a=c,c=k)):(a=c,c=k)):(a=c,c=k)):(a=c,c=k);return c}function D(){var c,e;
c=a;S.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(T));e!==b?(Z.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(aa)),e!==b?(Lb.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(Mb)),e!==b?(M.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(N)),e!==b?c=0:(a=c,c=k)):(a=c,c=k)):(a=c,c=k)):(a=c,c=k);return c}function K(){var c,e;c=a;Nb.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(Ob));e!==b?(La.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(Ma)),e!==b?(Q.test(d.charAt(a))?
(e=d.charAt(a),a++):(e=b,0===m&&g(R)),e!==b?(Pb.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(Qb)),e!==b?(Rb.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(Sb)),e!==b?c=0:(a=c,c=k)):(a=c,c=k)):(a=c,c=k)):(a=c,c=k)):(a=c,c=k);return c}function W(){var c,e;c=a;Z.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(aa));e!==b?(G.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(H)),e!==b?c=3:(a=c,c=k)):(a=c,c=k);return c}function wa(){var c,e;c=a;G.test(d.charAt(a))?(e=d.charAt(a),a++):(e=
b,0===m&&g(H));e!==b?(X.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(Y)),e!==b?(Q.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(R)),e!==b?c=0:(a=c,c=k)):(a=c,c=k)):(a=c,c=k);return c}function J(){var c,d;c=a;d=u();d!==b?(d=wa(),d!==b?c=0:(a=c,c=k)):(a=c,c=k);return c}function pa(){var c,e;c=a;e=u();e!==b?(G.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(H)),e!==b?(Ja.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(Ka)),e!==b?(S.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===
m&&g(T)),e!==b?(S.test(d.charAt(a))?(e=d.charAt(a),a++):(e=b,0===m&&g(T)),e!==b?c=2:(a=c,c=k)):(a=c,c=k)):(a=c,c=k)):(a=c,c=k)):(a=c,c=k);return c}var da=1<arguments.length?arguments[1]:{},b={},Na={start:e},Oa=e,k=b,I=null,ba=/^[ \t\n\r]/,ca={type:"class",value:"[ \\t\\n\\r]",description:"[ \\t\\n\\r]"},sa="-",ta={type:"literal",value:"-",description:'"-"'},ua="+",va={type:"literal",value:"+",description:'"+"'},Pa="~",Qa={type:"literal",value:"~",description:'"~"'},xa="||",Ra={type:"literal",value:"||",
description:'"||"'},Sa="*",Ta={type:"literal",value:"*",description:'"*"'},Ua="/",Va={type:"literal",value:"/",description:'"/"'},Wa="%",Xa={type:"literal",value:"%",description:'"%"'},ya="<<",Ya={type:"literal",value:"<<",description:'"<<"'},za=">>",Za={type:"literal",value:">>",description:'">>"'},$a="&",ab={type:"literal",value:"&",description:'"&"'},bb="|",cb={type:"literal",value:"|",description:'"|"'},Aa="<=",eb={type:"literal",value:"<=",description:'"<="'},Ba=">=",fb={type:"literal",value:">=",
description:'">="'},gb="<",hb={type:"literal",value:"<",description:'"<"'},ib=">",jb={type:"literal",value:">",description:'">"'},kb="=",lb={type:"literal",value:"=",description:'"="'},Ca="==",mb={type:"literal",value:"==",description:'"=="'},Da="!=",nb={type:"literal",value:"!=",description:'"!="'},Ea="<>",ob={type:"literal",value:"<>",description:'"<>"'},X=/^[oO]/,Y={type:"class",value:"[oO]",description:"[oO]"},Fa=/^[rR]/,Ga={type:"class",value:"[rR]",description:"[rR]"},tb=/^[0-9]/,ub={type:"class",
value:"[0-9]",description:"[0-9]"},qa=/^[A-Za-z0-9_]/,ra={type:"class",value:"[A-Za-z0-9_]",description:"[A-Za-z0-9_]"},vb=".",wb={type:"literal",value:".",description:'"."'},xb=",",yb={type:"literal",value:",",description:'","'},zb="(",Ab={type:"literal",value:"(",description:'"("'},Bb=")",Cb={type:"literal",value:")",description:'")"'},ha='"',ia={type:"literal",value:'"',description:'"\\""'},ja=/^[^"]/,ka={type:"class",value:'[^"]',description:'[^"]'},la="'",ma={type:"literal",value:"'",description:'"\'"'},
na=/^[^']/,oa={type:"class",value:"[^']",description:"[^']"},La=/^[aA]/,Ma={type:"class",value:"[aA]",description:"[aA]"},G=/^[nN]/,H={type:"class",value:"[nN]",description:"[nN]"},Db=/^[dD]/,Eb={type:"class",value:"[dD]",description:"[dD]"},Z=/^[iI]/,aa={type:"class",value:"[iI]",description:"[iI]"},Ha=/^[sS]/,Ia={type:"class",value:"[sS]",description:"[sS]"},M=/^[eE]/,N={type:"class",value:"[eE]",description:"[eE]"},Fb=/^[gG]/,Gb={type:"class",value:"[gG]",description:"[gG]"},Hb=/^[xX]/,Ib={type:"class",
value:"[xX]",description:"[xX]"},Jb=/^[pX]/,Kb={type:"class",value:"[pX]",description:"[pX]"},S=/^[lL]/,T={type:"class",value:"[lL]",description:"[lL]"},Lb=/^[kK]/,Mb={type:"class",value:"[kK]",description:"[kK]"},Nb=/^[mM]/,Ob={type:"class",value:"[mM]",description:"[mM]"},Q=/^[tT]/,R={type:"class",value:"[tT]",description:"[tT]"},Pb=/^[cC]/,Qb={type:"class",value:"[cC]",description:"[cC]"},Rb=/^[hH]/,Sb={type:"class",value:"[hH]",description:"[hH]"},Ja=/^[uU]/,Ka={type:"class",value:"[uU]",description:"[uU]"},
pb=/^[bB]/,qb={type:"class",value:"[bB]",description:"[bB]"},rb=/^[wW]/,sb={type:"class",value:"[wW]",description:"[wW]"},a=0,O=0,fa={line:1,column:1,seenCR:!1},V=0,ga=[],m=0,ea;if("startRule"in da){if(!(da.startRule in Na))throw Error("Can't start parsing from rule \""+da.startRule+'".');Oa=Na[da.startRule]}ea=Oa();if(ea!==b&&a===d.length)return ea;ea!==b&&a<d.length&&g({type:"end",description:"end of input"});throw function(a,b,e){function g(a){var b=1;for(a.sort(function(a,b){return a.description<
b.description?-1:a.description>b.description?1:0});b<a.length;)a[b-1]===a[b]?a.splice(b,1):b++}function k(a,b){function c(a){function b(a){return a.charCodeAt(0).toString(16).toUpperCase()}return a.replace(/\\/g,"\\\\").replace(/"/g,'\\"').replace(/\x08/g,"\\b").replace(/\t/g,"\\t").replace(/\n/g,"\\n").replace(/\f/g,"\\f").replace(/\r/g,"\\r").replace(/[\x00-\x07\x0B\x0E\x0F]/g,function(a){return"\\x0"+b(a)}).replace(/[\x10-\x1F\x80-\xFF]/g,function(a){return"\\x"+b(a)}).replace(/[\u0180-\u0FFF]/g,
function(a){return"\\u0"+b(a)}).replace(/[\u1080-\uFFFF]/g,function(a){return"\\u"+b(a)})}var d=Array(a.length),e;for(e=0;e<a.length;e++)d[e]=a[e].description;d=1<a.length?d.slice(0,-1).join(", ")+" or "+d[a.length-1]:d[0];e=b?'"'+c(b)+'"':"end of input";return"Expected "+d+" but "+e+" found."}var f=n(e),m=e<d.length?d.charAt(e):null;null!==b&&g(b);return new c(null!==a?a:k(b,m),b,m,e,f.line,f.column)}(null,ga,V);}}}(),importSql=function(){var c=function(c){return" "===c||"\t"===c||"\n"===c||"\v"===
c||"\f"===c||"\r"===c},d=function(d){for(var e=0;e<d.length;e++)if(!c(d[e]))if("/"==d[e]&&"*"==d[e+1]){for(e+=2;e<d.length&&("*"!=d[e]||"/"!=d[e+1]);)e++;if(e==d.length)return!1;e++}else if("-"==d[e]&&"-"==d[e+1]){for(e+=2;e<d.length&&"\n"!=d[e];)e++;if(e==d.length)break}else return!1;return!0},n=0;return function(g){n=0;var e=(new FileReaderSync).readAsText(g.file);g.transaction&&db.exec("BEGIN TRANSACTION");var q;try{for(var r={id:g.id,partialResponse:!0},x=e.split("\n"),u=e="",z,t=0,U=0,E=0,P=
(new Date).getTime(),L;E<x.length;)if(e=x[E],L=(new Date).getTime(),100<=L-P&&(r.progress=E/x.length,postMessage(r),P=L),E++,0!=t||!d(e)){for(var A=e,y=0;c(A[y]);)y++;(y<A.length&&"/"==A[y]&&d(A.substr(y+1))||y<A.length&&"g"==A[y].toLowerCase()&&"o"==A[y+1].toLowerCase()&&d(A.substr(y+2)))&&(u?SQL.isComplete(u+";"):1)&&(e=";");z=e.length;U=t;if(0==t){var D;for(D=0;D<z&&c(e[D]);D++);u=e.substr(D);n=E;t=z-D}else u=u+"\n"+e,t=t+1+z;var K;if(K=0<t)K=-1<u.substring(U).indexOf(";");K&&SQL.isComplete(u)?
(db.exec(u),t=0):0<t&&d(u)&&(t=0)}if(0<t&&!d(u))throw{message:"Incomplete SQL: "+u};q={done:!0};g.transaction&&db.exec("COMMIT TRANSACTION")}catch(W){g.transaction&&db.exec("ROLLBACK TRANSACTION"),q={error:W.message,line:n}}return q}}(),parseMimeType=function(){var c={},d=function(d,g){for(var e=c,q=0;q<g.length;q++)e[g[q]]||(e[g[q]]={}),e=e[g[q]];e.type=d};d("mp4",[0,0,0,"skip",102,116,121,112]);d("mp4",[51,103,112,53]);d("gif",[71,73,70,56,55,97]);d("gif",[71,73,70,56,57,97]);d("jpg",[255,216,255,
224]);d("jpg",[255,216,255,225]);d("jpg",[255,216,255,226]);d("jpg",[255,216,255,227]);d("jpg",[255,216,255,232]);d("zip",[80,75,3,4]);d("zip",[80,75,5,6]);d("zip",[80,75,7,8]);d("rar",[82,97,114,33,26,7,0]);d("rar",[82,97,114,33,26,7,1,0]);d("png",[137,80,78,71,13,10,26,10]);d("pdf",[37,80,68,70]);d("ogg",[79,103,103,83]);d("psd",[56,66,80,83]);d("mp3",[255,251]);d("mp3",[73,68,51]);d("bmp",[66,77]);d("mid",[77,84,104,100]);d("tar",[117,115,116,97,114,0,48,48]);d("tar",[117,115,116,97,114,32,32,
0]);d("7z",[55,122,188,175,39,28]);d("wav",[82,73,70,70,"skip","skip","skip","skip",87,65,86,69]);return function(d){for(var g=c,e=0;e<d.length;e++)if(g[d[e]]){if(g=g[d[e]],g.type)return g.type}else if(g.skip)g=g.skip;else break;return null}}();importScripts("../third_party/sql/sql.js");var db,cachedUrls=[];SQL.Statement.prototype.parseBlob=function(c){var d=parseMimeType(c);d||(d="blob");var n=URL.createObjectURL(new Blob([c]));cachedUrls.push(n);return{blobUrl:n,blobType:d,length:c.length}};
function openDb(c){if(c){var d=new FileReaderSync;db=new SQL.Database(new Uint8Array(d.readAsArrayBuffer(c)))}else db=new SQL.Database;return reloadMasterTable()}function reloadMasterTable(){return db.exec("SELECT name, type FROM sqlite_master")}
var handleCommand=function(c){if(!c.preserveBlobs&&0<cachedUrls.length){for(var d=0;d<cachedUrls.length;d++)URL.revokeObjectURL(cachedUrls[d]);cachedUrls=[]}switch(c.action){case "open":return openDb(c.file);case "reload":return reloadMasterTable();case "exec":if(c.query){try{Parser.parse(c.query)}catch(n){throw{message:"Invalid search params"};}c.sql=c.sql+" where "+c.query}return db.exec(c.sql);case "load":return loadTable(c.name);case "statement":return runStatement(c);case "export":return exportData(c);
case "exportDB":return exportDB(c);case "import":return importSql(c)}},runStatement=function(c){var d=db.prepare(c.sql);d.run(sanitizeArgs(c.args));d.free();if(!c.resultSql)return{result:"OK"};d=db.prepare(c.resultSql);c=d.get(sanitizeArgs(c.resultArgs));d.free();return c},sanitizeArgs=function(c){for(var d=0;d<c.length;d++)if(c[d]instanceof File){var n=(new FileReaderSync).readAsArrayBuffer(c[d]);c[d]=new Uint8Array(n)}else if(null!=c[d]&&c[d].blobType)if(n=new XMLHttpRequest,n.open("GET",c[d].blobUrl,
!1),n.responseType="arraybuffer",n.send(null),200===n.status)c[d]=new Uint8Array(n.response);else throw{message:"Error loading blob"};return c},loadTable=function(c){for(var d=db.exec("PRAGMA table_info("+escapeSql(c)+")")[0],n=d.columns.indexOf("pk"),g=!1,e=0;e<d.values.length;e++)if(1==d.values[e][n]){g=!0;break}c=(g?"select * from ":"select rowid, * from ")+escapeSql(c);e=db.exec(c)[0];if(!e){var q=[];g||q.push("rowid");for(var r=d.columns.indexOf("name"),e=0;e<d.values.length;e++)q.push(d.values[e][r]);
e={columns:q,values:[]}}return{0:e,1:d,hasPrimaryKey:g,baseSql:c,pkIndex:n}},exportData=function(c){for(var d="",n=db.exec("SELECT type, name, sql FROM sqlite_master")[0].values,g="",e=0;e<n.length;e++)if(-1!=c.type.indexOf(n[e][0])){var q=escapeSql(n[e][1]),d=d+("DROP "+n[e][0].toUpperCase()+" IF EXISTS "+q+";\n"),g=g+(n[e][2]+";\n");if(c.includeData&&"TABLE"==n[e][0].toUpperCase()){var r=db.prepare("SELECT * from "+q);for(r.parseBlob=function(c){return c};r.step();)var x=r.get().map(exportDataMapper).join(","),
g=g+("INSERT INTO "+q+" VALUES("+x+");\n");r.free()}}c.includeDrop&&(g=d+g);return{blob:new Blob([g],{type:"text/plain"})}},exportDataMapper=function(c){if(null==c)return"NULL";if("string"==typeof c)return escapeSql(c);if(c instanceof Uint8Array){for(var d="",n=0;n<c.length;n++)var g=c[n].toString(16),d=d+(2>g.length?"0"+g:g);return"X'"+d+"'"}return c},exportDB=function(c){return{blob:new Blob([db.export()])}};
self.onmessage=function(c){var d;try{d=handleCommand(c.data)}catch(n){d={error:n.message}}d.id=c.data.id;return postMessage(d)};var escapeSql=function(c){return"'"+c.replace(/'/g,"''")+"'"};
