T.FileOperations={};T.FileOperations.extractExtension=function(a){return(a=/[^.]+$/.exec(a))&&0<a.length?a[0].toLowerCase():""};T.FileOperations.extractName=function(a){return a.replace(/.[^.]+$/,"")};T.FileOperations.extractFileNameFromPath=function(a){return a.replace(/^.*[\\\/]/,"")};T.FileOperations.supportedImportExtension=function(a){switch(a.toLowerCase()){case "amf":case "babylon":case "ctm":case "dae":case "js":case "json":case "3geo":case "3mat":case "3obj":case "3scn":case "obj":case "ply":case "stl":case "3ds":case "vtk":case "wrl":case "thing":case "zip":return!0}return!1};
T.FileOperations.supportedResourceExtension=function(a){switch(a.toLowerCase()){case "jpeg":case "jpg":case "bmp":case "png":case "gif":case "tiff":case "dds":case "svg":case "mng":case "xbm":case "md2":case "pdb":case "utf8":case "bin":return!0}return!1};T.FileOperations.convertToFileName=function(a){var b=a.lastIndexOf(".");0<b&&b>=a.length-4&&(a=a.substring(0,b));return a.replace(/\.[^/.]+$/,"").replace(/[^a-z0-9]/gi,"_")};
T.FileOperations.getFileName=function(a){findTopNames=function(a){if(!0!==a.dummy&&a.name&&""!=a.name)return[a.name];for(var b=[],e=0,g=a.children.length;e<g;e++){var c=a.children[e];!0!==c.dummy?c.name&&""!=c.name?b.push(c.name):b.push("Untitled"):b=b.concat(findTopNames(a.children[e]))}return b};if((a=findTopNames(a))&&0<a.length){if(1==a.length)return T.FileOperations.convertToFileName(a[0]).substring(0,32);for(var b="Scene",c=0;c<a.length;++c)b+="-"+T.FileOperations.convertToFileName(a[c]);return b.substring(0,
32)}return"Untitled"};T.FileOperations.limitNameLength=function(a,b){return 2>b?"":b>=a.length?a:".."+a.substring(a.length-b+2)};
T.FileOperations.getErrorHandler=function(a){return function(b){var c="";switch(b.code){case FileError.QUOTA_EXCEEDED_ERR:c="Quota exceeded";break;case FileError.NOT_FOUND_ERR:c="File not found";break;case FileError.SECURITY_ERR:c="Security error";break;case FileError.INVALID_MODIFICATION_ERR:c="Invalid modification";break;case FileError.INVALID_STATE_ERR:c="Invalid state";break;default:c="Unknown Error"}a&&a.notifications.remind("Error!",c,50)}};
T.FileOperations.DnDFileController=function(a){this.drop=function(b){b.stopPropagation();b.preventDefault();document.querySelector("body").classList.remove("dropping");a(b.dataTransfer)};var b=document.querySelector("body");b&&b.addEventListener("drop",this.drop,!1)};
var dnd=new T.FileOperations.DnDFileController(function(a){chosenEntry=null;for(var b=0;b<a.items.length;b++){var c=a.items[b];"file"==c.kind&&c.webkitGetAsEntry()&&(fileEntry=c.webkitGetAsEntry(),function(a){chrome.fileSystem.getDisplayPath(a,function(b){a.file(function(a){editor.loader.loadFile(a,b)})})}(fileEntry))}0<a.items.length&&tipDialog&&tipDialog.cancel()});
T.FileOperations.importFile=function(a){var b=[];b.push({description:"All supported files",extensions:"stl obj ply dae ctm 3ds js json 3geo 3mat 3obj 3scn vtk wrl thing zip".split(" ")},{description:"STL files (*.stl)",extensions:["stl"]},{description:"OBJ files (*.obj)",extensions:["obj"]},{description:"AMF files (*.amf)",extensions:["amf"]},{description:"PLY files (*.ply)",extensions:["ply"]},{description:"Collada files (*.dae)",extensions:["dae"]},{description:"CTM files (*.ctm)",extensions:["ctm"]},
{description:"3DS files (*.3ds)",extensions:["3ds"]},{description:"JSON files (*.js;*.json;*.3geo;*.3mat;*.3obj;*.3scn)",extensions:"js json 3geo 3mat 3obj 3scn".split(" ")},{description:"VTK files (*.vtk)",extensions:["vtk"]},{description:"WRL files (*.wrl)",extensions:["wrl"]},{description:"Thingiverse files (*.thing)",extensions:["thing"]},{description:"Zip archives (*.zip)",extensions:["zip"]});b={type:"openFile",accepts:b,acceptsAllTypes:!0};30<=chromeVersion&&(b.acceptsMultiple=!0);chrome.fileSystem.chooseEntry(b,
function(b){if(void 0!==b)for(var d=0;d<b.length;d++)(function(b){chrome.fileSystem.getDisplayPath(b,function(e){b.file(function(b){a.loader.loadFile(b,e)})})})(b[d])})};
T.FileOperations.exportObject=function(a,b){try{var c=T.FileOperations.getFileName(a)+".zip";chrome.fileSystem.chooseEntry({type:"saveFile",suggestedName:c,accepts:[{description:"ZIP archive",extensions:["zip"]},{description:"STL file",extensions:["stl"]},{description:"OBJ file",extensions:["obj"]}],acceptsAllTypes:!1},function(d){if(d){try{switch(T.FileOperations.extractExtension(d.fullPath)){case "stl":var c=new T.STLExporter,e=c.exportMesh(a,!0);d.createWriter(function(a){a.onerror=T.FileOperations.getErrorHandler(b);
a.onwriteend=function(b){a.onwriteend=null;a.truncate(e.size)};a.write(e)},T.FileOperations.getErrorHandler(b));break;case "obj":var c=new T.OBJExporter,g=c.parse(a),e=new Blob([g],{type:"text/plain"});d.createWriter(function(a){a.onerror=T.FileOperations.getErrorHandler(b);a.onwriteend=function(b){a.onwriteend=null;a.truncate(e.size)};a.write(e)},T.FileOperations.getErrorHandler(b));break;case "zip":var h=null;notifications&&0<a.children.length&&(h=notifications.createProgress("Saving",d.name));
T.FileOperations.zipObject(a,new T.STLExporter,new zip.FileWriter(d),function(){notifications&&h&&(notifications.endProgress(h),h=null)},function(a,b,e){notifications&&h&&notifications.updateProgress(h,a/b*100)},function(a){notifications&&h&&(notifications.endProgress(h),h=null)},3)}}catch(k){console.log(k)}void 0!==e&&d.createWriter(function(a){a.onerror=T.FileOperations.getErrorHandler(b);a.onwriteend=function(b){a.onwriteend=null;a.truncate(e.size)};a.write(e)},T.FileOperations.getErrorHandler(b))}})}catch(d){console.log(d)}};
T.FileOperations.exportScene=function(a,b){try{b=b?b:a.scene;var c=T.FileOperations.getFileName(b)+".zip";chrome.fileSystem.chooseEntry({type:"saveFile",suggestedName:c,accepts:[{description:"ZIP archive",extensions:["zip"]},{description:"STL file",extensions:["stl"]}],acceptsAllTypes:!1},function(d){if(d)try{switch(T.FileOperations.extractExtension(d.fullPath)){case "stl":var c=(new T.STLExporter).exportScene(b,!0);d.createWriter(function(b){b.onerror=T.FileOperations.getErrorHandler(a);b.onwriteend=
function(a){b.onwriteend=null;b.truncate(c.size)};b.write(c)},T.FileOperations.getErrorHandler(a));break;case "zip":var e=null;notifications&&0<b.children.length&&(e=notifications.createProgress("Saving",d.name));T.FileOperations.zipObject(b,new T.STLExporter,new zip.FileWriter(d),function(){notifications&&e&&(notifications.endProgress(e),e=null)},function(a,b,c){notifications&&e&&notifications.updateProgress(e,a/b*100)},function(a){notifications&&e&&(notifications.endProgress(e),e=null)},3)}}catch(g){console.log(g)}})}catch(d){console.log(d)}};
T.FileOperations.exportSceneToFolder=function(a,b){try{b=b?b:a.scene,chrome.fileSystem.chooseEntry({type:"openDirectory"},function(c){var d=[],f=[];b.traverse(function(b){if(b instanceof T.Mesh&&!0!==b.dummy){var g=T.FileOperations.convertToFileName(b.name);""==g&&(g="untitled");if(0>d.indexOf(g))d.push(g),f[g]=1;else{var h=f[g]++;d.push(g+"("+h+")")}(function(b,e){c.getFile(e,{create:!0,exclusive:!0},function(e){if(e){try{var c=(new T.STLExporter).exportMesh(b,!0)}catch(d){console.log(d)}void 0!==
c&&e.createWriter(function(b){b.onerror=T.FileOperations.getErrorHandler(a);b.onwriteend=function(a){b.onwriteend=null;b.truncate(c.size)};b.write(c)},T.FileOperations.getErrorHandler(a))}})})(b,d[d.length-1]+".stl")}})})}catch(c){console.log(c)}};
T.FileOperations.showShareDialog=function(a,b){try{if(a&&a.id&&a.webContentLink){var c=a.webContentLink,d=a.id;chrome.app.window.create("shareDialog/shareDialog.html",{frame:"none",resizable:!1,width:598,height:320},function(f){f&&(T.FileOperations.shareDialogWindows.push(f),f.focus(),f.drawAttention(),f.contentWindow.link=c,f.contentWindow.filename=a.title,f.contentWindow.onclosed=function(){var e=T.FileOperations.shareDialogWindows.indexOf(f);0<=e&&T.FileOperations.shareDialogWindows.splice(e,1);
f.contentWindow.allowEdit||T.FileOperations.setGoogleDriveFilePermissions(d,"anyone","reader",!0,!0);var c=[];c.id=d;a.shared=!0;c.fileInfo=a;c.revisions=[{kind:"drive#revision",id:a.headRevisionId?a.headRevisionId:a.id,title:a.title,fileSize:a.fileSize,downloadUrl:a.downloadUrl,type:"",createdDate:a.createdDate,modifiedDate:a.modifiedDate,lastModifyingUser:a.lastModifyingUser,converted:!0}];f.contentWindow.comment?T.FileOperations.addComment(f.contentWindow.comment,d,function(a){c[0]=a;editor.signals.googleDriveCommentsChanged.dispatch(c)}):
editor.signals.googleDriveCommentsChanged.dispatch(c);b&&b.remind("Cleanup Google Drive","When shared files are not longer needed.\nClick here to go to your Google Drive.",1E3,500,12096E5,!0,function(){T.FileOperations.googleDrive()})})})}}catch(f){console.log(f)}};
T.FileOperations.shareScene=function(a){try{var b=null,c=T.FileOperations.getFileName(a.scene),c=c+".zip",d=null,f=a.notifications;f&&(d=f.createProgress("Compressing...",c,function(){if(b){var a=b.getCurrentXHR();void 0!==a&&null!==a&&a.abort()}},"Cancel upload"));b=T.FileOperations.uploadScene(a,c,"zip",null,function(a){d&&f.endProgress(d);b.folderId&&""==T.FileOperations.getGoogleDriveFolder()?T.FileOperations.setGoogleDriveFolderFromID(b.folderId):T.FileOperations.reloadGoogleDrive();T.FileOperations.showShareDialog(a,
f)},function(a,b,c,k){d&&(c&&f.updateTitle(d,c),k&&f.updateMessage(d,k),a&&b&&f.updateProgress(d,a/b*100))},function(){d&&f.endProgress(d);f&&f.remind("Upload failed!","Unable to upload "+c+" to Google Drive",50)})}catch(e){console.log(e)}};
T.FileOperations.uploadScene=function(a,b,c,d,f,e,g){try{var h=function(){function h(a){a?(a.name=b,e&&e(null,null,"Uploading to Google Drive",b),k.upload(a,function(a){f(a)},function(a){if(void 0!==a&&void 0!==a.loaded&&void 0!==a.total&&0<a.total&&!1!==a.lengthComputable&&e)return e(30+a.loaded/a.total*70,100)},function(a){g&&g()},!0,!0,d)):g&&g()}T.FileOperations.googleDriveAccessToken=k.accessToken;if("zip"==c)e&&e(null,null,"Compressing..."),T.FileOperations.zipObject(a.scene,new T.STLExporter,
new zip.BlobWriter("application/zip"),function(a){h(a)},function(a,b,c){if(e)return e(a/b*30,100,null,c)},function(a){g&&g()},3);else{var m=(new T.STLExporter).exportScene(a.scene,!0);h(m)}},k=new GDocs;if(0==a.scene.children.length)return g&&g(),k;k.accessToken?h():k.auth(!0,h)}catch(l){console.log(l)}return k};
