function isIE(){var a=navigator.userAgent.toLowerCase();return-1!=a.indexOf("msie")?parseInt(a.split("msie")[1]):!1}var seed=1;function random(){var a=1E4*Math.sin(seed++);return a-Math.floor(a)}T.GeometryUtils.removeItemsFromArray=function(){for(var a,b=arguments,c=b.length,e;c&&this.length;)for(a=b[--c];-1!==(e=this.indexOf(a));)this.splice(e,1);return this};T.GeometryUtils.orderedKey=function(a,b){return Math.min(a,b)+"_"+Math.max(a,b)};
T.GeometryUtils.getIndexesFromKey=function(a){a=a.split("_");return[parseInt(a[0]),parseInt(a[1])]};T.SceneUtils.createDummyMaterial=function(){return new T.ObjectMaterial};T.SceneUtils.wireframeMaterial=new T.MeshPhongMaterial({color:0,wireframe:!0,transparent:!0,opacity:.8,wireframeLinewidth:1.1,visible:!1});T.SceneUtils.badEdgesMaterial=new T.LineBasicMaterial({color:16776960,linewidth:1.5,depthTest:!1,visible:!1});
T.SceneUtils.contourSelectionMaterial=new T.LineBasicMaterial({color:6711039,linewidth:2.5,depthTest:!1});T.SceneUtils.xrayMaterial=new T.XrayMaterial;T.SceneUtils.xrayPackMaterial=new T.XrayPackMaterial;
T.SceneUtils.createDefaultMaterials=function(a){var b=random(),c=random(),b=(new T.Color).setHSL(b,1,.25*c+.5);return a?[new T.ObjectMaterial({specular:16777215,emissive:0,color:3355443,shininess:0,side:T.DoubleSide,vertexColors:T.FaceColors,shading:T.FlatShading}),T.SceneUtils.wireframeMaterial]:[new T.ObjectMaterial({specular:6316128,emissive:328965,color:b,side:T.DoubleSide,shading:T.FlatShading}),T.SceneUtils.wireframeMaterial]};
T.SceneUtils.createMultiMaterialMesh=function(a,b){if(void 0==b||0==b.length)b=T.SceneUtils.createDefaultMaterials(a.useColor||a.useVertexColor||a.useFaceColor||a.hasColors);a.dynamic=!0;for(var c=new T.Mesh(a,b[0]),e=1,d=b.length;e<d;e++)mesh=new T.Mesh(a,b[e]),mesh.dummy=!0,c.add(mesh);return c};T.SceneUtils.createMesh=function(a,b){void 0==b&&(b=T.SceneUtils.createDefaultMaterials(a.useColor||a.useVertexColor||a.useFaceColor)[0]);return new T.Mesh(a,b)};
T.SceneUtils.updateXray=function(a,b){if(!a)return!1;var c=T.GeometryUtils.getGlobalBoundingBox(a);if(!c||Infinity===Math.abs(c.min.distanceTo(c.max)))return!1;var e=Math.pow(16,1-2*(void 0!==a.xrayContrast?a.xrayContrast:.5)),d=(new T.V3).subVectors(c.max,c.min);T.SceneUtils.xrayMaterial.uniforms.minZ.value=0;T.SceneUtils.xrayMaterial.uniforms.maxZ.value=Math.min(3*d.x,3*d.y,3*d.z,.7*d.length())*e;var d=new T.Projector,c=c.getBoundingSphere(),f=new T.V3(0,0,1);d.unprojectVector(f,b);d=f.sub(b.position).normalize();
d=b.localToWorld(b.position.clone()).distanceTo(c.center.projectOnVector(d));T.SceneUtils.xrayPackMaterial.uniforms.minZ.value=d-1.1*c.radius*e;T.SceneUtils.xrayPackMaterial.uniforms.maxZ.value=d+1.1*c.radius*e;return!0};T.SceneUtils.updateMaterialAttributes=function(a,b){if(!isIE()){a.attributes={faceIndex:{type:"f",boundTo:"faces",value:[]}};for(var c=0;c<b.faces.length;c++)a.attributes.faceIndex.value[c]=c;a.needsUpdate=!0;a.attributes.faceIndex.needsUpdate=!0}};
T.SceneUtils.updateTriangleVisualization=function(a,b){var c=[];void 0==b&&(b=!0===T.SceneUtils.wireframeMaterial.visible);T.SceneUtils.wireframeMaterial.visible=b;a.traverse(function(a){!0===a.dummy&&!0===a.isWireframe&&(c[a.id]=[a.parent,a])});for(var e in c)c[e][0].remove(c[e][1]);b&&a.traverse(function(a){1!=a.dummy&&a instanceof T.Mesh&&(mesh=new T.Mesh(a.geometry,T.SceneUtils.wireframeMaterial),mesh.dummy=!0,mesh.isWireframe=!0,mesh.visible=a.visible,T.SceneUtils.wireframeMaterial.needsUpdate=
!0,a.add(mesh))})};T.SceneUtils.getBadEdges=function(a){if(!a)return null;for(var b=null,c=0,e=a.children.length;c<e;c++)if(a.children[c]instanceof T.Line&&a.children[c].dummy){b=a.children[c];break}return b};T.SceneUtils.getBadEdgesCount=function(a){if(!a)return null;var b=0;a.traverse(function(a){(a=T.SceneUtils.getBadEdges(a))&&a.geometry&&(b+=a.geometry.badEdgesCount)});return b};
T.SceneUtils.getThinWallsCount=function(a){if(!a)return null;var b=0;a.traverse(function(a){a.dummy||a.thinWalls||(b+=a.thinWalls)});return b};T.SceneUtils.getIntersectionsCount=function(a){if(!a)return null;var b=0;a.traverse(function(a){!a.dummy&&a.intersections&&(b+=a.intersections)});return b};T.SceneUtils.getFacesCount=function(a){if(!a)return null;var b=0;a.traverse(function(a){!a.dummy&&a.geometry&&a.geometry.faces&&(b+=a.geometry.faces.length)});return b};
T.SceneUtils.getVerticesCount=function(a){if(!a)return null;var b=0;a.traverse(function(a){!a.dummy&&a.geometry&&a.geometry.vertices&&(b+=a.geometry.vertices.length)});return b};
T.SceneUtils.updateBadEdges=function(a,b,c){var e=function(a,b){if(a instanceof T.Mesh&&!0!==a.dummy){var c=T.SceneUtils.getBadEdges(a);if(null==c||b){if(null!=c)for(c=0;c<a.children.length;++c)if(a.children[c]instanceof T.Line&&a.children[c].dummy){a.remove(a.children[c]);break}c=(new T.CalculateBadEdgesOperation).operate(a.geometry);c.vertices&&0<c.vertices.length&&(c=new T.Line(c,T.SceneUtils.badEdgesMaterial,T.LinePieces),c.badEdgesFor=a,c.renderDepth=9007199254740992,c.dummy=!0,a.add(c))}}};
!0===c?a.traverse(function(a){e(a,b)}):e(a,b)};T.GeometryUtils.getAdjacentFaces=function(a,b,c,e,d){var f=[];hash=T.GeometryUtils.orderedKey(b,c);faceList=d[hash];if(void 0!=faceList)for(key in faceList)b=e.faces[faceList[key]],b!=a&&f.push(b);return f};T.GeometryUtils.sameOrder=function(a,b,c){return a instanceof T.F3?a.a==b&&a.b==c||a.b==b&&a.c==c||a.c==b&&a.a==c:a instanceof T.Face4?a.a==b&&a.b==c||a.b==b&&a.c==c||a.c==b&&a.d==c||a.d==b&&a.a==c:!1};
T.GeometryUtils.traverseAdjacentFaces=function(a,b,c,e,d){var f=[a];_addAdjacentFaces=d?function(a,d,k){var p;hash=T.GeometryUtils.orderedKey(d,k);edgeFacesList=c[hash];if(void 0!=edgeFacesList&&0==edgeFacesList.length%2){var l=-1,r=2,q=b.faces[a];for(key in edgeFacesList)if(p=edgeFacesList[key],p!=a){var m=b.faces[p];T.GeometryUtils.sameOrder(m,d,k)!=T.GeometryUtils.sameOrder(q,d,k)&&(m=m.normal.dot(q.normal),-1!=m&&m<r&&(r=m,l=p))}-1!=l&&e(l,a,d,k)&&f.push(l)}}:function(a,b,d){var p;hash=T.GeometryUtils.orderedKey(b,
d);edgeFacesList=c[hash];if(void 0!=edgeFacesList)for(key in edgeFacesList)p=edgeFacesList[key],p!=a&&e(p,a,b,d)&&f.push(p)};for(e(a);0<f.length;)d=f.pop(),a=b.faces[d],a instanceof T.F3?(_addAdjacentFaces(d,a.a,a.b),_addAdjacentFaces(d,a.b,a.c),_addAdjacentFaces(d,a.c,a.a)):a instanceof T.Face4&&(_addAdjacentFaces(d,a.a,a.b),_addAdjacentFaces(d,a.b,a.c),_addAdjacentFaces(d,a.c,a.d),_addAdjacentFaces(d,a.d,a.a))};
T.GeometryUtils.traverseAdjacentEdges=function(a,b,c,e){var d=[a],f;_addAdjacentEdges=function(a,b){var f;edgeList=c[b];if(void 0!=edgeList)for(key in edgeList)f=edgeList[key],f!=a&&e(f,a,b)&&d.push(f)};for(e(a);0<d.length;)f=d.pop(),a=b[f],_addAdjacentEdges(f,a.v1),_addAdjacentEdges(f,a.v2)};
T.GeometryUtils.cloneGeometry=function(){for(var a=new T.Geometry,b=this.vertices,c=0,e=b.length;c<e;c++)a.vertices.push(b[c].clone());for(var b=this.faces,d,c=0,e=b.length;c<e;c++)d=b[c],d.removed||a.faces.push(d.clone());for(var f=this.faceVertexUvs[0],c=0,e=f.length;c<e;c++){for(var g=f[c],h=[],k=0,p=g.length;k<p;k++)(d=b[k])&&d.removed||h.push(new T.Vector2(g[k].x,g[k].y));a.faceVertexUvs[0].push(h)}return a};
T.GeometryUtils.getVertexReplacement=function(a,b){var c=a;if(0>c)return-1;for(;void 0!==b.vertices[c].replacedBy;)if(c=b.vertices[c].replacedBy,c==a)return-1;return c};T.GeometryUtils.getVertexEdges=function(a,b,c){a=T.GeometryUtils.getVertexReplacement(a,c);return 0>a?[]:b[a]};
T.GeometryUtils.traverseAdjacentVertexes=function(a,b,c,e,d){var f=[a],g,h;for(d(a);0<f.length;)if(h=f.pop(),h=T.GeometryUtils.getVertexReplacement(h,e),edgeList=c[h],void 0!=edgeList)for(key in edgeList)a=edgeList[key],g=b[a],g=g.v1==h?g.v2:g.v1,d(g,a,h)&&f.push(g)};
T.GeometryUtils.getFacesAdjacentToVertex=function(a,b,c,e){var d=[];T.GeometryUtils.traverseAdjacentFaces(b,c,e,function(b,e,h,k){e=c.faces[b];if(!e||e.traversedByVertex==a||!T.GeometryUtils.faceContainsVertex(e,a))return!1;e.traversedByVertex=a;d.push(b);return!0});for(b=0;b<d.length;++b)c.faces[d[b]].traversedByVertex=void 0;return d};T.GeometryUtils.updateEdgeFaces=function(a,b){if(void 0==a.edgeFaceMap||1==b)a.edgeFaceMap=T.GeometryUtils.computeEdgeFaces(a);return a.edgeFaceMap};
T.GeometryUtils.addFaceToEdgeFacesMap=function(a,b,c){function e(a,b){void 0===c[a]&&(c[a]=[]);c[a].push(b)}b=b.faces[a];var d,f=T.GeometryUtils.orderedKey;b instanceof T.F3?(d=f(b.a,b.b),e(d,a),d=f(b.b,b.c),e(d,a),d=f(b.c,b.a),e(d,a)):b instanceof T.Face4&&(d=f(b.a,b.b),e(d,a),d=f(b.b,b.c),e(d,a),d=f(b.c,b.d),e(d,a),d=f(b.d,b.a),e(d,a))};
T.GeometryUtils.removeFaceFromEdgeFacesMap=function(a,b,c){function e(a,b){var d=c[a];if(void 0!==d){for(var e=0,f=0;f<d.length;++f)d[e]=d[f],d[f]!=b&&++e;e!=d.length&&d.splice(e,d.length-e)}}b=b.faces[a];var d,f=T.GeometryUtils.orderedKey;b instanceof T.F3?(d=f(b.a,b.b),e(d,a),d=f(b.b,b.c),e(d,a),d=f(b.c,b.a),e(d,a)):b instanceof T.Face4&&(d=f(b.a,b.b),e(d,a),d=f(b.b,b.c),e(d,a),d=f(b.c,b.d),e(d,a),d=f(b.d,b.a),e(d,a))};
T.GeometryUtils.computeEdgeFaces=function(a){var b,c,e={};a.mergeVertices();a.verticesNeedUpdate=!0;b=0;for(c=a.faces.length;b<c;b++)T.GeometryUtils.addFaceToEdgeFacesMap(b,a,e);return e};T.GeometryUtils.replaceFacePoint=function(a,b,c){a instanceof T.F3?(a.a==b&&(a.a=c),a.b==b&&(a.b=c),a.c==b&&(a.c=c)):a instanceof T.Face4&&(a.a==b&&(a.a=c),a.b==b&&(a.b=c),a.c==b&&(a.c=c),a.d==b&&(a.d=c))};T.GeometryUtils.faceContainsVertex=function(a,b){return void 0!==T.GeometryUtils.getFaceVertexProperty(a,b)};
T.GeometryUtils.getFaceVertexProperty=function(a,b){if(a instanceof T.F3){if(a.a==b)return"a";if(a.b==b)return"b";if(a.c==b)return"c"}if(a instanceof T.Face4&&a.d==b)return"d"};T.GeometryUtils.getEdgeFaceDirection=function(a,b,c){if(!a)return 0;var e=T.GeometryUtils.getFaceVertexProperty(a,b),d=T.GeometryUtils.getFaceVertexProperty(a,c);if(b==c||!e||!d)return 0;a=a instanceof T.Face4?"d":"c";return e==a&&"a"==d?1:"a"==e&&d==a?-1:e<d?1:-1};
T.GeometryUtils.getOppositeFaceVertex=function(a,b,c){var e=[];a instanceof T.F3?e=[a.a,a.b,a.c]:a instanceof T.Face4&&(e=[a.a,a.b,a.c,a.d]);for(a=0;a<e.length;++a)if(e[a]!=b&&e[a]!=c)return e[a];return-1};
T.GeometryUtils.getEdgePointSurfaceParameters=function(a,b,c,e,d){var f=T.GeometryUtils.getVertexEdges(a,e,b);if(!f||2!=f.length)return null;e=f[0];var f=f[1],g=c[e],h=c[f],k=T.GeometryUtils.getEdgeFaceDirection(b.faces[g.faceIndex],g.v1,g.v2),p=T.GeometryUtils.getEdgeFaceDirection(b.faces[h.faceIndex],h.v1,h.v2);if(0==k*p)return null;c=1==k?g.v1:g.v2;k=1==k?g.v2:g.v1;g=1==p?h.v1:h.v2;h=1==p?h.v2:h.v1;if(a==c&&a==g||a==k&&a==h)return null;a==c&&(f=[e,e=f][0],g=[c,c=g][0],h=[k,k=h][0]);var l=b.vertices[c].clone().sub(b.vertices[k]),
r=b.vertices[g].clone().sub(b.vertices[h]),p=l.clone().add(r);if(0==p.lengthSq())return null;var g=new T.V3,k=1,q=0;d=d[a];var m,t;for(t in d){var n=b.faces[t];n&&(n.normal||T.GeometryUtils.computeFaceNormal.call(b,n),0<n.normal.lengthSq()&&(d=T.GeometryUtils.triangleArea(b.vertices[n.a],b.vertices[n.b],b.vertices[n.c]),g.add(n.normal.clone().setLength(d)),m?(n=n.normal.dot(m),k>n&&(k=n)):m=n.normal,q+=d))}if(0==q||0==g.lengthSq())return null;b=p.clone().cross(g).setLength(q);l.normalize();r.normalize();
m=-r.dot(l);t=r.cross(l).normalize();d=0<t.dot(g);return{normal:g.clone().normalize(),direction:b.clone().normalize(),perpendicular:p.clone().normalize(),flat:.99<k,convex:d,boundaryAngle:d?Math.acos(m):2*Math.PI-Math.acos(m),holeNormal:t,v:a,v1:c,v2:h,edgeIndex1:e,edgeIndex2:f,weightedNormal:g,weightedDirection:b,weightedPerpendicular:p}};T.GeometryUtils.normalizeCenters=function(a,b,c){a.traverse(function(a){a instanceof T.Mesh&&T.GeometryUtils.normalizeMeshCenter(a,b,c)})};
T.GeometryUtils.normalizeMeshCenter=function(a,b,c,e){if(a&&!(a instanceof T.Measurement)){var d=T.SceneUtils.wireframeMaterial.visible;d&&T.SceneUtils.updateTriangleVisualization(a,!1);var f=T.GeometryUtils.getGlobalBoundingBox(a),g=(new T.V3).addVectors(f.min,f.max).multiplyScalar(.5),h=new T.V3,k=new T.V3;isNaN(g.length())||(h.copy(g),k.copy(g).negate());e&&h.add(e);b&&(b=new T.V3,b.subVectors(f.max,f.min),f=Math.max(Math.max(b.x,b.y),b.z),2E3<f?(f=Math.floor(Math.log(f/2E3)/Math.LN10)+1,f=Math.pow(10,
f),a.scale.multiplyScalar(1/f),a.updateMatrix(),h.multiplyScalar(1/f),c&&c.remind("Model rescaled",a.name+" was rescaled 1/"+f+"X times to fit the view area",10)):.1>f&&0<f&&(f=Math.floor(Math.log(.1/f)/Math.LN10)+1,f=Math.pow(10,f),a.scale.multiplyScalar(f),a.updateMatrix(),h.multiplyScalar(f),c&&c.remind("Model rescaled",a.name+" was rescaled "+f+"X times to fit the view area",10)),(2E3<Math.abs(h.x)||2E3<Math.abs(h.y)||2E3<Math.abs(h.z))&&h.set(0,0,0));if(c=a.geometry)c.mergeVertices(),c.applyMatrix((new T.Matrix4).makeTranslation(k.x,
k.y,k.z)),c.verticesNeedUpdate=!0,c.normalsNeedUpdate=!0;a.applyMatrix((new T.Matrix4).makeTranslation(h.x,h.y,h.z));for(h=a;h.parent;h=h.parent);h&&h.traverse(function(b){b instanceof T.Measurement&&b.translatePointsForObject(a,k)});for(h=0;h<a.children.length;++h)T.GeometryUtils.normalizeMeshCenter(a.children[h],!1,!1,k);d&&T.SceneUtils.updateTriangleVisualization(a,!0)}};
T.GeometryUtils.getGlobalBoundingBox=function(a){for(var b=a instanceof Array?a:[a],c=new T.Box3,e=0;e<b.length;++e)if(a=b[e])a.globalBB||(a.globalBB=T.GeometryUtils.computeGlobalBoundingBox(a)),c.union(a.globalBB);return c};T.GeometryUtils.resetGlobalBoundingBox=function(a){if(a)for(a.traverse(function(a){a.globalBB=null});a;)a.globalBB=null,a=a.parent};
T.GeometryUtils.computeGlobalBoundingBox=function(a,b){a.globalBB=new T.Box3;var c=new T.V3;a.updateMatrixWorld(!0);if(void 0!==a.geometry){a.geometry.boundingBox||a.geometry.computeBoundingBox();for(var e=[a.geometry.boundingBox.min.toArray(),a.geometry.boundingBox.max.toArray()],d=0;2>d;++d)for(var f=0;2>f;++f)for(var g=0;2>g;++g)c.set(e[d][0],e[f][1],e[g][2]),c.applyMatrix4(a.matrixWorld),a.globalBB.expandByPoint(c)}if(b||!a.children)return a.globalBB;for(d=0;d<a.children.length;++d)a.globalBB.union(T.GeometryUtils.getGlobalBoundingBox(a.children[d]));
return a.globalBB};T.GeometryUtils.computeGlobalBoundingBoxOld=function(a){var b=new T.Box3,c=new T.V3;a.updateMatrixWorld(!0);a.traverse(function(a){if(void 0!==a.geometry&&void 0!==a.geometry.vertices&&!1!==a.visible)for(var d=a.geometry.vertices,f=0,g=d.length;f<g;f++)c.copy(d[f]),c.applyMatrix4(a.matrixWorld),b.expandByPoint(c)});return b};
T.GeometryUtils.invertGeometry=function(a){for(var b=a.faces,c,e,d=0,f=b.length;d<f;d++)c=b[d],e=c.a,c.a=c.b,c.b=e,T.GeometryUtils.computeFaceNormal.call(a,c)};T.GeometryUtils.calculateNormal=function(a,b,c){var e=new T.V3,d=new T.V3;e.subVectors(c,b);d.subVectors(a,b);e.cross(d);e.normalize();return e};
T.GeometryUtils.computeFaceNormal=function(a){var b=new T.V3,c=new T.V3;if(!a)return b;var e=this.vertices[a.a],d=this.vertices[a.b];b.subVectors(this.vertices[a.c],d);c.subVectors(e,d);b.cross(c);b.normalize();a.normal.copy(b);return a.normal};T.GeometryUtils.computeFaceCentroid=function(a){a.centroid.set(0,0,0);a.centroid.add(this.vertices[a.a]);a.centroid.add(this.vertices[a.b]);a.centroid.add(this.vertices[a.c]);a.centroid.divideScalar(3);return a.centroid};
T.GeometryUtils.getFaceQuality=function(a){var b=new T.V3,c=new T.V3,e=new T.V3,d=this.vertices[a.a],f=this.vertices[a.b];a=this.vertices[a.c];b.subVectors(a,f).normalize();c.subVectors(d,f).normalize();e.subVectors(d,a).normalize();d=(new T.V3).crossVectors(e,c);c=(new T.V3).crossVectors(b,c);b=(new T.V3).crossVectors(b,e);return Math.min(d.length(),c.length(),b.length())};
T.GeometryUtils.computeMeshVolume=function(a){if(!a.geometry)return 0;var b=0,c=a.geometry.faces;a=a.geometry.vertices;for(var e=0,d=c.length;e<d;++e)var f=c[e].a,g=c[e].b,h=c[e].c,f=new T.V3(a[f].x,a[f].y,a[f].z),g=new T.V3(a[g].x,a[g].y,a[g].z),h=new T.V3(a[h].x,a[h].y,a[h].z),b=b+(-(h.x*g.y*f.z)+g.x*h.y*f.z+h.x*f.y*g.z-f.x*h.y*g.z-g.x*f.y*h.z+f.x*g.y*h.z)/6;return b};
T.SceneUtils.getVolume=function(a){if(a.dummy)return 0;void 0===a.volume&&(a.volume=T.GeometryUtils.computeMeshVolume(a));for(var b=0,c=0;c<a.children.length;++c)b+=T.SceneUtils.getVolume(a.children[c]);return(a.volume+b)*a.scale.x*a.scale.y*a.scale.z};T.SceneUtils.getSupportVolume=function(a){if(a&&a.supportVolume&&!a.dummy)return a.supportVolume*a.scale.x*a.scale.y*a.scale.z};
T.GeometryUtils.findCommonParent=function(a){for(var b=[],c=0;c<a.length;++c){for(var e=[],d=d=a[c].parent;d;)e.push(d),d=d.parent;b.push(e)}a=null;for(var f=0;1E3>f;++f){for(var g=null,c=0;c<b.length;++c){e=b[c];if(e.length<=f)return a;d=e[e.length-f-1];if(!g)g=d;else if(g!=d)return a}a=g}};
T.GeometryUtils.cloneObject=function(a){var b=T.SceneUtils.createMesh(T.GeometryUtils.cloneGeometry.call(a.geometry),a.material.clone());for(T.Object3D.prototype.clone.call(a,b,!1);a.children.length;){var c=a.children[0];if(c instanceof T.Measurement)for(var e=c.measurementGizmo.controlPoints,d=0;d<e.length;++d)e[d].object=b;b.add(c)}b.geometry.computeCentroids();b.geometry.computeFaceNormals();b.geometry.computeVertexNormals();b.geometry.verticesNeedUpdate=!0;b.geometry.normalsNeedUpdate=!0;b.geometry.tangentsNeedUpdate=
!0;b.geometry.buffersNeedUpdate=!0;b.geometry.uvsNeedUpdate=!0;return b};T.GeometryUtils.disposeObject=function(a){a&&a.traverse&&a.traverse(function(a){})};
T.DynamicTorusGeometry=function(a,b,c,e,d){T.TorusGeometry.call(this,a,b,c,e,d);this.updateArc=function(a,b){this.arc=a||2*Math.PI;for(var c=new T.V3,d=[],e=[],l=0,r=0;l<=this.radialSegments;l++)for(var q=0;q<=this.tubularSegments;q++,r++){var m=q/this.tubularSegments*this.arc,t=l/this.radialSegments*Math.PI*2;c.x=this.radius*Math.cos(m);c.y=this.radius*Math.sin(m);var n=this.vertices[r];n.x=(this.radius+this.tube*Math.cos(t))*Math.cos(m);n.y=(this.radius+this.tube*Math.cos(t))*Math.sin(m);n.z=this.tube*
Math.sin(t);b&&(d.push(new T.Vector2(q/this.tubularSegments,l/this.radialSegments)),e.push(n.clone().sub(c).normalize()))}if(b){l=1;for(r=0;l<=this.radialSegments;l++)for(q=1;q<=this.tubularSegments;q++,r++){var c=this.faces[r],m=(this.tubularSegments+1)*l+q-1,t=(this.tubularSegments+1)*(l-1)+q-1,n=(this.tubularSegments+1)*(l-1)+q,u=(this.tubularSegments+1)*l+q;c.normal.copy(e[m]);c.normal.add(e[t]);c.normal.add(e[u]);c.normal.normalize();this.faceVertexUvs[0][r]=[d[m].clone(),d[t].clone(),d[u].clone()];
r++;c=this.faces[r];c.normal.copy(e[t]);c.normal.add(e[n]);c.normal.add(e[u]);c.normal.normalize();this.faceVertexUvs[0][r]=[d[t].clone(),d[n].clone(),d[u].clone()]}this.normalsNeedUpdate=this.uvsNeedUpdate=this.elementsNeedUpdate=!0;this.computeCentroids()}this.verticesNeedUpdate=!0}};T.DynamicTorusGeometry.prototype=Object.create(T.TorusGeometry.prototype);
