T.FileOperations.googleDriveWindow=null;T.FileOperations.shareDialogWindows=[];T.FileOperations.lastGoogleDriveUrl="";T.FileOperations.lastTimeCrashed=0;T.FileOperations.googleDriveAccessToken=null;T.FileOperations.googleDriveInfo=null;try{chrome.storage.local.get("last_google_drive_url",function(a){a.last_google_drive_url&&(T.FileOperations.lastGoogleDriveUrl=a.last_google_drive_url)})}catch(a){console.log(a)}
T.FileOperations.setXHRHeader=function(a,b){T.FileOperations.googleDriveAccessToken&&(0<=b.lastIndexOf("docs.google.com")||0<=b.lastIndexOf("googleusercontent"))&&a.setRequestHeader("Authorization","Bearer "+T.FileOperations.googleDriveAccessToken)};T.FileOperations.getGoogleDriveFolder=function(){return T.FileOperations.lastGoogleDriveUrl};T.FileOperations.setGoogleDriveFolder=function(a){T.FileOperations.lastGoogleDriveUrl=a;try{chrome.storage.local.set({last_google_drive_url:a})}catch(b){console.log(b)}};
T.FileOperations.setGoogleDriveFolderFromID=function(a){a&&""!=a?T.FileOperations.setGoogleDriveFolder("https://drive.google.com/#folders/"+a):T.FileOperations.setGoogleDriveFolder("")};T.FileOperations.getGoogleDriveDownloadUrlFromID=function(a){if(a&&""!=a)return"https://docs.google.com/uc?id="+a+"&export=download"};
T.FileOperations.extractIdFromGoogleDriveUIUrl=function(a){var b="",c=".google.com/",d=a.toLowerCase().indexOf(c);0>d&&(c=".com/",d=a.toLowerCase().indexOf(c));if(0<=d)for(a=a.substring(d+c.length).split(/\/|\?|&|=|\./g),c=a.length-1;0<=c;--c)if(28==a[c].length){b=a[c];break}return b};
T.FileOperations.requestGoogleDriveFileProperties=function(a,b,c){var d=new GDocs,e=function(){T.FileOperations.googleDriveAccessToken=d.accessToken;d.getItemProperties(a,function(a){try{var d=JSON.parse(a);b&&b(d)}catch(e){c&&c(e)}},c)};d.accessToken?e():d.auth(!0,e)};T.FileOperations.removeGoogleDriveFile=function(a,b,c){var d=new GDocs,e=function(){T.FileOperations.googleDriveAccessToken=d.accessToken;d.removeFile(a,function(a){try{b&&b()}catch(d){c&&c()}},c)};d.accessToken?e():d.auth(!0,e)};
T.FileOperations.requestGoogleDriveFileComments=function(a,b,c,d,e){var f=new GDocs,g=[],h=50;e&&(h=10);var k=function(l){T.FileOperations.googleDriveAccessToken=f.accessToken;f.getItemComments(a,l,b,function(a){try{var b=JSON.parse(a);b.items&&0<b.items.length?(g=g.concat(b.items),b.nextPageToken&&1E3>g.length&&!e?k(b.nextPageToken):c&&c(g)):c&&c(g)}catch(f){d&&d()}},d,h)};f.accessToken?k():f.auth(!0,k)};
T.FileOperations.loadComments=function(a,b,c,d,e){if(a&&""!=a){var f=T.FileOperations.extractIdFromGoogleDriveUIUrl(a);""==f&&26<=a.length&&36>=a.length&&(f=a);""!=f&&T.FileOperations.requestGoogleDriveFileComments(f,b,function(a){a.id=f;a.updatedMin=b;c&&c(a)},d,e)}};T.FileOperations.getAmountOfVisibleComments=function(a){var b=0,c;if(!a)return 0;for(var d=0;d<a.length;++d)if(c=a[d],!c.deleted&&(++b,a[d].replies))for(var e=0;e<c.replies.length;++e)c.replies[e].deleted||++b;return b};
T.FileOperations.getLastModifiedComment=function(a){for(var b=null,c=null,d=0;d<a.length;++d){var e=new Date(a[d].modifiedDate);if(!c||c<e)c=e,b=a[d]}return b};T.FileOperations.getCommentIndexByID=function(a,b){if(!a||!b)return null;for(var c=0;c<a.length;++c){var d=a[c];if((d.commentId?d.commentId:d.id)==b)return c}return null};
T.FileOperations.mergeComments=function(a,b){var c=b.length,d=a.length,e,f,g=!1;if(void 0==c)return!1;if(void 0==d){for(e=0;e<c;++e)a[e]=b[e];return!0}for(e=0;e<c;++e){var h=b[e],k=new Date(h.modifiedDate),l=h.commentId?h.commentId:h.id;for(f=0;f<d;++f){var m=a[f],n=new Date(m.modifiedDate);if((m.commentId?m.commentId:m.id)==l){n<k&&(a[f]=h,g=!0);break}}f==d&&(a.push(h),g=!0)}return g};
T.FileOperations.removeCommentFromList=function(a,b){var c;if(!a)return!1;for(var d=0;d<a.length;++d){c=a[d];if(c.commentId==b)return c.deleted=!0;if(a[d].replies)for(var e=0;e<c.replies.length;++e)if(c.replies[e].replyId==b)return c.replies[e].deleted=!0}return!1};
T.FileOperations.addComment=function(a,b,c,d){var e=new GDocs,f=function(){T.FileOperations.googleDriveAccessToken=e.accessToken;e.addItemComment(a,b,function(a){try{var b=JSON.parse(a);b.error?d&&d(b.error):c&&c(b)}catch(e){d&&d()}},d)};e.accessToken?f():e.auth(!0,f)};T.FileOperations.removeComment=function(a,b,c,d){var e=new GDocs,f=function(){T.FileOperations.googleDriveAccessToken=e.accessToken;e.removeItemComment(a,b,function(a){try{c&&c()}catch(b){d&&d()}},d)};e.accessToken?f():e.auth(!0,f)};
T.FileOperations.removeCommentReply=function(a,b,c,d,e){var f=new GDocs,g=function(){T.FileOperations.googleDriveAccessToken=f.accessToken;f.removeItemCommentReply(a,b,c,function(a){try{d&&d()}catch(c){e&&e()}},e)};f.accessToken?g():f.auth(!0,g)};
T.FileOperations.aboutGoogleDrive=function(a,b){var c=new GDocs,d=function(){T.FileOperations.googleDriveAccessToken=c.accessToken;c.about(function(c){try{var d=JSON.parse(c);d.error?b&&b(d.error):(T.FileOperations.googleDriveInfo=d,a&&a(d))}catch(g){b&&b()}},b)};c.accessToken?d():c.auth(!0,d)};
T.FileOperations.requestGoogleDriveFileRevisions=function(a,b,c){if(a&&""!=a){var d=T.FileOperations.extractIdFromGoogleDriveUIUrl(a);""==d&&26<=a.length&&36>=a.length&&(d=a);if(""!=d){var e=new GDocs;a=function(){T.FileOperations.googleDriveAccessToken=e.accessToken;e.getItemRevisions(d,function(a,d,e){try{var k=JSON.parse(a);k&&k.items?b&&b(k.items,200==e):k.error?c&&c(k.error):c&&c()}catch(l){c&&c()}},c)};e.accessToken?a():e.auth(!0,a)}}};
T.FileOperations.setGoogleDriveFilePermissions=function(a,b,c,d,e,f,g){var h=new GDocs,k=function(){T.FileOperations.googleDriveAccessToken=h.accessToken;h.setPermissions(a,b,c,d,e,function(a){try{var c=JSON.parse(a);c.error?g&&g(c.error):(T.FileOperations.googleDriveInfo=c,f&&f(c))}catch(b){g&&g()}},g)};h.accessToken?k():h.auth(!0,k)};
T.FileOperations.setGoogleDriveUrl=function(a){T.FileOperations.googleDriveWindow&&null!=T.FileOperations.googleDriveWindow&&T.FileOperations.googleDriveWindow.contentWindow&&T.FileOperations.googleDriveWindow.contentWindow.postMessage({navigateToUrl:a?a:"https://drive.google.com"},"*")};
T.FileOperations.reloadGoogleDrive=function(){T.FileOperations.googleDriveWindow&&null!=T.FileOperations.googleDriveWindow&&T.FileOperations.googleDriveWindow.contentWindow&&T.FileOperations.googleDriveWindow.contentWindow.postMessage({reloadPage:!0},"*")};T.FileOperations.closeGoogleDrive=function(){T.FileOperations.googleDriveWindow&&null!==T.FileOperations.googleDriveWindow&&T.FileOperations.googleDriveWindow.close()};
T.FileOperations.closeAllShareWindows=function(){for(var a=0;a<T.FileOperations.shareDialogWindows.length;++a){var b=T.FileOperations.shareDialogWindows[a];b&&b.close()}};T.FileOperations.removeRevision=function(a,b,c,d){var e=new GDocs,f=function(){T.FileOperations.googleDriveAccessToken=e.accessToken;e.removeRevision(a,b,function(a){try{c&&c()}catch(b){d&&d()}},d)};e.accessToken?f():e.auth(!0,f)};
T.FileOperations.downloadRevisionFromGoogleDrive=function(a,b){if(a&&b){var c=new GDocs,d=function(){T.FileOperations.googleDriveAccessToken=c.accessToken;c.getRevisionsProperties(a,b,function(a){try{var c=JSON.parse(a);c.error?onError&&onError(c.error):editor.loader.loadUrl(c.downloadUrl,c.originalFilename,!1,function(){editor.signals.unzoomCamera.dispatch();chrome.app.window.current().drawAttention()})}catch(b){onError&&onError()}},onError)};c.accessToken?d():c.auth(!0,d)}};
T.FileOperations.queryGoogleDriveFiles=function(a,b,c){var d=new GDocs,e=[],f=function(g){googleDriveAccessToken=d.accessToken;d.queryItems(a,g,function(a){try{var d=JSON.parse(a);d.items&&0<d.items.length?(e=e.concat(d.items),d.nextPageToken&&1E3>e.length?f(d.nextPageToken):b&&b(e)):b&&b(e)}catch(g){c&&c()}},c,100)};d.accessToken?f():d.auth(!0,f)};
T.FileOperations.downloadFromGoogleDrive=function(a,b){""!=a&&T.FileOperations.requestGoogleDriveFileProperties(a,function(c){if(c.title&&c.fileExtension&&c.downloadUrl){var d=T.FileOperations.extractExtension(c.title),e=c.fileExtension.toLowerCase();if(T.FileOperations.supportedImportExtension(e))d!=e&&(c.title+="."+e);else if(!T.FileOperations.supportedImportExtension(d)){editor.notifications.remind("Google Drive","The file you are trying to open is not supported by 3DView.",50);return}editor.loader.loadUrl(c.webContentLink,
c.title,a,function(){b?b():(editor.signals.unzoomCamera.dispatch(),chrome.app.window.current().drawAttention())},null,function(){editor.loader.loadUrl(c.downloadUrl,c.title,a,function(){b?b():(editor.signals.unzoomCamera.dispatch(),chrome.app.window.current().drawAttention())})})}else d=T.FileOperations.getGoogleDriveDownloadUrlFromID(a),editor.loader.loadUrl(d,"untitled.stl",a,function(){b?b():(editor.signals.unzoomCamera.dispatch(),chrome.app.window.current().drawAttention())})},function(){var c=
T.FileOperations.getGoogleDriveDownloadUrlFromID(a);editor.loader.loadUrl(c,"untitled.stl",a,function(){b?b():(editor.signals.unzoomCamera.dispatch(),chrome.app.window.current().drawAttention())})})};T.FileOperations.downloadListFromGoogleDrive=function(a,b){var c=void 0===b?0:b;c>=a.length?0<a.length&&(editor.signals.unzoomCamera.dispatch(),chrome.app.window.current().drawAttention()):T.FileOperations.downloadFromGoogleDrive(a[c],function(){T.FileOperations.downloadListFromGoogleDrive(a,c+1)})};
T.FileOperations.handleGoogleDriveEvents=function(a){a=a.data;if(a.loaded)T.FileOperations.setGoogleDriveUrl(T.FileOperations.getGoogleDriveFolder());else if(a.exit){if("ERR_ABORTED"!=a.exit){T.FileOperations.setGoogleDriveFolder("");var b=(new Date).getTime();2E3<b-T.FileOperations.lastTimeCrashed?T.FileOperations.setGoogleDriveUrl(""):setTimeout(function(){T.FileOperations.setGoogleDriveUrl("")},2E3);T.FileOperations.lastTimeCrashed=b;console.log("Google Drive window closed: ",a.exit)}}else a.commit?
0<=a.commit.toLowerCase().indexOf("//drive.google.com/#folders/")?T.FileOperations.setGoogleDriveFolder(a.commit):0<=a.commit.toLowerCase().indexOf("//drive.google.com")&&T.FileOperations.setGoogleDriveFolder(""):(a.openIds&&T.FileOperations.downloadListFromGoogleDrive(a.openIds),a.newWindow&&(b=a.newWindow.toLowerCase(),0<=b.indexOf(".google.com/file/")?(b=T.FileOperations.extractIdFromGoogleDriveUIUrl(a.newWindow),T.FileOperations.downloadFromGoogleDrive(b)):0<=b.indexOf("&export=download")?(b=
T.FileOperations.extractIdFromGoogleDriveUIUrl(a.newWindow),T.FileOperations.downloadFromGoogleDrive(b)):0<=b.indexOf("googleusercontent.com")&&0<=b.indexOf("&e=download")?(console.log("download",a.newWindow),(b=T.FileOperations.extractIdFromGoogleDriveUIUrl(a.newWindow))?T.FileOperations.downloadFromGoogleDrive(b):editor.loader.loadUrl(a.newWindow,"untitled.zip",!1,function(){editor.signals.unzoomCamera.dispatch();chrome.app.window.current().drawAttention()})):0<=b.indexOf("%22userid%22")&&0<=b.indexOf("%22ids%22")?
(b=function(a){var b=a.indexOf("?");0<b&&(a=a.substring(b+1));a=a.split("+").join(" ");for(var b={},e,f=/[?&]?([^=]+)=([^&]*)/g;e=f.exec(a);)b[decodeURIComponent(e[1])]=JSON.parse(decodeURIComponent(e[2]));return b}(a.newWindow))&&b.state&&b.state.ids?T.FileOperations.downloadListFromGoogleDrive(b.state.ids):(console.log("new window",a.newWindow),window.open(a.newWindow,"_blank")):"about:blank"==b?editor.notifications.remind("Google Drive","File Download is deprecated.\nPlease choose to open the file instead.",
50):(console.log("new window",a.newWindow),window.open(a.newWindow,"_blank"))))};T.FileOperations.googleDrive=function(){chrome.app.window.create("driveDialog/drive.html",{id:"Google Drive - 3DView",minWidth:640,minHeight:480,width:Math.min(1024,window.screen.width),height:Math.min(680,window.screen.height)},function(a){a&&(a.focus(),T.FileOperations.googleDriveWindow=a,T.FileOperations.googleDriveWindow.contentWindow.addEventListener("message",T.FileOperations.handleGoogleDriveEvents))})};
