var TimeoutChain=function(){var a=this;this._timeoutHandler=null;this.chain=[];this.currentStep=0;this.isRunning=!1;this.nextStep=function(){a.currentStep+=1;a.currentStep==a.chain.length?a.stop():a.processCurrentStep()};this.processCurrentStep=function(){a._timeoutHandler=window.setTimeout(function(){a.chain[a.currentStep].func();a.isRunning&&a.nextStep()},a.chain[a.currentStep].time)};this.start=function(){0!=a.chain.length&&1!=a.isRunning&&(a.isRunning=!0,a.currentStep=0,a.processCurrentStep())};
this.stop=function(){a.isRunning=!1;window.clearTimeout(a._timeoutHandler)};this.add=function(b,c){a.chain[a.chain.length]={func:b,time:c}}};
T.OperationBase=function(a,b){this.editor=a;this.notifications=b;this.iteration=-1;this.iterations=10;this.cancelled=!1;this.errorCallback=this.finishAllCallback=this.finishCallback=this.progressCallback=null;this.useNotifications=!1;this.notificationsMessage=this.notificationsTitle="";this.parentObject=null;this.operateObjects=[];this._skipIterations=this.objectIndex=0;this.postOperateProgressWeight=this.preOperateProgressWeight=1;this.operateIterationProgressWeights=[];this.operateObjectProgressWeights=
[];this.totalObjectsProgressWeight=this.currentProgressWeight=this.currentObjectProgressWeight=this.currentIterationProgressWeight=1;this.totalProgressWeight=2;this.progressNotification=null;this.delay=1};T.OperationBase.prototype.getCancelFunction=function(){var a=this;return function(){a.cancelled=!0}};T.OperationBase.prototype.getObjectProgressWeight=function(a){return a.geometry?a.geometry.faces.length:1};
T.OperationBase.prototype.filterObject=function(a){return a&&a.geometry&&a.geometry.faces.length&&!a.dummy};
T.OperationBase.prototype.initObjects=function(a,b){this.totalObjectsProgressWeight=0;this.operateObjects=[];for(var c=this,f=a instanceof T.Object3D?[a]:a,h=0;h<f.length;++h){var k=f[h];if(b)k.traverse(function(a){if(c.filterObject(a)){var d=c.getObjectProgressWeight(a);c.operateObjects.push(a);c.operateObjectProgressWeights.push(d);c.totalObjectsProgressWeight+=d}});else if(c.filterObject(k)){var l=c.getObjectProgressWeight(k);c.operateObjects.push(k);c.operateObjectProgressWeights.push(l);c.totalObjectsProgressWeight+=
l}}this.delay=10>c.operateObjects.length?5:1};
T.OperationBase.prototype.initIterations=function(a,b,c,f){void 0!=a&&(this.iterations=a);void 0!=b&&(this.operateIterationProgressWeights=b);void 0!=c&&(this.preOperateProgressWeight=c);void 0!=f&&(this.postOperateProgressWeight=f);this.currentIterationProgressWeight=this.currentProgressWeight=this.preOperateProgressWeight;this.totalProgressWeight=this.preOperateProgressWeight+this.postOperateProgressWeight;if(this.operateIterationProgressWeights&&0<this.operateIterationProgressWeights.length)for(a=
0;a<this.operateIterationProgressWeights.length;++a)this.totalProgressWeight+=this.operateIterationProgressWeights[a];else this.totalProgressWeight+=this.iterations};T.OperationBase.prototype.initNotifications=function(a,b){this.notificationsTitle=a;this.notificationsMessage=b;this.useNotifications=!0};T.OperationBase.prototype.getIteration=function(){return this.iteration};T.OperationBase.prototype.getCurrentObject=function(){return this.operateObjects[this.objectIndex]};
T.OperationBase.prototype.getObjectsCount=function(){return this.operateObjects.length};T.OperationBase.prototype.getCurrentTopLevelObject=function(){if(!this.parentObject)return this.getCurrentObject();if(this.parentObject instanceof T.Scene){var a;for(a=this.getCurrentObject();a&&a.parent!==this.parentObject;a=a.parent);return a}return this.parentObject};
T.OperationBase.prototype.getCurrentObjectName=function(){var a=this.getCurrentTopLevelObject();if(a)return T.FileOperations.limitNameLength(a.name,30)};T.OperationBase.prototype.getIterationsCount=function(){return this.iterations};T.OperationBase.prototype.skipIterations=function(a){for(var b=0;b<a;++b)this.nextIteration();this._skipIterations=a;return this.iteration};
T.OperationBase.prototype.nextIteration=function(){++this.iteration;this.iteration<this.iterations?(this.currentIterationProgressWeight=this.operateIterationProgressWeights&&0<this.operateIterationProgressWeights.length?this.operateIterationProgressWeights[this.iteration]:1,this.currentProgressWeight+=this.currentIterationProgressWeight):(this.currentIterationProgressWeight=this.postOperateProgressWeight,this.currentProgressWeight=this.totalProgressWeight);return this.iteration};
T.OperationBase.prototype.onCancel=function(){this.editor.noRendering=!1;this.finishCallback&&this.finishCallback(null);this.finishAllCallback&&this.finishAllCallback(null)};T.OperationBase.prototype.onFinish=function(a,b){this.finishCallback&&this.finishCallback(a?a:this.parentObject,b)};T.OperationBase.prototype.onFinishAll=function(a,b){this.editor.noRendering=!1;this.finishAllCallback&&this.finishAllCallback(a,b)};
T.OperationBase.prototype.onError=function(a){this.editor.noRendering=!1;this.errorCallback?this.errorCallback(a):console.log(a)};T.OperationBase.prototype.onProgress=function(a,b,c){this.notifications&&this.progressNotification&&(b&&this.notifications.updateProgress(this.progressNotification,a/b*100),c&&this.notifications.updateMessage(this.progressNotification,c));this.progressCallback&&this.progressCallback(a,b,c)};
T.OperationBase.prototype.onOperationProgress=function(a,b,c){if(b)this.onProgress(this.currentObjectProgressWeight-this.operateObjectProgressWeights[this.objectIndex]*(b-a)/b,this.totalObjectsProgressWeight,c)};T.OperationBase.prototype.onIterationProgress=function(a,b,c){if(b)this.onOperationProgress(this.currentProgressWeight-this.currentIterationProgressWeight*(b-a)/b,this.totalProgressWeight,c)};T.OperationBase.prototype.preOperateAll=function(a,b){};
T.OperationBase.prototype.preOperate=function(a,b){};T.OperationBase.prototype.preOperateObject=function(a,b){a.noRendering=!0};T.OperationBase.prototype.operateIteration=function(a,b){};
T.OperationBase.prototype.postOperateMesh=function(a,b,c){var f=a.selected==b,h=a.isMarked(b);c.geometry.verticesNeedUpdate=!0;c.geometry.elementsNeedUpdate=!0;c.geometry.morphTargetsNeedUpdate=!0;c.geometry.uvsNeedUpdate=!0;c.geometry.normalsNeedUpdate=!0;c.geometry.colorsNeedUpdate=!0;c.geometry.tangentsNeedUpdate=!0;c.material.needsUpdate=!0;for(T.Object3D.prototype.clone.call(b,c,!1);0<b.children.length;)c.add(b.children[0]);b.parent||(b.parent=a.scene);b.parent.add(c);a.signals.objectAdded.dispatch(c);
a.removeObject(b);f&&a.select(c);h&&a.mark(c);a.noRendering=!1;return c};T.OperationBase.prototype.postOperateObject=function(a,b){var c=new T.Mesh(b.geometry.clone(),b.material);return this.postOperateMesh(a,b,c)};T.OperationBase.prototype.postOperate=function(a,b){return b};T.OperationBase.prototype.postOperateAll=function(a,b){return b};
T.OperationBase.prototype.operate=function(a,b,c,f,h,k,l){function n(b,c,e){d.cancelled?b.stop():(c=d.postOperateAll(a,c),d.cancelled?(b.stop(),d.onCancel()):(d.progressNotification&&d.notifications.endProgress(d.progressNotification),this.useNotifications=!1,d.onFinishAll(c,e)))}var d=this,g=b instanceof T.Object3D?[b]:b,m=g.slice(0);this.parentObject=b instanceof T.Object3D?b:null;this.progressCallback=k;this.finishCallback=f;this.finishAllCallback=h;this.errorCallback=l;this.initObjects(b,!1!==
c);if(0==d.getObjectsCount())d.onFinish(b);else{this.notifications&&this.useNotifications&&(this.progressNotification=this.notifications.createProgress(this.notificationsTitle,this.notificationsMessage,this.getCancelFunction(),"Cancel"));this.initIterations();this.cancelled=!1;this.currentObjectProgressWeight=0;try{var e=new TimeoutChain;(function(){e.add(function(){d.cancelled?(e.stop(),d.onCancel()):d.preOperateAll(a,g)},d.delay)})();for(b=0;b<g.length;++b)(function(b){e.add(function(){var c=g[b];
d.cancelled?(e.stop(),d.onCancel()):d.preOperate(a,c)},d.delay)})(b);for(c=0;c<d.getObjectsCount();++c)(function(b){e.add(function(){if(d.cancelled)e.stop(),d.onCancel();else{d.objectIndex=b;d.currentObjectProgressWeight+=d.operateObjectProgressWeights[d.objectIndex];d.currentProgressWeight=d.preOperateProgressWeight;var c=d.getCurrentObject();d.onOperationProgress(0,d.totalProgressWeight,d.getCurrentObjectName(c));d.iteration=-1;d.preOperateObject(a,c);d.nextIteration()}},d.delay);for(var c=0;c<
d.getIterationsCount();++c)(function(a){e.add(function(){if(d.cancelled)e.stop(),d.onCancel();else if(0<d._skipIterations)e.currentStep+=d._skipIterations-1,d._skipIterations=0;else{d.objectIndex=b;var a=d.getCurrentObject();d.onOperationProgress(d.currentProgressWeight-d.currentIterationProgressWeight,d.totalProgressWeight);d.operateIteration(a,d.iteration);d.nextIteration()}},d.delay)})(c);e.add(function(){var c;d.cancelled?(e.stop(),d.onCancel(),c=void 0):(d.objectIndex=b,c=d.getCurrentObject(),
c=d.postOperateObject(a,c));for(var f=0;f<g.length;++f)c&&d.operateObjects[b]==g[f]&&(g[f]=c)},d.delay)})(c);for(b=0;b<g.length;++b)(function(b){e.add(function(){var c=g[b],f=m[b];if(d.cancelled)e.stop();else if(c=d.postOperate(a,c),d.cancelled)e.stop(),d.onCancel();else d.onFinish(c,f)},d.delay)})(b);(function(){e.add(function(){n(e,g,m)},d.delay)})();e.start()}catch(p){this.onError(p)}}};
