T.FileOperations.tempFiles=[];T.FileOperations.clearTempFile=function(a){if(a.fileEntry)for(var b=0;b<T.FileOperations.tempFiles.length;++b)if(a.fileEntry.fullPath==T.FileOperations.tempFiles[b].fullPath){T.FileOperations.tempFiles[b].remove(function(){});T.FileOperations.tempFiles.splice(b,1);break}};
T.FileOperations.clearTempFiles=function(a){if(a)for(var b=0;b<a;++b)T.FileOperations.clearTempFile(a[b]);else{for(b=0;b<T.FileOperations.tempFiles.length;++b)T.FileOperations.tempFiles[b].remove(function(){});T.FileOperations.tempFiles=[]}};T.FileOperations.tempFileExists=function(a){for(var b=0;b<T.FileOperations.tempFiles.length;++b)if("/"+a==T.FileOperations.tempFiles[b].fullPath)return!0;return!1};
T.FileOperations.getLocalURL=function(a){var b=a.split("/");for(a=0;a<b.length;)"."==b[a]?b.splice(a,1):".."==b[a]&&0<a?(--a,b.splice(a,2)):++a;baseUrl=1>b.length?".":b.join("/");for(a=0;a<T.FileOperations.tempFiles.length;++a)if(b=T.FileOperations.tempFiles[a],b.fullPath==baseUrl)return b.toURL();return null};
T.FileOperations.createTempFile=function(a,b,p,f){window.webkitRequestFileSystem(TEMPORARY,b,function(b){function k(){b.root.getFile(a,{create:!0},function(b){T.FileOperations.tempFiles.push(b);p&&p(b)},f)}function q(b,a,t){if("."==a[0]||""==a[0])a=a.slice(1);1==a.length?t&&t(a[0],b):b.getDirectory(a[0],{create:!0},function(b){a.length&&q(b,a.slice(1),t)},f)}q(b.root,a.split("/"),function(a,b){b.getFile(a,null,function(a){a.remove(k,k)},k)})})};
T.FileOperations.getBinaryHeader=function(a,b){if("string"===typeof a){for(var p=Math.min(a.length,b),f=new Uint8Array(p),n=0;n<p;n++)f[n]=a.charCodeAt(n)&255;return f.buffer||f}return a};T.FileOperations.isZipData=function(a){a=new DataView(T.FileOperations.getBinaryHeader(a,2));return"PK"===String.fromCharCode(a.getUint8(0),a.getUint8(1))};
T.FileOperations.unzip=function(a,b,p,f,n,k){function q(c,d,u,f,e,m){function l(a){b&&g&&b.updateMessage(g,T.FileOperations.limitNameLength(h.filename,30));var y;y=a?new zip.FileWriter(a):new zip.BlobWriter("application/octet-stream");h.getData(y,function(b){a&&(b.fileEntry=a);b.compressedSize=h.compressedSize;b.name=h.filename;t.push(b);d+=h.compressedSize;c.shift();u&&u(b);q(c,d,u,f,e,m)},function(a,b){e&&e(a+d,h.filename)&&(r=!0)},function(a){c.shift();m&&m(a);q(c,d,u,f,e,m)})}for(;0<c.length&&
(c[0].directory||!T.FileOperations.supportedImportExtension(T.FileOperations.extractExtension(c[0].filename))&&!T.FileOperations.supportedResourceExtension(T.FileOperations.extractExtension(c[0].filename)));)c.shift();if(0==c.length||r)f(t);else{var h=c[0];T.FileOperations.tempFileExists(h.filename)||a.name==h.filename?l():T.FileOperations.createTempFile(h.filename,h.uncompressedSize,l,function(a){l()})}}function w(a,d,u,f,e,m,l){for(;0<a.length&&!T.FileOperations.supportedImportExtension(T.FileOperations.extractExtension(a[0].name));)a.shift();
if(0==a.length||r)f&&f();else{var h=a[0];b&&g&&b.updateMessage(g,T.FileOperations.limitNameLength(h.name,30));u(h,function(){T.FileOperations.clearTempFile(h);a.shift();e&&e(d+h.compressedSize,h.name)&&(r=!0);w(a,d+h.compressedSize,u,f,e,m,l)},l)}}var v=!1,t=[],d=0,l=0;T.FileOperations.extractExtension(a.name);var g=null,r=!1;if(void 0!==a.data)dataReader=new zip.StringReader(a.data);else if(void 0!==a.size)dataReader=new zip.BlobReader(a);else return;try{zip.createReader(dataReader,function(c){function t(){r=
!0;b&&g&&(b.endProgress(g),g=null)}c.getEntries(function(u){function k(a,b){for(var d=0;d<u.length&&!r;++d){var c=u[d],e=T.FileOperations.extractExtension(c.filename);!c.directory&&a(e)&&b(c)}}function e(a){m.push(a);d+=a.compressedSize;l+=a.compressedSize;v=!0;++x}var m=[],x=0;k(T.FileOperations.supportedResourceExtension,function(a){m.push(a);d+=a.compressedSize});k(function(a){return T.FileOperations.supportedImportExtension(a)&&"js"!==a&&"zip"!==a},e);k(function(a){return T.FileOperations.supportedImportExtension(a)&&
"zip"==a},e);k(function(a){return T.FileOperations.supportedImportExtension(a)&&"js"==a},e);v?(b&&1048576<l&&(g=b.createProgress("Extracting",T.FileOperations.limitNameLength(a.name,30),t,"Cancel")),q(m,0,null,function(a){c.close();b&&g&&b.updateTitle(g,"Loading");w(a,0,p,function(){b&&g&&(b.endProgress(g),g=null);f&&f(a)},function(a,c){b&&g&&(b.updateProgress(g,(d+a)/(d+l)*100),a==l&&(b.endProgress(g),g=null));n&&n(d+a,d+l,c)&&t()},null,x)},function(a,c){b&&g&&b.updateProgress(g,a/(d+l)*100);n&&
n(a,d+l,c)&&t()},function(a){console.log(a)})):(b&&g&&(b.endProgress(g),g=null),f&&f([]))})},function(a){b&&g&&(b.endProgress(g),g=null);k&&k()})}catch(c){k&&k(c)}};
T.FileOperations.zipObject=function(a,b,p,f,n,k,q){var w=!1,v=a;(a=function(a){for(var b=a;b&&!(b instanceof T.Mesh);){for(var f=0,g=null,k=0;b.children&&k<b.children.length;++k){var c=b.children[k];!0===c.dummy||c instanceof T.Light||c instanceof T.Camera||(++f,g=c)}if(0==f){b=null;break}else if(1==f)b=g;else break}a!=b&&b instanceof T.Mesh&&(b=b.parent);return b}(a))?zip.createWriter(p,function(k){function d(c){function g(b,d,e,h){d?k.add(b.referenceName+"."+e,new zip.BlobReader(d),function(){d=
null;var a=[];if(b instanceof T.Mesh)b.traverse(function(b){b instanceof T.Measurement&&a.push(b.exportMeasurement())});else for(var c=0;c<b.children.length;++c)b.children[c]instanceof T.Measurement&&a.push(b.children[c].exportMeasurement());0<a.length?(c=JSON.stringify({metadata:{type:"Measurement",version:"1.0"},measurements:a},null,"\t"),c=c.replace(/[\n\t]+([\d\.e\-\[\]]+)/g,"$1"),d=new Blob([c],{type:"text/plain"}),k.add(b.referenceName+".js",new zip.BlobReader(d),function(){d=null;h&&h()},function(a,
b){})):h&&h()},function(d,e){n&&n(100*c+d/e*100,100*a.children.length,b.referenceName+".stl")&&(w=!0,k.close(function(){f&&f()}))}):h&&h()}if(w||c>=a.children.length)k.close(function(a){f&&f(a)});else{var e=a.children[c];if(e&&!0!==e.dummy)if(e instanceof T.Platform&&e.isPlatformVisible()){var m=JSON.stringify({metadata:{type:"Platform",version:"1.0"},platform:e.getPlatformDTO()},null,"\t"),m=m.replace(/[\n\t]+([\d\.e\-\[\]]+)/g,"$1");e.sendStatistic("save");(m=new Blob([m],{type:"text/plain"}))&&
0<m.size?g(e,m,"js",function(){d(c+1)}):d(c+1)}else if(0===q||0>=q||e instanceof T.Mesh||!e.children||0==e.children.length)(m=b.exportScene(e,!0))&&0<m.size?g(e,m,"stl",function(){d(c+1)}):d(c+1);else{var l=function(a){var f;f=a?new zip.FileWriter(a):new zip.BlobWriter("application/octet-stream");T.FileOperations.zipObject(e,b,f,function(b){b&&0<b.size?g(e,b,"zip",function(){a&&T.FileOperations.clearTempFile({fileEntry:a});d(c+1)}):d(c+1)},function(){},function(f){a&&T.FileOperations.clearTempFile({fileEntry:a});
(f=b.exportScene(e,!0))&&0<f.size?g(e,f,"stl",function(){d(c+1)}):d(c+1)},void 0!==q?q-1:void 0)},h=0;e.traverse(function(a){a instanceof T.Mesh&&!a.dummy&&a.geometry&&a.geometry.faces&&(h+=a.geometry.faces.length)});T.FileOperations.createTempFile(e.name?e.name:"untitled.zip",80+50*h,l,function(a){l()})}else d(c+1)}}var l=[],g=[];a instanceof T.Mesh?a={children:[a]}:v instanceof T.Platform&&v.isPlatformVisible()&&(a={children:[v].concat(a.children)});for(var r=0;r<a.children.length;++r){var c=T.FileOperations.convertToFileName(a.children[r].name);
""==c&&(c="untitled");if(0>l.indexOf(c))g[c]=1;else var p=g[c]++,c=c+"("+p+")";l.push(c);a.children[r].referenceName=c}d(0)},function(a){k&&k(a)}):f&&f()};
