window.onresize=doLayout;var isLoading=!1;window.addEventListener("message",messageHandler);
onload=function(){var a=document.querySelector("#drive-browser"),b=document.querySelector("#drive-web");document.querySelector("#files-switch").onclick=function(){a.style.display="block";b.style.visibility="hidden"};document.querySelector("#explore-switch").onclick=function(){a.style.display="none";b.style.visibility="visible"};doLayout();_onWebLoad();_onBrowserLoad();a.style.display="block";b.style.visibility="hidden"};
function _onWebLoad(){var a=document.querySelector("webview");a&&(window.top.postMessage({loaded:!0},"*"),document.querySelector("#back").onclick=function(){a.back()},document.querySelector("#forward").onclick=function(){a.forward()},document.querySelector("#home").onclick=function(){navigateTo("http://www.google.com/")},document.querySelector("#reload").onclick=function(){isLoading?a.stop():a.reload()},document.querySelector("#reload").addEventListener("webkitAnimationIteration",function(){isLoading||
document.body.classList.remove("loading")}),document.querySelector("#terminate").onclick=function(){a.terminate()},document.querySelector("#location-form").onsubmit=function(a){a.preventDefault();navigateTo(document.querySelector("#location").value)},a.addEventListener("exit",handleExit),a.addEventListener("loadstart",handleLoadStart),a.addEventListener("loadstop",handleLoadStop),a.addEventListener("loadabort",handleLoadAbort),a.addEventListener("loadredirect",handleLoadRedirect),a.addEventListener("loadcommit",
handleLoadCommit),a.addEventListener("newwindow",handleNewWindow),a.addEventListener("permissionrequest",handlePermisssion))}function navigateTo(a){resetExitedState();document.querySelector("webview").src=a}function doLayout(){_doBrowserLayout();_doWebLayout()}
function _doWebLayout(){var a=document.querySelector("webview");if(a){var b=document.querySelector("#top-controls").offsetHeight,c=document.documentElement.clientWidth,b=document.documentElement.clientHeight-b;a.style.width=c+"px";a.style.height=b+"px";a=document.querySelector("#sad-webview");a.style.width=c+"px";a.style.height=2*b/3+"px";a.style.paddingTop=b/3+"px"}}
function handleExit(a){console.log(a.type);document.body.classList.add("exited");"abnormal"==a.type?(document.body.classList.add("crashed"),window.top.postMessage({exit:"crashed"},"*")):"killed"==a.type?(document.body.classList.add("killed"),window.top.postMessage({exit:"killed"},"*")):window.top.postMessage({exit:"exited"},"*")}function resetExitedState(){document.body.classList.remove("exited");document.body.classList.remove("crashed");document.body.classList.remove("killed")}
function handleLoadCommit(a){var b=document.querySelector("webview");b&&(window.top.postMessage({commit:a.url},"*"),resetExitedState(),a.isTopLevel&&(document.querySelector("#location").value=a.url,b=document.querySelector("webview"),document.querySelector("#back").disabled=!b.canGoBack(),document.querySelector("#forward").disabled=!b.canGoForward()))}
function handleLoadStart(a){document.body.classList.add("loading");isLoading=!0;resetExitedState();a.isTopLevel&&(document.querySelector("#location").value=a.url)}function handleLoadStop(a){isLoading=!1}function handleLoadAbort(a){window.top.postMessage({exit:a.reason},"*")}function handleLoadRedirect(a){resetExitedState();window.top.postMessage({redirect:a.newUrl},"*");a.isTopLevel&&(document.querySelector("#location").value=a.newUrl)}
function handleNewWindow(a){resetExitedState();a.preventDefault();if("about:blank"!==a.targetUrl)window.top.postMessage({newWindow:a.targetUrl},"*");else{var b=document.createElement("webview");b.style.visibility="hidden";document.body.appendChild(b);b.request.onBeforeRequest.addListener(function(a){return"main_frame"===a.type&&"about:blank"!==a.url?(window.top.postMessage({newWindow:a.url},"*"),document.body.removeChild(b),{cancel:!0}):{cancel:!1}},{urls:["*://*/*"]},["blocking"]);a.window.attach(b)}}
function handlePermisssion(a){resetExitedState();window.top.postMessage({permission:a.targetUrl},"*")}function messageHandler(a){a&&a.data&&(a.data.navigateToUrl?(navigateTo(a.data.navigateToUrl),showFolders()):a.data.reloadPage&&webview.reload())};
