var gdriveFoldersTree=[],gdriveFileList=[],selectedGDriveFolder={},selectedFilesCount=0,lastSelectedFileIndex=0,foldersToProcess=0,folderIdsList=[];T={FileOperations:{}};
function onDividerDrag(a){var c=document.querySelector("#left-panel"),b=document.querySelector("#right-panel"),d=document.querySelector("#panel-divider"),f=document.documentElement.clientWidth;15<a.clientX&&a.clientX<f-15&&(c.style.width=a.clientX-20+"px",b.style.left=a.clientX+10+"px",b.style.width=f-a.clientX-20+"px",d.style.left=a.clientX+"px")}
function onDividerDragFinish(a){document.removeEventListener("mousemove",onDividerDrag,!1);document.removeEventListener("mouseup",onDividerDragFinish,!1)}
function _doBrowserLayout(){var a=document.querySelector("#left-panel"),c=document.querySelector("#right-panel"),b=document.querySelector("#panel-divider"),d=document.querySelector("#top-controls"),f=document.querySelector("#bottom-controls"),e=document.documentElement.clientWidth,d=document.documentElement.clientHeight-d.offsetHeight-f.offsetHeight;a.style.height=d-30+"px";c.style.height=d-30+"px";c.style.width=e-b.offsetLeft-20+"px";b.style.height=d+"px"}
function _onBrowserLoad(){document.querySelector("#panel-divider").onmousedown=function(){document.addEventListener("mousemove",onDividerDrag,!1);document.addEventListener("mouseup",onDividerDragFinish,!1)};document.querySelector("#drive-browser").onclick=onItemClick;document.querySelector("#open").onclick=onOpenClick;document.querySelector("#close").onclick=onCloseClick}
function showFolders(){var a=T.FileOperations.extractIdFromGoogleDriveUIUrl(document.querySelector("webview").src);a||(a="root");var c=document.getElementById("tree-wrapper");if(c){c.innerHTML="";selectedFilesCount=lastSelectedFileIndex=0;var b=document.createElement("div");b.className="grdive-loading";b.id="grdive-folders-loading";c.appendChild(b);b=document.createElement("table");c.appendChild(b);c=document.createElement("tr");b.appendChild(c);b=document.createElement("td");b.id="grdive-folders-tree";
c.appendChild(b);updateGDriveFoldersTree(function(){var b=document.getElementById("grdive-folders-loading");b&&(b.style.display="none");$("#grdive-folders-tree").fancytree({source:gdriveFoldersTree,clickFolderMode:3,activate:function(b,a){selectGDRiveFolder(a.node)},checkbox:!1});(b=$("#grdive-folders-tree").fancytree("getTree"))&&(b.getNodeByKey(a)?b.activateKey(a):b.activateKey("root"))});updateGDriveFileList(a)}}
function parentIsSelected(a,c){function b(d){if(!d)return null;if(d.key==a)return[d];if(d.children)for(var c=0;c<d.children.length;++c){var e=b(d.children[c]);if(e)return e.push(d),e}return null}return function(b){if(!b)return!1;var a;for(a=0;a<b.length&&b[a].key!=c;++a);if(a==b.length)return!1;for(a=0;a<b.length;++a){var e=getFolderById(b[a].key);if(e&&!1!==e.active&&e.checked)return!0;if(b[a].key==c)break}return!1}(b(gdriveFoldersTree[0]))}
function resetGDriveFoldersTree(){gdriveFoldersTree=[]}
function updateGDriveFoldersTree(a){function c(a,b,c){for(c=void 0==c?0:c;c<b.length;++c)if(b[c].parents)for(var g=0;g<b[c].parents.length;++g)if(b[c].parents[g].id==a||"root"==a&&b[c].parents[g].isRoot)return c;return-1}function b(a,f,e){var g=null;if("root"==f)a.push({title:"Google Drive",key:"root",expanded:!0}),g=a[0];else{a:{for(g=0;g<e.length;++g)if(e[g].id==f)break a;g=-1}if(0>g)return;a.children||(a.children=[]);a.children.push({title:e[g].title,key:e[g].id,folder:!0});g=a.children[a.children.length-
1]}for(a=c(f,e);0<=a;)b(g,e[a].id,e),a=c(f,e,a+1)}gdriveFoldersTree&&0<gdriveFoldersTree.length?a&&a():T.FileOperations.queryGoogleDriveFiles("mimeType = 'application/vnd.google-apps.folder' and trashed=false",function(c){gdriveFoldersTree=[];c.sort(function(a,b){return a.title.toLowerCase()>b.title.toLowerCase()||a.title.toLowerCase()==b.title.toLowerCase()&&a.title>b.title?1:a.title!==b.title?-1:0});b(gdriveFoldersTree,"root",c);a&&a()})}
function selectGDRiveFolder(a){if(!selectedGDriveFolder||selectedGDriveFolder.id!=a.key){for(var c="",b=a;b&&"Google Drive"!==b.title;b=b.parent)c=c?b.title+"\\"+c:b.title;""==c&&(c="Google Drive");var b=null,d=a.getParent();"root"!==a.key&&d&&(b=d.key);selectedGDriveFolder={id:a.key,name:c,parentId:b};updateGDriveFileList(a.key,b);window.top.postMessage({commit:"https://drive.google.com/#folders/"+a.key},"*")}}
function showFileList(a){var c=document.getElementById("grdive-file-list");c.innerHTML="";unselectAllFiles();for(var b=0;b<a.length;++b){var d=a[b],f=document.createElement("div");f.className="grdive-file";f.id="grdive-"+d.id;f.setAttribute("gdrive_id",d.id);c.appendChild(f);var e=document.createElement("div");e.className="grdive-icon";var g=document.createElement("img");e.appendChild(g);0<d.mimeType.indexOf(".folder")?(g.src="/assets/buttons/folder.png",f.ondblclick=onFolderDblClick,f.setAttribute("type",
"folder")):T.FileOperations.supportedImportExtension(T.FileOperations.extractExtension(d.title))?(g.src="/assets/icons/icon16.png",f.ondblclick=onPartDblClick,f.setAttribute("type","part")):(g.src="/assets/buttons/file.png",f.setAttribute("type","file"));f.appendChild(e);e=document.createElement("div");e.className="grdive-file-title";e.textContent=d.title;f.appendChild(e);e=document.createElement("div");e.className="grdive-file-date";if(d.createdDate||d.modifiedDate)e.textContent=(new Date(d.modifiedDate?
d.modifiedDate:d.createdDate)).toLocaleDateString(),f.appendChild(e);d.shared&&(d=document.createElement("div"),d.className="grdive-file-shared",d.textContent="Shared",f.appendChild(d))}}
function updateGDriveFileList(a,c,b){if(gdriveFileList[a])showFileList(gdriveFileList[a]),b&&b();else{var d=document.getElementById("grdive-files-loading");d&&(d.style.display="inline");T.FileOperations.queryGoogleDriveFiles("trashed=false and '"+a+"' in parents",function(f){d&&(d.style.display="none");gdriveFileList[a]=f;f.sort(function(a,b){var c=4,d=4;0<a.mimeType.indexOf(".folder")?c=0:T.FileOperations.supportedImportExtension(T.FileOperations.extractExtension(a.title))&&(c=2);0<b.mimeType.indexOf(".folder")?
d=0:T.FileOperations.supportedImportExtension(T.FileOperations.extractExtension(b.title))&&(d=2);a.title.toLowerCase()>b.title.toLowerCase()?c+=1:a.title.toLowerCase()==b.title.toLowerCase()&&a.title>b.title?c+=1:a.title!==b.title&&(d+=1);return c-d});c&&f.unshift({title:"..",id:c,mimeType:"application/vnd.google-apps.folder"});showFileList(f);b&&b()})}}function getFileElement(a){for(;a&&"grdive-file"!==a.className&&"grdive-file-selected"!==a.className;)a=a.parentNode;return a}
function extractIdFromEvent(a){if(a=getFileElement(a.target))return a.getAttribute("gdrive_id")}function unselectAllFiles(){var a=document.getElementById("grdive-file-list");if(a){for(var c=0;c<a.childNodes.length;++c){var b=a.childNodes[c];fileIsSelected(b)&&selectFile(b,!1)}document.getElementById("open").className="bbm-button inactive";lastSelectedFileIndex=selectedFilesCount=0}}function getElementIndex(a){var c=a.parentNode;return c?Array.prototype.indexOf.call(c.childNodes,a):0}
function selectFile(a,c){0==c?(a.className="grdive-file",selectedFilesCount=Math.max(selectedFilesCount-1,0)):(a.className="grdive-file-selected",selectedFilesCount++);document.getElementById("open").className=0<selectedFilesCount?"bbm-button":"bbm-button inactive"}function fileIsSelected(a){return"grdive-file-selected"==a.className}
function onItemClick(a){var c=getFileElement(a.target);if(c){a.preventDefault();a.stopPropagation();var b=c.getAttribute("type");if("part"==b||"folder"==b)if(a.shiftKey)for(a=document.getElementById("grdive-file-list"),c=getElementIndex(c),b=Math.max(0,Math.min(c,lastSelectedFileIndex));b<=Math.min(a.childNodes.length-1,Math.max(c,lastSelectedFileIndex));++b)selectFile(a.childNodes[b]);else a.ctrlKey||unselectAllFiles(),lastSelectedFileIndex=getElementIndex(c),fileIsSelected(c)?selectFile(c,!1):selectFile(c,
!0)}else a.ctrlKey&&a.shiftKey||unselectAllFiles()}function onFolderDblClick(a){if(a=extractIdFromEvent(a)){console.log("select",a);var c=$("#grdive-folders-tree").fancytree("getTree");c&&c.activateKey(a)}}function onPartDblClick(a){if(a=extractIdFromEvent(a))window.top.postMessage({newWindow:T.FileOperations.getGoogleDriveDownloadUrlFromID(a)},"*"),setTimeout(function(){window.close()},100)}
function getFileIdsFromFolder(a,c){var b;b="'"+a+"' in parents and trashed=false and (mimeType = 'application/zip' OR mimeType = 'application/vnd.ms-pki.stl'";b+=" OR mimeType = 'application/vnd.ms-pki.obj'";b+=" OR mimeType = 'application/vnd.ms-pki.amf'";b+=" OR mimeType = 'application/vnd.ms-pki.3ds'";b+=" OR mimeType = 'application/vnd.ms-pki.ctm'";b+=" OR mimeType = 'application/vnd.ms-pki.dae'";b+=" OR mimeType = 'application/vnd.ms-pki.ply'";b+=" OR mimeType = 'application/vnd.ms-pki.vtk'";
b+=" OR mimeType = 'application/vnd.ms-pki.babylon'";b+=" OR mimeType = 'application/vnd.ms-pki.wrl'";b+=" OR mimeType = 'application/vnd.ms-pki.thing'";b+=")";foldersToProcess++;T.FileOperations.queryGoogleDriveFiles(b,function(a){foldersToProcess--;for(var b=0;b<a.length;++b)folderIdsList.push(a[b].id);0===foldersToProcess&&c&&c(folderIdsList)})}
function onOpenClick(){var a=document.getElementById("grdive-file-list");if(a){foldersToProcess=0;folderIdsList=[];for(var c=0;c<a.childNodes.length;++c){var b=a.childNodes[c];if(fileIsSelected(b)){var d=b.getAttribute("gdrive_id"),b=b.getAttribute("type");d&&("part"==b?folderIdsList.push(d):"folder"==b&&getFileIdsFromFolder(d,function(a){foldersToProcess=null;window.top.postMessage({openIds:a},"*");setTimeout(function(){window.close()},100)}))}}0===foldersToProcess&&window.top.postMessage({openIds:folderIdsList},
"*");setTimeout(function(){0===foldersToProcess&&window.close()},100)}}function onCloseClick(){window.close()};
