T.Loader3DS=function(){};T.Loader3DS.prototype={constructor:T.Loader3DS,materials:[],meshes:[],nodes:[],masterScale:1,currentFrame:0};
T.Loader3DS.prototype.load=function(a,b){var d=this,c=new XMLHttpRequest;c.addEventListener("load",function(c){if(200===c.target.status||0===c.target.status){var f=d.parse(c.target.response||c.target.responseText);c.target.response=void 0;c.target.responseText=void 0;d.dispatchEvent({type:"load",content:f});b&&b(f)}else d.dispatchEvent({type:"error",message:"Couldn't load URL ["+a+"]",responseStatus:c.target.status})},!1);c.addEventListener("progress",function(a){d.dispatchEvent({type:"progress",
loaded:a.loaded,total:a.total})},!1);c.addEventListener("error",function(){d.dispatchEvent({type:"error",message:"Couldn't load URL ["+a+"]"})},!1);c.overrideMimeType("text/plain; charset=x-user-defined");c.open("GET",a,!0);T.FileOperations.setXHRHeader&&T.FileOperations.setXHRHeader(c,a);c.send(null);return c};T.Loader3DS.prototype.findObjectByName=function(a,b){for(key in a)if(a[key].name==b)return a[key];return!1};T.Loader3DS.prototype.findNodeByParentRef=function(a,b){return 65535==b?!1:a[b]};
T.Loader3DS.prototype.getNodeTransformation=function(a){var b=(new T.Matrix4).makeTranslation(0,0,0);a.positions&&a.positions[0]&&b.multiply((new T.Matrix4).makeTranslation(a.positions[0].x,a.positions[0].y,a.positions[0].z));if(a.rotations&&a.rotations[0]){var d=(new T.V3(a.rotations[0].x,a.rotations[0].y,a.rotations[0].z)).normalize();b.multiply((new T.Matrix4).makeRotationAxis(d,-a.rotations[0].value))}a.scales&&a.scales[0]&&b.multiply((new T.Matrix4).makeScale(a.scales[0].x,a.scales[0].y,a.scales[0].z));
a.pivot&&b.multiply((new T.Matrix4).makeTranslation(-a.pivot.x,-a.pivot.y,-a.pivot.z));return b};T.Loader3DS.prototype.applyLocalTransformation=function(a){if(a.localMatrix){var b=a.localMatrix,d=(new T.Matrix4).getInverse(b);a.applyMatrix(d);if(0>b.determinant())for(b=0,d=a.vertices.length;b<d;b++){var c=a.vertices[b];c.x=-c.x}}};
T.Loader3DS.prototype.setObjectTransformation=function(a,b){if(b&&a){for(var d=b,c=(new T.Matrix4).makeTranslation(0,0,0);d;)c=this.getNodeTransformation(d).multiply(c),d=this.findNodeByParentRef(this.nodes,d.parentRef);a.geometry&&(a.geometry.applyMatrix(c),a.geometry.computeFaceNormals(),a.geometry.computeCentroids(),a.geometry.computeBoundingSphere())}};
T.Loader3DS.prototype.makeHierarchy=function(){function a(c){if(c.object)return c.object;var e;(e=c.mesh)?1<e.nodeReferences?(c.object=new T.Mesh(e.geometry.clone(),e.material.clone()),c.object.name=e.name,c.object.geometry.localMatrix=e.geometry.localMatrix):c.object=e:(c.object=new T.Object3D,c.object.name=c.instanceName?c.instanceName:c.name);e=c.object;if(65535==c.parentRef)return d.push(e),e;c=b.findNodeByParentRef(b.nodes,c.parentRef);if(!c)return d.push(e),e;(c=a(c))&&c.add(e);return e}var b=
this,d=[];(function(){for(var a=0;a<b.nodes.length;++a){var c=b.nodes[a],d=b.findObjectByName(b.meshes,c.name);c.mesh=d;d.nodeReferences=d.nodeReferences?d.nodeReferences+1:1}})();for(var c=0;c<this.nodes.length;++c)a(this.nodes[c]);if(0==d.length)for(d=this.meshes,c=0;c<d.length;++c){var e=d[c];e.geometry&&(e.geometry.computeFaceNormals(),e.geometry.computeCentroids(),e.geometry.computeBoundingSphere())}for(c=0;c<this.nodes.length;++c){var f=this.nodes[c];(e=f.object)&&this.setObjectTransformation(e,
f)}if(1==d.length)return d[0];e=new T.Object3D;for(c=0;c<d.length;++c)e.add(d[c]);return e};T.Loader3DS.prototype.parse=function(a){this._parse(a);for(a=0;a<this.meshes.length;++a){var b=this.meshes[a];b.geometry&&b.geometry.localMatrix&&0>b.geometry.localMatrix.determinant()&&T.GeometryUtils.invertGeometry(b.geometry)}a=this.makeHierarchy();1!=this.masterScale&&(a.scale.multiplyScalar(this.masterScale),a.updateMatrix());return a};T.Loader3DS.prototype._parse=function(a){this.parseBinary(this.ensureBinary(a))};
T.Loader3DS.prototype.readChunk=function(a,b,d){var c=a.getUint16(b,!0),e=a.getUint32(b+2,!0);if(d&&0==d(a,b,c,e))for(c=b+6;c<b+e;)c=this.readChunk(a,c,d);return b+e};T.Loader3DS.prototype.parseString=function(a,b,d){for(var c,e="",f=0;f<d;++f){c=a.getUint8(b+f,!0);if(0==c)break;e+=String.fromCharCode(c)}return e};T.Loader3DS.prototype.parseFloatChunk=function(a,b){return a.getFloat32(b+6,!0)};T.Loader3DS.prototype.parseShortChunk=function(a,b){return a.getUint16(b+6,!0)};
T.Loader3DS.prototype.parseCoordinateChunk=function(a,b){return new T.V3(a.getFloat32(b+6,!0),a.getFloat32(b+10,!0),a.getFloat32(b+14,!0))};T.Loader3DS.prototype.parseFloatColorChunk=function(a,b,d){var c=b+6,e;b=a.getFloat32(c,!0);e=a.getFloat32(c+4,!0);a=a.getFloat32(c+8,!0);d.setRGB(b,e,a)};T.Loader3DS.prototype.parse24BitColorChunk=function(a,b,d){var c=b+6,e;b=a.getUint8(c,!0);e=a.getUint8(c+1,!0);a=a.getUint8(c+2,!0);d.setRGB(b/255,e/255,a/255)};
T.Loader3DS.prototype.parseColorChunk=function(a,b,d,c,e){var f=this;for(d=b+6;d<b+c;)d=this.readChunk(a,d,function(a,b,c,d){switch(c){case 16:f.parseFloatColorChunk(a,b,e);break;case 17:f.parse24BitColorChunk(a,b,e)}return!0})};
T.Loader3DS.prototype.parseLocalAxisChunk=function(a,b){for(var d=b+6,c=[],e,f,g,h=0;4>h;++h)e=a.getFloat32(d,!0),f=a.getFloat32(d+4,!0),g=a.getFloat32(d+8,!0),c.push(new T.V3(e,f,g)),d+=12;return new T.Matrix4(c[0].x,c[1].x,c[2].x,c[3].x,c[0].y,c[1].y,c[2].y,c[3].y,c[0].z,c[1].z,c[2].z,c[3].z,0,0,0,1)};T.Loader3DS.prototype.parseMeshColorChunk=function(a,b,d){d.colorIndex=a.getUint16(b+6,!0)};
T.Loader3DS.prototype.parseVertexListChunk=function(a,b,d){var c=a.getUint16(b+6,!0);b=b+6+2;for(var e,f,g,h=0;h<c;++h)e=a.getFloat32(b,!0),f=a.getFloat32(b+4,!0),g=a.getFloat32(b+8,!0),d.vertices.push(new T.V3(e,f,g)),b+=12};
T.Loader3DS.prototype.parseFaceMaterialChunk=function(a,b,d,c){d=this.parseString(a,b+6,d-6);b=b+d.length+6+1;if((d=this.findObjectByName(this.materials,d))&&c&&c.faces){var e=a.getUint16(b,!0);b+=2;if(e==c.faces.length)c.color=(new T.Color).copy(d.diffuseColor);else{c.useFaceColor=!0;for(var f,g=0;g<e;++g)f=a.getUint16(b,!0),b+=2,f<c.faces.length&&d.diffuseColor&&(c.faces[f].color=d.diffuseColor);c.useFaceColor=!0}}};
T.Loader3DS.prototype.parseFaceListChunk=function(a,b,d,c,e){var f=this;d=a.getUint16(b+6,!0);for(var g=b+6+2,h,l,m,k=0;k<d;++k)h=a.getUint16(g,!0),l=a.getUint16(g+2,!0),m=a.getUint16(g+4,!0),e.faces.push(new T.F3(h,l,m)),g+=8;for(;g<b+c;)g=this.readChunk(a,g,function(a,b,c,d){switch(c){case 16688:f.parseFaceMaterialChunk(a,b,d,e);break;case 16720:break;default:console.log("Face List Chunk 0x4120 >",c.toString(16))}return!0})};
T.Loader3DS.prototype.parseMeshChunk=function(a,b,d,c,e){var f=this;for(d=b+6;d<b+c;)d=this.readChunk(a,d,function(a,b,c,d){switch(c){case 16656:f.parseVertexListChunk(a,b,e);break;case 16672:f.parseFaceListChunk(a,b,c,d,e);break;case 16736:e.localMatrix=f.parseLocalAxisChunk(a,b);break;case 16704:break;default:console.log("Mesh Chunk 0x4100 >",c.toString(16))}return!0})};
T.Loader3DS.prototype.parseObjectChunk=function(a,b,d,c){var e=this.parseString(a,b+6,c-6);d=b+e.length+6+1;for(var f=this;d<b+c;)d=this.readChunk(a,d,function(a,b,c,d){switch(c){case 16640:var k=new T.Geometry;k.sourceType="3ds";f.parseMeshChunk(a,b,c,d,k);a=T.SceneUtils.createMesh(k);a.material.color=k.color?k.color:new T.Color(268435455);f.applyLocalTransformation(k);a.name=e;f.meshes.push(a);break;default:console.log("Object Chunk 0x4000 >",c.toString(16))}return!0})};
T.Loader3DS.prototype.parseHierarchyChunk=function(a,b,d,c){d=this.parseString(a,b+6,d-6);a=a.getUint16(b+d.length+6+1+4,!0);c.name=d;c.parentRef=a};T.Loader3DS.prototype.parseInfoListChunk=function(a,b,d){b+=6;var c=[];a.getUint16(b,!0);b+=10;var e=a.getUint16(b,!0);b+=4;for(var f=0;f<e;++f){var g=a.getUint16(b,!0),h={};b+=6;d&&(h.value=a.getFloat32(b,!0),b+=4);h.x=a.getFloat32(b+0,!0);h.y=a.getFloat32(b+4,!0);h.z=a.getFloat32(b+8,!0);c[g]=h;b+=12}return c};
T.Loader3DS.prototype.parseNodeIDChunk=function(a,b,d){d.id=a.getUint16(b+6,!0)};
T.Loader3DS.prototype.parseNodeChunk=function(a,b,d,c){d=b+6;var e=this,f={};for(e.nodes.push(f);d<b+c;)d=this.readChunk(a,d,function(a,b,c,d){switch(c){case 45072:e.parseHierarchyChunk(a,b,d,f);break;case 45073:f.instanceName=e.parseString(a,b+6,d-6);break;case 45075:f.pivot=e.parseCoordinateChunk(a,b);break;case 45088:f.positions=e.parseInfoListChunk(a,b);break;case 45089:f.rotations=e.parseInfoListChunk(a,b,!0);break;case 45090:f.scales=e.parseInfoListChunk(a,b);break;case 45093:f.colors=e.parseInfoListChunk(a,
b);break;case 45104:e.parseNodeIDChunk(a,b,f);break;case 45076:break;default:console.log("Node Chunk 0xB002 >",c.toString(16))}return!0})};
T.Loader3DS.prototype.parseMaterialChunk=function(a,b,d,c){d=b+6;var e=this,f={};for(this.materials.push(f);d<b+c;)d=this.readChunk(a,d,function(a,b,c,d){switch(c){case 40960:f.name=e.parseString(a,b+6,d-6);break;case 40976:f.ambientColor=new T.Color;e.parseColorChunk(a,b,c,d,f.ambientColor);break;case 40992:f.diffuseColor=new T.Color;e.parseColorChunk(a,b,c,d,f.diffuseColor);break;case 41008:f.specularColor=new T.Color,e.parseColorChunk(a,b,c,d,f.specularColor)}return!0})};
T.Loader3DS.prototype.parseBinary=function(a){reader=new DataView(a);var b=this;this.materials=[];this.meshes=[];this.nodes=[];this.masterScale=1;this.currentFrame=0;this.readChunk(reader,0,function(a,c,e,f){switch(e){case 19789:case 15677:case 45056:return!1;case 45055:b.parseMaterialChunk(a,c,e,f);break;case 16384:b.parseObjectChunk(a,c,e,f);break;case 45058:b.parseNodeChunk(a,c,e,f);break;case 256:b.masterScale=b.parseFloatChunk(a,c);break;case 45065:b.currentFrame=b.parseShortChunk(a,c);break;
case 0:case 2:case 15678:case 5:case 45066:case 45064:break;default:console.log("Generic Chunk >",e.toString(16))}return!0})};T.Loader3DS.prototype.ensureBinary=function(a){if("string"===typeof a){for(var b=new Uint8Array(a.length),d=0;d<a.length;d++)b[d]=a.charCodeAt(d)&255;return b.buffer||b}return a};T.EventDispatcher.prototype.apply(T.Loader3DS.prototype);
