T.AMFLoader=function(p){this.manager=void 0!==p?p:T.DefaultLoadingManager};
T.AMFLoader.prototype={constructor:T.AMFLoader,load:function(p,l,E,A){var B=this,u=new T.XHRLoader(B.manager);u.setCrossOrigin(this.crossOrigin);u.setResponseType("arraybuffer");u.load(p,function(a){l(B.parse(a))},E,A)},parse:function(p,l){function E(q){for(var a="",H=q.attributes.id.textContent,b={r:1,g:1,b:1,a:1},c=null,c=0;c<q.children.length;c++){var d=q.children[c];"metadata"===d.nodeName.toLowerCase()&&void 0!==d.attributes.type?"name"===d.attributes.type.value.toLowerCase()&&(a=d.textContent):
"color"===d.nodeName.toLowerCase()&&(b=A(d))}c=new T.MeshPhongMaterial({shading:T.FlatShading,color:(new T.Color).setRGB(b.r,b.g,b.b),name:a});1!==b.a&&(c.transparent=!0,c.opacity=b.a);return{id:H,material:c}}function A(q){for(var a={r:1,g:1,b:1,a:1},b=0;b<q.children.length;b++){var c=q.children[b];"r"===c.nodeName.toLowerCase()?a.r=c.textContent:"g"===c.nodeName.toLowerCase()?a.g=c.textContent:"b"===c.nodeName.toLowerCase()?a.b=c.textContent:"a"===c.nodeName.toLowerCase()&&(a.a=c.textContent)}return a}
function B(a){var c={name:"",triangles:[],materialid:null},b=a.firstElementChild;void 0!==a.attributes.materialid&&(c.materialId=a.attributes.materialid.nodeValue);for(;b;){if("metadata"===b.nodeName.toLowerCase())void 0!==b.attributes.type&&"name"===b.attributes.type.value.toLowerCase()&&(c.name=b.textContent);else if("triangle"===b.nodeName.toLowerCase()){a=b.getElementsByTagName("v1")[0].textContent;var d=b.getElementsByTagName("v2")[0].textContent,e=b.getElementsByTagName("v3")[0].textContent;
c.triangles.push(a);c.triangles.push(d);c.triangles.push(e)}b=b.nextElementSibling}return c}function u(a){var b,c,d=a.attributes.id.textContent,e={name:"amfobject "+d,meshes:[]},k=null;for(a=a.firstElementChild;a;){if("metadata"===a.nodeName.toLowerCase())void 0!==a.attributes.type&&"name"===a.attributes.type.value.toLowerCase()&&(e.name=a.textContent);else if("color"===a.nodeName.toLowerCase())k=A(a);else if("mesh"===a.nodeName.toLowerCase()){for(var f=a.firstElementChild,g={vertices:[],normals:[],
volumes:[],color:k};f;){if("vertices"===f.nodeName.toLowerCase()){b=[];c=[];for(var h=f.firstElementChild;h;){if("vertex"===h.nodeName.toLowerCase())for(var n=h.firstElementChild;n;){if("coordinates"===n.nodeName.toLowerCase()){var l=n.getElementsByTagName("x")[0].textContent,m=n.getElementsByTagName("y")[0].textContent,p=n.getElementsByTagName("z")[0].textContent;b.push(l);b.push(m);b.push(p)}else"normal"===n.nodeName.toLowerCase()&&(l=n.getElementsByTagName("nx")[0].textContent,m=n.getElementsByTagName("ny")[0].textContent,
p=n.getElementsByTagName("nz")[0].textContent,c.push(l),c.push(m),c.push(p));n=n.nextElementSibling}h=h.nextElementSibling}g.normals=g.normals.concat(c);g.vertices=g.vertices.concat(b)}else"volume"===f.nodeName.toLowerCase()&&g.volumes.push(B(f));f=f.nextElementSibling}e.meshes.push(g)}a=a.nextElementSibling}return{id:d,obj:e}}var a=function(a){a="string"===typeof a?a:(new TextDecoder("utf-8")).decode(new DataView(a));a=(new DOMParser).parseFromString(a,"application/xml");return"amf"!==a.documentElement.nodeName.toLowerCase()?
(console.log("\tError loading AMF - no AMF document found."),null):a}(p);l&&l(10,100);for(var v="",w="",r=function(a){var b=1,c="millimeter";void 0!==a.documentElement.attributes.unit&&(c=a.documentElement.attributes.unit.value.toLowerCase());a={millimeter:1,inch:25.4,feet:304.8,meter:1E3,micron:.001};void 0!==a[c]&&(b=a[c]);console.log("\tUnit scale: "+b);return b}(a),m={},x={},F=0,e=a.documentElement.children,a=0;a<e.length;a++){var c=e[a];"metadata"===c.nodeName.toLowerCase()?void 0!==c.attributes.type&&
("name"===c.attributes.type.value.toLowerCase()?v=c.textContent:"author"===c.attributes.type.value.toLowerCase()&&(w=c.textContent)):"material"===c.nodeName.toLowerCase()?(c=E(c),m[c.id]=c.material):"object"===c.nodeName.toLowerCase()&&(c=u(c),x[c.id]=c.obj,F++);l&&l(10+50*a/e.length,100)}e=new T.Object3D;c=new T.MeshPhongMaterial({color:11184895,shading:T.FlatShading});e.name=v;e.userData.author=w;e.userData.loader="AMF";var v=0,C;for(C in x){var w=x[C].meshes,f;1==F?f=e:(f=new T.Object3D,f.name=
x[C].name);for(a=0;a<w.length;a++){for(var y=c,b=w[a],D=[],a=0,d=b.vertices.length-3;a<=d;a+=3)D.push(new T.V3(parseFloat(b.vertices[a]),parseFloat(b.vertices[a+1]),parseFloat(b.vertices[a+2])));for(var z=[],a=0,d=b.normals.length-3;a<=d;a+=3)z.push(new T.V3(parseFloat(b.normals[a]),parseFloat(b.normals[a+1]),parseFloat(b.normals[a+2])));if(b.color){var g=b.color,y=c.clone();y.color=new T.Color(g.r,g.g,g.b);1!==g.a&&(y.transparent=!0,y.opacity=g.a)}for(var g=b.volumes,t=0;t<g.length;t++){var k=g[t],
b=new T.Geometry;if(0==t)b.vertices=D;else for(b.vertices=[],a=0,d=D.length;a<d;++a)b.vertices.push(D[a].clone());for(var I=a=0,d=k.triangles.length-3;a<=d;a+=3,++I){var h=new T.F3(parseInt(k.triangles[a]),parseInt(k.triangles[a+1]),parseInt(k.triangles[a+2])),G=z.length;h.a<G&&h.b<G&&h.c<G?h.normal.copy(z[h.a]).add(z[h.b]).add(z[h.c]).normalize():T.GeometryUtils.computeFaceNormal.call(b,h);b.faces.push(h)}d=y;void 0!==m[k.materialId]&&(d=m[k.materialId]);b=new T.Mesh(b,d.clone());1==g.length?(f=
b,0<=d.name.toLowerCase().indexOf("material")&&(d.name=""),d.name||k.name?b.name=k.name?k.name:d.name?d.name:"volume "+t:f.name=x[C].name):(b.name=k.name?k.name:d.name?d.name:"volume "+t,f.add(b))}}f.scale.set(r,r,r);f!=e&&e.add(f);l&&l(60+40*v/F,100);++v}return 1==e.children.length?(m=e.children[0],m.scale.set(r,r,r),m.name=e.name,m.userData=e.userData,m):e}};
