T.BinaryLoader=function(n){T.Loader.call(this,n)};T.BinaryLoader.prototype=Object.create(T.Loader.prototype);T.BinaryLoader.prototype.load=function(n,p,h,m){h=h||this.extractUrlBase(n);m=m||this.extractUrlBase(n);var f=this.showProgress?T.Loader.prototype.updateProgress:void 0;this.onLoadStart();this.loadAjaxJSON(this,n,p,h,m,f)};
T.BinaryLoader.prototype.loadAjaxJSON=function(n,p,h,m,f,d){var g=new XMLHttpRequest;m=m&&"string"===typeof m?m:this.extractUrlBase(p);f=f&&"string"===typeof f?f:this.extractUrlBase(p);g.onreadystatechange=function(){if(4==g.readyState)if(200==g.status||0==g.status){var G=JSON.parse(g.responseText);n.loadAjaxBuffers(G,h,f,m,d)}else console.error("T.BinaryLoader: Couldn't load ["+p+"] ["+g.status+"]")};g.open("GET",p,!0);T.FileOperations.setXHRHeader&&T.FileOperations.setXHRHeader(g,p);g.send(null)};
T.BinaryLoader.prototype.loadAjaxBuffers=function(n,p,h,m,f){var d=new XMLHttpRequest,g=h+"/"+n.buffers;d.addEventListener("load",function(g){g=d.response;void 0===g&&(g=(new Uint8Array(d.responseBody)).buffer);if(0==g.byteLength){g=new ArrayBuffer(d.responseText.length);for(var f=new Uint8Array(g),h=0,H=d.responseText.length;h<H;h++)f[h]=d.responseText.charCodeAt(h)&255}T.BinaryLoader.prototype.createBinModel(g,p,m,n.materials)},!1);void 0!==f&&d.addEventListener("progress",function(d){d.lengthComputable&&
f(d)},!1);d.addEventListener("error",function(n){console.error("T.BinaryLoader: Couldn't load ["+g+"] ["+d.status+"]")},!1);d.open("GET",g,!0);T.FileOperations.setXHRHeader&&T.FileOperations.setXHRHeader(d,g);d.responseType="arraybuffer";d.overrideMimeType&&d.overrideMimeType("text/plain; charset=x-user-defined");d.send(null)};
T.BinaryLoader.prototype.createBinModel=function(n,p,h,m){var f=function(d){function g(b){return b%4?4-b%4:0}function h(b,a){return(new Uint8Array(b,a,1))[0]}function f(b,a){return(new Uint32Array(b,a,1))[0]}function m(b,a){var c,k,d,e,f,g,h,l=new Uint32Array(n,a,3*b);for(c=0;c<b;c++)k=l[3*c],d=l[3*c+1],e=l[3*c+2],f=q[2*k],k=q[2*k+1],g=q[2*d],h=q[2*d+1],d=q[2*e],e=q[2*e+1],y.faceVertexUvs[0].push([new T.Vector2(f,k),new T.Vector2(g,h),new T.Vector2(d,e)])}function p(b,a){var c,k,d,e,f,g,h,l,r,m,C=
new Uint32Array(n,a,4*b);for(c=0;c<b;c++)k=C[4*c],d=C[4*c+1],e=C[4*c+2],f=C[4*c+3],g=q[2*k],k=q[2*k+1],h=q[2*d],r=q[2*d+1],l=q[2*e],m=q[2*e+1],e=q[2*f],d=q[2*f+1],f=y.faceVertexUvs[0],f.push([new T.Vector2(g,k),new T.Vector2(h,r),new T.Vector2(e,d)]),f.push([new T.Vector2(h,r),new T.Vector2(l,m),new T.Vector2(e,d)])}function B(b,a,c){var k,d,e,f;a=new Uint32Array(n,a,3*b);var g=new Uint16Array(n,c,b);for(c=0;c<b;c++)k=a[3*c],d=a[3*c+1],e=a[3*c+2],f=g[c],y.faces.push(new T.F3(k,d,e,null,null,f))}function D(b,
a,c){var k,d,e,f,g;a=new Uint32Array(n,a,4*b);var h=new Uint16Array(n,c,b);for(c=0;c<b;c++){k=a[4*c];d=a[4*c+1];e=a[4*c+2];f=a[4*c+3];g=h[c];var l=y;l.faces.push(new T.F3(k,d,f,null,null,g));l.faces.push(new T.F3(d,e,f,null,null,g))}}function E(b,a,c,k){var d,e,f,g,h,m,r;a=new Uint32Array(n,a,3*b);c=new Uint32Array(n,c,3*b);var q=new Uint16Array(n,k,b);for(k=0;k<b;k++){d=a[3*k];e=a[3*k+1];f=a[3*k+2];h=c[3*k];m=c[3*k+1];r=c[3*k+2];g=q[k];var p=l[3*m],t=l[3*m+1];m=l[3*m+2];var u=l[3*r],v=l[3*r+1];r=
l[3*r+2];y.faces.push(new T.F3(d,e,f,[new T.V3(l[3*h],l[3*h+1],l[3*h+2]),new T.V3(p,t,m),new T.V3(u,v,r)],null,g))}}function F(b,a,c,k){var d,e,f,g,h,m,r,q,p;a=new Uint32Array(n,a,4*b);c=new Uint32Array(n,c,4*b);var t=new Uint16Array(n,k,b);for(k=0;k<b;k++){d=a[4*k];e=a[4*k+1];f=a[4*k+2];g=a[4*k+3];m=c[4*k];r=c[4*k+1];q=c[4*k+2];p=c[4*k+3];h=t[k];var u=y,v=l[3*r],w=l[3*r+1];r=l[3*r+2];var z=l[3*q],A=l[3*q+1];q=l[3*q+2];var x=l[3*p],B=l[3*p+1];p=l[3*p+2];u.faces.push(new T.F3(d,e,g,[new T.V3(l[3*m],
l[3*m+1],l[3*m+2]),new T.V3(v,w,r),new T.V3(x,B,p)],null,h));u.faces.push(new T.F3(e,f,g,[new T.V3(v,w,r),new T.V3(z,A,q),new T.V3(x,B,p)],null,h))}}var y=this;d=0;var e,l=[],q=[],v,w,z,A,x,t,u;T.Geometry.call(this);e=function(b,a){for(var c=new Uint8Array(b,a,12),d="",e=0;12>e;e++)d+=String.fromCharCode(c[a+e]);return{signature:d,header_bytes:h(b,a+12),vertex_coordinate_bytes:h(b,a+13),normal_coordinate_bytes:h(b,a+14),uv_coordinate_bytes:h(b,a+15),vertex_index_bytes:h(b,a+16),normal_index_bytes:h(b,
a+17),uv_index_bytes:h(b,a+18),material_index_bytes:h(b,a+19),nvertices:f(b,a+20),nnormals:f(b,a+20+4),nuvs:f(b,a+20+8),ntri_flat:f(b,a+20+12),ntri_smooth:f(b,a+20+16),ntri_flat_uv:f(b,a+20+20),ntri_smooth_uv:f(b,a+20+24),nquad_flat:f(b,a+20+28),nquad_smooth:f(b,a+20+32),nquad_flat_uv:f(b,a+20+36),nquad_smooth_uv:f(b,a+20+40)}}(n,d);d+=e.header_bytes;t=3*e.vertex_index_bytes+e.material_index_bytes;u=4*e.vertex_index_bytes+e.material_index_bytes;v=e.ntri_flat*t;w=e.ntri_smooth*(t+3*e.normal_index_bytes);
z=e.ntri_flat_uv*(t+3*e.uv_index_bytes);A=e.ntri_smooth_uv*(t+3*e.normal_index_bytes+3*e.uv_index_bytes);x=e.nquad_flat*u;t=e.nquad_smooth*(u+4*e.normal_index_bytes);u=e.nquad_flat_uv*(u+4*e.uv_index_bytes);d+=function(b){var a=e.nvertices;b=new Float32Array(n,b,3*a);var c,d,f,g;for(c=0;c<a;c++)d=b[3*c],f=b[3*c+1],g=b[3*c+2],y.vertices.push(new T.V3(d,f,g));return 3*a*Float32Array.BYTES_PER_ELEMENT}(d);d+=function(b){var a=e.nnormals;if(a){b=new Int8Array(n,b,3*a);var c,d,f,g;for(c=0;c<a;c++)d=b[3*
c],f=b[3*c+1],g=b[3*c+2],l.push(d/127,f/127,g/127)}return 3*a*Int8Array.BYTES_PER_ELEMENT}(d);d+=g(3*e.nnormals);d+=function(b){var a=e.nuvs;if(a){b=new Float32Array(n,b,2*a);var c,d,f;for(c=0;c<a;c++)d=b[2*c],f=b[2*c+1],q.push(d,f)}return 2*a*Float32Array.BYTES_PER_ELEMENT}(d);v=d+v+g(2*e.ntri_flat);w=v+w+g(2*e.ntri_smooth);z=w+z+g(2*e.ntri_flat_uv);A=z+A+g(2*e.ntri_smooth_uv);x=A+x+g(2*e.nquad_flat);t=x+t+g(2*e.nquad_smooth);u=t+u+g(2*e.nquad_flat_uv);(function(b){var a=e.ntri_flat_uv;if(a){var c=
b+a*Uint32Array.BYTES_PER_ELEMENT*3;B(a,b,c+a*Uint32Array.BYTES_PER_ELEMENT*3);m(a,c)}})(w);(function(b){var a=e.ntri_smooth_uv;if(a){var c=b+a*Uint32Array.BYTES_PER_ELEMENT*3,d=c+a*Uint32Array.BYTES_PER_ELEMENT*3;E(a,b,c,d+a*Uint32Array.BYTES_PER_ELEMENT*3);m(a,d)}})(z);(function(b){var a=e.nquad_flat_uv;if(a){var c=b+a*Uint32Array.BYTES_PER_ELEMENT*4;D(a,b,c+a*Uint32Array.BYTES_PER_ELEMENT*4);p(a,c)}})(t);(function(b){var a=e.nquad_smooth_uv;if(a){var c=b+a*Uint32Array.BYTES_PER_ELEMENT*4,d=c+a*
Uint32Array.BYTES_PER_ELEMENT*4;F(a,b,c,d+a*Uint32Array.BYTES_PER_ELEMENT*4);p(a,d)}})(u);(function(b){var a=e.ntri_flat;a&&B(a,b,b+a*Uint32Array.BYTES_PER_ELEMENT*3)})(d);(function(b){var a=e.ntri_smooth;if(a){var c=b+a*Uint32Array.BYTES_PER_ELEMENT*3;E(a,b,c,c+a*Uint32Array.BYTES_PER_ELEMENT*3)}})(v);(function(b){var a=e.nquad_flat;a&&D(a,b,b+a*Uint32Array.BYTES_PER_ELEMENT*4)})(A);(function(b){var a=e.nquad_smooth;if(a){var c=b+a*Uint32Array.BYTES_PER_ELEMENT*4;F(a,b,c,c+a*Uint32Array.BYTES_PER_ELEMENT*
4)}})(x);this.computeCentroids();this.computeFaceNormals()};f.prototype=Object.create(T.Geometry.prototype);f=new f(h);h=this.initMaterials(m,h);this.needsTangents(h)&&f.computeTangents();p(f,h)};
