T.MTLLoader=function(a,b,c){this.baseUrl=a;this.options=b;this.crossOrigin=c};
T.MTLLoader.prototype={constructor:T.MTLLoader,load:function(a,b,c,g){var d=this;c=new T.XHRLoader;c.setCrossOrigin(this.crossOrigin);c.load(a,function(a){b(d.parse(a))})},parse:function(a){var b=a.split("\n"),c={},g=/\s+/;a={};for(var d=0;d<b.length;d++){var e=b[d],e=e.trim();if(0!==e.length&&"#"!==e.charAt(0)){var h=e.indexOf(" "),f=0<=h?e.substring(0,h):e,f=f.toLowerCase(),e=0<=h?e.substring(h+1):"",e=e.trim();"newmtl"===f?(c={name:e},a[e]=c):c&&("ka"===f||"kd"===f||"ks"===f?(e=e.split(g,3),c[f]=
[parseFloat(e[0]),parseFloat(e[1]),parseFloat(e[2])]):c[f]=e)}}b=new T.MTLLoader.MaterialCreator(this.baseUrl,this.options);b.setMaterials(a);return b}};T.MTLLoader.MaterialCreator=function(a,b){this.baseUrl=a;this.options=b;this.materialsInfo={};this.materials={};this.materialsArray=[];this.nameLookup={};this.side=this.options&&this.options.side?this.options.side:T.FrontSide;this.wrap=this.options&&this.options.wrap?this.options.wrap:T.RepeatWrapping};
T.MTLLoader.MaterialCreator.prototype={constructor:T.MTLLoader.MaterialCreator,setMaterials:function(a){this.materialsInfo=this.convert(a);this.materials={};this.materialsArray=[];this.nameLookup={}},convert:function(a){if(!this.options)return a;var b={},c;for(c in a){var g=a[c],d={};b[c]=d;for(var e in g){var h=!0,f=g[e],k=e.toLowerCase();switch(k){case "kd":case "ka":case "ks":this.options&&this.options.normalizeRGB&&(f=[f[0]/255,f[1]/255,f[2]/255]);this.options&&this.options.ignoreZeroRGBs&&0===
f[0]&&0===f[1]&&0===f[1]&&(h=!1);break;case "d":this.options&&this.options.invertTransparency&&(f=1-f)}h&&(d[k]=f)}}return b},preload:function(){for(var a in this.materialsInfo)this.create(a)},getIndex:function(a){return this.nameLookup[a]},getAsArray:function(){var a=0,b;for(b in this.materialsInfo)this.materialsArray[a]=this.create(b),this.nameLookup[b]=a,a++;return this.materialsArray},create:function(a){void 0===this.materials[a]&&this.createMaterial_(a);return this.materials[a]},createMaterial_:function(a){var b=
this.materialsInfo[a],c={name:a,side:this.side},g;for(g in b){var d=b[g];switch(g.toLowerCase()){case "kd":c.diffuse=(new T.Color).fromArray(d);break;case "ka":c.ambient=(new T.Color).fromArray(d);break;case "ks":c.specular=(new T.Color).fromArray(d);break;case "map_kd":c.map=this.loadTexture(this.baseUrl+d);c.map.wrapS=this.wrap;c.map.wrapT=this.wrap;break;case "ns":c.shininess=d;break;case "d":1>d&&(c.transparent=!0,c.opacity=d)}}c.diffuse&&(c.ambient||(c.ambient=c.diffuse),c.color=c.diffuse);this.materials[a]=
new T.ObjectMaterial(c);return this.materials[a]},loadTexture:function(a,b,c,g){if(/\.dds$/i.test(a))var d=T.ImageUtils.loadCompressedTexture(a,b,c,g);else g=new Image,d=new T.Texture(g,b),b=new T.ImageLoader,b.crossOrigin=this.crossOrigin,b.load(a,function(a){d.image=T.MTLLoader.ensurePowerOfTwo_(a);d.needsUpdate=!0;c&&c(d)});return d}};
T.MTLLoader.ensurePowerOfTwo_=function(a){if(!T.MTLLoader.isPowerOfTwo_(a.width)||!T.MTLLoader.isPowerOfTwo_(a.height)){var b=document.createElement("canvas");b.width=T.MTLLoader.nextHighestPowerOfTwo_(a.width);b.height=T.MTLLoader.nextHighestPowerOfTwo_(a.height);b.getContext("2d").drawImage(a,0,0,a.width,a.height,0,0,b.width,b.height);return b}return a};T.MTLLoader.isPowerOfTwo_=function(a){return 0===(a&a-1)};
T.MTLLoader.nextHighestPowerOfTwo_=function(a){--a;for(var b=1;32>b;b<<=1)a|=a>>b;return a+1};T.EventDispatcher.prototype.apply(T.MTLLoader.prototype);
