T.OBJLoader=function(b){this.manager=void 0!==b?b:T.DefaultLoadingManager};
T.OBJLoader.prototype={constructor:T.OBJLoader,load:function(b,p,q,l){var e=this,f=new T.XHRLoader(e.manager);f.setCrossOrigin(this.crossOrigin);return f.load(b,function(b){p(e.parse(b))},q,l)},parse:function(b){function p(a,b,c){return new T.V3(a,b,c)}function q(a,b){return new T.Vector2(a,b)}function l(a,b,c,d){return new T.F3(a,b,c,d)}b=b.replace(/\ \\\r\n/g,"");var e="/f$1$2$3\n/f$3$4$5\n/f$5$6$1\n/f$1$3$5";b=b.replace(/f( +\d+)( +\d+)( +\d+)( +\d+)( +\d+)( +\d+)/g,e);b=b.replace(/f( +\d+\/\d+)( +\d+\/\d+)( +\d+\/\d+)( +\d+\/\d+)( +\d+\/\d+)( +\d+\/\d+)/g,
e);b=b.replace(/f( +\d+\/\d+\/\d+)( +\d+\/\d+\/\d+)( +\d+\/\d+\/\d+)( +\d+\/\d+\/\d+)( +\d+\/\d+\/\d+)( +\d+\/\d+\/\d+)/g,e);b=b.replace(/f( +\d+\/\/\d+)( +\d+\/\/\d+)( +\d+\/\/\d+)( +\d+\/\/\d+)( +\d+\/\/\d+)( +\d+\/\/\d+)/g,e);e="/f$1$2$5\n/f$5$2$3\n/f$3$4$5";b=b.replace(/f( +\d+)( +\d+)( +\d+)( +\d+)( +\d+)/g,e);b=b.replace(/f( +\d+\/\d+)( +\d+\/\d+)( +\d+\/\d+)( +\d+\/\d+)( +\d+\/\d+)/g,e);b=b.replace(/f( +\d+\/\d+\/\d+)( +\d+\/\d+\/\d+)( +\d+\/\d+\/\d+)( +\d+\/\d+\/\d+)( +\d+\/\d+\/\d+)/g,e);
b=b.replace(/f( +\d+\/\/\d+)( +\d+\/\/\d+)( +\d+\/\/\d+)( +\d+\/\/\d+)( +\d+\/\/\d+)/g,e);e="/f$1$2$3\n/f$3$4$1";b=b.replace(/f( +\d+)( +\d+)( +\d+)( +\d+)/g,e);b=b.replace(/f( +\d+\/\d+)( +\d+\/\d+)( +\d+\/\d+)( +\d+\/\d+)/g,e);b=b.replace(/f( +\d+\/\d+\/\d+)( +\d+\/\d+\/\d+)( +\d+\/\d+\/\d+)( +\d+\/\d+\/\d+)/g,e);b=b.replace(/f( +\d+\/\/\d+)( +\d+\/\/\d+)( +\d+\/\/\d+)( +\d+\/\/\d+)/g,e);var e=new T.Object3D,f,m,c;!1===/^o /gm.test(b)&&(f=new T.Geometry,m=T.SceneUtils.createDefaultMaterials()[0],
c=T.SceneUtils.createMesh(f,m),e.add(c));var g=[];c=0;var h=[],k=[],t=/v( +[\d|\.|\+|\-|e]+)( +[\d|\.|\+|\-|e]+)( +[\d|\.|\+|\-|e]+)/,u=/vn( +[\d|\.|\+|\-|e]+)( +[\d|\.|\+|\-|e]+)( +[\d|\.|\+|\-|e]+)/,v=/vt( +[\d|\.|\+|\-|e]+)( +[\d|\.|\+|\-|e]+)/,w=/f( +\d+)( +\d+)( +\d+)/,x=/f( +(\d+)\/(\d+))( +(\d+)\/(\d+))( +(\d+)\/(\d+))/,y=/f( +(\d+)\/(\d+)\/(\d+))( +(\d+)\/(\d+)\/(\d+))( +(\d+)\/(\d+)\/(\d+))/,z=/f( +(\d+)\/\/(\d+))( +(\d+)\/\/(\d+))( +(\d+)\/\/(\d+))/,r=b.split("\n");for(b=0;b<r.length;b++){var d=
r[b],d=d.trim(),a;if(0!==d.length&&"#"!==d.charAt(0))if(null!==(a=t.exec(d)))g.push(p(parseFloat(a[1]),parseFloat(a[2]),parseFloat(a[3])));else if(null!==(a=u.exec(d)))h.push(p(parseFloat(a[1]),parseFloat(a[2]),parseFloat(a[3])));else if(null!==(a=v.exec(d)))k.push(q(parseFloat(a[1]),parseFloat(a[2])));else if(null!==(a=w.exec(d)))f.vertices.push(g[parseInt(a[1])-1],g[parseInt(a[2])-1],g[parseInt(a[3])-1]),f.faces.push(l(c++,c++,c++));else if(null!==(a=x.exec(d))){f.vertices.push(g[parseInt(a[2])-
1],g[parseInt(a[5])-1],g[parseInt(a[8])-1]);f.faces.push(l(c++,c++,c++));var d=parseInt(a[3]-1),n=parseInt(a[6]-1);a=parseInt(a[9]-1);k.length>Math.max(d,n,a)&&f.faceVertexUvs[0].push([k[d],k[n],k[a]])}else null!==(a=y.exec(d))?(f.vertices.push(g[parseInt(a[2])-1],g[parseInt(a[6])-1],g[parseInt(a[10])-1]),f.faces.push(parseInt(a[4])-1<h.length||parseInt(a[8])-1<h.length||parseInt(a[12])-1<h.length?l(c++,c++,c++,[h[parseInt(a[4])-1],h[parseInt(a[8])-1],h[parseInt(a[12])-1]]):l(c++,c++,c++)),d=parseInt(a[3]-
1),n=parseInt(a[7]-1),a=parseInt(a[11]-1),k.length>Math.max(d,n,a)&&f.faceVertexUvs[0].push([k[d],k[n],k[a]])):null!==(a=z.exec(d))?(f.vertices.push(g[parseInt(a[2])-1],g[parseInt(a[5])-1],g[parseInt(a[8])-1]),f.faces.push(parseInt(a[3])-1<h.length||parseInt(a[6])-1<h.length||parseInt(a[9])-1<h.length?l(c++,c++,c++,[h[parseInt(a[3])-1],h[parseInt(a[6])-1],h[parseInt(a[9])-1]]):l(c++,c++,c++))):/^o /.test(d)?(f=new T.Geometry,m=T.SceneUtils.createDefaultMaterials()[0],c=T.SceneUtils.createMesh(f,m),
c.name=d.substring(2).trim(),e.add(c),c=0):/^g /.test(d)||(/^usemtl /.test(d)?m.name=d.substring(7).trim():/^mtllib /.test(d)||/^s /.test(d)||console.log("T.OBJLoader: Unhandled line "+d))}b=0;for(m=e.children.length;b<m;b++)f=e.children[b].geometry,f.computeCentroids(),f.computeFaceNormals(),f.computeBoundingSphere();return e}};
