T.PLYLoader=function(){};
T.PLYLoader.prototype={constructor:T.PLYLoader,load:function(a,d){var b=this,c=new XMLHttpRequest;c.addEventListener("load",function(c){200===c.target.status||0===c.target.status?(c=b.parse(c.target.response||c.target.responseText),b.dispatchEvent({type:"load",content:c}),d&&d(c)):b.dispatchEvent({type:"error",message:"Couldn't load URL ["+a+"]",responseStatus:c.target.status})},!1);c.addEventListener("progress",function(a){b.dispatchEvent({type:"progress",loaded:a.loaded,total:a.total})},!1);c.addEventListener("error",
function(){b.dispatchEvent({type:"error",message:"Couldn't load URL ["+a+"]"})},!1);c.overrideMimeType("text/plain; charset=x-user-defined");c.open("GET",a,!0);T.FileOperations.setXHRHeader&&T.FileOperations.setXHRHeader(c,a);c.send(null);return c},ensureString:function(a){if("string"!==typeof a){for(var d=new Uint8Array(a),b=[],c=0;c<a.byteLength;c++)b.push(String.fromCharCode(d[c]));return b.join("")}return a},ensureBinary:function(a){if("string"===typeof a){for(var d=new Uint8Array(a.length),b=
0;b<a.length;b++)d[b]=a.charCodeAt(b)&255;return d.buffer||d}return a},getStringHeader:function(a){if("string"!==typeof a){var d=new Uint8Array(a),b=[];a=Math.min(a.byteLength,8192);for(var c=0;c<a;c++)b.push(String.fromCharCode(d[c]));return b.join("")}return a},isASCII:function(a){return"ascii"===this.parseHeader(this.getStringHeader(a)).format},parse:function(a){return this.isASCII(a)?this.parseASCII(this.ensureString(a)):this.parseBinary(this.ensureBinary(a))},parseHeader:function(a){function d(a){var b=
{};b.type=a[0];"list"===b.type?(b.name=a[3],b.countType=a[1],b.itemType=a[2]):b.name=a[1];return b}var b={comments:[],elements:[],headerLength:0};a=a.substring(0,Math.min(a.length,8192));var c=a.indexOf("ply"),c=0<=c?c:a.indexOf("PLY"),g=a.indexOf("end_header"),g=0<=g?g:a.indexOf("END_HEADER");if(c>g||0>c||0>g)return b;headerText=a.substring(c+3,g);b.headerEnds=g+11;b.headerLength=g-c+11;a=headerText.split("\n");for(var c=void 0,e,f=0;f<a.length;f++){var h=a[f],h=h.trim();if(""!==h)switch(e=h.split(/\s+/),
g=e.shift(),h=e.join(" "),g){case "format":b.format=e[0];b.version=e[1];break;case "comment":b.comments.push(h);break;case "element":void 0!==c&&b.elements.push(c);c={};c.name=e[0];c.count=parseInt(e[1]);c.properties=[];break;case "property":c.properties.push(d(e));break;default:console.log("unhandled",g,e)}}void 0!==c&&b.elements.push(c);return b},parseASCIINumber:function(a,d){switch(d){case "char":case "uchar":case "short":case "ushort":case "int":case "uint":case "int8":case "uint8":case "int16":case "uint16":case "int32":case "uint32":return parseInt(a);
case "float":case "double":case "float32":case "float64":return parseFloat(a)}},parseASCIIElement:function(a,d){values=d.split(/\s+/);for(var b={},c=0;c<a.length;c++)if("list"===a[c].type){var g=[],e=this.parseASCIINumber(values.shift(),a[c].countType);for(j=0;j<e;j++)g.push(this.parseASCIINumber(values.shift(),a[c].itemType));b[a[c].name]=g}else b[a[c].name]=this.parseASCIINumber(values.shift(),a[c].type);return b},parseASCII:function(a){var d=new T.Geometry,b=this.parseHeader(a);a=a.substring(b.headerEnds).split("\n");
var c=0,g=0;d.useColor=!1;for(var e=0;e<a.length;e++){var f=a[e],f=f.trim();""!==f&&(g>=b.elements[c].count&&(c++,g=0),f=this.parseASCIIElement(b.elements[c].properties,f),this.handleElement(d,b.elements[c].name,f),g++)}return this.postProcess(d)},postProcess:function(a){if(a.useVertexColor){for(var d=0;d<a.faces.length;d++)a.faces[d].vertexColors=[a.colors[a.faces[d].a],a.colors[a.faces[d].b],a.colors[a.faces[d].c]];a.elementsNeedUpdate=!0}a.computeFaceNormals();a.computeCentroids();a.computeBoundingSphere();
return a},handleElement:function(a,d,b){"vertex"===d?(a.vertices.push(new T.V3(b.x,b.y,b.z)),"red"in b&&"green"in b&&"blue"in b&&(a.useVertexColor=!0,color=new T.Color,color.setRGB(b.red/255,b.green/255,b.blue/255),a.colors.push(color))):"face"===d&&("red"in b&&"green"in b&&"blue"in b?(a.useFaceColor=!0,color=new T.Color,color.setRGB(b.red/255,b.green/255,b.blue/255),a.faces.push(new T.F3(b.vertex_indices[0],b.vertex_indices[1],b.vertex_indices[2],void 0,color))):a.faces.push(new T.F3(b.vertex_indices[0],
b.vertex_indices[1],b.vertex_indices[2])))},binaryRead:function(a,d,b,c){switch(b){case "int8":case "char":return[a.getInt8(d),1];case "uint8":case "uchar":return[a.getUint8(d),1];case "int16":case "short":return[a.getInt16(d,c),2];case "uint16":case "ushort":return[a.getUint16(d,c),2];case "int32":case "int":return[a.getInt32(d,c),4];case "uint32":case "uint":return[a.getUint32(d,c),4];case "float32":case "float":return[a.getFloat32(d,c),4];case "float64":case "double":return[a.getFloat64(d,c),8]}},
binaryReadElement:function(a,d,b,c){for(var g={},e,f=0,h=0;h<b.length;h++)if("list"===b[h].type){var k=[];e=this.binaryRead(a,d+f,b[h].countType,c);var l=e[0],f=f+e[1];for(j=0;j<l;j++)e=this.binaryRead(a,d+f,b[h].itemType,c),k.push(e[0]),f+=e[1];g[b[h].name]=k}else e=this.binaryRead(a,d+f,b[h].type,c),g[b[h].name]=e[0],f+=e[1];return[g,f]},parseBinary:function(a){var d=new T.Geometry,b=this.parseHeader(this.ensureString(a)),c="binary_little_endian"===b.format;a=new DataView(a,b.headerLength);for(var g,
e=0,f=0;f<b.elements.length;f++)for(var h=0;h<b.elements[f].count;h++)g=this.binaryReadElement(a,e,b.elements[f].properties,c),e+=g[1],this.handleElement(d,b.elements[f].name,g[0]);return this.postProcess(d)}};T.EventDispatcher.prototype.apply(T.PLYLoader.prototype);
