T.STLLoader=function(){};T.STLLoader.prototype={constructor:T.STLLoader};
T.STLLoader.prototype.load=function(b,d){var a=this,c=new XMLHttpRequest;c.addEventListener("load",function(c){if(200===c.target.status||0===c.target.status){var e=a.parse(c.target.response||c.target.responseText);c.target.response=void 0;c.target.responseText=void 0;a.dispatchEvent({type:"load",content:e});d&&d(e)}else a.dispatchEvent({type:"error",message:"Couldn't load URL ["+b+"]",responseStatus:c.target.status})},!1);c.addEventListener("progress",function(b){a.dispatchEvent({type:"progress",
loaded:b.loaded,total:b.total})},!1);c.addEventListener("error",function(){a.dispatchEvent({type:"error",message:"Couldn't load URL ["+b+"]"})},!1);c.overrideMimeType("text/plain; charset=x-user-defined");c.open("GET",b,!0);T.FileOperations.setXHRHeader&&T.FileOperations.setXHRHeader(c,b);a.xhrSetup&&a.xhrSetup(c);c.send(null);return c};
T.STLLoader.prototype.parse=function(b){function d(a,b){a.sourceType="stl";var c=T.SceneUtils.createMesh(a);void 0!==b&&(c.name="Part_"+b.toString());a.color&&(c.material.color=a.color);return c}if((b=this._parse(b))&&b.length&&!(0>=b.length)){if(1==b.length)return d(b[0]);for(var a=new T.Object3D,c=0;c<b.length;++c)a.add(d(b[c],c));return a}};
T.STLLoader.prototype._parse=function(b){var d=b.length?b.length:b.byteLength?b.byteLength:b.size,a=this.getBinaryHeader(b),c;var f,a=new DataView(a);try{f=a.getUint32(80,!0),c=84+50*f===d}catch(e){c=!1}return c?this.parseBinary(this.ensureBinary(b)):[this.parseASCII(this.ensureString(b))]};
T.STLLoader.prototype.parseBinary=function(b){var d,a,c,f,e,g,h=[];b=new DataView(b);var q=0,l=null,k=null,p=!0,n=searchInDataView(b,"COLOR=",0,80);if(0<=n){var k=b.getUint8(n+6,!0),m=b.getUint8(n+7,!0);d=b.getUint8(n+8,!0);k=(new T.Color).setRGB(k/255,m/255,d/255)}m=[];d=searchInDataView(b,"PARTS=",0,80);if(0<=d)for(d+=6;76>=d;d+=4){a=b.getUint32(d,!0);if(0==a)break;m.push(a)}facesTotal=b.getUint32(80,!0);a=new T.Geometry;k&&(a.color=(new T.Color).copy(k));h.push(a);for(d=0;d<facesTotal;d++){c=84+
50*d;f=new T.V3(b.getFloat32(c,!0),b.getFloat32(c+4,!0),b.getFloat32(c+8,!0));for(e=1;3>=e;e++)g=c+12*e,a.vertices.push(new T.V3(b.getFloat32(g,!0),b.getFloat32(g+4,!0),b.getFloat32(g+8,!0)));c=b.getUint16(g+12,!0);0==c>>15!=0>n?(0<c&&(a.useFaceColor=!0),e=new T.Color,e.setRGB((c&31)/31,(c>>5&31)/31,(c>>10&31)/31),null==l?l=(new T.Color).copy(e):e.getHex()!==l.getHex()&&(p=!1)):e=null;c=a.vertices.length;0==f.length()&&++q;a.faces.push(new T.F3(c-3,c-2,c-1,f,e));if(d+1==facesTotal||0<m.length&&a.faces.length==
m[0])p&&null!==l&&(a.useFaceColor=!1,a.color=(new T.Color).copy(l)),p=!0,l=null,0<q&&a.computeFaceNormals(),a.computeCentroids(),a.computeBoundingSphere(),a=new T.Geometry,k&&(a.color=(new T.Color).copy(k)),h.push(a),m.shift()}0<h.length&&0==h[h.length-1].faces.length&&h.pop();return h};
T.STLLoader.prototype.parseASCII=function(b){var d,a,c,f,e,g;d=new T.Geometry;for(f=/facet([\s\S]*?)endfacet/g;null!=(a=f.exec(b));){g=a[0];for(e=/normal[\s]+([\-+]?[0-9]+\.?[0-9]*([eE][\-+]?[0-9]+)?)+[\s]+([\-+]?[0-9]*\.?[0-9]+([eE][\-+]?[0-9]+)?)+[\s]+([\-+]?[0-9]*\.?[0-9]+([eE][\-+]?[0-9]+)?)+/g;null!=(a=e.exec(g));)c=new T.V3(parseFloat(a[1]),parseFloat(a[3]),parseFloat(a[5]));for(e=/vertex[\s]+([\-+]?[0-9]+\.?[0-9]*([eE][\-+]?[0-9]+)?)+[\s]+([\-+]?[0-9]*\.?[0-9]+([eE][\-+]?[0-9]+)?)+[\s]+([\-+]?[0-9]*\.?[0-9]+([eE][\-+]?[0-9]+)?)+/g;null!=
(a=e.exec(g));)d.vertices.push(new T.V3(parseFloat(a[1]),parseFloat(a[3]),parseFloat(a[5])));a=d.vertices.length;d.faces.push(new T.F3(a-3,a-2,a-1,c))}d.computeCentroids();d.computeBoundingBox();d.computeBoundingSphere();return d};T.STLLoader.prototype.ensureString=function(b){if("string"!==typeof b){for(var d=new Uint8Array(b),a=[],c=0;c<b.byteLength;c++)a.push(String.fromCharCode(d[c]));return a.join("")}return b};
T.STLLoader.prototype.ensureBinary=function(b){if("string"===typeof b){for(var d=new Uint8Array(b.length),a=0,c=b.length;a<c;a++)d[a]=b.charCodeAt(a)&255;return d.buffer||d}return b};T.STLLoader.prototype.getBinaryHeader=function(b){if("string"===typeof b){for(var d=Math.min(b.length,84),a=new Uint8Array(d),c=0;c<d;c++)a[c]=b.charCodeAt(c)&255;return a.buffer||a}return b};T.EventDispatcher.prototype.apply(T.STLLoader.prototype);
