T.UTF8Loader=function(){};T.UTF8Loader.prototype.load=function(b,a,c){this.downloadModelJson(b,c,a)};T.UTF8Loader.BufferGeometryCreator=function(){};
T.UTF8Loader.BufferGeometryCreator.prototype.create=function(b,a){var c=a.length/3,f=new T.BufferGeometry,e=new Float32Array(9*c),h=new Float32Array(9*c),c=new Float32Array(6*c),d,g,l,k,m,n=b.length;for(d=g=0;d<n;d+=8)l=b[d],k=b[d+1],m=b[d+2],e[g++]=l,e[g++]=k,e[g++]=m;g=0;for(d=3;d<n;d+=8)l=b[d],k=b[d+1],c[g++]=l,c[g++]=k;g=0;for(d=5;d<n;d+=8)l=b[d],k=b[d+1],m=b[d+2],h[g++]=l,h[g++]=k,h[g++]=m;d=f.attributes;d.index={itemSize:1,array:a,numItems:a.length};d.position={itemSize:3,array:e,numItems:e.length};
d.normal={itemSize:3,array:h,numItems:h.length};d.uv={itemSize:2,array:c,numItems:c.length};f.offsets=[{start:0,count:a.length,index:0}];f.computeBoundingSphere();return f};T.UTF8Loader.GeometryCreator=function(){};
T.UTF8Loader.GeometryCreator.prototype={create:function(b,a){var c=new T.Geometry;this.init_vertices(c,b,8,0);var f=this.init_uvs(b,8,3),e=this.init_normals(b,8,5);this.init_faces(c,e,f,a);c.computeCentroids();c.computeFaceNormals();return c},init_vertices:function(b,a,c,f){for(var e,h,d,g=a.length;f<g;f+=c)e=a[f],h=a[f+1],d=a[f+2],this.addVertex(b,e,h,d)},init_normals:function(b,a,c){for(var f=[],e,h,d,g=b.length;c<g;c+=a)e=b[c],h=b[c+1],d=b[c+2],f.push(e,h,d);return f},init_uvs:function(b,a,c){for(var f=
[],e,h,d=b.length;c<d;c+=a)e=b[c],h=b[c+1],f.push(e,h);return f},init_faces:function(b,a,c,f){var e,h,d,g,l,k,m,n=f.length;for(e=0;e<n;e+=3)h=f[e],d=f[e+1],g=f[e+2],this.f3n(b,a,h,d,g,0,h,d,g),l=c[2*h],h=c[2*h+1],k=c[2*d],d=c[2*d+1],m=c[2*g],g=c[2*g+1],this.uv3(b.faceVertexUvs[0],l,h,k,d,m,g)},addVertex:function(b,a,c,f){b.vertices.push(new T.V3(a,c,f))},f3n:function(b,a,c,f,e,h,d,g,l){var k=a[3*g],m=a[3*g+1],n=a[3*g+2];g=a[3*l];var q=a[3*l+1];l=a[3*l+2];a=new T.V3(a[3*d],a[3*d+1],a[3*d+2]);k=new T.V3(k,
m,n);m=new T.V3(g,q,l);b.faces.push(new T.F3(c,f,e,[a,k,m],null,h))},uv3:function(b,a,c,f,e,h,d){var g=[];g.push(new T.Vector2(a,c));g.push(new T.Vector2(f,e));g.push(new T.Vector2(h,d));b.push(g)}};var DEFAULT_DECODE_PARAMS={decodeOffsets:[-4095,-4095,-4095,0,0,-511,-511,-511],decodeScales:[1/8191,1/8191,1/8191,1/1023,1/1023,1/1023,1/1023,1/1023]};
T.UTF8Loader.prototype.decompressAttribsInner_=function(b,a,c,f,e,h,d,g){for(var l=0;a<c;a++){var k=b.charCodeAt(a),l=l+(k>>1^-(k&1));f[e]=g*(l+d);e+=h}};T.UTF8Loader.prototype.decompressIndices_=function(b,a,c,f,e){for(var h=0,d=0;d<c;d++){var g=b.charCodeAt(a++);f[e++]=h-g;0===g&&h++}};
T.UTF8Loader.prototype.decompressAABBs_=function(b,a,c,f,e){var h=6*c;c=a+h;for(var d=0,h=new Float32Array(h);a<c;a+=6){var g=b.charCodeAt(a+0)+f[0],l=b.charCodeAt(a+1)+f[1],k=b.charCodeAt(a+2)+f[2],m=b.charCodeAt(a+3)+1>>1,n=b.charCodeAt(a+4)+1>>1,q=b.charCodeAt(a+5)+1>>1;h[d++]=e[0]*(g+m);h[d++]=e[1]*(l+n);h[d++]=e[2]*(k+q);h[d++]=e[0]*m;h[d++]=e[1]*n;h[d++]=e[2]*q}return h};
T.UTF8Loader.prototype.decompressMesh=function(b,a,c,f,e,h){var d=c.decodeScales.length,g=c.decodeOffsets;c=c.decodeScales;for(var l=a.attribRange[1],k=a.attribRange[0],m=new Float32Array(d*l),n=0;n<d;n++){var q=k+l,x=c[n];x&&this.decompressAttribsInner_(b,k,q,m,n,d,g[n],x);k=q}l=3*a.indexRange[1];d=new Uint16Array(l);this.decompressIndices_(b,k,l,d,0);k=void 0;(l=a.bboxes)&&(k=this.decompressAABBs_(b,l,a.names.length,g,c));h(f,e,m,d,k,a)};
T.UTF8Loader.prototype.copyAttrib=function(b,a,c,f){for(var e=0;e<b;e++)c[e]=a[b*f+e]};T.UTF8Loader.prototype.decodeAttrib2=function(b,a,c,f,e,h,d,g,l,k){for(var m=0;5>m;m++){var n=b.charCodeAt(e+h*m+k);l[m]+=n>>1^-(n&1);g[a*k+m]=l[m];d[a*k+m]=f[m]*(l[m]+c[m])}};
T.UTF8Loader.prototype.accumulateNormal=function(b,a,c,f,e){var h=f[8*b],d=f[8*b+1],g=f[8*b+2],l=f[8*a],k=f[8*a+1],m=f[8*a+2],n=f[8*c],q=f[8*c+1];f=f[8*c+2];l-=h;k-=d;m-=g;n-=h;q-=d;f-=g;h=k*f-m*q;d=m*n-l*f;g=l*q-k*n;e[3*b]+=h;e[3*b+1]+=d;e[3*b+2]+=g;e[3*a]+=h;e[3*a+1]+=d;e[3*a+2]+=g;e[3*c]+=h;e[3*c+1]+=d;e[3*c+2]+=g};
T.UTF8Loader.prototype.decompressMesh2=function(b,a,c,f,e,h){var d=c.decodeScales.length,g=c.decodeOffsets,l=c.decodeScales;c=a.attribRange[0];for(var k=a.attribRange[1],m=a.codeRange[0],n=3*a.codeRange[2],q=new Uint16Array(n),x=new Int32Array(3*k),A=new Uint16Array(d),t=new Uint16Array(d*k),B=new Float32Array(d*k),v=0,D=0,r=0;r<n;r+=3){var p=b.charCodeAt(m++),u=Math.min(r,96);if(p<u){var w=p%3,p=r-(p-w),y,z,C;switch(w){case 0:y=q[p+2];z=q[p+1];C=q[p+0];break;case 1:y=q[p+0];z=q[p+2];C=q[p+1];break;
case 2:y=q[p+1],z=q[p+0],C=q[p+2]}q[D++]=y;q[D++]=z;p=b.charCodeAt(m++);w=v-p;q[D++]=w;if(0===p){for(p=0;5>p;p++)u=b.charCodeAt(c+k*p+v),u=(u>>1^-(u&1))+t[d*y+p]+t[d*z+p]-t[d*C+p],A[p]=u,t[d*v+p]=u,B[d*v+p]=l[p]*(u+g[p]);v++}else this.copyAttrib(d,t,A,w);this.accumulateNormal(y,z,w,t,x)}else{w=v-(p-u);q[D++]=w;p===u?this.decodeAttrib2(b,d,g,l,c,k,B,t,A,v++):this.copyAttrib(d,t,A,w);p=b.charCodeAt(m++);u=v-p;q[D++]=u;0===p?this.decodeAttrib2(b,d,g,l,c,k,B,t,A,v++):this.copyAttrib(d,t,A,u);var p=b.charCodeAt(m++),
E=v-p;q[D++]=E;if(0===p){for(p=0;5>p;p++)A[p]=(t[d*w+p]+t[d*u+p])/2;this.decodeAttrib2(b,d,g,l,c,k,B,t,A,v++)}else this.copyAttrib(d,t,A,E);this.accumulateNormal(w,u,E,t,x)}}for(r=0;r<k;r++)g=x[3*r],y=x[3*r+1],z=x[3*r+2],C=511/Math.sqrt(g*g+y*y+z*z),l=b.charCodeAt(c+5*k+r),m=b.charCodeAt(c+6*k+r),n=b.charCodeAt(c+7*k+r),B[d*r+5]=C*g+(l>>1^-(l&1)),B[d*r+6]=C*y+(m>>1^-(m&1)),B[d*r+7]=C*z+(n>>1^-(n&1));h(f,e,B,q,void 0,a)};
T.UTF8Loader.prototype.downloadMesh=function(b,a,c,f,e){function h(b,h){for(;g<c.length;){var m=c[g],n=m.indexRange;if(n){n=n[0]+3*n[1];if(b.responseText.length<n)break;d.decompressMesh(b.responseText,m,f,a,g,e)}else{n=m.codeRange;n=n[0]+n[1];if(b.responseText.length<n)break;d.decompressMesh2(b.responseText,m,f,a,g,e)}++g}}var d=this,g=0;getHttpRequest(b,function(a,c){200!==a.status&&0!==a.status||h(a,c)},h)};
T.UTF8Loader.prototype.downloadMeshes=function(b,a,c,f){for(var e in a)this.downloadMesh(b+e,e,a[e],c,f)};
T.UTF8Loader.prototype.createMeshCallback=function(b,a,c){var f=0,e=0,h={},d={},g={},l=a.urls,k;for(k in l)h[k]=l[k].length,d[k]=0,e++,g[k]=new T.Object3D;var m=new T.Object3D,n=new T.MTLLoader.MaterialCreator(b,a.options);n.setMaterials(a.materials);n.preload();var q=new T.UTF8Loader.GeometryCreator,x=new T.UTF8Loader.BufferGeometryCreator;return function(b,k,l,v,D,r){k=(void 0!==a.options.useBuffers?a.options.useBuffers:1)?x.create(l,v):q.create(l,v);r=n.create(r.material);r=new T.Mesh(k,r);g[b].add(r);
d[b]++;d[b]===h[b]&&(f++,m.add(g[b]),f===e&&c(m))}};T.UTF8Loader.prototype.downloadModel=function(b,a,c,f){a=this.createMeshCallback(a,c,f);this.downloadMeshes(b,c.urls,c.decodeParams,a)};
T.UTF8Loader.prototype.downloadModelJson=function(b,a,c){getJsonRequest(b,function(f){f.decodeParams||(f.decodeParams=a&&a.decodeParams?a.decodeParams:DEFAULT_DECODE_PARAMS);f.options=a;var e=b.substr(0,b.lastIndexOf("/")+1),h=e;a&&a.geometryBase&&(e=a.geometryBase,"/"!==e.charAt(e.length-1)&&(e+="/"));a&&a.materialBase&&(h=a.materialBase,"/"!==h.charAt(h.length-1)&&(h+="/"));this.downloadModel(e,h,f,c)}.bind(this))};
function getHttpRequest(b,a,c){var f=new XMLHttpRequest;addListeners(f,{load:function(b){a(f,b)},progress:function(a){c(f,a)}});f.open("GET",b,!0);T.FileOperations.setXHRHeader&&T.FileOperations.setXHRHeader(f,b);f.send(null)}function getJsonRequest(b,a){getHttpRequest(b,function(b){a(JSON.parse(b.responseText))},function(){})}function addListeners(b,a){for(var c in a)b.addEventListener(c,a[c])};
