T.VRMLLoader=function(){};
T.VRMLLoader.prototype={constructor:T.VRMLLoader,isRecordingPoints:!1,isRecordingFaces:!1,points:[],indexes:[],isRecordingAngles:!1,isRecordingColors:!1,angles:[],colors:[],recordingFieldname:null,load:function(n,t){var l=this,g=new XMLHttpRequest;g.addEventListener("load",function(m){200===m.target.status||0===m.target.status?(m=l.parse(m.target.responseText),l.dispatchEvent({type:"load",content:m})):l.dispatchEvent({type:"error",message:"Couldn't load URL ["+n+"]",responseStatus:m.target.status})},!1);
g.addEventListener("progress",function(m){l.dispatchEvent({type:"progress",loaded:m.loaded,total:m.total})},!1);g.addEventListener("error",function(){l.dispatchEvent({type:"error",message:"Couldn't load URL ["+n+"]"})},!1);g.open("GET",n,!0);T.FileOperations.setXHRHeader&&T.FileOperations.setXHRHeader(g,n);g.send(null);return g},parse:function(n){var t=function(m,g){var k={},n=/(\b|\-|\+)([\d\.e]+)/,l=/([\d\.\+\-e]+),?\s+([\d\.\+\-e]+),?\s+([\d\.\+\-e]+)/,t=function(d,f,a,b,c){var e,h,g;e=c?1:-1;
var n=["a","b","c","d"],m=[],l,k=1,p={};g=!1;if(a)for(var r=0;r<a.length;r++){var q={};q.y=e*Math.cos(a[r])*f;q.x=e*Math.sin(a[r])*f;m.push(q)}for(r=0;r<d.faces.length;r++)for(a=d.faces[r],e=a instanceof T.F3?3:4,q=0;q<e;q++)if(h=a[n[q]],h=d.vertices[h],b)for(var u=0;u<b.length;u++)if(k=0===u?c?f:-1*f:m[u-1].y,p=m[u],void 0!==p){if(g=c?h.y<=k&&h.y>p.y:h.y>=k&&h.y<p.y){g=b[u+1];l=b[u];k=Math.abs(h.y-k)/(k-p.y);p=l;l=p.r-g.r;var t=p.g-g.g;g=p.b-g.b;var v=new T.Color;v.r=p.r-k*l;v.g=p.g-k*t;v.b=p.b-
k*g;g=v;a.vertexColors[q]=g}}else void 0===a.vertexColors[q]&&(g=c?b.length-1:0,a.vertexColors[q]=b[g])},w=function(d,f){for(var a=[],b,c={},e=/[^\s,\[\]]+/g;null!=(b=e.exec(f));)a.push(b[0]);b=a[0];switch(b){case "skyAngle":case "groundAngle":this.recordingFieldname=b;this.isRecordingAngles=!0;this.angles=[];break;case "skyColor":case "groundColor":this.recordingFieldname=b;this.isRecordingColors=!0;this.colors=[];break;case "point":this.recordingFieldname=b;this.isRecordingPoints=!0;this.points=
[];break;case "coordIndex":this.recordingFieldname=b,this.isRecordingFaces=!0,this.indexes=[]}if(this.isRecordingFaces){if(0<a.length)for(b=[],e=0;e<a.length;e++)/(-?\d+)/.test(a[e])&&("-1"===a[e]?(0<b.length&&this.indexes.push(b),b=[]):b.push(parseInt(a[e])));/]/.exec(f)&&(this.isRecordingFaces=!1,d.coordIndex=this.indexes)}else if(this.isRecordingPoints)a=l.exec(f),null!=a&&(a={x:parseFloat(a[1]),y:parseFloat(a[2]),z:parseFloat(a[3])},this.points.push(a)),/]/.exec(f)&&(this.isRecordingPoints=!1,
d.points=this.points);else if(this.isRecordingAngles){if(0<a.length)for(e=0;e<a.length;e++)n.test(a[e])&&this.angles.push(parseFloat(a[e]));/]/.exec(f)&&(this.isRecordingAngles=!1,d[this.recordingFieldname]=this.angles)}else if(this.isRecordingColors){for(b=/([\d\.\+\-e]+),?\s+([\d\.\+\-e]+),?\s+([\d\.\+\-e]+)/g;null!==(a=b.exec(f));)color={r:parseFloat(a[1]),g:parseFloat(a[2]),b:parseFloat(a[3])},this.colors.push(color);/]/.exec(f)&&(this.isRecordingColors=!1,d[this.recordingFieldname]=this.colors)}else if("NULL"!==
a[a.length-1]&&"children"!==b){switch(b){case "diffuseColor":case "emissiveColor":case "specularColor":case "color":if(4!=a.length){console.warn("Invalid color format detected for "+b);break}c={r:parseFloat(a[1]),g:parseFloat(a[2]),b:parseFloat(a[3])};break;case "translation":case "scale":case "size":if(4!=a.length){console.warn("Invalid vector format detected for "+b);break}c={x:parseFloat(a[1]),y:parseFloat(a[2]),z:parseFloat(a[3])};break;case "radius":case "topRadius":case "bottomRadius":case "height":case "transparency":case "shininess":case "ambientIntensity":if(2!=
a.length){console.warn("Invalid single float value specification detected for "+b);break}c=parseFloat(a[1]);break;case "rotation":if(5!=a.length){console.warn("Invalid quaternion format detected for "+b);break}c={x:parseFloat(a[1]),y:parseFloat(a[2]),z:parseFloat(a[3]),w:parseFloat(a[4])};break;case "ccw":case "solid":case "colorPerVertex":case "convex":if(2!=a.length){console.warn("Invalid format detected for "+b);break}c="TRUE"===a[1]?!0:!1}d[b]=c}return c},x=function(d,f){if("string"===typeof d){if(/USE/.exec(d)){var a=
/USE\s+?(\w+)/.exec(d)[1];void 0==k[a]?console.warn(a+" is not defined."):/appearance/.exec(d)&&a?f.material=k[a].clone():/geometry/.exec(d)&&a?(f.geometry=k[a].clone(),void 0!==k[a].solid&&!1===k[a].solid&&(f.geometry.solid=!1,f.material.side=T.DoubleSide)):a&&(a=k[a].clone(),f.add(a))}}else{a=f;if("Transform"===d.nodeType||"Group"===d.nodeType){a=new T.Object3D;/DEF/.exec(d.string)&&(a.name=/DEF\s+(\w+)/.exec(d.string)[1],k[a.name]=a);if(void 0!==d.translation){var b=d.translation;a.position.set(b.x,
b.y,b.z)}if(void 0!==d.rotation){var c=d.rotation;a.quaternion.setFromAxisAngle(new T.V3(c.x,c.y,c.z),c.w)}void 0!==d.scale&&(b=d.scale,a.scale.set(b.x,b.y,b.z));f.add(a)}else if("Shape"===d.nodeType)a=new T.Mesh,/DEF/.exec(d.string)&&(a.name=/DEF (\w+)/.exec(d.string)[1],k[a.name]=a),f.add(a);else if("Background"===d.nodeType){var c=2E4,b=new T.SphereGeometry(c,20,20),e=new T.MeshBasicMaterial({color:"white",vertexColors:T.VertexColors,shading:T.NoShading});e.side=T.BackSide;e.fog=!1;e.color=new T.Color;
t(b,c,d.skyAngle,d.skyColor,!0);c=new T.Mesh(b,e);g.add(c);c=12E3;b=new T.SphereGeometry(c,20,20,0,2*Math.PI,.5*Math.PI,1.5*Math.PI);e=new T.MeshBasicMaterial({color:"white",vertexColors:T.VertexColors,shading:T.NoShading});e.side=T.BackSide;e.fog=!1;e.color=new T.Color;t(b,c,d.groundAngle,d.groundColor,!1);c=new T.Mesh(b,e);g.add(c)}else{if(/geometry/.exec(d.string)){if("Box"===d.nodeType)b=d.size,f.geometry=new T.CubeGeometry(b.x,b.y,b.z);else if("Cylinder"===d.nodeType)f.geometry=new T.CylinderGeometry(d.radius,
d.radius,d.height);else if("Cone"===d.nodeType)f.geometry=new T.CylinderGeometry(d.topRadius,d.bottomRadius,d.height);else if("Sphere"===d.nodeType)f.geometry=new T.SphereGeometry(d.radius);else if("IndexedFaceSet"===d.nodeType){c=new T.Geometry;b=0;for(e=d.children.length;b<e;b++){var a=d.children[b],h;if("Coordinate"===a.nodeType){b=0;for(e=a.points.length;b<e;b++)h=a.points[b],h=new T.V3(h.x,h.y,h.z),c.vertices.push(h);break}}b=h=0;for(e=d.coordIndex.length;b<e;b++)for(a=d.coordIndex[b],h=0;3<=
a.length&&h<a.length-2;){var l=new T.F3(a[0],a[h+1],a[h+2],null);h++;c.faces.push(l)}!1===d.solid&&(f.material.side=T.DoubleSide);c.solid=d.solid;c.computeFaceNormals();c.computeBoundingSphere();/DEF/.exec(d.string)&&(c.name=/DEF (\w+)/.exec(d.string)[1],k[c.name]=c);f.geometry=c}return}if(/appearance/.exec(d.string)){for(b=0;b<d.children.length;b++)if(a=d.children[b],"Material"===a.nodeType){c=new T.ObjectMaterial;void 0!==a.diffuseColor&&(b=a.diffuseColor,c.color.setRGB(b.r,b.g,b.b));void 0!==a.emissiveColor&&
(b=a.emissiveColor,c.emissive.setRGB(b.r,b.g,b.b));void 0!==a.specularColor&&(b=a.specularColor,c.specular.setRGB(b.r,b.g,b.b));void 0!==a.transparency&&(b=a.transparency,c.opacity=Math.abs(1-b),c.transparent=!0);/DEF/.exec(d.string)&&(c.name=/DEF (\w+)/.exec(d.string)[1],k[c.name]=c);f.material=c;break}return}}b=0;for(e=d.children.length;b<e;b++)x(d.children[b],a)}};x(function(d){for(var f={string:"Scene",children:[]},a=f,b,c,e=0;e<d.length;e++){var g="";c=d[e];null===(result=/^\s+?$/g.exec(c))&&
(c=c.trim(),""!==c&&(/#/.exec(c)&&(b=c.split("#"),c=b[0],g=b[1]),(b=/([^\s]*){1}\s?{/.exec(c))?(b={nodeType:b[1],string:c,parent:a,children:[],comment:g},a.children.push(b),a=b,/}/.exec(c)&&(c=/{(.*)}/.exec(c)[1],b.children.push(c),w(a,c),a=a.parent)):/}/.exec(c)?a=a.parent:""!==c&&(w(a,c),a.children.push(c))))}return f}(m),g)},l=new T.Scene;n=n.split("\n");var g=n.shift();/V1.0/.exec(g)?console.warn("VRML V1.0 not supported yet"):/V2.0/.exec(g)&&t(n,l);return l}};T.EventDispatcher.prototype.apply(T.VRMLLoader.prototype);
