function is_array(a){return"object"===typeof a&&a instanceof Array}function convert_formated_hex_to_bytes(a){var c=0,b=[],d,e;if(""==a.trim())return[];if(/[^0-9a-fA-F\s]/.test(a))return!1;d=a.length;for(e=0;e<d;e+=2)b[c++]=parseInt(a[e]+a[e+1],16);return b}function convert_to_formated_hex(a){var c="",b,d,e;if(!is_array(a))return!1;d=a.length;for(b=0;b<d;++b)0>a[b]&&(a[b]+=256),e=a[b].toString(16),1==e.length&&(e="0"+e),c+=e;return c.trim()}
function convert_to_formated_bitstring(a){var c,b,d,e,g,f=a.length;c=""+String.fromCharCode(f%3+63);for(b=0;b<f;b+=3)d=a[b]&255,e=b<f-1?a[b+1]&255:0,g=b<f-2?a[b+2]&255:0,c+=String.fromCharCode((d>>2&255)+63),c+=String.fromCharCode(((d&3)<<4&255)+(e>>4&255)+63),c+=String.fromCharCode(((e&15)<<2&255)+(g>>6&255)+63),c+=String.fromCharCode((g&63)+63);return c}
function convert_formated_bitstring_to_bytes(a){var c=a.length,b,d=[];b=1;for(j=0;b<c;b+=4)d[j++]=(a.charCodeAt(b)-63<<2)+(a.charCodeAt(b+1)-63>>4),d[j++]=((a.charCodeAt(b+1)-63&15)<<4)+(a.charCodeAt(b+2)-63>>2),d[j++]=((a.charCodeAt(b+2)-63&3)<<6)+(a.charCodeAt(b+3)-63);1==a.charCodeAt(0)-63?(d.pop(),d.pop()):2==a.charCodeAt(0)-63&&d.pop();return d}
function readFloat32(a,c){var b=a[c+2]&255,d=a[c+3]&255,e=(d<<1&255|b>>7)-127,b=(b&127)<<16|(a[c+1]&255)<<8|a[c]&255;return 0==b&&-127==e?0:(1-2*(d>>7))*(1+b*Math.pow(2,-23))*Math.pow(2,e)}function readUInt16(a,c){return((a[c+1]&255)<<8)+(a[c]&255)}function readUInt32(a,c){return((a[c+3]&255)<<24)+((a[c+2]&255)<<16)+((a[c+1]&255)<<8)+(a[c]&255)}function s4(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)}
function createGuid(){return s4()+s4()+"-"+s4()+"-"+s4()+"-"+s4()+"-"+s4()+s4()+s4()}function sleep(a){for(var c=(new Date).getTime();(new Date).getTime()<c+a;);}function getUID(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)}
String.prototype.hashCode=function(){if(Array.prototype.reduce)return this.split("").reduce(function(a,b){a=(a<<5)-a+b.charCodeAt(0);return a&a},0);var a=0;if(0===this.length)return a;for(var c=0;c<this.length;c++)var b=this.charCodeAt(c),a=(a<<5)-a+b,a=a&a;return a};function searchInDataView(a,c,b,d){d=d?d:a.byteLength-c.length;for(var e=0,g=c.length,f=b?b:0;f<=d;++f)if(b=a.getUint8(f),b==c.charCodeAt(e)&&++e,e==g)return f-g+1;return-1}
function insertTextToDataView(a,c,b){b=b?b:0;for(var d=Math.min(c.length,a.byteLength-b),e=0;e<d;++e)a.setUint8(e+b,c.charCodeAt(e))}function projectPointToVector(a,c,b){return(new T.V3).copy(a).sub(c).projectOnVector(b).add(c)}function projectPointToPlane(a,c,b){return(new T.V3).copy(a).sub(c).projectOnPlane(b).add(c)}
function linePlaneIntersection(a,c,b,d){c=(new T.V3).copy(c);b=(new T.V3).copy(a).sub(b);var e=(new T.V3).copy(d);d=e.dot(c);b=-1*e.dot(b);if(!(1E-5>Math.abs(d)))return d=b/d,(new T.V3).copy(a).add(c.multiplyScalar(d))}
CircleFitting=function(){this.radius=-1;this.center=new T.V3;this.normal=new T.V3;this.fitPoints=function(a,c,b){var d=(new T.V3).subVectors(c,b),e=(new T.V3).subVectors(a,c);this.normal.copy(d).cross(e);this.radius=-1;if(1E-4<this.normal.length()){this.normal.normalize();var g=(new T.V3).copy(e).cross(this.normal),f=(new T.V3).copy(d).cross(this.normal),h=(new T.V3).addVectors(a,c).divideScalar(2),k=(new T.V3).addVectors(c,b).divideScalar(2),e=linePlaneIntersection(k,f,h,e),d=linePlaneIntersection(h,
g,k,d);if(e&&d)this.center=e.add(d).divideScalar(2);else if(e)this.center=e;else if(d)this.center=d;else return!1;this.radius=(this.center.distanceTo(a)+this.center.distanceTo(c)+this.center.distanceTo(b))/3;return!0}return!1}};helpWindow=null;
openHelp=function(a){helpWindow?(a&&helpWindow.contentWindow.postMessage({command:"set_url",url:a},"*"),helpWindow.focus()):chrome.app.window.create("HelpDialog/help.html",{id:"Help",minWidth:800,minHeight:300,width:Math.min(850,window.screen.width),height:Math.min(750,window.screen.height)},function(c){c&&c.contentWindow&&(c.onClosed.addListener(function(){helpWindow=null}),c.contentWindow.addEventListener("load",function(b){helpWindow=c;a&&helpWindow.contentWindow.postMessage({command:"set_url",
url:a},"*");helpWindow.focus()}))})};
"undefined"===typeof DataView&&(DataView=function(a,c,b){this.buffer=a;this.byteOffset=c||0;this.byteLength=b||a.byteLength||a.length;this._isString="string"===typeof a},DataView.prototype={_getCharCodes:function(a,c,b){c=c||0;b=b||a.length;b=c+b;for(var d=[];c<b;c++)d.push(a.charCodeAt(c)&255);return d},_getBytes:function(a,c,b){void 0===b&&(b=this._littleEndian);c=void 0===c?this.byteOffset:this.byteOffset+c;void 0===a&&(a=this.byteLength-c);if("number"!==typeof c)throw new TypeError("DataView byteOffset is not a number");if(0>
a||c+a>this.byteLength)throw Error("DataView length or (byteOffset+length) value is out of bounds");c=this.isString?this._getCharCodes(this.buffer,c,c+a):this.buffer.slice(c,c+a);!b&&1<a&&(c instanceof Array||(c=Array.prototype.slice.call(c)),c.reverse());return c},getFloat64:function(a,c){var b=this._getBytes(8,a,c),d=1-2*(b[7]>>7),e=((b[7]<<1&255)<<3|b[6]>>4)-1023,b=(b[6]&15)*Math.pow(2,48)+b[5]*Math.pow(2,40)+b[4]*Math.pow(2,32)+b[3]*Math.pow(2,24)+b[2]*Math.pow(2,16)+b[1]*Math.pow(2,8)+b[0];return 1024===
e?0!==b?NaN:Infinity*d:-1023===e?d*b*Math.pow(2,-1074):d*(1+b*Math.pow(2,-52))*Math.pow(2,e)},getFloat32:function(a,c){var b=this._getBytes(4,a,c),d=1-2*(b[3]>>7),e=(b[3]<<1&255|b[2]>>7)-127,b=(b[2]&127)<<16|b[1]<<8|b[0];return 128===e?0!==b?NaN:Infinity*d:-127===e?d*b*Math.pow(2,-149):d*(1+b*Math.pow(2,-23))*Math.pow(2,e)},getInt32:function(a,c){var b=this._getBytes(4,a,c);return b[3]<<24|b[2]<<16|b[1]<<8|b[0]},getUint32:function(a,c){return this.getInt32(a,c)>>>0},getInt16:function(a,c){return this.getUint16(a,
c)<<16>>16},getUint16:function(a,c){var b=this._getBytes(2,a,c);return b[1]<<8|b[0]},getInt8:function(a){return this.getUint8(a)<<24>>24},getUint8:function(a){return this._getBytes(1,a)[0]}});function bytesToSize(a){if(0===a)return"0 Bytes";var c=parseInt(Math.floor(Math.log(a)/Math.log(1024)),10);return(a/Math.pow(1024,c)).toPrecision(3)+" "+["Bytes","KB","MB","GB","TB"][c]}
function linkify(a){return a.replace(/(\b(https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig,function(a){return'<a href="'+a+'">'+a+"</a>"})}var loadedImagesCache=[];function loadImage(a,c){if(void 0!==loadedImagesCache[a])c(loadedImagesCache[a],a);else{var b=new XMLHttpRequest;b.responseType="blob";b.onload=function(){var d=window.URL.createObjectURL(b.response);loadedImagesCache[a]=d;c(d,a)};b.open("GET",a,!0);b.send()}}
function indexOfMinElementMatchingCriteria(a,c,b){if(!a||!a.length)return-1;var d,e;maxElement=null;for(var g=0;g<a.length;++g){e=[];for(var f=0,h=a.length;f<h;++f)if(d=a[f],!maxElement||0>c(maxElement,d))0==e.length?e.push(f):(sort=c(a[e[0]],d),0==sort?e.push(f):0<sort&&(e=[f]));f=0;for(h=e.length;f<h;++f)if(b(a[e[f]]))return e[f];if(!e.length)break;maxElement=a[e[0]]}return-1};
