//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Little_Disk_Cleaner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool searchSystem {
            get {
                return ((bool)(this["searchSystem"]));
            }
            set {
                this["searchSystem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool searchReadOnly {
            get {
                return ((bool)(this["searchReadOnly"]));
            }
            set {
                this["searchReadOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool searchHidden {
            get {
                return ((bool)(this["searchHidden"]));
            }
            set {
                this["searchHidden"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool searchArchives {
            get {
                return ((bool)(this["searchArchives"]));
            }
            set {
                this["searchArchives"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool searchZeroByte {
            get {
                return ((bool)(this["searchZeroByte"]));
            }
            set {
                this["searchZeroByte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int removeMode {
            get {
                return ((int)(this["removeMode"]));
            }
            set {
                this["removeMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string moveFolder {
            get {
                return ((string)(this["moveFolder"]));
            }
            set {
                this["moveFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool autoRestorePoints {
            get {
                return ((bool)(this["autoRestorePoints"]));
            }
            set {
                this["autoRestorePoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int filterMode {
            get {
                return ((int)(this["filterMode"]));
            }
            set {
                this["filterMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*.tmp; *.temp; *.gid; *.chk; *.~*;")]
        public string searchFilters {
            get {
                return ((string)(this["searchFilters"]));
            }
            set {
                this["searchFilters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ignoreWriteProtected {
            get {
                return ((bool)(this["ignoreWriteProtected"]));
            }
            set {
                this["ignoreWriteProtected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int findFilesMode {
            get {
                return ((int)(this["findFilesMode"]));
            }
            set {
                this["findFilesMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool findFilesAfter {
            get {
                return ((bool)(this["findFilesAfter"]));
            }
            set {
                this["findFilesAfter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool findFilesBefore {
            get {
                return ((bool)(this["findFilesBefore"]));
            }
            set {
                this["findFilesBefore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("06/14/2010 21:39:00")]
        public global::System.DateTime dateTimeAfter {
            get {
                return ((global::System.DateTime)(this["dateTimeAfter"]));
            }
            set {
                this["dateTimeAfter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("06/14/2010 21:39:00")]
        public global::System.DateTime dateTimeBefore {
            get {
                return ((global::System.DateTime)(this["dateTimeBefore"]));
            }
            set {
                this["dateTimeBefore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>?:\program files\common files</string>
  <string>?:\program files\uninstall information</string>
  <string>?:\win*\security</string>
  <string>*\sendto</string>
  <string>*\i386</string>
  <string>*\resources\themes</string>
  <string>*\microsoft\office\data</string>
  <string>*\microsoft\money\*\webcache</string>
  <string>*\chaos32</string>
  <string>*\paprport\data</string>
  <string>*\symantec shared\virusdefs</string>
  <string>?:\system volume information</string>
  <string>?:\_restore</string>
  <string>?:\recycle?</string>
  <string>*\temp\incredimail</string>
  <string>*\norton antivirus\quarantine</string>
  <string>*\system32\usmt</string>
  <string>*\system32\catroot2</string>
  <string>*\application data\microsoft</string>
  <string>?:\windows</string>
  <string>?:\winnt</string>
  <string>?:\win*\pif</string>
  <string>?:\win*\resources</string>
  <string>\win*\system32\oldole</string>
  <string>?:\win*\Sysbackup</string>
  <string>?:\win*\system32\olebackup</string>
  <string>?:\win*\system32\usmt</string>
  <string>?:\$recycle.bin</string>
  <string>*\Application Data\Aim</string>
  <string>*\symantec shared\virusdefs</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection excludedDirs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["excludedDirs"]));
            }
            set {
                this["excludedDirs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>config.*</string>
  <string>autoexec.*</string>
  <string>data.bak</string>
  <string>_Default.pif</string>
  <string>Calendar.tmp</string>
  <string>Data.sav</string>
  <string>Default.pif</string>
  <string>Donotdel.tmp</string>
  <string>DonotDelete.tmp</string>
  <string>Drelres.pif</string>
  <string>FTP.log</string>
  <string>Http.log</string>
  <string>Index.dat</string>
  <string>Install.log</string>
  <string>MM2048.DAT</string>
  <string>MM256.DAT</string>
  <string>Modem.log</string>
  <string>Script.bak</string>
  <string>System.old</string>
  <string>Uninstall.log</string>
  <string>User.old</string>
  <string>WebPoolFileFile</string>
  <string>Win.bak</string>
  <string>Win.old</string>
  <string>Wnccdctl.log</string>
  <string>wz.pif</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection excludedFileTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["excludedFileTypes"]));
            }
            set {
                this["excludedFileTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool findNotAccessed {
            get {
                return ((bool)(this["findNotAccessed"]));
            }
            set {
                this["findNotAccessed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int findNotAccessedValue {
            get {
                return ((int)(this["findNotAccessedValue"]));
            }
            set {
                this["findNotAccessedValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkFileSize {
            get {
                return ((bool)(this["checkFileSize"]));
            }
            set {
                this["checkFileSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int checkFileSizeLeast {
            get {
                return ((int)(this["checkFileSizeLeast"]));
            }
            set {
                this["checkFileSizeLeast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int checkFileSizeMost {
            get {
                return ((int)(this["checkFileSizeMost"]));
            }
            set {
                this["checkFileSizeMost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoClean {
            get {
                return ((bool)(this["autoClean"]));
            }
            set {
                this["autoClean"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList diskDrives {
            get {
                return ((global::System.Collections.ArrayList)(this["diskDrives"]));
            }
            set {
                this["diskDrives"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool firstRun {
            get {
                return ((bool)(this["firstRun"]));
            }
            set {
                this["firstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://littleapps.co.cc/bugreport.php")]
        public string crashReportURI {
            get {
                return ((string)(this["crashReportURI"]));
            }
            set {
                this["crashReportURI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://lildiskcleaner.sourceforge.net/update.xml")]
        public string updateURI {
            get {
                return ((string)(this["updateURI"]));
            }
            set {
                this["updateURI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long lastUpdateDate {
            get {
                return ((long)(this["lastUpdateDate"]));
            }
            set {
                this["lastUpdateDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection includedFolders {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["includedFolders"]));
            }
            set {
                this["includedFolders"] = value;
            }
        }
    }
}
