var UI={Element:function(){}};UI.Element.prototype={setId:function(a){this.dom.id=a;return this},setClass:function(a){this.dom.className=a;return this},setStyle:function(a,c){for(var b=0;b<c.length;b++)this.dom.style[a]=c[b]},getStyle:function(a){return this.dom.style[a]},setDisabled:function(a){this.dom.disabled=a;return this},setTextContent:function(a){var c=this.dom.childNodes[0];c?c.nodeValue=a:this.dom.textContent=a;return this}};var properties="position left top right bottom width height border borderLeft borderTop borderRight borderBottom borderColor display overflow margin marginLeft marginTop marginRight marginBottom padding paddingLeft paddingTop paddingRight paddingBottom color backgroundColor opacity fontSize fontWeight textTransform cursor".split(" ");
properties.forEach(function(a){var c="set"+a.substr(0,1).toUpperCase()+a.substr(1,a.length);UI.Element.prototype[c]=function(){this.setStyle(a,arguments);return this};c="get"+a.substr(0,1).toUpperCase()+a.substr(1,a.length);UI.Element.prototype[c]=function(){return this.getStyle(a,arguments)}});var events="KeyUp KeyDown MouseOver MouseOut Click Change Resize Select Mark".split(" ");
events.forEach(function(a){UI.Element.prototype["on"+a]=function(c,b){!0!==b?this.dom.addEventListener(a.toLowerCase(),c,!1):this.dom.addEventListener(a.toLowerCase(),function(){c.apply(this,arguments);0<arguments.length&&(void 0!==arguments[0].stopPropagation&&arguments[0].stopPropagation(),void 0!==arguments[0].currentTarget&&void 0!==arguments[0].currentTarget.parentElement&&void 0!==arguments[0].currentTarget.parentElement.style&&(arguments[0].currentTarget.parentElement.style.display="none"))},
!1);return this}});UI.Panel=function(){UI.Element.call(this);var a=document.createElement("div");a.className="Panel";a.style.userSelect="none";a.style.WebkitUserSelect="none";a.style.MozUserSelect="none";this.dom=a;return this};UI.Panel.prototype=Object.create(UI.Element.prototype);UI.Panel.prototype.add=function(){for(var a=0;a<arguments.length;a++)this.dom.appendChild(arguments[a].dom);return this};
UI.Panel.prototype.remove=function(){for(var a=0;a<arguments.length;a++)this.dom.removeChild(arguments[a].dom);return this};UI.Panel.prototype.clear=function(){for(;this.dom.children.length;)this.dom.removeChild(this.dom.lastChild)};
UI.CollapsiblePanel=function(){UI.Panel.call(this);this.dom.className="Panel CollapsiblePanel";this.button=document.createElement("div");this.button.className="CollapsiblePanelButton";this.dom.appendChild(this.button);var a=this;this.button.addEventListener("click",function(c){a.toggle()},!1);this.content=document.createElement("div");this.content.className="CollapsibleContent";this.dom.appendChild(this.content);this.isCollapsed=!1;return this};UI.CollapsiblePanel.prototype=Object.create(UI.Panel.prototype);
UI.CollapsiblePanel.prototype.addStatic=function(){for(var a=0;a<arguments.length;a++)this.dom.insertBefore(arguments[a].dom,this.content);return this};UI.CollapsiblePanel.prototype.removeStatic=UI.Panel.prototype.remove;UI.CollapsiblePanel.prototype.clearStatic=function(){this.dom.childNodes.forEach(function(a){a!==this.content&&this.dom.removeChild(a)})};UI.CollapsiblePanel.prototype.add=function(){for(var a=0;a<arguments.length;a++)this.content.appendChild(arguments[a].dom);return this};
UI.CollapsiblePanel.prototype.remove=function(){for(var a=0;a<arguments.length;a++)this.content.removeChild(arguments[a].dom);return this};UI.CollapsiblePanel.prototype.clear=function(){for(;this.content.children.length;)this.content.removeChild(this.content.lastChild)};UI.CollapsiblePanel.prototype.toggle=function(){this.setCollapsed(!this.isCollapsed)};UI.CollapsiblePanel.prototype.collapse=function(){this.setCollapsed(!0)};UI.CollapsiblePanel.prototype.expand=function(){this.setCollapsed(!1)};
UI.CollapsiblePanel.prototype.setCollapsed=function(a){a?this.dom.classList.add("collapsed"):this.dom.classList.remove("collapsed");this.isCollapsed=a};UI.Text=function(a){UI.Element.call(this);var c=document.createElement("span");c.className="Text";c.style.cursor="default";c.style.display="inline-block";c.style.verticalAlign="middle";this.dom=c;this.setValue(a);return this};UI.Text.prototype=Object.create(UI.Element.prototype);
UI.Text.prototype.setValue=function(a){void 0!==a&&(this.dom.textContent=a);return this};UI.Input=function(){UI.Element.call(this);var a=document.createElement("input");a.className="Input";a.style.padding="2px";a.style.border="1px solid #ccc";a.addEventListener("keydown",function(a){a.stopPropagation()},!1);this.dom=a;return this};UI.Input.prototype=Object.create(UI.Element.prototype);UI.Input.prototype.getValue=function(){return this.dom.value};
UI.Input.prototype.setValue=function(a){this.dom.value=a;return this};UI.TextArea=function(){UI.Element.call(this);var a=document.createElement("textarea");a.className="TextArea";a.style.padding="2px";a.style.border="1px solid #ccc";a.addEventListener("keydown",function(a){a.stopPropagation()},!1);this.dom=a;return this};UI.TextArea.prototype=Object.create(UI.Element.prototype);UI.TextArea.prototype.getValue=function(){return this.dom.value};
UI.TextArea.prototype.setValue=function(a){this.dom.value=a;return this};UI.Select=function(){UI.Element.call(this);var a=document.createElement("select");a.className="Select";a.style.width="64px";a.style.height="16px";a.style.border="0px";a.style.padding="0px";this.dom=a;return this};UI.Select.prototype=Object.create(UI.Element.prototype);UI.Select.prototype.setMultiple=function(a){this.dom.multiple=a;return this};
UI.Select.prototype.setOptions=function(a){for(var c=this.dom.value;0<this.dom.children.length;)this.dom.removeChild(this.dom.firstChild);for(var b in a){var e,d=a[b];if("object"==typeof d){e=document.createElement("optgroup");e.label=b;for(var f in d)if("string"==typeof d[f]){var g=document.createElement("option");g.value=d instanceof Array?d[f]:f;g.innerHTML=d[f];e.appendChild(g)}}else if("string"==typeof d)e=document.createElement("option"),e.innerHTML=d;else continue;e.value=b;this.dom.appendChild(e)}this.dom.value=
c;return this};UI.Select.prototype.getValue=function(){return this.dom.value};UI.Select.prototype.setValue=function(a){this.dom.value=a;return this};UI.FancySelect=function(){UI.Element.call(this);var a=document.createElement("div");a.className="FancySelect";a.style.background="#fff";a.style.border="1px solid #ccc";a.style.padding="0";a.style.cursor="default";a.style.overflow="auto";this.dom=a;this.options=[];this.selectedValue=null;return this};UI.FancySelect.prototype=Object.create(UI.Element.prototype);
UI.FancySelect.prototype.setOptions=function(a){var c=this,b=document.createEvent("HTMLEvents");for(b.initEvent("change",!0,!0);0<c.dom.children.length;)c.dom.removeChild(c.dom.firstChild);c.options=[];for(var e in a){var d=document.createElement("div");d.style.padding="4px";d.style.whiteSpace="nowrap";d.innerHTML=a[e];d.value=e;c.dom.appendChild(d);c.options.push(d);d.addEventListener("click",function(a){c.setValue(this.value);c.dom.dispatchEvent(b)},!1)}return c};
UI.FancySelect.prototype.getValue=function(){return this.selectedValue};UI.FancySelect.prototype.setValue=function(a){"number"===typeof a&&(a=a.toString());for(var c=0;c<this.options.length;c++){var b=this.options[c];if(b.value===a){b.style.backgroundColor="#f0f0f0";var b=c*b.clientHeight,e=this.dom.scrollTop,d=this.dom.clientHeight;if(b<e||b>e+d)this.dom.scrollTop=b}else b.style.backgroundColor=""}this.selectedValue=a;return this};UI.EditorSelect=function(){UI.FancySelect.call(this);return this};
UI.EditorSelect.prototype=Object.create(UI.FancySelect.prototype);
UI.EditorSelect.prototype.setOptions=function(a){var c=this,b=document.createEvent("HTMLEvents");for(b.initEvent("change",!0,!0);0<c.dom.children.length;)c.dom.removeChild(c.dom.firstChild);c.options=[];for(var e=0;e<a.length;++e){var d=document.createElement("div");d.style.padding="4px";d.style.whiteSpace="nowrap";d.innerHTML=a[e].option;d.value=a[e].key.toString();c.dom.appendChild(d);c.options.push(d);d.addEventListener("click",function(a){c.setValue(this.value);c.dom.dispatchEvent(b)},!1)}return c};
UI.Tree=function(){UI.Element.call(this);var a=document.createElement("div");a.className="Tree";a.id="fancy-tree";a.style.background="#fff";a.style.border="1px solid #ccc";a.style.padding="0";a.style.cursor="default";a.style.overflow="hidden";this.dom=a;this.tree=null;return this};UI.Tree.prototype=Object.create(UI.Element.prototype);
UI.Tree.prototype.init=function(){function a(){e.dom.dispatchEvent(d)}function c(){e.dom.dispatchEvent(f)}function b(){e.dom.dispatchEvent(g)}var e=this,d=document.createEvent("HTMLEvents");d.initEvent("select",!0,!0);var f=document.createEvent("HTMLEvents");f.initEvent("mark",!0,!0);var g=document.createEvent("HTMLEvents");g.initEvent("resize",!0,!0);if(!this.tree){var h=$("#"+this.dom.id);h.fancytree({source:[],clickFolderMode:3,selectMode:2,fx:null,activate:a,select:c,collapse:b,expand:b,createNode:function(a,
b){e.bindContextMenu(b.node)},checkbox:!0});this.tree=h.fancytree("getTree");this.updateLayout()}};UI.Tree.prototype.bindContextMenu=function(a){};UI.Tree.prototype.setId=function(a){this.tree||UI.Element.prototype.setId.call(this,a);return this};
UI.Tree.prototype.updateLayout=function(){if(this.tree){var a=this.tree.$container.get(0);if(a){var c=a.style.width?a.offsetWidth-parseInt(a.style.width):0,b=a.style.height?a.offsetHeight-parseInt(a.style.height):0;a.style.width=this.dom.offsetWidth-c-1+"px";a.style.height=this.dom.offsetHeight-b-1+"px"}}};
UI.Tree.prototype.getContentHeight=function(){if(!this.tree)return 0;var a=this.tree.$container.get(0);if(!a)return 0;var c=a.style.height;a.style.height="0px";var b=a.scrollHeight;a.style.height=c;return b};UI.Tree.prototype.addNode=function(a,c){if(!this.tree)return console.error("tree must be initialized before use"),null;var b;c&&(b=this.tree.getNodeByKey(c));b||(b=this.tree.rootNode);return b.addNode(a,"child")};
UI.Tree.prototype.removeNodeByKey=function(a){if(!this.tree)return console.error("tree must be initialized before use"),null;(a=a?this.tree.getNodeByKey(a):null)&&a.remove();return a};UI.Tree.prototype.getNodeByKey=function(a){return this.tree?a?this.tree.getNodeByKey(a):null:(console.error("tree must be initialized before use"),null)};
UI.Tree.prototype.updateNode=function(a){if(!this.tree)return console.error("tree must be initialized before use"),null;var c=a&&a.key?this.tree.getNodeByKey(a.key):null;c&&c.fromDict(a);return c};UI.Tree.prototype.getSelectedNode=function(){return this.tree?this.tree.getActiveNode():(console.error("tree must be initialized before use"),null)};UI.Tree.prototype.selectNodeByKey=function(a){if(!this.tree)return console.error("tree must be initialized before use"),this;this.tree.activateKey(a);return this.tree.getActiveNode()};
UI.Tree.prototype.getMarkedNodes=function(){if(!this.tree)return console.error("tree must be initialized before use"),[];var a=this.tree.getSelectedNodes(!1);return 0<a.length?a:[]};UI.Tree.prototype.unMarkNodes=function(a){if(!this.tree)return console.error("tree must be initialized before use"),[];var c=this.getMarkedNodes(),b;for(b in c)a&&-1!=a.indexOf(c[b].key)||c[b].setSelected(!1)};
UI.Tree.prototype.markNodesByKey=function(a){if(!this.tree)return console.error("tree must be initialized before use"),this;for(var c in a){var b=this.tree.getNodeByKey(a[c]);b&&b.setSelected()}this.unMarkNodes(a)};UI.ObjectsTree=function(){UI.Tree.call(this);return this};UI.ObjectsTree.prototype=Object.create(UI.Tree.prototype);UI.ObjectsTree.prototype.getSelectedObjectId=function(){var a=UI.Tree.prototype.getSelectedNode.call(this);return a?parseInt(a.key):null};
UI.ObjectsTree.prototype.selectObjectById=function(a){if(!a)return null;(a=UI.Tree.prototype.selectNodeByKey.call(this,a.toString()))&&a.makeVisible({noAnimation:!0,noEvents:!1,scrollIntoView:!0});return a};UI.ObjectsTree.prototype.getMarkedObjectIds=function(){for(var a=UI.Tree.prototype.getMarkedNodes.call(this),c=[],b=0;b<a.length;++b)c.push(parseInt(a[b].key));return c};
UI.ObjectsTree.prototype.markObjects=function(a){if(a&&a.length){var c=[],b;for(b in a){var e=a[b];e&&e instanceof T.Object3D&&c.push(e.id.toString())}UI.Tree.prototype.markNodesByKey.call(this,c)}};UI.ObjectsTree.prototype.markObjectsByIds=function(a){if(a&&a.length){var c=[],b;for(b in a)c.push(a[b].toString());UI.Tree.prototype.markNodesByKey.call(this,c)}};UI.ObjectsTree.prototype.addNode=function(a,c){return UI.Tree.prototype.addNode.call(this,a,c?c.toString():null)};
UI.ObjectsTree.prototype.getNodeByObjectId=function(a){return UI.Tree.prototype.getNodeByKey.call(this,a?a.toString():null)};
UI.ObjectsTree.prototype.update=function(a,c){if(!a||!a instanceof T.Object3D)return this;var b=a.id.toString(),e=this.getNodeByObjectId(b),d=c?c(a):{mode:"show"};if("show"==d.mode||"parent"==d.mode)if(b={key:b,title:a.getDescription?a.name?a.name+" "+a.getDescription():a.getDescription():a.name?a.name:"Untitled"},d.icon&&(b.icon=d.icon),d.iconStyle&&(b.iconStyle=d.iconStyle),e)UI.Tree.prototype.updateNode.call(this,b);else{e=this.addNode(b,a.parent?a.parent.id:null);if("parent"==d.mode){if(d=e.parent.getChildren())for(;1<
d.length;)d[0].copyTo(e,"child"),d[0].remove();e.setExpanded()}e.parent&&a.parent&&a.parent instanceof T.Scene&&e.parent.setExpanded()}else if("children"==d.mode)e=e?e.parent:this.tree.rootNode;else return UI.Tree.prototype.removeNodeByKey.call(this,b),this;var e=e.getChildren(),d=[],f;for(f in e)(b=e[f])&&!a.getObjectById(parseInt(b.key),!1)&&d.push(b.key);for(f in d)UI.Tree.prototype.removeNodeByKey.call(this,d[f]);for(f=0;f<a.children.length;++f)this.update(a.children[f],c);return this};
UI.MultiCheckbox=function(a,c){UI.Element.call(this);var b=this,e=document.createElement("img");e.className="multi-checkbox";e.style.cursor="default";this.dom=e;this.srcList=c;this.setValue(a);var d=document.createEvent("HTMLEvents");d.initEvent("change",!0,!0);e.addEventListener("click",function(a){b.value=(b.value+1)%b.srcList.length;b.setValue(b.value);b.dom.dispatchEvent(d)},!1);return this};UI.MultiCheckbox.prototype=Object.create(UI.Element.prototype);UI.MultiCheckbox.prototype.getValue=function(){return this.value};
UI.MultiCheckbox.prototype.setValue=function(a){if(0!=this.srcList.length)return this.value=a=void 0!==a&&a<this.srcList.length?a:0,this.dom.src=this.srcList[a],this};UI.Checkbox=function(a){UI.MultiCheckbox.call(this,a,["./assets/checkboxes/unchecked.gif","./assets/checkboxes/checked.gif"]);return this};UI.Checkbox.prototype=Object.create(UI.MultiCheckbox.prototype);UI.Checkbox.prototype.getValue=function(){return 0!==UI.MultiCheckbox.prototype.getValue.call(this)};
UI.Checkbox.prototype.setValue=function(a){return UI.MultiCheckbox.prototype.setValue.call(this,a?1:0)};UI.SectionCutCheckbox=function(a){UI.MultiCheckbox.call(this,a,["./assets/checkboxes/no-clip.gif","./assets/checkboxes/left-clip.gif","./assets/checkboxes/right-clip.gif"]);return this};UI.SectionCutCheckbox.prototype=Object.create(UI.MultiCheckbox.prototype);
UI.Color=function(){UI.Element.call(this);var a=document.createElement("input");a.className="Color";a.style.width="64px";a.style.height="16px";a.style.border="0px";a.style.padding="0px";a.style.backgroundColor="transparent";try{a.type="color"}catch(c){}this.dom=a;return this};UI.Color.prototype=Object.create(UI.Element.prototype);UI.Color.prototype.getValue=function(){return this.dom.value};UI.Color.prototype.getHexValue=function(){return parseInt(this.dom.value.substr(1),16)};
UI.Color.prototype.setValue=function(a){this.dom.value=a;return this};UI.Color.prototype.setHexValue=function(a){this.dom.value="#"+("000000"+a.toString(16)).slice(-6);return this};
UI.Number=function(a){UI.Element.call(this);var c=this,b=document.createElement("input");b.className="Number";b.style.color="#c75050";b.style.fontSize="12px";b.style.backgroundColor="transparent";b.style.border="1px solid transparent";b.style.padding="2px";b.style.cursor="col-resize";b.value="0.00";b.addEventListener("keydown",function(a){a.stopPropagation();13===a.keyCode&&b.blur()},!1);this.min=-Infinity;this.max=Infinity;this.precision=2;this.step=1;this.dom=b;this.setValue(a);var e=document.createEvent("HTMLEvents");
e.initEvent("change",!0,!0);var d=0,f=0,g=function(a){var g=b.value;d+=(a.movementX||a.mozMovementX||0)-(a.movementY||a.mozMovementY||0);b.value=Math.min(c.max,Math.max(c.min,f+d/(a.shiftKey?5:50)*c.step)).toFixed(c.precision);g!==b.value&&b.dispatchEvent(e)},h=function(a){document.removeEventListener("mousemove",g,!1);document.removeEventListener("mouseup",h,!1);2>Math.abs(d)&&(b.focus(),b.select())};b.addEventListener("mousedown",function(a){a.preventDefault();d=0;f=parseFloat(b.value);document.addEventListener("mousemove",
g,!1);document.addEventListener("mouseup",h,!1)},!1);b.addEventListener("change",function(a){a=parseFloat(b.value);!1===isNaN(a)&&(b.value=a)},!1);b.addEventListener("focus",function(a){b.style.backgroundColor="";b.style.borderColor="#ccc";b.style.cursor=""},!1);b.addEventListener("blur",function(a){b.style.backgroundColor="transparent";b.style.borderColor="transparent";b.style.cursor="col-resize"},!1);return this};UI.Number.prototype=Object.create(UI.Element.prototype);
UI.Number.prototype.getValue=function(){return parseFloat(this.dom.value)};UI.Number.prototype.setValue=function(a){void 0!==a&&(this.dom.value=a.toFixed(this.precision));return this};UI.Number.prototype.setRange=function(a,c){this.min=a;this.max=c;return this};UI.Number.prototype.setPrecision=function(a){this.precision=a;return this};UI.Slider=function(a,c){UI.Number.call(this);this.dom.type="range";return this};UI.Slider.prototype=Object.create(UI.Number.prototype);
UI.Slider.prototype.setWidth=function(a){UI.Number.prototype.setWidth.call(this,a);this.step=50/parseInt(a);return this};UI.Slider.prototype.setRange=function(a,c,b){UI.Number.prototype.setRange.call(this,a,c);this.dom.min=a;this.dom.max=c;this.dom.step=b?b:(c-a)/100;return this};
UI.Integer=function(a){UI.Element.call(this);var c=this,b=document.createElement("input");b.className="Number";b.style.color="#0080f0";b.style.fontSize="12px";b.style.backgroundColor="transparent";b.style.border="1px solid transparent";b.style.padding="2px";b.style.cursor="col-resize";b.value="0.00";b.addEventListener("keydown",function(a){a.stopPropagation()},!1);this.min=-Infinity;this.max=Infinity;this.step=1;this.dom=b;this.setValue(a);var e=document.createEvent("HTMLEvents");e.initEvent("change",
!0,!0);var d=0,f=0,g=function(a){var g=b.value;d+=(a.movementX||a.webkitMovementX||a.mozMovementX||0)-(a.movementY||a.webkitMovementY||a.mozMovementY||0);b.value=Math.min(c.max,Math.max(c.min,f+d/(a.shiftKey?5:50)*c.step))|0;g!==b.value&&b.dispatchEvent(e)},h=function(a){document.removeEventListener("mousemove",g,!1);document.removeEventListener("mouseup",h,!1);2>Math.abs(d)&&(b.focus(),b.select())};b.addEventListener("mousedown",function(a){a.preventDefault();d=0;f=parseFloat(b.value);document.addEventListener("mousemove",
g,!1);document.addEventListener("mouseup",h,!1)},!1);b.addEventListener("change",function(a){a=parseInt(b.value);!1===isNaN(a)&&(b.value=a)},!1);b.addEventListener("focus",function(a){b.style.backgroundColor="";b.style.borderColor="#ccc";b.style.cursor=""},!1);b.addEventListener("blur",function(a){b.style.backgroundColor="transparent";b.style.borderColor="transparent";b.style.cursor="col-resize"},!1);return this};UI.Integer.prototype=Object.create(UI.Element.prototype);
UI.Integer.prototype.getValue=function(){return parseInt(this.dom.value)};UI.Integer.prototype.setValue=function(a){void 0!==a&&(this.dom.value=a|0);return this};UI.Integer.prototype.setRange=function(a,c){this.min=a;this.max=c;return this};UI.Break=function(){UI.Element.call(this);var a=document.createElement("br");a.className="Break";this.dom=a;return this};UI.Break.prototype=Object.create(UI.Element.prototype);
UI.HorizontalRule=function(){UI.Element.call(this);var a=document.createElement("hr");a.className="HorizontalRule";this.dom=a;return this};UI.HorizontalRule.prototype=Object.create(UI.Element.prototype);UI.Button=function(a){UI.Element.call(this);var c=document.createElement("button");c.className="Button";this.dom=c;this.dom.textContent=a;return this};UI.Button.prototype=Object.create(UI.Element.prototype);UI.Button.prototype.setLabel=function(a){this.dom.textContent=a;return this};
UI.Image=function(a){UI.Element.call(this);var c=document.createElement("img");c.className="Image";c.style.cursor="default";c.style.display="inline-block";c.style.verticalAlign="middle";this.dom=c;a&&(this.dom.src=a);return this};UI.Image.prototype=Object.create(UI.Element.prototype);UI.Image.prototype.setSource=function(a){void 0!==a&&(this.dom.src=a);return this};
